### ISSUE TITLE
pixiv的翻页不是很完美

### ISSUE THREAD

**Issue by liaanj** [hoothin/UserScripts#100]
https://www.pixiv.net/users/24234/artworks?p=1
![image](https://user-images.githubusercontent.com/98246557/166649459-51afa9c3-e264-4b5c-bb5c-15cb083a6cdf.png)
同时与插件pixiv增强插件无法同时打开：https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus
![image](https://user-images.githubusercontent.com/98246557/166649789-f3462f94-b764-4cb7-9f43-5a861ac5edfb.png)
谢谢！

**Comment by hoothin** [comment]
[#98](98#issuecomment-1110630549) 参考最下方解决方案

**Comment by hoothin** [comment]
#98

**Comment by liaanj** [comment]
谢谢，可以同时开启了，但是下面这么大的空白和标题图能消除吗？单独开启也会有这个情况
![image](https://user-images.githubusercontent.com/98246557/166651782-74bffeb1-4399-4627-af38-34c18c045bef.png)

**Comment by hoothin** [comment]
因为下一页body高度就是这么多，我试试优化一下

**Comment by liaanj** [comment]
嗯嗯，静待更新！

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name":"Pixiv",
    "url":"^https://www\\.pixiv\\.net/",
    "action":2,
    "pageElement":"body>*",
    "nextLink":"a[class*='filterProps-Styled-Component']:last-child",
    "wait":1000,
    "init":"if(iframe){iframe.style.height=doc.querySelector('section').scrollHeight+100+'px';doc.documentElement.scrollTop=500}"
  }
</pre>
改了下规则，你更新脚本再点击上面导入试试，不过我是针对你给的这个页面写的，不知道其他页面会不会不兼容，你遇到不适配的页面再提交给我吧。

**Comment by liaanj** [comment]
我这里导入了之后似乎并没有什么变化啊……
![image](https://user-images.githubusercontent.com/98246557/166671291-87b1cd37-81be-4067-8bd8-781dd04b269b.png)

**Comment by hoothin** [comment]
要更新脚本，原先这边init不生效

**Comment by liaanj** [comment]
OK可以了 谢谢
