### ISSUE TITLE
开着这个脚本好像会被谷歌搜索判定为异常流量

### ISSUE THREAD

**Issue by vicentory** [hoothin/UserScripts#101]
开着这个脚本好像会被谷歌搜索判定为异常流量，最近打开谷歌搜索，甚至youtube都会提示有异常流量，要输入验证码，不知道和这个脚本有没有关系。

**Comment by hoothin** [comment]
你是说永页机吗？我之前用superpreloader的时候也遇到过异常流量检测的情况，但自从我开启ipv6之后再没遇见过，不知道谷歌是如何判定异常流量的。不过如果你有这种需求的话可以模仿内置规则中的“魂+”规则，添加谷歌自定义规则，增加"sleep":1000 ，这样谷歌翻页会增加1秒的间隔。

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name":"Google Search",
    "nextLink":"id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
    "pageElement":"id('rso')/div|id('center_col')//style[contains(.,'relative')]|id('search')/div/div/style[1]",
    "insert":"id('center_col')/div[@role='navigation']",
    "type":0,
    "action":1,
    "pageNum":"&start={10*($p-1)}",
    "url":"^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)",
    "sleep":1000
  }
</pre>
像是这样，当然如果最后确定不是频繁访问导致的就不用添加了
