### ISSUE TITLE
10086网站通话详单页面帮忙设置一下自动翻页呗，谢谢。

### ISSUE THREAD

**Issue by vicentory** [hoothin/UserScripts#102]
大佬，帮个忙啊，10086网站通话详单这个页面也是需要翻页才能看的，自己加的规则也不起作用，帮忙调试一下看看呗，谢谢。
想导出自己的通话记录，移动没有导出功能，也不能设置每页显示200条之类的，就一页50条，自己复制到表格里16次才导出来，太费劲了。还想找程序员朋友写脚本导出，但也费劲。昨天夜里想到这个翻页脚本应该会更快捷啊。
格式无所谓，只要能把当月十几页的通话记录显示出来就行，强行拼接的也可以的。这个网站好像没有强行拼接的选项，以前在有的网站好像看到过的。
https://shop.10086.cn/i/?f=billdetailqry
<img width="791" alt="cc289a7ce4844102f73d213c428d572" src="https://user-images.githubusercontent.com/10493597/167512213-13d7a8d3-c8ae-48fb-b5e0-f02f249438c2.png">
<img width="530" alt="0e88bda813551e9da7c01d379831ac3" src="https://user-images.githubusercontent.com/10493597/167512225-9609d1b2-30e1-4981-820d-58642353d058.png">

**Comment by hoothin** [comment]
不合适，这边是ajax请求的，而且提交参数全是动态的，用永页机实现还不如另写一个脚本。
只需要模拟点击，存储tbody，循环至没有下一页之后拼接tdoby输出。这样实现起来就简单很多，甚至直接用浏览器生成csv文件也没问题
