### ISSUE TITLE
Github 个人STAR页面自动翻页显示问题

### ISSUE THREAD

**Issue by GamerNoTitle** [hoothin/UserScripts#103]
如图

![image](https://user-images.githubusercontent.com/28426291/167609549-b5a71d69-5484-4ac3-9bb8-064cec191e15.png)
![image](https://user-images.githubusercontent.com/28426291/167609579-b6cc53ec-03bb-4e4e-8239-e7875aacf33a.png)

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name":"Github",
    "url":"^https://github\\.com/",
    "pageElement":".col-lg-12>.col-12,.col-lg-9>.col-12",
    "nextLink":".paginate-container>div>a:nth-child(2)"
  }
</pre>

**Comment by GamerNoTitle** [comment]
可以了 感谢
