### ISSUE TITLE
[NSFW] 请问自定义规则后，这个网站为什么首页有效，里面没效果。

### ISSUE THREAD

**Issue by cybertahr** [hoothin/UserScripts#104]
https://buondua.com/
NSFW网站，不要在公共场合打开 😃 
不懂代码的小白，自己参考范例乱写了规则，网站首页可以自动翻页，点进里面的页面就没效果，不能自动翻页了。
谢谢。
```
  {
    "name":"buondua",
    "url":"^https://www\\.buondua\\.com/",
    "pageElement":"div.article-fulltext",
    "nextLink":"span>a.pagination-link.is-current+a"
  }
```

**Comment by hoothin** [comment]
nextLink有点问题，a元素被span包裹了，这样是取不到的，css选择器抓不了，换成xpath抓取吧
<pre name="pagetual">
  {
    "name":"buondua",
    "url":"^https://(.*\\.)?buondua\\.com/",
    "type":0,
    "pageElement":"//div[@class='article-fulltext']",
    "nextLink":"//span[.//a[@class='pagination-link is-current']]/following-sibling::span/a"
  }
</pre>

**Comment by hoothin** [comment]
另外多谢分享色图啊😀
