### ISSUE TITLE
水木社区自动加载有问题

### ISSUE THREAD

**Issue by byedo** [hoothin/UserScripts#105]
![屏幕截图_1](https://user-images.githubusercontent.com/11496932/168423552-d087a515-7d67-459d-874f-f040dfd3fce5.png)

页数少的时候，自动翻页没问题，但是页数超过20就变成这样了

**Comment by hoothin** [comment]
你没有导入规则吧

**Comment by byedo** [comment]
> 
是这样的，水木社区页数少的翻页是没问题的，页数多的就是上面的图，你可以试试，我没有导入规则库，这个脚本在同一个网站上表现不一致
https://www.mysmth.net/nForum/#!article/WorkLife/2932566  这个是有问题的
https://www.mysmth.net/nForum/#!article/MilitaryView/2665226  这个没问题

**Comment by hoothin** [comment]
这里必须要用规则库中的规则。
因为帖内图片一多，脚本抓到的主框架就会变成主楼，接下来就会把下一页的主楼插入当前页，这样排版自然就错位了。

**Comment by byedo** [comment]
> 

导入试了，没问题，感谢
