### ISSUE TITLE
Help on adding next page rule for alibaba.com

### ISSUE THREAD

**Issue by reddysat07** [hoothin/UserScripts#107]
Could you help with the example of how to add rule for Alibaba,
Example alibaba search results page:  https://www.alibaba.com/trade/search?IndexArea=product_en&SearchText=torch&page=2&f0=y

When the page data is viewed, the link to 'next' page Arrow ( > ) element is:
//*[@id="root"]/div/div[4]/div/div[1]/a[9]

Full Xpath:
/html/body/div[4]/div[2]/div/div[4]/div/div[1]/a[9]

Could you help by providing Pagetual rule and also Autopagerize rule for this website?

Thank you in advance

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name":"Alibaba",
    "url":"^https://www\\.alibaba\\.com/trade/search",
    "pageElement":".organic-list>*",
    "nextLink":".seb-pagination__pages>span+a",
    "action":1,
    "pageAction":"eles.forEach(ele=>{let img=ele.querySelector('div[data-image]>img');if(!img)return;img.src=img.parentNode.dataset.image})",
    "wait":"return doc.querySelector('.seb-pagination__pages') && !doc.querySelector('.organic-list>p>i.ui2-icon-loading')"
  }
</pre>
Autopagerize will not support until it add page action for javascript

**Comment by reddysat07** [comment]
Thank you,
     Could you help by providing Pagetual syntax rule for this website:flipkart.com

Sample search:
https://www.flipkart.com/search?q=torch&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off

Seems the syntax needs more expertise than finding out Xpath or the element data that represents 'next' link/button to create a new rule, so I am asking for your help

Thanks in advance

**Comment by reddysat07** [comment]
Thank you, it worked

**Comment by hoothin** [comment]
Flipkart.com will work with automatic rule so don't need to create new one.
