### ISSUE TITLE
版本升级后,原来的一个页面不支持自动翻页了

### ISSUE THREAD

**Issue by fujpck2008** [hoothin/UserScripts#108]
上个月咨询过:
什么值得买这个页面能支持一下么? 
https://www.smzdm.com/jingxuan/
这网页它自己会翻到第3页,之后要点4才会到第4页
你给了以下代码,就可以一直自动翻页了
但最近两天,永页机更新到1.6.9.9和1.7版后,不行了,又不能翻页了
我测试了好多次,都不行,退回到1.6.6版,才可以(其他版本未测试)
希望解决一下

PS:刚发现有历史版本,就测试了一下,一直到1.6.9.5版都可以用,但到1.6.9.6版之后就不能用了

  {
    "name":"smzdm jingxuan",
    "action":0,
    "url":"^https://.*\\.smzdm\\.com/jingxuan",
    "pageElement":"ul#feed-main-list>li",
    "nextLinkByUrl":["(.*jingxuan)(/p)?(\\d*)","$1/p{($3.0||1)+3}"],
    "insert":"ul#feed-main-list",
    "insertPos":2,
    "delay":"let curpage=location.href.match(/\\d+$/);if(curpage)
curpage=parseInt(curpage[0])+2;else curpage=3;return 
document.querySelector
('#J_feed_pagenation>li.current').innerText>=curpage&&document.queryS
elector('#J_feed_loading').style.display=='none'"
  }

**Comment by hoothin** [comment]
感谢反馈，我修复一下。
代码迭代之后我一个人没法测试所有情况，所以你的反馈对其他用户来说很重要

**Comment by hoothin** [comment]
已经修复了，如果以后再遇到bug，还请继续反馈

**Comment by fujpck2008** [comment]
OK了
