### ISSUE TITLE
翻页机在不同浏览器的不同问题 [1.7.5]

### ISSUE THREAD

**Issue by SummerAirflow** [hoothin/UserScripts#109]
打开煎蛋无聊图
在Vivaldi，使用规则会导致JS按钮失效，强制拼接则会无限翻页，无法使用。
在Firefox，使用规则JS按钮有效，但发送CTRL+END滚动到底部时，会导致无限翻页。而强制拼接则似乎完美解决所有问题，甚至没有拼接痕迹。

**Comment by hoothin** [comment]
js按钮失效是因为你的规则库没有导入或者规则更新没有完成。
无限翻页这个我也很困惑，看起来似乎浏览器有两种逻辑，一种是插入新内容后滚动条保持原始位置，一种是插入新内容后滚动至末尾，而后者就会触发翻页。
临时的解决方案可以是用滚轮事件代替滚动事件，但如果能找出原因彻底解决就更好了。
更奇怪的是我测试了Vivaldi，不论强制拼接与否，一切正常。请问你是否对Vivaldi做了什么特殊设置或者安装了什么特殊的插件呢？

**Comment by SummerAirflow** [comment]
不，我算是接触这个脚本有段时间了，不会犯规则库和更新的错误。我确定二者都是最新的。
Vivaldi方面唯一的可疑点是，整个tampermonkey脚本都是从firefox导出的，似乎firefox产生的相关设置也被导入并生效了。我用个全新配置试试。

**Comment by hoothin** [comment]
感谢提供这些信息，原因找到了，是因为Vivaldi下子iframe的#锚点会影响父页面的导航。已经更新了一个版本，你试试
