### ISSUE TITLE
反馈下纠错相关的想法

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#111]
在Super_preloaderPlus_one上，我遇到过很多次因为规则不当而出现的疯狂加载。当然翻页机也有，比如以前的规则在豆瓣的一些网页上。
我觉得应该在设置一个翻页的间隔时间，比如1.5-2秒，低于这个时间的加载连续出现了两次，就视为出现了错误，应当停止加载。当然发送"CRTL+PGDN"滚动到底部时，应该重置这个时间。

然后就是错误触发规则的纠错。应该只加载同域名的链接，以及不能加载与当前网址或者已加载网页重复的链接。就像这个帖子类似的状况：
https://github.com/hoothin/UserScripts/issues/110

**Comment by hoothin** [comment]
首先多谢反馈，我在下面解释一下。

间隔时间可以自行在规则里手动设置，添加sleep:1000就行。

然后很久以前的版本就已经把重复的链接排除了，110号也并非出于这个问题。豆瓣在之前的版本疯狂加载则是因为网页自己在加载时触发了下一次loadmore，现在没问题了是因为我抛弃了网站发出的卷轴事件。这些原因各不相同，大多需要单独分析。

只加载同域名的链接是不可行的，因为类似魂＋以及一些其他网站会触发反cc，返回的是子域名的链接。另外例如百度快照等一些网站，下一页则是处于两个不同域名。

如果你有发现出错的网站，可以直接把网址发上来给我分析一下。

**Comment by hoothin** [comment]
另外朋友看你测试这么用心，也帮我试用一下这个新脚本呗 https://greasyfork.org/scripts/445274-searchjumper

**Comment by Frozen1084** [comment]
谢谢。
我试用的感受。
我个人是鼠标手势用户，有快速且直观的搜索手势，所以我不喜欢收缩在上的方式。使用需要至少三步：准确移动到指定位置，悬停，选择。我希望选择的过程更直观更快速，更少步骤。比如将按钮放到搜索框的后面，直接显示出来，图标可以小一些。
在Vivaldi，google未触发。
在firefox，所有搜索都有一条横向滚动条。

**Comment by hoothin** [comment]
感谢！对我很有用，我来参照你的意见修改优化一下。请问你 Vivaldi 上的 google 域名是哪一个呢？

**Comment by Frozen1084** [comment]
https://www.google.com/search?num=50&safe=off&filter=0&newwindow=1&hl=zh-CN&safe=off&filter=0&q=%E6%96%B0
