### ISSUE TITLE
not working for eksi sozluk

### ISSUE THREAD

**Issue by Eikosa** [hoothin/UserScripts#112]
https://eksisozluk.com/turkiyenin-iflas-etmesi--5240794?a=popular
for example does not working for this website, idk how can fix this

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name":"ekşi sözlük",
    "action":0,
    "url":"^https://eksisozluk\\.com",
    "pageElement":"#entry-item-list",
    "nextLinkByJs":"let pager=doc.querySelector('.pager');if(!pager || pager.dataset.currentpage==pager.dataset.pagecount)return null;else return location.href.replace(/&p=\\d+/,'&p='+(parseInt(pager.dataset.currentpage)+1))"
  }
</pre>

**Comment by hoothin** [comment]
This site has CORS so you can't use iframe to get content.
But the next page button is hided until page loaded.
So you should create a next URL with static page by js.

**Comment by Eikosa** [comment]
thanks so much <3
