### ISSUE TITLE
pornhub 主页不翻页

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#118]
pornhub的主页不加载，https://cn.pornhub.com/
但手动翻页后其他页面会加载 https://cn.pornhub.com/video?page=2

**Comment by hoothin** [comment]
可以添加如下自定义规则
<pre name="pagetual">
  {
    "type":0,
    "name":"Pornhub.com",
    "action":0,
    "url":"^https://[^.]+\\.pornhub\\.com",
    "pageElement":"id(\"videoCategory\") | id(\"incategoryVideos\") | id(\"videoSearchResult\") | id(\"mostRecentVideosSection\") | id(\"photosAlbumsSection\") | id(\"claimedRecentVideoSection\") | //div[@class='recommendedVideosContainer']/ul | id(\"popularPornstars\") | //ul[contains(concat(' ', normalize-space(@class), ' '), ' streamateContent ')] | id('filterChannelsSection') | id('playListSection')",
    "nextLink":"//li[contains(concat(\" \", normalize-space(@class), \" \"), \" page_next \")]/a",
    "insertPos":1
  }
</pre>
我觉得首页不翻页比较好

**Comment by Frozen1084** [comment]
thanks!
