### ISSUE TITLE
东方永页机加一个洛谷题解翻页

### ISSUE THREAD

**Issue by LiaoYifan2021** [hoothin/UserScripts#119]
洛谷题解不能翻页啊，还有题目也不能

**Comment by hoothin** [comment]
地址发给我

**Comment by LiaoYifan2021** [comment]
https://www.luogu.com.cn/problem/solution/P1000

**Comment by LiaoYifan2021** [comment]
https://www.luogu.com.cn/problem/list

**Comment by hoothin** [comment]
这什么鬼网站，有点吓人啊。加这么多限制，又是vue又是安全限制的。
<pre name="pagetual">
    {
        "name": "题目列表 - 洛谷",
        "url": "^https://www\\.luogu\\.com\\.cn/problem/list",
        "nextLinkByUrl": [
            "(\\?page=|$)(\\d*)",
            "?page={$2+1}"
        ],
        "wait": 1000,
        "pagePre": [
            "<a href=\"(.*?)\">(.*?)</a></li>",
            "<div data-v-c06fccc2=\"\" data-v-24f898d2=\"\" class=\"row\"> <span data-v-c06fccc2=\"\" data-v-24f898d2=\"\" class=\"status\"><svg data-v-1b44b3e6=\"\" data-v-c06fccc2=\"\" aria-hidden=\"true\" focusable=\"false\" data-prefix=\"fas\" data-icon=\"minus\" role=\"img\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\" class=\"icon svg-inline--fa fa-minus fa-w-14\" data-v-24f898d2=\"\" style=\"opacity: 0.7;\"><path data-v-1b44b3e6=\"\" fill=\"currentColor\" d=\"M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z\" class=\"\"></path></svg></span> <span data-v-c06fccc2=\"\" data-v-24f898d2=\"\" class=\"pid\">$1</span> <div data-v-c06fccc2=\"\" data-v-24f898d2=\"\" class=\"title\"><a data-v-303bbf52=\"\" data-v-c06fccc2=\"\" href=\"/problem/$1\" target=\"_blank\" colorscheme=\"default\" class=\"title color-default\" data-v-24f898d2=\"\">$2</a></div> <div data-v-187aafe9=\"\" data-v-c06fccc2=\"\" class=\"tags\" data-v-24f898d2=\"\"><div data-v-187aafe9=\"\" class=\"tags-wrap multiline\"></div></div> <div data-v-c06fccc2=\"\" data-v-24f898d2=\"\" class=\"difficulty\"></div> <div data-v-c06fccc2=\"\" data-v-24f898d2=\"\" class=\"progress\"><div data-v-47712372=\"\" data-v-c06fccc2=\"\" class=\"progress-frame has-tooltip\" data-original-title=\"null\" data-v-24f898d2=\"\"><div data-v-47712372=\"\" style=\"width: 37.2682%; background-color: rgb(52, 152, 219);\"></div></div></div></div>"
        ],
        "pageElement": ".row"
    }
</pre>
<pre name="pagetual">
    {
        "name": "题单广场 - 洛谷",
        "url": "^https://www\\.luogu\\.com\\.cn/training/list",
        "nextLinkByUrl": [
            "(&page=|$)(\\d*)",
            "&page={$2+1}"
        ],
        "wait": 1000,
        "pagePre": [
            "<li><a href=\"(.*?)\">(.*?)</a></li>",
            "<div data-v-128051e7=\"\" data-v-24f898d2=\"\" class=\"row\"><span data-v-128051e7=\"\" data-v-24f898d2=\"\" class=\"id\">$1</span> <span data-v-128051e7=\"\" data-v-24f898d2=\"\" class=\"name\"><a data-v-303bbf52=\"\" data-v-128051e7=\"\" href=\"/training/$1\" target=\"_blank\" colorscheme=\"default\" class=\"color-default\" data-v-24f898d2=\"\"> $2 </a></span>  <span data-v-128051e7=\"\" data-v-24f898d2=\"\" class=\"problem-count\">0</span> <span data-v-128051e7=\"\" data-v-24f898d2=\"\" class=\"collection\">0</span> <span data-v-128051e7=\"\" class=\"creator\" data-v-24f898d2=\"\"><span data-v-dfb4a326=\"\"><span data-v-58fd269e=\"\" data-v-dfb4a326=\"\"><span data-v-58fd269e=\"\"><a data-v-303bbf52=\"\" data-v-dfb4a326=\"\" href=\"/user/0\" target=\"_blank\" colorscheme=\"none\" class=\"color-none\" data-v-58fd269e=\"\"><span data-v-dfb4a326=\"\" data-v-303bbf52=\"\" style=\"font-weight: bold; color: rgb(254, 76, 97);\"> author </span></a></span> </span></span></span></div>"
        ],
        "pageElement": ".row"
    }
</pre>
记得配合最新版脚本使用。

因为无法页内eval，故取不到创建者和收藏数这些信息。

如果想要的话可以用python抓取下来分析或者单独为它写个脚本，但那样也没啥意义。

**Comment by hoothin** [comment]
```
// ==UserScript==
// @name         东方永页机洛谷扩展
// @namespace    hoothin
// @version      0.1
// @description  东方永页机洛谷扩展
// @author       hoothin
// @match        https://www.luogu.com.cn/training/list*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    function pagetualPagePre (response) {
        let listData = response.match(/window\._feInjection = JSON\.parse\(decodeURIComponent\(\"(.*)\"\)\);window\._feConfigVersio/);
        listData = JSON.parse(decodeURIComponent(listData[1]));
        let resultStr = "";
        listData.currentData.trainings.result.forEach(data => {
            resultStr+=
`<div data-v-128051e7="" data-v-24f898d2="" class="row"><span data-v-128051e7="" data-v-24f898d2="" class="id">${data.id}</span> <span data-v-128051e7="" data-v-24f898d2="" class="name"><a data-v-303bbf52="" data-v-128051e7="" href="/training/${data.id}" target="_blank" colorscheme="default" class="color-default" data-v-24f898d2="">
        ${data.title}
      </a></span> <!----> <span data-v-128051e7="" data-v-24f898d2="" class="problem-count">${data.problemCount}</span> <span data-v-128051e7="" data-v-24f898d2="" class="collection">${data.markCount}</span> <span data-v-128051e7="" class="creator" data-v-24f898d2=""><span data-v-dfb4a326=""><span data-v-58fd269e="" data-v-dfb4a326=""><span data-v-58fd269e=""><a data-v-303bbf52="" data-v-dfb4a326="" href="/user/${data.provider.uid}" target="_blank" colorscheme="none" class="color-none" data-v-58fd269e=""><span data-v-dfb4a326="" data-v-303bbf52="" style="font-weight: bold; color: ${data.provider.color};">
  ${data.provider.name}
</span></a></span> </span>
</span></span></div>`;
        });
        return response+resultStr;
    }
    window.pagetualPagePre = pagetualPagePre;
})();
```
这是给这个网站的扩展，加上这个可以包含创建者和收藏数，不过我写死了，vue一旦重新打包就失效了，最好是自己读取页面元素构建。我也不想为这个网站花费精力，你自己参照着去改吧。

**Comment by LiaoYifan2021** [comment]
题解P1001样本https://www.luogu.com.cn/problem/solution/P1001 别的题一样
题目https://www.luogu.com.cn/problem/list
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月18日 8:36
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [hoothin/UserScripts] 东方永页机加一个洛谷题解翻页 (Issue #119)


地址发给我

―
