### ISSUE TITLE
能把历史记录做成白名单的吗?

### ISSUE THREAD

**Issue by Noah1995** [hoothin/UserScripts#120]
1丶不想全部网页都历史记录
可以添加在这里加个开关匹配当前网址或者自定义...
![image](https://user-images.githubusercontent.com/25548230/174486296-88492467-da2f-4779-8641-472edeb10aa3.png)

2丶鼠标左键page:2的时候丶能不能不要打开页面...
而是快速跳转到page:2的页面头部开始看...
因为当你看到page:2的时候page:1的内容已经看完了...
鼠标中键默认也是会新标签页打开的功能的...

题外话历史记录开关可以加在这里的吗?
![image](https://user-images.githubusercontent.com/25548230/174486681-196bb6fe-69c6-4f32-a088-5248b592b0fe.png)

**Comment by hoothin** [comment]
“不想全部网页都历史记录”是啥意思？是说你想要用规则来控制是否写入历史记录吗？

左键单击跳转下一页这个建议不错，容我考虑一下

**Comment by hoothin** [comment]
已经加上了，现在你可以关闭全局的“历史记录”选项，
在单个站点规则中添加 history:1 属性来启用。

左键跳转也加上了，不过会稍微偏离页首50像素，来为顶部导航栏空出位置。

**Comment by Noah1995** [comment]
> 已经加上了，现在你可以关闭全局的“历史记录”选项， 在单个站点规则中添加 history:1 属性来启用。
> 
> 左键跳转也加上了，不过会稍微偏离页首50像素，来为顶部导航栏空出位置。

![image](https://user-images.githubusercontent.com/25548230/174530656-7ee8956b-c51f-4a38-9548-977fe8987313.png)
我的意思是这里和 加个 添加【启用历史记录】的按钮...
如果需要具体什么位置通配符再自定义编辑...
如果每次需要历史记录要跳转打开编辑也太磨蹭了...
自动启用，否则为白名单模式一样哪种....
![image](https://user-images.githubusercontent.com/25548230/174530933-3dfc9ab9-e14d-4c83-847d-46308b569abc.png)

**Comment by hoothin** [comment]
你这需求有点奇怪，是什么场景下需要快速切换【是否写入历史记录】呢？
个性化设置是不适合放在命令菜单里的，因为其他人用不到。
如果可以的话，希望你再详细描述一下你的使用场景。

**Comment by Noah1995** [comment]
> 你这需求有点奇怪，是什么场景下需要快速切换【是否写入历史记录】呢？ 个性化设置是不适合放在命令菜单里的，因为其他人用不到。 如果可以的话，希望你再详细描述一下你的使用场景，以及向我解释下你需要启用或禁用历史记录的理由。

比如我固定的标签页...
看美剧的网站希望他永远锁定page1....
每次我翻页后要重新点击返回首页很麻烦...
比如https://hoothin.bdsmlr.com/archive*我就需要记住上次看的页面...

**Comment by hoothin** [comment]
是这样啊，那以下方法如何？
启用全局的“历史记录”，然后在不需要启用的网站点击编辑当前规则，添加 history:0 属性来排除。

或者你有啥好建议？除了添加命令菜单与显示在分隔条上之外？
要么等我有空，再添加一个分隔条扩展的选项，通过自定义代码来实现这个。

**Comment by Noah1995** [comment]
那等你有空再说吧
history:1 是怎么编辑的..

**Comment by hoothin** [comment]
很简单啊，打开页面，点击“自定义此站规则”，当前站点的规则会自动提取并且粘贴到自定义代码框里面。
然后你在大括号里面最后一行加上`,history: 0`，点击保存就行了。注意这里有个逗号

**Comment by Noah1995** [comment]
> ,history: 0
![image](https://user-images.githubusercontent.com/25548230/174555763-cc86e09b-00c3-46ca-8e67-da790e88262d.png)
不是很懂

**Comment by hoothin** [comment]
要加在大括号里面。也就是`clearfix"`后面

**Comment by Noah1995** [comment]
> 要加在大括号里面。也就是`clearfix"`后面

[
    {
        "name": "在线看美剧 - LIBVIO",
        "url": "^https://www\\.libvio\\.me",
        "pageElement": "BODY > DIV.container > DIV.row > DIV.stui-pannel > DIV.container > DIV.stui-pannel__bd.clearfix > UL.stui-vodlist.clearfix",history:0
    }
]
![image](https://user-images.githubusercontent.com/25548230/174559298-e140fa17-5626-4edc-adda-fe57d6fa86f3.png)

**Comment by Noah1995** [comment]
要加冒号吗?

**Comment by hoothin** [comment]
加不加都是可以的，我做了兼容的

**Comment by hoothin** [comment]
history需要加冒号

**Comment by Noah1995** [comment]
没用卵用啊...
你是不是记错了?

**Comment by Noah1995** [comment]
手动实在太慢了...
点击选择开或关然后点编辑跳转也可以...
这样只要再点github保存就可以了

但是这样油猴可以同步git设置吗?

**Comment by Noah1995** [comment]
仔细想了一下还是添加这里更好都不用跳转保存
![image](https://user-images.githubusercontent.com/25548230/205618025-3767b7f3-3239-45ea-952e-af391d676ddd.png)
