### ISSUE TITLE
加入实际页数显示..

### ISSUE THREAD

**Issue by Noah1995** [hoothin/UserScripts#121]
![image](https://user-images.githubusercontent.com/25548230/174563753-b5e16a99-6d45-4805-8851-cfa9c34a8154.png) 
加入实际页数显示... 
比如我从第2页打开的网页预读第2页其实是第3页...

要不你还是添加一个像Super-preloader改的那种小浮窗吧...
顺便把历史记录 拼接开关都放在这里...
![录制_2022_06_20_17_04_51_896](https://user-images.githubusercontent.com/25548230/174567318-168fa0a1-4321-49e4-9ec7-6121c472351c.gif)

https://github.com/machsix/Super-preloader

**Comment by hoothin** [comment]
感谢建议。
不过我没兴趣。
实际页数可以自己写规则提取，这个不可能通用。
其他的需求。。。你直接用Super-preloader就OK了
