### ISSUE TITLE
下载出错

### ISSUE THREAD

**Issue by Mahonezgg** [hoothin/UserScripts#122]
![image](https://user-images.githubusercontent.com/107932195/174807117-d131d62c-6864-4496-8e25-c7ecf2311787.png)

试了很多次，每次都是这样，爬取好了后就一直卡在这页面，浏览器下载没有动静，点临时保存也没反应，只能点那个叉关掉这个页面

**Comment by hoothin** [comment]
先翻墙，下载的依赖库目前已经被墙了。
