### ISSUE TITLE
能不能整一个类似Superpreloader那种比较明显的浮动按钮

### ISSUE THREAD

**Issue by 0rt** [hoothin/UserScripts#123]
比较容易观察到脚本工作情况和临时禁用（我个人使用情况来说，双击空白区经常不灵）

**Comment by hoothin** [comment]
三种方法：
1、单击分隔条
2、设置禁用快捷键
3、点击命令菜单

**Comment by hoothin** [comment]
三种方法：
1、单击分隔条
2、设置禁用快捷键
3、点击命令菜单

**Comment by 0rt** [comment]
preloader的小方块挺好的，还有颜色报告工作情况。能一眼了解到规则是否发挥作用

**Comment by hoothin** [comment]
我个人不大喜欢这种设计，我期望对我来说翻页是无感的
