### ISSUE TITLE
虎扑论坛第二页经常拼到顶楼

### ISSUE THREAD

**Issue by 0rt** [hoothin/UserScripts#124]
https://bbs.hupu.com/54023807.html
比如这页，我发现多数情况是拼到第一楼。这种情况是脚本识别问题还是只能写规则解决？
如图：
![image](https://user-images.githubusercontent.com/822795/175196369-8d39b4f8-2ccd-47f7-9802-ff4acc3ee5be.png)

**Comment by hoothin** [comment]
因为你没导入规则

**Comment by 0rt** [comment]
> 因为你没导入规则。
> 
> 我很好奇，我已经用最大号的字体说明了，为何还是无视呢？

导入什么规则呢？我连特殊库规则都导入了。你多试两次

**Comment by hoothin** [comment]
你可以打开控制台看下当前使用规则，上图明显是裸奔状态，因为论坛页面主楼长度不一，无法智能判断主体，所以当主楼过长的时候，无规则驱动就有可能拼接到一楼后面。
如果你访问不了raw.github，那么你应当导入镜像地址。
如果还是有问题，重开一个issue，按照我设置的模板提交[最小重现](https://stackoverflow.com/help/minimal-reproducible-example)。
