### ISSUE TITLE
在NGA会出错

### ISSUE THREAD

**Issue by momoblydblk** [hoothin/UserScripts#125]
**Describe the bug**
在NGA有时候会把第二页拼到主楼的缩进里面去（见附图三分之二处）

**To Reproduce**
主楼浏览结束后有几率出现

**Expected behavior**
附图三分之二处有错误示范（上半）和正确示范（下半）

**Screenshots**
![图片](https://user-images.githubusercontent.com/21081757/175229654-9cf2a5bc-3c8e-44be-99c2-8440200e1ed8.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 101.0.1

**Additional context**

**Comment by hoothin** [comment]
感谢反馈。
请按以下步骤排错。
1、首先请打开配置页查看下规则是否已经导入成功，如果没有导入，请先导入规则。
2、如果规则已经导入成功，请打开 https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json 查看是否能正常访问。
  + 如果无法正常访问，请使用镜像站（例如fastgit、ghproxy等）替换规则
  + 如果可以正常访问，请打开控制台寻找pagetual开头的调试输出复制上来。
3、如果以上方法皆未解决，请自行将[nga的规则](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L599)复制入你的自定义规则框，用中括号”[]“包起来

**Comment by momoblydblk** [comment]
并没有找到pagetual开头的调试输出,但是显示有隐藏项目.我研究研究看看能不能调出来

**Comment by hoothin** [comment]
请问能否把目标链接发给我瞅瞅？也许是Url没有匹配上规则

**Comment by momoblydblk** [comment]
> 请问能否把目标链接发给我瞅瞅？也许是Url没有匹配上规则

https://ngabbs.com/read.php?tid=32325602

**Comment by hoothin** [comment]
感谢反馈，的确是url没覆盖到。以下是最新规则
<pre name="pagetual">
  {
    "name": "NGA列表页",
    "url": "^https?://(.*\\.nga\\.cn|nga\\.178\\.com|ngabbs\\.com)/thread\\.php",
    "action": 1,
    "pageElement": "#topicrows"
  }
</pre>
<pre name="pagetual">
  {
    "name":"NGA内容页",
    "url":"^https?://(.*\\.nga\\.cn|nga\\.178\\.com|ngabbs\\.com)/read\\.php",
    "nextLink":"a[title='下一页']",
    "action":2,
    "pageElement":"div#m_posts",
    "init":"doc&&doc.addEventListener('mouseover',e=>{e.preventDefault();e.stopPropagation()},true)"
  }
</pre>
