### ISSUE TITLE
Autoclick stopped working recently

### ISSUE THREAD

**Issue by GoroFourArms** [hoothin/UserScripts#126]
https://infinitenoveltranslations.net/dungeon-battle-royale-chapter-244-part-245/
https://infinitenoveltranslations.net/dungeon-battle-royal/act-ix/chapter-244-part-245/
{
        "url": "^https://infinitenoveltranslations\\.net",
        "nextLink": ".entry-content > p:nth-child(4) > a:nth-child(3)",
        "pageElement": "div.entry-content",
        "autoClick": "//a[contains(text(),'Enjoy')]",
        "pinUrl": true
    },

**Comment by hoothin** [comment]
Try this
<pre name='pagetual'>
    {
        "url": "^https://infinitenoveltranslations\\.net",
        "type": 0,
        "pageElement": "//div[@class='entry-content']",
        "nextLink": "//a[contains(text(),'Next Chapter')]",
        "autoClick": "//a[contains(text(),'Enjoy')]",
        "pinUrl": true
    }
</pre>

**Comment by hoothin** [comment]
But the link you pasted above actually has no next page. The next chater point to "www.patreon.com"

**Comment by GoroFourArms** [comment]
No I was talking about the autoclick on the first page doesn't work recently. Its suppose to go to the second page.

**Comment by GoroFourArms** [comment]
Its not just this site all my sites stopped working and I tried your new one but it doesn't work.

**Comment by hoothin** [comment]
That's strange as I test with right result.
What's your browser? Can you test the old version of pagetual?

**Comment by GoroFourArms** [comment]
I have firefox. I will try.

**Comment by GoroFourArms** [comment]
sorry i never installed old version i have violentmonkey how do i do that.

**Comment by hoothin** [comment]
You can get history versions here https://greasyfork.org/en/scripts/438684-pagetual/versions

**Comment by GoroFourArms** [comment]
1.9.8 is working

**Comment by GoroFourArms** [comment]
1.9.20 is not

**Comment by hoothin** [comment]
Thank you for report. It's fixed now:-)

**Comment by GoroFourArms** [comment]
1.9.19 is working so it breaks on 1.9.20

**Comment by GoroFourArms** [comment]
yeah the new version is working thanks
