### ISSUE TITLE
明月中文的自定义下载

### ISSUE THREAD

**Issue by lollypopyoung** [hoothin/UserScripts#127]
”明月中文“https://www.56bok.com/这个站点下载出错，能帮忙编写一下自定义规则吗？谢谢

我不是很会查看css选择器，但这个网站的目录页好像没有目录链接。

**Comment by hoothin** [comment]
明天帮你写。粗略看了下，链接在dataset里，用管道抓取拼接就行了，至于所有目录，可以用永页机自动翻页拼接

**Comment by hoothin** [comment]
明天帮你写。粗略看了下，链接在dataset里，用管道抓取拼接就行了，至于所有目录，可以用永页机自动翻页拼接

**Comment by lollypopyoung** [comment]
回复得好快！那拜托了，我顶多只能在开发者工具的Elements里挖出来<a href="javascript:void(0);" onclick="window.open('/chapter/68/68861/12567624.html','_self');">为止。。并不知道拿它怎么办

**Comment by hoothin** [comment]
打开目录页，用东方永页机自动翻完所有目录
点击自定义下载，输入以下代码
<pre>
ul.readlist>li>a>>let href=item.getAttribute("onclick").replace(/.*open\('(.*)','.*/,"$1");item.href=href;return item;
</pre>
