### ISSUE TITLE
netflav 自定义好像不起效果

### ISSUE THREAD

**Issue by fireinrain** [hoothin/UserScripts#128]
大佬你好 在自定义配置页面上 配置如下：

[
    {
        "name": "netflav",
        "action": 0,
        "url": "^https://netflav\\.com/",
        "pageElement": "#general-pagination>div> a",
        "nextLink": "#general-pagination>div>a>i"
    }
]

刷新页面后是能看到软件的自动加载动画的 但是就是没有加载出内容。我以为要指定强制使用自定义page拼接
但是自定义拼接的正则有点看不懂  试了下面这个也不行

[
    {
        "name": "netflav",
        "action": 0,
        "url": "^https://netflav\\.com/",
        "pageElement": "#general-pagination>div> a",
        "nextLink": "#general-pagination>div>a>i",
        "nextLinkByUrl": [
            "(https://netflav\\.com/?)(?:\\?page=|$)(\\d*)",
            "$1?page={($2.0||1)+1}"
        ]
    }
]

大佬能帮忙看看不 感激不尽

**Comment by hoothin** [comment]
试过"action": 1了吗

**Comment by hoothin** [comment]
找到了一个没人的地方，帮你看了下，这个站类似于百度贴吧，有lazyload，需要这样写
<pre>
    {
        "name": "netflav",
        "url": "^https://netflav\\.com/",
        "pageElement": ".video_grid_container>.grid_root",
        "nextLink": "#general-pagination>div>a[aria-current='true']+a",
        "wait": "let pagination= doc.querySelector(\"#general-pagination\");let pageReady=pagination&&pagination.style.opacity!=0&&pagination.querySelector(\"a[aria-current='true']+a\");if(doc==document)return pageReady;if(!pageReady)return false;let lazy=doc.querySelector('div.lazyload-placeholder,.grid_cover.image:not(.fadeIn)');if(lazy){var actualTop=lazy.offsetTop;var current=lazy.offsetParent;while(current!==null){actualTop+=current.offsetTop;current=current.offsetParent;}doc.body.scrollTop=actualTop;doc.documentElement.scrollTop=actualTop;return false}else{return true}"
    }
</pre>
如果类似网站多的话，我试试提纯简化一下规则写法

**Comment by fireinrain** [comment]
> 找到了一个没人的地方，帮你看了下，这个站类似于百度贴吧，有lazyload，需要这样写
> 
>     {
>         "name": "netflav",
>         "url": "^https://netflav\\.com/",
>         "pageElement": ".video_grid_container>.grid_root",
>         "nextLink": "#general-pagination>div>a[aria-current='true']+a",
>         "wait": "let pagination= doc.querySelector(\"#general-pagination\");let pageReady=pagination&&pagination.style.opacity!=0&&pagination.querySelector(\"a[aria-current='true']+a\");if(doc==document)return pageReady;if(!pageReady)return false;let lazy=doc.querySelector('div.lazyload-placeholder,.grid_cover.image:not(.fadeIn)');if(lazy){var actualTop=lazy.offsetTop;var current=lazy.offsetParent;while(current!==null){actualTop+=current.offsetTop;current=current.offsetParent;}doc.body.scrollTop=actualTop;doc.documentElement.scrollTop=actualTop;return false}else{return true}"
>     }
> 如果类似网站多的话，我试试提纯简化一下规则写法

感谢大佬，大佬666

**Comment by hoothin** [comment]
这是简化规则。
其中waitElement包括两个选择器：
+ 第一个选择器是必须等待至出现的元素（例如这个站的页码部分）
+ 第二个元素是必须等待至消失的元素（例如这个站的加载中的图片，脚本会自动触发lazyload事件以获取完整元素）
<pre>
    {
        "name": "netflav",
        "url": "^https://netflav\\.com/",
        "pageElement": ".video_grid_container>.grid_root",
        "nextLink": "#general-pagination>div>a[aria-current='true']+a",
        "waitElement": [
            "a[aria-current='true']+a",
            "div.lazyload-placeholder,.grid_cover.image:not(.fadeIn)"
        ]
    }
</pre>
