### ISSUE TITLE
虎牙直播会导致直播出现两个声音

### ISSUE THREAD

**Issue by TwooSix** [hoothin/UserScripts#131]
虎牙直播会导致直播出现两个声音

**Comment by hoothin** [comment]
啥？

**Comment by TwooSix** [comment]
> 

开启脚本进入虎牙的网页直播时，会导致当前直播间的声音重复，并且尝试暂停直播后声音依旧存在，每次都可以复现，不知道是不是加载了两个直播源导致的。

**Comment by hoothin** [comment]
哪一个脚本？

**Comment by hoothin** [comment]
永页机不建议在视频站使用，你可以手动禁用

**Comment by TwooSix** [comment]
> 永页机不建议在视频站使用，你可以手动禁用

ok，了解

**Comment by hoothin** [comment]
你也可以添加规则，排除所有视频站
<pre name="pagetual">
  {
    "name":"检测到视频就不运行",
    "url":".",
    "pageElement":"video,iframe[src*=player]",
    "enable":0
  }
</pre>
