### ISSUE TITLE
Skips page 2 on Literotica

### ISSUE THREAD

**Issue by litfan01** [hoothin/UserScripts#133]
Always skips page 2.

**Comment by hoothin** [comment]
Giveme a link at first pls.

**Comment by litfan01** [comment]
here's a link:

https://www.literotica.com/s/the-shepherds-crook-pt-03

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "type": 0,
        "name": "Literotica",
        "action": 0,
        "url": "^https://www\\.literotica\\.com/.",
        "pageElement": "//div[contains(@class,\"panel article\") or @class=\"b-story-list\"]/div",
        "nextLink": "//a[@title='Next Page' or @class='b-pager-next']",
        "insertPos": 1,
        "wait": 2500
    },
</pre>

**Comment by litfan01** [comment]
Got it! Thanks for the quick response.
