### ISSUE TITLE
https://movie.douban.com/tv/    根本停不下来，而禁用后

### ISSUE THREAD

**Issue by xoxlll** [hoothin/UserScripts#134]
，需要翻页的如相册又不工作 https://movie.douban.com/celebrity/1334866/photos/
当添加禁用时，是否仅对上一个子域工作为好？而非全局禁用

**Comment by hoothin** [comment]
豆瓣这个页面禁止无限翻页是写在[规则](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L930)里的。
你看一下你有没有导入并完整更新规则，以及能否正常访问github的[rawcontent](https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json)
不能访问说明你没法过墙，需要用cdn镜像替代。

当然你也可以自定义，假如以后遇到类似的内页不需要翻页的情况，可以打开设置页，点击“编辑黑名单URL”，输入“https://movie.douban.com/tv/*”支持*(任意字符)?(单个字符)两个通配符
