### ISSUE TITLE
微博翻页如何绕开 lazy load？

### ISSUE THREAD

**Issue by twio142** [hoothin/UserScripts#136]
我在微博主页上应用如下设置，虽然能够顺利翻页，但是翻页后再滚动到底部的 lazy load 元素，就无法继续加载页面。

```json
[
    {
        "name": "weibo",
        "url": "^https://weibo\\.com",
        "pageElement": "div.WB_feed",
        "waitElement": [
            "div.WB_feed",
        ],
        "action": 1,
        "nextLink": "a.page.next"
    }
]
```

试过设置 waitElement 的 exist 为页面底部的翻页按钮元素 `div.W_pages`，或是设置 not exist 为 lazy load 元素 `div[node-type=lazyload]`，则完全无法翻页。

请问有解决的办法吗？

**Comment by hoothin** [comment]
哪个页面？微博有好几套前端模板。这个是[微博搜索](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L843)的规则，你可以参考看看
