### ISSUE TITLE
小木虫自动翻页出错

### ISSUE THREAD

**Issue by pencilheart** [hoothin/UserScripts#137]
此页错误地从侧边加载。http://muchong.com/t-10612678-1
![image](https://user-images.githubusercontent.com/61617063/181041012-80cd3082-1092-484b-ba45-dd3241470263.png)

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "小木虫论坛",
        "url": "^http://muchong\\.com",
        "pageElement": "div#maincontent"
    }
</pre>
