### ISSUE TITLE
Photos won't load

### ISSUE THREAD

**Issue by rahaaatul** [hoothin/UserScripts#138]
**Description**
Posters won't load in `yts.mx` from page 2 onwards.

**To Reproduce**
1. Go to 'https://yts.mx/'
2. Search something
3. Keep scrolling

**Expected behavior**
Should load the picture.

**Screenshots**
![Screenshot_20220727_215331](https://user-images.githubusercontent.com/86149861/181294058-c0fa1948-0c4b-4e51-8c0a-225b38c2eb4c.jpg)

**Smartphone:**
![Screenshot_2022_0727_220130](https://user-images.githubusercontent.com/86149861/181294716-5a17bcc1-6357-471a-ba83-fb9fec611aad.jpg)

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "YTS Movies",
        "type": 0,
        "url": "^https://yts\\.mx/browse-movies",
        "pageElement": "//section/div[@class=\"row\"]/div",
        "nextLink": "//li[./a[@class=\"current\"]]/following-sibling::li[1]/a",
        "css": "img{visibility: visible!important; display: block!important;}"
    }
</pre>

**Comment by rahaaatul** [comment]
> {
>         "name": "YTS Movies",
>         "type": 0,
>         "url": "^https://yts\\.mx/browse-movies",
>         "pageElement": "//section/div[@class=\"row\"]/div",
>         "nextLink": "//li[./a[@class=\"current\"]]/following-sibling::li[1]/a",
>         "css": "img{visibility: visible!important; display: block!important;}",
>         "lazyImgSrc":"data-cfsrc"
>     }

That Fixed it. Thank you @hoothin
