### ISSUE TITLE
GitHub page issue

### ISSUE THREAD

**Issue by rahaaatul** [hoothin/UserScripts#140]
# Description
GitHub page is narrowed slightly by white block line like this -
![Screenshot_20220728_182318](https://user-images.githubusercontent.com/86149861/181504536-e71ba93b-1902-41b5-a58d-5dcc5ce900d9.jpg)

# Steps to reproduce the issue
1. Go to [Github](https://github.com/hoothin/UserScripts/tree/master/Pagetual) 

# Expected behavior
![Screenshot_20220728_183252](https://user-images.githubusercontent.com/86149861/181505758-86c02acd-7d97-425b-90d2-76738ee0baa0.jpg)

# Device Information
 - Device: Vivo V2043
 - OS: Android 11
 - Browser: Kiwi Browser (103.0.5060.104)
 - Pagetual Version: 1.9.30.3.11

**Comment by rahaaatul** [comment]
Also this happens while scrolling,
![Screenshot_20220728_184000](https://user-images.githubusercontent.com/86149861/181507290-b671bf56-b7cd-45e7-8953-de59d352404c.jpg)

**Comment by hoothin** [comment]
Fixed in version 1.9.30.3.16.5

**Comment by rahaaatul** [comment]
> Fixed in version 1.9.30.3.16.5

I think it because of this box right in the bottom that's causing this issue
![chrome_screenshot_Jul 28, 2022 7_19_43 PM GMT+06_00](https://user-images.githubusercontent.com/86149861/181515594-b7fc1e76-2d9e-4253-ba50-7bbd10eee46f.png)

Is this browser problem? Cause if I turn pagetual off, that configuration table goes away and it works okay. But if I turn pagetual on, the problem comes back.

**Comment by hoothin** [comment]
Have you already updated the script?

**Comment by rahaaatul** [comment]
> Have you already updated the script?

Yes, I did.

**Comment by hoothin** [comment]
Maybe you should try to check your script's version again to make sure that the version is latest.
![image](https://user-images.githubusercontent.com/5361213/181518200-5d3bfc86-af30-425c-b2ee-de37a5f3c375.png)

**Comment by hoothin** [comment]
Just update from github, click the pagetual.user.js and view raw then.

**Comment by rahaaatul** [comment]
> Just update from github, click the pagetual.user.js and view raw then.

Sorry I thought, when I clicked update all scripts, it updated all the scripts, but it didn't. So I reinstalled it again and now it's working fine.

Thank you.
