### ISSUE TITLE
Configuration won't save

### ISSUE THREAD

**Issue by rahaaatul** [hoothin/UserScripts#141]
# Description
Trying to configure the personal configuration but it won't save the value.

# Steps to reproduce the behavior:
1. Go to [Configuration](https://github.com/hoothin/UserScripts/tree/master/Pagetual) 
2. Input something in personal configuration, eg. Opacity to 0.
3. Refresh.
4. See error.

# Expected behavior
Should save the value.

# Device Information
 - Device: Vivo V2043
 - OS: Android 11
 - Browser: Kiwi Browser (103.0.5060.104)
 - Pagetual Version: 1.9.30.3.11

**Comment by hoothin** [comment]
You should click the save button.

**Comment by rahaaatul** [comment]
> You should click the save button.

This one?
![Screenshot_2022_0728_184708](https://user-images.githubusercontent.com/86149861/181508554-685f8a88-f2a5-4ce5-ae8e-64d796be9abf.jpg)
I did. But nothing happened. I thought this was for custom rules only. Other than this one there's no save button.

**Comment by hoothin** [comment]
Yes, That will be a little difficult to click it on phone. I'll optimize it for phone view soon.

**Comment by rahaaatul** [comment]
Thanks.
