### ISSUE TITLE
"强制拼接"被删除了？

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#142]
https://www.maofly.com/manga/32015/370253_2.html
在这个网页，似乎是有规则触发的。但它一直处于加载中。这种情况我都会试试强制拼接。
但现在工具栏找不到强制拼接按钮了，它被删除了吗？

我也试用了"编辑此站规则"下的元素选择工具。为什么只有主体的选择，没有"下一页拉链"的选择呢？

**Comment by hoothin** [comment]
估计因为这个站下一页没有链接，你可以把鼠标放上去看看。没有链接是没法强制拼接的。一直加载说明网站有反爬，只能自己写规则拼接请求获取数据再生成列表

**Comment by hoothin** [comment]
遇到这种情况你只能提交上来，等我空了写个规则。没有比较通用的傻瓜式的兼容方案

**Comment by Frozen1084** [comment]
好的，谢谢。
