### ISSUE TITLE
[Urgent] Not Working on this website for jobs

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#144]
Hi there,,hope you are doing well

So it doesn't to work on this website at all, I am not much of a tech geek just a general user.

https://www.hirelateral.com/latest-government-jobs-india

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

Please guide me how to fix this. Need this urgently

![Screenshot from 2022-07-29 17-28-54](https://user-images.githubusercontent.com/64612555/181753963-c74699bb-fc30-42a6-ae24-6d95aeac7e51.png)

**Comment by hoothin** [comment]
just for this page, let me know if you found any page on this site that don't work as expect
<pre name="pagetual">
    {
        "name": "hirelateral",
        "url": "^https://www\\.hirelateral\\.com/",
        "pageElement": "div.mainwrap > div.contentwrap > div.leftwrap > table.table-bordered.table-hover.govt_tbl > tbody> tr.govt_tr"
    }
</pre>

**Comment by rakitanc** [comment]
Thankyou so much brother. it's working Now. You are the Best

I have one request to you..is there a way to apply search functionality on this website, as they dont have . So if there's a particular job i am looking for i can do that. In this case i was looking for "Steno" or "Stenographer"

Right now with pagination i could use the find function but  in that not all the details are mentioned on that job and the keyword is not there But when you some job  link, you find that That job position is also available under description. I hope you get my point. I tried my best to explain

**Comment by hoothin** [comment]
I think you'd better to search "site:www.hirelateral.com Stenographer" with some search engines.

**Comment by rakitanc** [comment]
Just a little off topic but needed your help with this. 

Is there a way to search through this pdf for text as really hard to find what to look for in this as they release every week

https://sikkusports.com/wp-content/uploads/2022/07/Employment-News-16-22-July-2022-1.pdf

**Comment by rakitanc** [comment]
> I think you'd better to search "site:[www.hirelateral.com](http://www.hirelateral.com) Stenographer" with some search engines.

Not working on this website Brother..After reload only loads one next page

https://agristudyinfo.in/

**Comment by rakitanc** [comment]
Same here 

https://20govtjobs.com/?s=STENO

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name": "Agristudyinfo & 20govtjobs",
    "url": "^(https://agristudyinfo\\.in/|https://20govtjobs\\.com/)",
    "pageElement": "#main>article",
    "nextLink": ".page-numbers.current+a"
  }
</pre>

**Comment by rahaaatul** [comment]
@hoothin off topic but related
Pagetual isn't working on this [site](https://www.animetime.pw/)

**Comment by hoothin** [comment]
Update script first
<pre name="pagetual">
    {
        "name": "Anime Time",
        "url": "^https://www\\.animetime\\.pw",
        "pageElement": "div.blog-posts.container > div.grid-posts",
        "nextLink": "a.page-num.page-next",
        "waitElement": [
            "",
            "img.post-thumb:not(.lazy-yard)"
        ]
    }
</pre>

**Comment by rahaaatul** [comment]
> Update script first

It worked! But it takes time to load the next pages at least 3 seconds after you reach the 1st page.

How should I force it to load at least 3 pages from the start?

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Anime Time",
        "url": "^https://www\\.animetime\\.pw",
        "pageElement": "div.blog-posts.container > div.grid-posts",
        "nextLink": "a.page-num.page-next",
        "rate": "3",
        "waitElement": [
            "",
            "img.post-thumb:not(.lazy-yard)"
        ]
    }
</pre>

**Comment by rahaaatul** [comment]
> {
>         "name": "Anime Time",
>         "url": "^https://www\\.animetime\\.pw",
>         "pageElement": "div.blog-posts.container > div.grid-posts",
>         "nextLink": "a.page-num.page-next",
>         "rate": "3",
>         "waitElement": [
>             "",
>             "img.post-thumb:not(.lazy-yard)"
>         ]
>     }


Didn't work. It's the same, have to go down to load next page.
https://user-images.githubusercontent.com/86149861/182025086-270336f1-7fb6-4855-ae4f-c3ea2a75d93b.mp4

**Comment by hoothin** [comment]
Yes, it's just for load before scroll to bottom.
You should click the command "load next page now" to auto load next 10 pages.

**Comment by rahaaatul** [comment]
> Yes, it's just for load before scroll to bottom. You should click the command "load next page now" to auto load next 10 pages.

Yes, that's what I was asking. How do I force it to load next 10 pages without clicking the command "load next page now"?

**Comment by hoothin** [comment]
Update the script first
<pre name="pagetual">
    {
        "name": "Anime Time",
        "url": "^https://www\\.animetime\\.pw",
        "pageElement": "div.blog-posts.container > div.grid-posts",
        "nextLink": "a.page-num.page-next",
        "autoLoadNum": 10,
        "waitElement": [
            "",
            "img.post-thumb:not(.lazy-yard)"
        ]
    }
</pre>

**Comment by rahaaatul** [comment]
> Update the script first
> <pre name="pagetual">
>     {
>         "name": "Anime Time",
>         "url": "^https://www\\.animetime\\.pw",
>         "pageElement": "div.blog-posts.container > div.grid-posts",
>         "nextLink": "a.page-num.page-next",
>         "autoLoadNum": 10,
>         "waitElement": [
>             "",
>             "img.post-thumb:not(.lazy-yard)"
>         ]
>     }
> </pre>

Perfect! Do you think I could do this for all pages with one custom rule?

**Comment by rahaaatul** [comment]
@hoothin 
> Update the script first

- When you open the site, it automatically goes down.
- You have to wait for it to load the pages, even with preloading 10 page on.

**Demo Video**:

https://user-images.githubusercontent.com/86149861/182100841-83b38fbb-dce0-4878-ada4-2b2d686805b2.mp4

**Comment by hoothin** [comment]
> @hoothin
> 
> > Update the script first
> 
> * When you open the site, it automatically goes down.
> * You have to wait for it to load the pages, even with preloading 10 page on.
> 

Still under kiwi & android?

**Comment by rakitanc** [comment]
Hey mate..why is that on

**Comment by rakitanc** [comment]
Hey mate..why is that on Ycombinator the page scroll down automatically. How do i turn it off?

https://news.ycombinator.com/item?id=32304456

**Comment by rahaaatul** [comment]
> Hey mate..why is that on Ycombinator the page scroll down automatically. How do i turn it off?
> 
> https://news.ycombinator.com/item?id=32304456

Same thing as the issue related to my comment before. @hoothin

**Comment by rahaaatul** [comment]
> Hey mate..why is that on Ycombinator the page scroll down automatically. How do i turn it off?
> 
> https://news.ycombinator.com/item?id=32304456

The issue doesn't occur for me with Kiwi Browser & Violentmonkey, but does with IceRaven & TamperMonkey.

**Comment by hoothin** [comment]
Hello there, the two issues above are fixed, need more test.

**Comment by rahaaatul** [comment]
> Hello there, the two issues above are fixed, need more test.

For me, https://news.ycombinator.com/item?id=32304456 is fixed. But,
AnimeTime is still behaving the same. Auto scrolls down and keep loading page 1 by 1.

**Comment by hoothin** [comment]
You can try the version 1.9.30.6.10.
If it still does not effect, you can try this rule.
<pre name="pagetual">
    {
        "name": "Anime Time",
        "url": "^https://www\\.animetime\\.pw",
        "pageElement": "div.blog-posts.container > div.grid-posts>*",
        "nextLink": "a.page-num.page-next",
        "pageAction": "eles.forEach(ele=>{let img=ele.querySelector('img');if(!img)return;img.classList.add('lazy-yard');img.src=img.src.replace('w72-h72','w325-h198')})"
    }
</pre>

**Comment by rahaaatul** [comment]
> You can try the version 1.9.30.6.10.
> If it still does not effect, you can try this rule.
> <pre name="pagetual">
>     {
>         "name": "Anime Time",
>         "url": "^https://www\\.animetime\\.pw",
>         "pageElement": "div.blog-posts.container > div.grid-posts>*",
>         "nextLink": "a.page-num.page-next",
>         "pageAction": "eles.forEach(ele=>{let img=ele.querySelector('img');if(!img)return;img.classList.add('lazy-yard');img.src=img.src.replace('w72-h72','w325-h198')})"
>     }
> </pre>

YOU DID IT! IT'S WORKING!
Thank you.
