### ISSUE TITLE
Pagetual: Preload X Amount

### ISSUE THREAD

**Issue by rahaaatul** [hoothin/UserScripts#145]
# Description
Some page takes too much time to load, or we want all sites to already load at least `x` amount. So an option in configuration to set custom amount to preload pages would be very helpful.

# Solution
Add a setting in configuration, naming **Preload [`x`] pages** under **Preload next page for speeding up**. This will always preload `x` amount of pages in all sites that pagetual supports.

# Alternative Solution
We could set up a custom rule for a single site. But wouldn't it be great if we could do it for all?

Idea came from this [issue](https://github.com/hoothin/UserScripts/issues/144#issuecomment-1200417027_).

**Comment by hoothin** [comment]
Done

**Comment by rahaaatul** [comment]
> Done

Awesome! Can you fix this?
![IMG_20220801_113008.jpg](https://user-images.githubusercontent.com/86149861/182078498-a2ccb6db-406c-44bc-9349-44eb6a99bf08.jpg)
Can't see what's in there.

**Comment by hoothin** [comment]
fixed, need your test.

**Comment by rahaaatul** [comment]
> fixed, need your test.

Super! It's fixed for me too.
![Screenshot_2022_0801_132059.jpg](https://user-images.githubusercontent.com/86149861/182094517-b7c1691e-7343-4449-9858-8f527b73bacc.jpg)
