### ISSUE TITLE
请求适配

### ISSUE THREAD

**Issue by pencilheart** [hoothin/UserScripts#147]
请求适配https://www.voachinese.com/a/pelosi-taiwan-visit-update/6683521.html

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "voachinese",
        "url": "^https://www\\.voachinese\\.com",
        "loadMore": ".btn--load-more>a.link-showMore",
        "nextLink": 0
    }
</pre>

**Comment by hoothin** [comment]
还有点bug，会点击不存在的加载更多，等会儿修正

**Comment by pencilheart** [comment]
感谢👍

**Comment by hoothin** [comment]
应该可以了，你试试
