### ISSUE TITLE
[东方永页机] 翻页结果为前一页结果?

### ISSUE THREAD

**Issue by Bush2021** [hoothin/UserScripts#149]
**Describe the bug**
在卡饭论坛中打开一个帖子的最后一页, 正常应该不翻页才对, 最近会往前翻页

**To Reproduce**
重现该行为的步骤: 
1. 打开 https://bbs.kafan.cn/thread-2240658-1-1.html
2. 选择最后一页并滑到底部
3. 复现

**Expected behavior**
当原本是最后一页是, 停止翻页

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome v104
 - Version: 1.9.30.6.26.3

**Comment by hoothin** [comment]
这是新加的特性，和命令菜单中的“切换下一页选择器”相绑定。
可以切换向前翻页或者向后翻页。
你是觉得不适应吗？

**Comment by hoothin** [comment]
不想要这个特性的话可以用以下自定义规则覆盖
<pre name="pagetual">
{
    "name": "bbsPostlist1",
    "url": "/t",
    "nextLink": "a.nxt",
    "pageNum": "\\-\\d+\\-{$p}\\-\\d+\\.html",
    "pageElement": "div#postlist>*"
}
</pre>

**Comment by Bush2021** [comment]
> 这是新加的特性，和命令菜单中的“切换下一页选择器”相绑定。 可以切换向前翻页或者向后翻页。 你是觉得不适应吗？
> 
> 试想假如一页之中有3套页码，这个特性可以分别指定3套不同的下一页和页面内容。 而用户并不知道当前页面中哪一套存在，所以寻找规则中指定的已存在的页码并且以此为基准是符合期望的行为。

抱歉, 您说的3套页码是什么意思呢?
一般 (尤其是在论坛) 不会有人向前翻页吧?
这个功能应该和论坛中的"正序浏览"和"倒叙浏览"相适应吧? 不然太怪了

**Comment by Bush2021** [comment]
> 

额, 怎么我导入了该规则还是不行呀?

**Comment by hoothin** [comment]
你怎么导入的？

**Comment by Bush2021** [comment]
> 你怎么导入的？

直接点击你的回复右侧的导入按钮

**Comment by hoothin** [comment]
你看看你控制台使用的是哪一条规则？

**Comment by Bush2021** [comment]
> 你看看你控制台使用的是哪一条规则？

控制台是指这个吗?
![2022-08-06_232116](https://user-images.githubusercontent.com/79072750/183255316-4201c032-3c4e-40e8-bad5-4b5110979def.jpg)

**Comment by hoothin** [comment]
是浏览器控制台

**Comment by Bush2021** [comment]
> 是浏览器控制台

怎么看啊

**Comment by hoothin** [comment]
我想了下，还是把自动查找去掉了
现在这一版不手动指定就不会取其他页码
