### ISSUE TITLE
快捷键问题

### ISSUE THREAD

**Issue by SettingDust** [hoothin/UserScripts#15]
和N卡的Experience自带录制会冲突，还是比较普及的软件吧，希望可以改成192 就是Esc底下~`这个键，摁起来一只手也方便 ，自用已改OVO

**Comment by hoothin** [comment]
感谢反馈，但是alt+`和老板键冲突了ㄒoㄒ，另外如果Experience自带录制也用alt+f8，那vs的格式重排、excel的显示“宏”不是都不能用了？所以换作我的使用场景，更改Experience快捷键可能更合适
