### ISSUE TITLE
Add Collage to Picview CE+

### ISSUE THREAD

**Issue by neoOpus** [hoothin/UserScripts#150]
Hi,

It would be great to add the possibility to make a collage and also add some text to the picture that've been selected, without the need to download and use another software or service...
This can be handy when you want to share a meme, or a compilation of pictures to explain a point...

Have the ability to customize the disposition and spacing would be cool, but if an algorithm can just do that automagically via a preset selection, it is super fine.

For adding text, this is optional and only if there is a library that could help otherwise... but if you go for it then, maybe having google fonts and RTL support and being able to some transformations to the text like rotation, adding shadow, changing background color with transparency, and saving a preset or a template.

Thank you.

**Comment by hoothin** [comment]
Thanks, I think you'd better click "online edit" to seek more powerful functions like collage.
Picviewer ce+ is a free open source software to view online pictures. I don't think it's a good idea to make it too heavy.
