### ISSUE TITLE
github加载下一页很慢

### ISSUE THREAD

**Issue by photkey** [hoothin/UserScripts#154]
github加载下一页非常慢，以至于经常无响应一段时间

已经挂了梯子，手动点击下一页加载是很快的。

版本 1.9.30.6.26.8
Edge浏览器

**Comment by hoothin** [comment]
我这边加载很顺畅，大概等待半秒就行。
永页机加载的流量是从扩展走的，也许你可以往这个方向找找原因。

**Comment by photkey** [comment]
应该不是这个原因，我是用的软路由 全局都可以翻墙的，之前有段时间加载也是很流畅的，就是最近几天 开始 就总是加载很慢。
要么我换个浏览器试试。

**Comment by hoothin** [comment]
应该也和浏览器没关系，我自己edge chrome firefox都在用。
刚刚用edge测试了一下，也是很顺畅的。

**Comment by photkey** [comment]
![github](https://user-images.githubusercontent.com/60434581/184596880-c4a6a8b0-492c-4ce1-86e0-6814d708b124.gif)

不知道该从哪里排查了……

**Comment by hoothin** [comment]
终极大法，删除永页机重装试试😄

**Comment by photkey** [comment]
![github禁用](https://user-images.githubusercontent.com/60434581/184597324-30e38c66-37cf-4db0-8fe4-4bad33bce5e7.gif)
这是我禁用后，手动翻页，速度挺快的

**Comment by hoothin** [comment]
你应该已经导入规则库了吧？打开控制台看看用的是哪一条规则呢？如果是框架加载的规则确实会很慢

**Comment by hoothin** [comment]
emm需要重现
