### ISSUE TITLE
Turn off right/left arrows keybinds.

### ISSUE THREAD

**Issue by younyokel** [hoothin/UserScripts#155]
Hello. How do I turn off right/left arrow keys binds so I would be able to use Picviewer gallery?

**Comment by hoothin** [comment]
I will make a option to turn off on next version.
May I ask why do you want to turn off these binds?

**Comment by younyokel** [comment]
> I will make a option to turn off on next version. May I ask why do you want to turn off these binds?

I use Picviewer CE+ on imageboards. In gallery mode, I would be happy to use the keyboard to change images rather than the mouse.

**Comment by younyokel** [comment]
Nice. Can you add the same option for Pagetual?

**Comment by hoothin** [comment]
I think Pagetual has no function about arrow key. What did you mean by it?

**Comment by younyokel** [comment]
> I think Pagetual has no function about arrow key. What did you mean by it?

Oh, nevermind. Apparently the keyboard shortcuts were at the site, so I had the page change when I pressed the arrows. Closing the issue.
