### ISSUE TITLE
适配请求https://www.cdxsw.cc/

### ISSUE THREAD

**Issue by dk0pp** [hoothin/UserScripts#157]
适配请求https://www.cdxsw.cc/

**Comment by dk0pp** [comment]
目录https://www.cdxsw.cc/53/53458/
分页第一章第一页https://www.cdxsw.cc/53/53458/32430724.html
分页第一章第二页https://www.cdxsw.cc/53/53458/32430724_1.html

**Comment by hoothin** [comment]
<pre>
.section-list>li>a@@@@@@let content="";let checkContent=(doc,over)=>{word=doc.querySelector('.word_read');if(!word)content+='\n'+doc.body.innerText;else [].forEach.call(word.querySelectorAll('p,h3'),c=>content+='\n'+c.innerText);let next=doc.querySelector(".read_btn>a:nth-child(4)");if(next&&/_\d\.html/.test(next.href)){fetch(next.href).then(r => r.text()).then(d => {let _doc = document.implementation.createHTMLDocument('');_doc.documentElement.innerHTML = d;checkContent(_doc,over);});}else over();};checkContent(data,()=>{cb(content)});return false;
</pre>
可以先用永页机翻完全部章节再用自定义下载。

**Comment by dk0pp** [comment]
谢谢，我试试

**Comment by hoothin** [comment]
记得先更新脚本

**Comment by dk0pp** [comment]
嗯嗯~
