### ISSUE TITLE
Translations for Pagetual?

### ISSUE THREAD

**Issue by younyokel** [hoothin/UserScripts#158]
Hi, are there any plans of translating Pagetual with different languages?

**Comment by hoothin** [comment]
All translations are welcome:)
<PRE>
                enableDebug:"Enable debug output",
                disable:"Disable",
                disableSite:"Toggle disabled state",
                disableSiteTips:"Disabled on this site",
                enableSiteTips:"Enabled on this site",
                enable:"Enable",
                toTop:"To Top",
                toBottom:"To Bottom",
                current:"Current Page",
                forceIframe:"Force to join next page",
                cancelForceIframe:"Cancel Force join",
                configure:"Configure",
                firstUpdate:"Click here to initialize the rules",
                update:"Update online rules",
                click2update:"Click to update rules from url now",
                loadNow:"Load next page now",
                loadConfirm:"How much pages do you want to load? (0 means infinite)",
                noNext:"No next link found, please create a new rule",
                passSec:"Updated #t# seconds ago",
                passMin:"Updated #t# minutes ago",
                passHour:"Updated #t# hours ago",
                passDay:"Updated #t# days ago",
                cantDel:"Can't delete buildin rules",
                confirmDel:"Are you sure you want to delete this rule?",
                updateSucc:"Update succeeded",
                beginUpdate:"Begin update, wait a minute please",
                customUrls:"Import Pagetual or AutoPagerize rule url, One url per line",
                customRules:"Input custom rules with [Pagetual] format",
                save:"Save",
                loadingText:"Shojo Now Loading...",
                opacity:"Opacity",
                opacityPlaceholder:"0:hide",
                hideBar:"hide the paging spacer",
                dbClick2Stop:"Double-click on the blank space to pause",
                sortTitle:"Sorting takes effect after the next rule update",
                autoRun:"Auto run (black list mode)",
                autoLoadNum:"Amount for preload pages",
                inputPageNum:"Enter page number to jump",
                enableHistory:"Write history after page turning",
                initRun:"Turn pages immediately after opening",
                preload:"Preload next page for speeding up",
                click2ImportRule:"Click to import base rules link, then wait until the update is complete:",
                forceAllBody:"Join full body of page?",
                openInNewTab:"Open urls of additions in new tab",
                importSucc:"Import completed",
                import:"Import",
                editCurrent:"Edit rule for current",
                editBlacklist:"Edit the blacklist urls, line by line, Support ? * for wildcard",
                upBtnImg:"Icon of back to top",
                downBtnImg:"Icon of go to footer",
                loadingTextTitle:"Loading text",
                dbClick2StopCtrl:"Ctrl key",
                dbClick2StopAlt:"Alt key",
                dbClick2StopShift:"Shift key",
                dbClick2StopMeta:"Meta key",
                dbClick2StopKey:"Shortcut key",
                pageElementCss:"Custom style for main page elements",
                customCss:"Custom complete css",
                firstAlert:"You have not imported the base rule, please select the appropriate rule to import",
                picker:"Pagetual page element picker",
                closePicker:"Close Pagetual picker",
                pickerPlaceholder:"Leave empty if you have no idea",
                pickerCheck:"Check selector",
                gotoEdit:"Go to edit rule with current selector",
                manualMode:"Disable splicing, manually turn pages with the right arrow keys (or dispatch event 'pagetual.next')",
                nextSwitch:"Switch next link"
</PRE>

**Comment by younyokel** [comment]
I made the Russian translation for myself, but if you want you can add it too 😉
```
case "ru":
            config={
                enableDebug:"Включить отладку",
                disable:"Отключить",
                disableSite:"Переключить состояние отключения",
                disableSiteTips:"Отключено на этом сайте",
                enableSiteTips:"Включено на этом сайте",
                enable:"Включить",
                toTop:"В начало",
                toBottom:"В конец",
                current:"Текущая страница",
                forceIframe:"Принудительно присоединить следующую страницу",
                cancelForceIframe:"Отменить принудительное присоединение",
                configure:"Настроить",
                firstUpdate:"Нажмите здесь, чтобы инициализировать правила",
                update:"Обновить правила онлайн",
                click2update:"Нажмите, чтобы обновить правила по URL сейчас",
                loadNow:"Загрузить следующую страницу сейчас",
                loadConfirm:"Сколько страниц вы хотите загрузить? (0 означает бесконечность)",
                noNext:"Ссылка на следующую страницу не найдена, пожалуйста, создайте новое правило",
                passSec:"Обновлено #t# секунд назад",
                passMin:"Обновлено #t# минут назад",
                passHour:"Обновлено #t# часов назад",
                passDay:"Обновлено #t# дней назад",
                cantDel:"Невозможно удалить встроенные правила",
                confirmDel:"Вы уверены, что хотите удалить это правило?",
                updateSucc:"Обновление прошло успешно",
                beginUpdate:"Обновление начато, подождите минуту, пожалуйста",
                customUrls:"Импортировать URL-адрес правила Пэйджтуал или AutoPagerize по одному URL на строку",
                customRules:"Введите пользовательские правила с форматом [Pagetual]",
                save:"Сохранить",
                loadingText:"Shojo загружается...",
                opacity:"Непрозрачность",
                opacityPlaceholder:"0:скрыть",
                hideBar:"скрыть промежуток переключения страниц",
                dbClick2Stop:"Двойной щелчок по пустому пространству для паузы",
                sortTitle:"Сортировка вступает в силу после следующего обновления правила",
                autoRun:"Автозапуск (режим черного списка)",
                autoLoadNum:"Количество для предварительной загрузки страниц",
                inputPageNum:"Введите номер страницы для перехода",
                enableHistory:"Записать историю после переключения страниц",
                initRun:"Переключать страницы сразу после открытия",
                preload:"Предварительная загрузка следующей страницы для ускорения",
                click2ImportRule:"Нажмите, чтобы импортировать ссылку базовых правил, затем дождитесь завершения обновления:",
                forceAllBody:"Присоединить полное тело страницы?",
                openInNewTab:"Открыть дополнительные URL-адреса в новой вкладке",
                importSucc:"Импорт завершен",
                import:"Импорт",
                editCurrent:"Редактировать правило для текущего",
                editBlacklist:"Редактировать URL-адреса черного списка, по одной строке, поддержка ? * для подстановочного знака",
                upBtnImg:"Иконка возврата к началу",
                downBtnImg:"Иконка перехода в нижний колонтитул",
                loadingTextTitle:"Текст загрузки",
                dbClick2StopCtrl:"Клавиша Ctrl",
                dbClick2StopAlt:"Клавиша Alt",
                dbClick2StopShift:"Клавиша Shift",
                dbClick2StopMeta:"Клавиша Meta",
                dbClick2StopKey:"Клавиша быстрого доступа",
                pageElementCss:"Пользовательский стиль для основных элементов страницы",
                customCss:"Полный пользовательский CSS",
                firstAlert:"Вы не импортировали базовое правило, пожалуйста, выберите соответствующее правило для импорта",
                picker:"Выбор элемента страницы Пэйджтуал",
                closePicker:"Закрыть выбор Пэйджтуал",
                pickerPlaceholder:"Оставьте пустым, если вы не знаете",
                pickerCheck:"Проверить селектор",
                gotoEdit:"Перейти к редактированию правила с текущим селектором",
                manualMode:"Отключить автоматическую перелистывание страниц, перелистывать страницы вручную с помощью стрелок справа (или вызвать событие 'pagetual.next')",
                nextSwitch:"Переключить ссылку на следующую страницу"
            };
```

**Comment by hoothin** [comment]
Thank you, it's added now.
