### ISSUE TITLE
I need assistance with using Pager

### ISSUE THREAD

**Issue by DeathNorn** [hoothin/UserScripts#159]
**Device: iPhone 12 
Web browser: Safari
Sofware Version: IOS 15.6.1**

I wanted to use pager on imhentai.xxx but I don’t know how?

When I use pager on this site it works when going through comics in the home menu.  But when I click on the comic, and click on the image to read it.  It doesn’t load the next page under it 

I tried this line of code 
`[
  {
    "name":imhentai",
    "url":"https://imhentai.xxx",
    "pageElement":"body > div.overlay > div.container > div.row.gallery_view > div.col-md-12.gview > div.nav_pagination.col-md-12 > a.nav_next > i.fa.fa-chevron-right"
  }
]`

But I didn’t know where to put it in the script to begin with since I didn’t see any instructions on where to paste it?

**Comment by DeathNorn** [comment]
Also when you "load next page now" it it shows it multiples times/each time you hit ok or cancel (BUG)

**Comment by hoothin** [comment]
As I said on greasyfork, you'd better to check your script manager at first. Maybe you have multiple managers and install twice.
For "imhentai.xxx", use this rule.
Make sure you have updated script.
<pre name="pagetual">
    {
        "name": "IMHentai",
        "url": "^https://imhentai\\.xxx",
        "pageElement": "#gimg",
        "nextLink": ".nav_next",
        "css": "#footer,#bar{display:none}.pre_img+.nav_pagination{bottom: 10px; position: fixed; width: 100%;}.return_btn{bottom: 0; position: fixed; width: 100%;}"
    }
</pre>

**Comment by DeathNorn** [comment]
Where do I put the script? ![image](https://user-images.githubusercontent.com/75560758/187224719-2cdb0f4a-fa94-4b5a-a218-e359d01e28d5.jpeg)

**Comment by DeathNorn** [comment]
Nvm mind I just have to sue [code in here] anywhere where there's a empty space
