### ISSUE TITLE
The line of code won't work on Pager

### ISSUE THREAD

**Issue by DeathNorn** [hoothin/UserScripts#160]
**Device:iPhone 12
Script:Up to date
Problem:Very little understanding of scripts in general**

![image](https://user-images.githubusercontent.com/75560758/187309163-43a94834-487c-4956-8e61-96a00ae689c8.jpeg)

**Line of code used:**

```

```[    
  {
        "name": "IMHentai",
        "url": "^https://imhentai\\.xxx",
        "pageElement": "#gimg",
        "nextLink": ".nav_next",
        "css": "#footer,#bar{display:none}.pre_img+.nav_pagination{bottom: 10px; position: fixed; width: 100%;}.return_btn{bottom: 0; position: fixed; width: 100%;}"
  }
]

**Ps** _Please tell where and how to paste the line of code into the script_

**Comment by hoothin** [comment]
Hi, it seems that you are a beginner of user script.
You can import my rule follow below, DO NOT paste into code:
+ open the issue page #159 
+ refresh the page
+ click the import button when mouse over the rule content

That's all.
