### ISSUE TITLE
Misunderstanding

### ISSUE THREAD

**Issue by DeathNorn** [hoothin/UserScripts#161]
I don't have a curser to hover over the rule do I touch it?

**Comment by hoothin** [comment]
Just to try it dude😿
![image](https://user-images.githubusercontent.com/5361213/187327364-66bd6db9-2f9e-4c86-90fe-9f18af67a76b.png)

**Comment by DeathNorn** [comment]
I don’t see that little import button on my phone?

**Comment by hoothin** [comment]
Touch it and you'll see.

**Comment by DeathNorn** [comment]
![3CF45060-205A-4ECF-A181-0963CC4CC6E2](https://user-images.githubusercontent.com/75560758/187328121-9c26df6c-f77f-40ef-b715-235be31c258e.jpeg) no button and I touched it mutile times

**Comment by hoothin** [comment]
Since you modified the code of script, anything will be destroyed. 
So reinstall it at first.

**Comment by DeathNorn** [comment]
Ok

**Comment by DeathNorn** [comment]
I’m using “stay 2” the app to manage my scripts maybe it’s my script manager if you have any apps I could use for iOS other than this one
![AF8A6032-2399-492B-A2AF-DDB78736796D](https://user-images.githubusercontent.com/75560758/187328460-0bb56936-cf20-4a94-a499-df3a0b8350c8.jpeg)

**Comment by DeathNorn** [comment]
Reinstalling doesn’t work

**Comment by hoothin** [comment]
As I know, stay 2 is not a fine platform and safari do not make a full support for user script.
btw, I test pagetual on ios with [this](https://apps.apple.com/us/app/userscripts/id1463298887)

**Comment by DeathNorn** [comment]
Ok I'll download scriptable used it before but though the other app was better

**Comment by DeathNorn** [comment]
It worked on that app thank you
Well at least importing it

**Comment by DeathNorn** [comment]
Holly Molly thank you your a real g and I love your script
