### ISSUE TITLE
插件关闭依旧生效

### ISSUE THREAD

**Issue by 3217333857** [hoothin/UserScripts#162]
油猴里面关掉插件还是依旧生效，这个插件会导致有些网站排版很奇怪，无法正常阅读，请问如何解决，我在网站点击切换禁用状态也没用

**Comment by hoothin** [comment]
检查下是否装了诸如暴力猴或者Tampermonkey之类的多个脚本管理器

**Comment by 3217333857** [comment]
> 检查下是否装了诸如暴力猴或者Tampermonkey之类的多个脚本管理器

是的，我用的是Tampermonkey，不管是在油猴里面关掉永页机，还是直接把油猴关掉，永页机插件依旧会生效

**Comment by hoothin** [comment]
没有脚本管理器，永页机是不会运行的。
所以你应该是在其他脚本管理器上也安装了一份永页机，你可以检查一下运行中的扩展，看下其中有没有其他脚本管理器

**Comment by 3217333857** [comment]
> 

我懂了谢谢谢谢，我想起了csdn插件也自带脚本管理
