### ISSUE TITLE
konachan 站无法正常显示(NSFW) 

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#164]
https://konachan.com/post?page=2&tags=

内置规则似乎是正常预读了的，但显示时出了问题。只显示一个长条。
强制拼接也没有效果。

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Moebooru:Danbooru clones",
        "url": "^https?://(konachan\\.com|yande\\.re|www\\.sakugabooru\\.com)/(post|comment)($|\\?|#|/search\\?)",
        "pageElement": "//li[contains(@class, 'creator-id-')]|//div[@id='comment-list']/div[@class='post']|//table[@class='highlightable']",
        "nextLink": "//a[@class='next_page']",
        "css": ".javascript-hide { display: inline-block !important; }.pagetual_pageBar { display: inline-flex!important;width: 100%!important; }"
    }
</pre>
用这个，原因是匹配到的wedata规则加了@-moz-document，只会在火狐上取消隐藏

**Comment by Frozen1084** [comment]
谢谢。
不过还是那个老问题。滚动到底部时，开始持续加载，并保持在底部。正常应该跳到新加载页面的顶部才合理。虽然也是因为新加载的页面高度过小。

另外，可以自定义下一页关键词吗？比如这页是有"[Next](https://konachan.com/post/show/345606)"链接的，但强制拼接无法触发。
https://konachan.com/post/show/345605/animal-barefoot-blonde_hair-boat-fish-flowers-kofu

**Comment by hoothin** [comment]
似乎是火狐的某种特性，chrome不会有这种情况，我有空排查一下看看。
如果想要限制滚轮，用"wheel":true就行。
指定下一页的话，用编辑当前规则里的元素抓取器抓取你要的那个next，然后粘贴进nextLink就行

**Comment by fir05** [comment]
谢谢。与其针对每个网站写规则，我还是更希望完善强制拼接，这样后面再有同样网页就不是问题了。至少把"next"关键词用上。
我个人对规则无爱，在我看来强制拼接除了多滚动下外，没有什么缺点。


对了，那个从上掉落的太极鱼是BUG还是特效，能加个开关吗？太让人烦躁了。

**Comment by hoothin** [comment]
从天而降是css错乱了，给个示例页面我呢，我修一下。
以后我再加个加载太极的开关吧

**Comment by Frozen1084** [comment]
https://yande.re/post

**Comment by hoothin** [comment]
已经修复了，另外添加了隐藏加载太极的选项。
针对火狐锁定在页面底部的问题，给滚动加载添加了0.5s的延时。

**Comment by Frozen1084** [comment]
https://yande.re/post 在 Vivaldi 测试正常。但在 firefox 仍旧与 Vivaldi 有差别。
firefox 最初加载的几页正常，滚动条会上跳，留出滚动空间。但再多加载几页，滚动条就不动了，保持在底部。 而 Vivaldi 是不论加载多少页，滚动条都会上跳。这时 firefox 也不会再加载了，需要滚动滚轮触发加载。但这违反直觉。

**Comment by hoothin** [comment]
这个我改不了，如我上面所说，似乎是火狐的某种特性，会把视点锁定在新插入的元素上。
Vivaldi就是 Chromium 套壳，所以没问题。
如果你发现解决了这个问题的扩展，可以发给我参考一下。

**Comment by Frozen1084** [comment]
tks. 测试正常。

**Comment by hoothin** [comment]
//a[contains(text(), '下一个') and contains(text(), '次章')]

**Comment by Frozen1084** [comment]
现在在konachan.com的子页面预读有个问题。似乎是触发规则，将预读下一页图片直接拼接到当前图片的下方，而将下一页的网页内容抛弃掉。而我是需要查看内面内容的，因为需要下载大图的链接。
所以我设置开启了强制拼接。子页面的问题解决了。但强制拼接下主页面无法正常显示了。如1楼所述，只显示横条。

所以我想问 konachan.com 也是因为安全限制而无法使用强制拼接的吗？
如果没有安全限制，我们能让强制拼接将网页完全完整地加载再拼接出来吗？

**Comment by hoothin** [comment]
强制拼接时页内逻辑会一并带上，像是konachan这个站，有个行为是检测到被嵌入就用css隐藏。

内页拼接内容的问题，你可以点击编辑此站规则，用元素抓取器调整你想要拼接的内容。

内页拼接body的规则如下
<pre name='pagetual'>
    {
        "name": "Konachan.com Anime Wallpapers",
        "url": "^https://konachan\\.com/post/show",
        "nextLink": "id(\"post-view\")/div[@class=\"sidebar\"]/div[5]/ul/li[2]/a",
        "pageElement": "body",
        "action": 1
    }
</pre>

**Comment by Frozen1084** [comment]
谢谢。我还是想极力避免使用规则，只想用"下一页"+"强制拼接"，一个脚本走天下。

**Comment by Frozen1084** [comment]
类似的问题还有 https://danbooru.donmai.us/posts/5657234，预读的内容也是只显示一条。

在 Super_preloaderPlus_one_改，无论是konachan，yande，或者这个donmai，我都是用强制拼接正常拼接的。
主要的操作就是
1，寻找下一页关键词，修改脚本源码，添加进去。
2，启用强制拼接。不正常就开启iframe.

几乎90%网站的强制拼接都正常。

我也从来不用规则，这样用了很多年。强制拼接真的是超好用。为何太极这个的强制拼接就这么难用呢。。。

**Comment by Frozen1084** [comment]
能不能从头理下这个帖子。。。
首先，wedata错误导致翻页异常。那么能否增加一个开启强制拼接后"禁用所有内置规则"的选项？
我从来不用规则，可Super_preloaderPlu还是愉快地用了N多年。这应该能说明不用规则的可行性。

我们只需要下一页的关键词。我把Super_preloaderPlu里的关键词复制了份。(这个列表是我提供的)


```
	  var nextPageKey = ['下一页', '下一頁', '下1页', '下1頁', '下页', '下页 ›', '下頁', '翻页', '翻頁', '翻下頁', '翻下页', '下一张', '下一張', '下一幅', '下一章', '下一节', '下一節', '下一篇', '前进', '下篇', '后页', '往后', 'Next', 'Next Page', '次へ', '次のページ', '次のページ »', '下一页 →', '下一頁 →', '下1页 →', '下1頁 →', '下页 →', '下一个', '下頁 →', '翻页 →', '翻頁 →', '翻下頁 →', '翻下页 →', '下一张 →', '下一張 →', '下一幅 →', '下一章 →', '下一节 →', '下一節 →', '下一篇 →', '前进 →', '下篇 →', '后页 →', '往后 →', 'Next →', 'Next Page →', '次へ →', '次のページ →', '下一页 »', '下一頁 »', '下1页 »', '下1頁 »', '下页 »', '下頁 »', '翻页 »', '翻頁 »', '翻下頁 »', '翻下页 »', '下一张 »', '下一張 »', '下一幅 »', '下一章 »', '下一节 »', '下一節 »', '下一篇 »', '前进 »', '下篇 »', '后页 »', '往后 »', 'Next »', 'Next Page »', '次へ »', '后一页', '後一頁', '下一页 ›', '下一頁 ›', '下1页 ›', '下1頁 ›', '下頁 ›', '翻页 ›', '翻頁 ›', '翻下頁 ›', '翻下页 ›', '下一张 ›', '下一張 ›', '下一幅 ›', '下一章 ›', '下一节 ›', '下一節 ›', '下一篇 ›', '前进 ›', '下篇 ›', '后页 ›', '往后 ›', 'Next ›', 'Next >', 'Next Page ›', '次へ ›', '次のページ ›', '»', '→', '早期文章→']; // THX to https://greasyfork.org/en/forum/discussion/39361/x

```

最后，能否添加一个 "使用iframe强制拼接" 选项？

**Comment by hoothin** [comment]
永页机是我写来自用的，我也没想过有人会像你一样”强制拼接走天下“。
donmai的错误也是wedata的通用规则造成的。
晚些时候我优化一下强制拼接吧。

**Comment by hoothin** [comment]
已经更新了，把wedata的通用规则整个屏蔽掉了。目前测试下来这几个通用规则似乎只会产生错误结果。
另外如果选择强制拼接且拼接所有，则忽略当前规则强制以iframe嵌入页尾。
你试试。

**Comment by Frozen1084** [comment]
3Q。在https://yande.re/post/show/1018884 强制拼接仍旧只翻一页就停止了。
另外，以我在Super_preloader的经验来说，只有少部分的网页需要使用 iframe，另外少部分使用了iframe反而无法正常拼接。所以最好还是作为选项存在。

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/189333906-79429e18-9f3b-4325-84c8-21ef05db0d29.png)

我这边测试是正常的，是不是网络问题呢？
强制拼接只有选择全部拼接才会使用iframe，否则只会利用iframe加载后调取内容。

**Comment by Frozen1084** [comment]
找到原因了，是你前几天给我写的规则与强制拼接冲突了。
"全部拼接"是个选项吗，在哪里设置？

**Comment by hoothin** [comment]
点击强制拼接之后不是会有个确认框吗？”确定“是强制使用iframe拼接全部，”取消“是iframe加载后取出。

**Comment by Frozen1084** [comment]
明白了。
测试了一圈，用起来太顺手了。太感谢了。

**Comment by Frozen1084** [comment]
取消强制拼接再次启用后，不再显示全部拼接的确认框了，也就是说现在无法切换"全部拼接"这个选项。

**Comment by hoothin** [comment]
是这样的，如果有自定义规则存在，并且此规则已经是iframe加载调出的了，那就只有iframe强制嵌入一种选择。所以不会弹出确认框。

**Comment by Frozen1084** [comment]
清空cookie后，确认框就再次出现了。这种情形是你说的情况吗？
使用iframe和不使用iframe，是需要频繁切换的选项，能添加个按钮吗？比如 分裂成"强制拼接"和"iframe强制拼接"，两个按钮。。。。

**Comment by hoothin** [comment]
好的，更新版本时我会在编辑此站规则的面板上加几个立即按钮，点击切换强制拼接状态
