### ISSUE TITLE
Pagetual: Breaks Wordpress Developer

### ISSUE THREAD

**Issue by JGan678** [hoothin/UserScripts#165]
**Describe the bug**
When browsing https://developer.wordpress.org/, the script will break the webpage.

**To Reproduce**
It seems that this site uses flex box row no-wrap around \<main\> and nav \<div\> to put them side by side, and current rule will catch next page's <main> and put it directly after present \<main\>, causing the page to overflow.

**Expected behavior**
I think appending everything between \<header\> and \<footer\> is a better choice than appending \<main\>, since it's common to put main inside a grid or flex.

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Browser both safari with Userscripts and chrome with Tampermonkey.
 - Version 1.9.30.11

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "developer.wordpress",
        "url": "^https://developer\\.wordpress\\.org/",
        "pageElement": "#content",
        "nextLink": "[rel=next]"
    }
</pre>

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "developer.wordpress",
        "url": "^https://developer\\.wordpress\\.org/",
        "pageElement": "#primary>*",
        "nextLink": "[rel=next]"
    }
</pre>
Or this, you can use "Edit rule for current" to change the page content you want to splice
