### ISSUE TITLE
pornav 强制拼接无效 [NSFW]

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#166]
某些使用 JS 加载内容的网页，各个预载脚本都无法正确加载。但强制拼接通常可以正常加载。
比如这个网站，鼠标悬停可以预览视频，规则预载的内容就无法预览。使用强制拼接，翻页的内容预览仍旧有效。
https://jable.tv/new-release/

但强制拼接在这个 pornav 失效了
https://pornav.co/jp/page-1

在这个网站有两个问题，1是触发规则加载的页面不显示图片。2是切换到强制拼接后，不翻页。

====

能不能添加一个类似"真实模式"的强制拼接？不管多浪费资源，多慢，都把预载页当作独立的页面加载，极尽真实，然后拼接到当前页面

**Comment by hoothin** [comment]
不是资源浪费的问题。
强制拼接的使用存在条件限制，1是必须有单独的url，2是当前网站不能有对于内嵌的安全限制，你给出的pornav就不满足第二个条件。

**Comment by hoothin** [comment]
所以强制拼接并不是万能的，关于这个站，晚些时候我写个规则

**Comment by Frozen1084** [comment]
3Q。这个安全限制能通过编译firefox 进行定制吗？比如给翻页机加个白名单。

**Comment by hoothin** [comment]
chrome 是添加--args --disable-web-security 火狐不清楚，但应该不能单独加白名单

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "PornAV",
        "url": "^https://pornav\\.co",
        "pageElement": "div#grid-container",
        "css": ".cbp-lightbox{visibility: visible;}.cbp-caption-defaultWrap{-webkit-transition: -webkit-transform .6s cubic-bezier(.19,1,.22,1); transition: transform .6s cubic-bezier(.19,1,.22,1)}.cbp-caption:hover .cbp-caption-defaultWrap{-webkit-transform: scale(1.25); -moz-transform: scale(1.25); transform: scale(1.25);}.cbp-caption-activeWrap{opacity:0}.cbp-caption-activeWrap:hover{opacity:1}#grid-container.cbp-l-grid-blog{visibility: visible;}"
    }
</pre>
样式你自己微调一下就好

**Comment by Frozen1084** [comment]
tks. firefox 正常。
