### ISSUE TITLE
Pagetual: rule for https://www.camp-firefox.de/forum/ungelesene-beitraege/

### ISSUE THREAD

**Issue by benzBrake** [hoothin/UserScripts#168]
订阅了规则在 https://www.camp-firefox.de/forum/ungelesene-beitraege/ 这个页面（需要登录）翻页错误，照猫画虎写一下，不知道 from type action 都是什么
```
[
    {
        "name": "Camp Firefox Forum",
        "from": 1,
        "type": 0,
        "action": 0,
        "url": "^https://www\\.camp-firefox\\.de/forum/ungelesene-beitraege/",
        "pageElement": "#content > div > ol.tabularList",
        "nextLink": "nav.pagination > ul > li.skip:last-child > a",
        "updatedAt": "2022-09-10"
    }
]
```
本来是想在  greasyfork 那评分的，但是死活上不去，来到这边想发  disscussion，但是这个项目没有开这个功能

**Comment by hoothin** [comment]
感谢分享。
from:1 代表是wedata规则库的规则，from:2 代表是github规则库的规则。
type,action都可以删除。
已经添加进入内置规则了 https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L306
