### ISSUE TITLE
能否求大大写个新规则

### ISSUE THREAD

**Issue by kissmemory** [hoothin/UserScripts#169]
能否求大大写个https://www.zhihu.com/pub/book/119604467这类书籍的规则，这是知乎盐选的电子书，它用大大提供的常用格式无法下载，文档好像是加密过的，我尝试直接用小说下载只能下到空文档。大大如果有空，能否帮忙看看？辛苦大大了

**Comment by hoothin** [comment]
是加密了，不打算写这个规则。会被找麻烦。

**Comment by hoothin** [comment]
```
                var i, o;
                if ("string" == typeof r) {
                    var s = t.from(r, "base64");
                    i = t.alloc(16),
                    o = t.alloc(s.length - 16),
                    s.copy(i, 0, 0, 16),
                    s.copy(o, 0, 16)
                } else {
                    if (!(r instanceof t))
                        return "";
                    i = r.slice(0, 16),
                    o = r.slice(16)
                }
                return Object(a.createDecipheriv)("aes-128-cfb8", e, i).update(o, null, n)
```
这段是它的解密代码，你有兴趣可以自己研究

**Comment by kissmemory** [comment]
> ```
>                 var i, o;
>                 if ("string" == typeof r) {
>                     var s = t.from(r, "base64");
>                     i = t.alloc(16),
>                     o = t.alloc(s.length - 16),
>                     s.copy(i, 0, 0, 16),
>                     s.copy(o, 0, 16)
>                 } else {
>                     if (!(r instanceof t))
>                         return "";
>                     i = r.slice(0, 16),
>                     o = r.slice(16)
>                 }
>                 return Object(a.createDecipheriv)("aes-128-cfb8", e, i).update(o, null, n)
> ```
> 
> 这段是它的解密代码，你有兴趣可以自己研究

真的是太感谢大大了，我去研究一下，太麻烦你了，给大大送小花花((｡◕‿‿◕｡)づ╭--<-<-<@
