### ISSUE TITLE
希望添加深圳文献港移动图书馆扫描页面自动翻页

### ISSUE THREAD

**Issue by cizhai** [hoothin/UserScripts#170]
我希望永页机能对下面网页自动翻页：http://img.3g.chaoxing.com/n/mbreader/book/mblib/14534159/911844db735d4ea0a4ef7dbfb7a6d840/a8800956af880bd8753bc4c81216429e.shtml?domain=m.szwxg.5read.com&indexdomain=m.szwxg.5read.com&searchurl=http%3A%2F%2Fqw.szwxg.5read.com%2FgetPage%3Fchannel%3Dgoqw.jsp%26sw%3D%25E9%2592%25B1%25E9%2592%259F%25E4%25B9%25A6%26ecode%3Dutf-8%26xc%3D6%26Page%3D&sw=%E9%92%B1%E9%92%9F%E4%B9%A6&t=5&template=0
这是 http://qw.szwxg.5read.com/getPage?sw=%E9%92%B1%E9%92%9F%E4%B9%A6&ecode=UTF-8&xc=6 检索结果中第一个链接。链接打开到扫描图书的页面，我希望能自动翻页。
<img width="1680" alt="截屏2022-09-18 07 50 02" src="https://user-images.githubusercontent.com/113806806/190879901-0e9c479b-c18c-4041-a999-1b62e5066e86.png">

**Comment by hoothin** [comment]
私发我一个账号呢

**Comment by cizhai** [comment]
“章节”频道不需要帐号，可以翻几页，但是不能持续翻下去。帐号的话，您稍等，我想想怎么给你。
在 2022年9月18日 +0800 09:46，hoothin ***@***.***>，写道：

**Comment by cizhai** [comment]
mc.szwxg.5read.com
账号       0440050253005
密码    Feifei88
在 2022年9月18日 +0800 09:46，hoothin ***@***.***>，写道：

**Comment by hoothin** [comment]
试试 1.9.31.22 版，账密我先帮你删掉了

**Comment by cizhai** [comment]
我更新了一次，版本显示21，删掉重装后，版本显示还是21
在 2022年9月18日 +0800 09:57，hoothin ***@***.***>，写道：

**Comment by hoothin** [comment]
greasyfork有缓存，你点击点击历史版本。选择最新版安装，或者直接在github上安装

**Comment by cizhai** [comment]
> 刚试了一下安装后的 1.9.31.21版，不能实现我要的功能。就是打开的图片式扫描图书，要能自动翻页。没装成 1.9.31.22版，不知道咋回事。
>

在 2022年9月18日 +0800 09:57，hoothin ***@***.***>，写道：

**Comment by hoothin** [comment]
https://greasyfork.org/en/scripts/438684-pagetual?version=1094978

cizhai ***@***.***> 于2022年9月18日周日 10:06写道：

**Comment by cizhai** [comment]
老大，谢谢你，实现了我要的功能！只是更新版本时老更新不了，现在才更新好了。
在 2022年9月18日 +0800 10:20，hoothin ***@***.***>，写道：
