### ISSUE TITLE
PO18只有目录第一页可用，后面页再执行无反应

### ISSUE THREAD

**Issue by nssdd** [hoothin/UserScripts#172]
**Describe the bug**
PO18，下载成功，但只有目录第一页可下载，后面页再执行无反应

**To Reproduce**
使用简易自定义例子.l_chaptname>a@@articles@@articlescontent

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [edge]
 - Version [ 2.7.3.13]

**Additional context**
失败后尝试使用无缝翻页后再执行，仍然不可用

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/191384550-ef886daf-21bb-4e5d-9f04-d14d4fd43501.png)
先用永頁機翻完所有目錄再下載

**Comment by nssdd** [comment]
用过了，我用的是东方永页机，下载的数量跟第一页一样，也就是依然只有第一页生效。
大佬你用的是哪个永页机？

**Comment by nssdd** [comment]
再次尝试后发现是我反馈错误，不是目录页数的事。我也有用永页机试过，其实是因为能下载的只有免费章节，比如天生尤物能下载到很后面的三章免费阅读的680-682。
QAQ白嫖好像失败了
