### ISSUE TITLE
请求为 Userscripts 适配 `Switch Traditional Chinese and Simplified Chinese`

### ISSUE THREAD

**Issue by SunBK201** [hoothin/UserScripts#173]
`Switch Traditional Chinese and Simplified Chinese` iOS 目前不可用，请求为 [Userscripts](https://github.com/quoid/userscripts) 适配 `Switch Traditional Chinese and Simplified Chinese`

**Comment by hoothin** [comment]
一直都支持ios的，在脚本详情页开启自动转换，或者把你要开启转换的页面填入对应框内

**Comment by SunBK201** [comment]
Safari 经过测试不支持

**Comment by hoothin** [comment]
不是修改脚本代码，是在脚本详情页设置

**Comment by SunBK201** [comment]
我使用的是 Usercripts，不是 Tampermonkey在 2022年9月22日，22:25，hoothin ***@***.***> 写道：﻿
不是修改脚本代码，是在脚本详情页设置

**Comment by hoothin** [comment]
我用的也是Usercripts，当然stay2也有测试过。
是让你打开greasyfork的“脚本详情页”

**Comment by SunBK201** [comment]
thanks，解决了。另外能否为脚本加入 `@updateURL`，Usercripts 的更新需要此 Metadata，如果用户手动添加，脚本更新后的全部内容都会被最新的内容全部覆盖，包括`@updateURL`

**Comment by hoothin** [comment]
可以，但油叉会自动删除updateurl，想要保留必须从github仓库安装

**Comment by SunBK201** [comment]
好的，谢谢
