### ISSUE TITLE
yande.re 不触发规则

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#177]
不好意思，重装了下浏览器，翻页机在 yande.re 就不触发了。图标显示的是
https://i.imgur.com/H2OzuH4.png
没有编辑规则或者强制拼接的选项。

而且 https://yande.re/post?page=1
这个页面是有明显的递增链接的，即使没有规则，这种递增链接也可以触发吧

**Comment by hoothin** [comment]
你看看是否脚本没有下载完整，截图里永页机完全没有运行

**Comment by Frozen1084** [comment]
脚本应该没问题，在其他网站是正常翻页的。

**Comment by hoothin** [comment]
那就不清楚了，我这边各大浏览器下重新安装永页机后在yandere都是正常的

**Comment by Frozen1084** [comment]
另外一个问题。点击强制拼接的链接，不是整个标签加载这个链接，而是强制拼接的框架加载了这个链接。
你可以在煎蛋无聊图试试。强制拼接还是很有必要的。无聊图规则拼接的内容过滤会失效，被隐藏的图片也会显示出来。

**Comment by hoothin** [comment]
煎蛋无聊图我是适配了规则的，你没导入规则库？

**Comment by Frozen1084** [comment]
导入了啊，两个都全部更新了。
我是说规则会将"手贱一回"也加载出来
https://i.imgur.com/EFUIjkh.png

**Comment by Frozen1084** [comment]
有点奇怪啊。konachan.com几乎和yande一样的，konachan.com就正常。

**Comment by Frozen1084** [comment]
呃，应该是我的问题。我全新安装了firefox，tampermonkey和翻页器。yande就正常了。
出问题这个是我从旧firefox导出到新firefox的，但我后来也完全删除翻页器，重新安装了次，还是不能加载yande，好奇怪。

**Comment by Frozen1084** [comment]
请问能从控制台看出为啥不加载吗？
https://i.imgur.com/sepdbSy.png
====
啊我明白了，是整个tampermonkey在这个网页都没有工作，因为以往我看控制台，都会看到那个"网页限制解除"，现在没看到。看来是tampermonkey的问题。

**Comment by hoothin** [comment]
原来是这样啊。
煎蛋那个我再优化一下规则。我不大喜欢强制拼接，因为重复的页内代码执行太浪费资源

**Comment by Frozen1084** [comment]
强制拼接的优点也很明显，最大程度上还原加载页面的本来样貌，而且简单不折腾，适合我这种小白。
