### ISSUE TITLE
After new update site doesn't work anymore

### ISSUE THREAD

**Issue by DeathNorn** [hoothin/UserScripts#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [safari]

**Smartphone (please complete the following information):**
 - Device: [ipad]
 - OS: [latest version]
 - Browser [safari]

**Additional context**

Imhentai doesn't work anymore with pager it doesn't load next page just try's to load for a little bit then stops

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "IMHentai",
        "url": "^https://imhentai\\.xxx",
        "pageElement": "#gimg",
        "nextLink": ".nav_next",
        "css": "#footer,#bar{display:none}.pre_img+.nav_pagination{bottom: 10px; position: fixed; width: 100%;}.return_btn{bottom: 0; position: fixed; width: 100%;}",
        "lazyImgSrc": 0
    }
</pre>

**Comment by DeathNorn** [comment]
Thanks works now
