### ISSUE TITLE
[东方永页机]GitHub Stars 页面显示异常

### ISSUE THREAD

**Issue by wordpure** [hoothin/UserScripts#182]
在 GitHub 的星标页面，永页机显示分页隔条时，页面是横向拼接的。

将分页隔条的不透明值改为 0 后，页面才会正常拼接。

![图片](https://user-images.githubusercontent.com/68013962/194037616-a4635176-c9ce-439c-b234-e520775b8377.png)

![图片](https://user-images.githubusercontent.com/68013962/194038759-a2ae8997-e92d-4168-9e05-5e73b4a8091c.png)

浏览器：Firefox 106
脚本管理器：Violentmonkey 2.13.1.4

**Comment by wordpure** [comment]
> 另外好奇问一下，搜索酱是哪里不合意，使你想要迁移到context search ext ？

没……

Context Search 我用好一段时间了，觉得基本够用就没怎么尝试其他搜索工具。

之前发 Issue 的时候，是考虑把散落在其他地方的搜索引擎 URL 一并集中到 Context Search 里面去。实际上搜索酱我装了之后一直没开始体验😂

**Comment by hoothin** [comment]
这样啊，还是期待你能试用下，然后提点意见。
搜索酱比起context search多了搜索引擎挑战，多种批量打开方式，0 js代码页内点击搜索，连续正则替换，拖拽轮盘，关键词屏蔽元素，搜索引擎筛选搜索，批量选取页内元素并搜索等好多功能。页内高亮没有像context search一样用highlight库，完全是从头手写的，因此更加灵活。支持保存自定义自动高亮规则，自定义高亮css等。
而且不用装python就能调用本地应用。

小小推广了一下，见谅见谅。😄

**Comment by hoothin** [comment]
这样啊，还是期待你能试用下，然后提点意见。
搜索酱比起context search多了搜索引擎挑战，多种批量打开方式，0 js代码页内点击搜索，连续正则替换，拖拽轮盘，关键词屏蔽元素，搜索引擎筛选搜索，批量选取页内元素并搜索等好多功能。页内高亮没有像context search一样用highlight库，完全是从头手写的，因此更加灵活。支持保存自定义自动高亮规则，自定义高亮css等。
而且不用装python就能调用本地应用。

小小推广了一下，见谅见谅。😄

**Comment by hoothin** [comment]
这样啊，还是期待你能试用下，然后提点意见。
搜索酱比起context search多了搜索引擎挑战，多种批量打开方式，0 js代码页内点击搜索，连续正则替换，拖拽轮盘，关键词屏蔽元素，搜索引擎筛选搜索，批量选取页内元素并搜索等好多功能。页内高亮没有像context search一样用highlight库，完全是从头手写的，因此更加灵活。支持保存自定义自动高亮规则，自定义高亮css等。
而且不用装python就能调用本地应用。

小小推广了一下，见谅见谅。😄
