### ISSUE TITLE
Please add pre loading

### ISSUE THREAD

**Issue by DeathNorn** [hoothin/UserScripts#183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

You know how manga loader allows you to press a button in the corner,and it allows you to change the amount of pages loaded. 
![image](https://user-images.githubusercontent.com/75560758/194155284-3cfd44c8-8831-49c0-a231-2da8f6d6e6fd.jpeg)
Well I wanted to ether increase the amount of pages loaded or load all pages with a max of idk lest say 100 at a single time.

Hope there's something that can be done
I'm a iOS iPad user

**Comment by hoothin** [comment]
Pagetual has an command option 'Load next page manually' which you can input the amount of pages you want to load.
But unfortunately there is no command menu under IOS.

You still have two ways to reach it.
1. Open Configure, check "Turn pages immediately after opening", input 100 for "Amount for preload pages".
2. Write a rule for that site with a prop `autoLoadNum: 100`.

**Comment by DeathNorn** [comment]
Could you make a rule were I can just change the name of the site and it will preload it for me

**Comment by hoothin** [comment]
I can't as every rule is different.
I think it may be nice to add a option which can show command on ios. I'll try to design one for you later.

**Comment by hoothin** [comment]
Done, just check "Click the middle of the page bar to open the menu" and you can click the middle of page bar to call command menu. Then you can see the "Load next page manually".

**Comment by DeathNorn** [comment]
Thanks it loads the next page manually but is incapable of loading more than 1 page manually. Still a great feature and implementation to your script. Works great!
