### ISSUE TITLE
触发规则的网站没有强制拼接选项 [NSFW]

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#185]
这个网站是可以通过鼠标悬停来预览视频的。用规则加载的内容预览会失效，强制拼接则没有问题。
https://tktube.com/latest-updates/

但在这个页面，规则仍旧会触发，但没有"强制拼接"的选项。
https://tktube.com/categories/mgs/

https://i.imgur.com/WQ97AkQ.png

我觉得你仍旧会写一个新规则来解决预览失效的问题。。。能不能不用规则，用强制拼接来解决呢？这样下次再有类似问题的网站就不会出问题了。谢谢。

**Comment by Frozen1084** [comment]
但规则是正常翻页的啊，不能使用强制拼接选项时，将规则显示的内容强制改为"body"吗？
也就是规则只负责找到下一页链接，然后其他按强制拼接来显示。。。

**Comment by hoothin** [comment]
智能规则不是通过页码来翻的。
没有页码链接就没法用强制拼接。

**Comment by hoothin** [comment]
我之前已经解释过了，强制拼接有两个前提条件，一是必须有单独页码，二是页面没有csp安全限制

**Comment by Frozen1084** [comment]
抱歉。。。我可能还是没理解它的工作机制。。。。
那能从"下一頁"这个JS按钮得到下一页链接吗？

**Comment by hoothin** [comment]
多数情况下是不可以的，除非它本身处于一个表单元素内。但那样智能规则会自动处理生成链接，而且也会有强制拼接的选项。

类似你贴上来的第二个页面，是通过 ajax 获取 https://tktube.com/categories/mgs/?mode=async&function=get_block&block_id=list_videos_common_videos_list&sort_by=post_date&from=2&_=1665194984115
这个链接然后通过处理添加到框架里去的。不存在一个单独页面可以强制拼接

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "MGS Videos",
        "url": "^https?://tktube\\.com/",
        "pageElement": " div.list-videos > div#list_videos_common_videos_list_items > div.item",
        "nextLink": ".next>a[href^='#']",
        "pageAction": "eles.forEach(ele=>{let img=ele.querySelector('img[data-preview]');if(!img)return;let video=document.createElement('video');video.src=img.dataset.preview;video.setAttribute('playsinline','true');video.setAttribute('autoplay','');video.setAttribute('loop','');video.style.cssText='position: absolute; left: 0px; top: 0px; width: 318px; height: 179px; background: rgb(0, 0, 0); visibility: visible;';ele.onmouseenter=e=>{video.play();img.parentNode.appendChild(video)};ele.onmouseleave=e=>{img.parentNode.removeChild(video)}})"
    }
</pre>

**Comment by Frozen1084** [comment]
多谢
