### ISSUE TITLE
【东方永页机】bilibili搜索页自动滚动加载下一页

### ISSUE THREAD

**Issue by wordpure** [hoothin/UserScripts#187]
**Describe the bug**
同时启用东方永页机和搜索酱时，若永页机设置了「翻页前预读下一页」，在bilibili搜索页会无限自动滚动加载下一页

**To Reproduce**
1. 同时启用永页机和搜索酱
2. 永页机设置「翻页前预读下一页」
3. 打开bilibili搜索页，等待十来秒
4. 网页自动滚动到底部，永页机开始加载下一页

**Screenshots**
https://user-images.githubusercontent.com/68013962/194769078-356cab56-aa6b-449d-b69c-64e1cc50e16d.mp4

**Desktop (please complete the following information):**
 - 浏览器： Firefox 106
 - 脚本管理器：Tampermonkey 4.18.0

**Comment by hoothin** [comment]
感谢反馈，修复了

**Comment by wordpure** [comment]
更新脚本后问题解决了🌹
