### ISSUE TITLE
I will try this for sure brother

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#188]
I will try this for sure brother

Btw are you working on any youtube scripts?

One idea i can give is for Disable autopley and load buffer on start of video as all the other user scripts doesn't work perfectly at all. That would be cool if you can achieve that

_Originally posted by @rakitanc in https://github.com/hoothin/UserScripts/issues/153#issuecomment-1214143582_

**Comment by hoothin** [comment]
Sorry, I have no idea how to make that as I make every script or other software beside work just for myself. I have no interest on that. If I made a script for all video on web, I'll add that function.
