### ISSUE TITLE
Not working on this forum

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#189]
https://forum.ru-board.com/forum.cgi?forum=5

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by hoothin** [comment]
Take it
<pre name='pagetual'>
    {
        "name": "Ru.Board",
        "url": "^https?://forum\\.ru-board\\.com/",
        "nextLink": "table .small>b+a"
    }
</pre>
