### ISSUE TITLE
My searches are hijacked with this script enabled

### ISSUE THREAD

**Issue by xcloudx01** [hoothin/UserScripts#191]
Googled "vlc hide title bar" and every result sent me to greencoin.life instead. Turning extension off fixed it, turning it on hijacked the links again.
Oddly seems only this specific phrase triggers it.

**Comment by hoothin** [comment]
Thanks for report, I think maybe some style conflicts are triggered when css on next page inserted. Then one of the results contains the xx.life is threw to very front.
I'll check and fix it tomorrow.

**Comment by hoothin** [comment]
By the way, If you have some skill of css and xpath, you can modify rule on google.com by click command menu with yourself to fix it.

**Comment by xcloudx01** [comment]
Ahh that makes sense. My bad. I got worried when the results had been changed but I incorrectly jumped to a conclusion. Sorry mate 💖. I know css so I'll have a look at the rule as suggested.

**Comment by hoothin** [comment]
Good day.
It doesn't matter :), I have already checked on my chrome and firefox, It works well with "vlc hide title bar" on google.
Maybe you can import and update the base rule and check again.
<pre name="pagetual">
    {
        "name": "Google Search",
        "nextLink": [
            "id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
            "id('pnprev')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a"
        ],
        "pageElement": "id('rso')|id('center_col')/style[contains(.,'relative')][id('rso')]|id('search')/div/div/style[1]",
        "action": 1,
        "pageNum": "&start={10*($p-1)}",
        "pageBarTop": 55,
        "url": "^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)",
        "replaceElement": "[role='navigation']>[role='presentation']"
    }
</pre>

**Comment by xcloudx01** [comment]
Thanks :D. You're right, that'll teach me for not reading the instructions lol. The bug went away as soon as I imported the base rules. I then tried importing the above code and yes it still works correctly 👍. I had a lookie and yeah the offending link was on page 2 of the results.
