### ISSUE TITLE
以图库方式浏览，无法设置最佳缩放比例

### ISSUE THREAD

**Issue by Rocky-CN** [hoothin/UserScripts#195]
**Is your feature request related to a problem? Please describe.**
---
在[wallhaven](https://wallhaven.cc/)以图库方式浏览，开启大图缩放，**默认的缩放比例太小**，如下图：

<img src="https://user-images.githubusercontent.com/56460701/197315925-c1b874f3-8d21-479c-9c3e-165ca7846f2f.png" width = "640" height = "400" alt="默认的缩放比例太小" align=center />

每切换一张图片，都**需要手动点击图片放大两次，才能达到最佳缩放比例**。比如下图，22.87% --> 100% -->32.88%。

<img src="https://user-images.githubusercontent.com/56460701/197315998-bfdc266e-837e-42ad-81aa-1f3ac90073be.png" width = "640" height = "400" alt="默认的缩放比例太小" align=center />

在设置中，只找到”大图缩放“，没有找到关于缩放模式的设置

<img src="https://user-images.githubusercontent.com/56460701/197316107-8d07d14d-7ce4-4f92-a5af-bdd3d7523f69.png" width = "400" height = "600" alt="默认的缩放比例太小" align=center />

**Describe the solution you'd like**
---
希望调整默认缩放模式为**填满浏览器的列高度**，或者增加一个设置项来调整缩放模式。

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by hoothin** [comment]
关闭图库切换特效试试

**Comment by Rocky-CN** [comment]
> 关闭图库切换特效试试
解决了，谢谢！
