### ISSUE TITLE
[Picviewer CE+] 更新 @homepage

### ISSUE THREAD

**Issue by wordpure** [hoothin/UserScripts#197]
当前的主页地址 <http://hoothin.com> 已停更，不如改成脚本在 GreasyFork 的地址，方便查看脚本信息和反馈。

![图片](https://user-images.githubusercontent.com/68013962/197566781-f3613ec1-af32-4c7e-87df-28030d6daab3.png)

**Comment by hoothin** [comment]
感谢建议，如果是在油叉安装的，tm 的 Report a bug 应该会直接跳转到油叉的反馈页面。
暴力猴貌似只有主页。不设定 homepage 也会跳转到记录的安装页，但也没啥大影响。
我问问看寂寞的原子兄能不能加个反馈页按钮，这个我就不改啦。

**Comment by wordpure** [comment]
> 我问问看寂寞的原子兄能不能加个反馈页按钮

我昨晚已经反馈加上去啦，现在有 @supportURL 的可以点击直接跳转。
[[Feature] Add a script support button in the extension's popup · Issue #1635 · violentmonkey/violentmonkey](https://github.com/violentmonkey/violentmonkey/issues/1635)

> 如果是在油叉安装的，tm 的 Report a bug 应该会直接跳转到油叉的反馈页面。

感谢提醒，我再提个 Issue 问问，GreasyFork 和 GitHub 的脚本在没有 @supportURL 的时候能不能自动创建一个。

> 暴力猴貌似只有主页。不设定 homepage 也会跳转到记录的安装页，但也没啥大影响。

没设定 homepage 确实会跳转到记录的安装页，但 Picviewer CE+ 已经设定 <http://hoothin.com> 为主页，所以点击主页跳转的是<http://hoothin.com>，再跳到 GreasyFork 就麻烦些😂

**Comment by hoothin** [comment]
嗯，先前我已经添加 supportURL 了。
tm 就好一点，可以根据安装链接自动指定反馈页面。
另外还有上次那个 inline style 的安全限制。虽然可以强行通过 shadowdom + iframe 绕过，但搜索酱的高亮需要替换页内元素的样式，在 serx.ml 这类网站用暴力猴就无论如何都没法实现了。

**Comment by wordpure** [comment]
各有优劣吧，Tampermonkey 之前用了一段时间，感觉用不惯就换了回来，现在准备用扩展禁用 CSP 来解决这个问题。

不得不说，Firefox + Violentmonkey 的组合问题多多🤣
