### ISSUE TITLE
设置页面问题

### ISSUE THREAD

**Issue by Semidio** [hoothin/UserScripts#2]
在设置页面（https://github.com/hoothin/UserScripts/tree/master/Easy offline#一键离线下载）保存设置后，会导致所有连接都被识别为下载链接，破坏了页面显示。
同时，如果单独隐藏了某几个项目的话会导致在排这几个项目之后的项目无法点击，表现为列表中间空一段，一旦鼠标移至空白区域，列表自动隐藏关闭。

Tampermonkey v4.2.7
Chrome 54.0.2840.71 m

**Comment by hoothin** [comment]
识别错误是因为空字符串被识别为合法正则了，1.0.49已经修复。
列表排序已经1.1.0已经修复。
感谢反馈
