### ISSUE TITLE
【Picviewer CE+】问题和功能请求

### ISSUE THREAD

**Issue by wordpure** [hoothin/UserScripts#200]
1. 在网页边缘显示时，浮动工具栏图标有部分会超出可视区域。
	
	![图片](https://user-images.githubusercontent.com/68013962/198887017-7a5c745f-e200-4473-ab21-09f548bf0262.png)
2. 预览功能键容易误触。
	设置预览功能键为 `Ctrl` 时，在图片上按下 `Ctrl` + `D`，也会弹出预览。
	
	![图片](https://user-images.githubusercontent.com/68013962/198887571-48d50842-f743-4ed8-80c6-7d475a835848.png)
3. 希望按 `Esc` 可以取消放大镜。
4. 希望图片窗口可以支持快捷键操作。
	比方说，旋转、缩放、复制链接、打开图库、打开设置……

**Comment by hoothin** [comment]
旋转的快捷键是r，其他的快捷键我另外加了一下，暂时没做自定义。
缩放是 z 顺时针，shift + z 逆时针
复制是 c
图库是 g

预览误触我本地没有重现，目前如果鼠标不动应该是不会弹出预览的。

**Comment by wordpure** [comment]
> 旋转的快捷键是r，其他的快捷键我另外加了一下，暂时没做自定义。

感谢🌹

> 预览误触我本地没有重现，目前如果鼠标不动应该是不会弹出预览的。

刚试了下，鼠标不动确实不会弹出预览，可能是我之前的操作习惯有点问题😂

**Comment by wordpure** [comment]
> 1. 在网页边缘显示时，浮动工具栏图标有部分会超出可视区域。
>        ![图片](https://user-images.githubusercontent.com/68013962/198887017-7a5c745f-e200-4473-ab21-09f548bf0262.png)

最新版好像还是有这个问题。

**Comment by hoothin** [comment]
这个我本地也没有重现，边缘我是做了判断的。你把其他设置参数贴上来看看呢

**Comment by wordpure** [comment]
脚本、扩展、浏览器设置排查了一圈，最后发现是小众软件「优雅主题」的问题😂

![图片](https://user-images.githubusercontent.com/68013962/199412937-26fdd49f-9af2-416a-b279-d4bd91ee2593.png)

![图片](https://user-images.githubusercontent.com/68013962/199412980-92342f19-8978-400e-ac17-cd6b833d2a03.png)
