### ISSUE TITLE
[车万永页机]Ci-en的页面拼接不正常

### ISSUE THREAD

**Issue by PoiDaisuki** [hoothin/UserScripts#204]
**Describe the bug**
Ci-en的页面在拼接后会使现有内容被覆盖

**To Reproduce**
https://ci-en.dlsite.com/creator/10446
↑这是遇到问题的作者...姑且没有测试其他的情况...
F12看了眼，似乎第一页的东西彻底被顶掉了...?而且css也有明显问题

**Screenshots**

**Desktop (please complete the following information):**
<html>
<body>

Google Chrome | 107.0.5304.88 (正式版本) （64 位） (cohort: Bypass)
-- | --
修订版本 | f59ffb32abf8c01e9aa298400314bfdf0221b02f-refs/branch-heads/5304@{#1093}
操作系统 | Windows 10 Version 21H2 (Build 19044.2130)
JavaScript | V8 10.7.193.18
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
命令行 | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end

</body>
</html>

**Additional context**

**Comment by hoothin** [comment]
感谢反馈，修复了

**Comment by hoothin** [comment]
另外这个页面要显示图片的话需要自定义规则添加 `action:1`，或者点击“强制拼接”-“不拼接整页”
