### ISSUE TITLE
[东方永页机]谷歌学术中文乱码

### ISSUE THREAD

**Issue by destroy314** [hoothin/UserScripts#208]
**Describe the bug**
谷歌学术搜索第一页之后的页面内中文变为乱码，见截图。[这是截图中的网页](https://scholar.google.com/scholar?hl=zh-CN&as_sdt=0%2C5&q=network+security)
`相关文章`变为了乱码`Ïà¹ØÎÄÕÂ`，这看起来是使用iso-8859-1解释了GBK编码的文字；奇怪的是网页响应中charset=UTF-8。

**Screenshots**
<img width="627" alt="image" src="https://user-images.githubusercontent.com/35775292/199763004-4a7a7f32-8ffe-41f8-8b69-7cc613381287.png">

**Desktop:**
 - macOS 13.0
 - Safari 16.1

**Comment by hoothin** [comment]
用的脚本管理器是哪个？猜测可能是你用的脚本管理器不支持覆写请求头里的charset导致的

![image](https://user-images.githubusercontent.com/5361213/199863406-6e41f337-5e12-4581-aab2-c08a2e89423a.png)

**Comment by destroy314** [comment]
从App Store下载的Tampermonkey（4.17.6162），试了一下发现Userscripts不会乱码

**Comment by destroy314** [comment]
> 从App Store下载的Tampermonkey（4.17.6162），试了一下发现Userscripts不会乱码

油猴环境下[自动无缝翻页](https://greasyfork.org/zh-CN/scripts/419215-自动无缝翻页)不会乱码

**Comment by hoothin** [comment]
晚些时候我来 debug 一下，现在手头没有 mac。
可能 mac 上的 Tampermonkey 有哪里不兼容吧。
你有空的话可以帮我测一下 mac 下chrome + Tampermonkey 有没有乱码

**Comment by destroy314** [comment]
Chrome上的Tampermonkey是4.18.0，无乱码

**Comment by hoothin** [comment]
应该是修复了，但 mac 上的 tm 要买，没舍得花钱，所以还没测试。
你看看最新版有没有解决

**Comment by destroy314** [comment]
已解决🎉
