### ISSUE TITLE
RAR文件没有弹出匹配按钮

### ISSUE THREAD

**Issue by cnpirti** [hoothin/UserScripts#21]
类似这样的链接
http://xx.cc.aaaaaaa.bbbb/res/20180316/kdyn (4).rar
kdyn和(4)的中间有个空格
为什么没有弹出匹配按钮

**Comment by hoothin** [comment]
因为不是正确的url，需要转义，`空格->%20`例如
[http://xx.cc.aaaaaaa.bbbb/res/20180316/kdyn (4).rar](http://xx.cc.aaaaaaa.bbbb/res/20180316/kdyn%20(4).rar)
