### ISSUE TITLE
继Greasy Fork给的建议的后续

### ISSUE THREAD

**Issue by Lion-hk** [hoothin/UserScripts#215]
* *您的功能请求是否与某个问题相关？请描述一下。
https://greasyfork.org/zh-CN/scripts/24204-picviewer-ce/discussions/156440
继后半问题，
优化建议2：图库里遇到高分辨率的图片，比如2500 x 3000等大分辨率的图片，单击后会直接100%大小显示，
只能看到图片一小亏，不能看见完整面貌，很突兀，
且本脚本作为脚本显示图库本身显示的面积就小（占据浏览器的一半屏幕）的限制，
所以我的建议是可以增加一个选项：
##高分辨率大图单击后根据屏幕上下或者左右的距离（是叫平铺？拉伸？我不了解）限制显示图片，我的意思是显示全貌图片。
因为2500x3000本身分辨率就大，后续要100%显示就用户自己鼠标滑轮放大缩小就ok了。

* 很好的脚本，已好评+star了

**Comment by hoothin** [comment]
感谢建议。
你是否已经启用 “对图片进行缩放以适应屏幕” 的选项了？
如果已经启用的话，在图库中打开应该默认就是缩放至屏幕大小的。

**Comment by Lion-hk** [comment]
> 

开启了，标准的进入图库打开的确是默认的适应屏幕大小的，中等图片单击放大100%还是很完美的，
但是超过屏幕的分辨率图片，比如说的2500x3000，开始默认是适应屏幕的，单击以后就会过分大，
我的初衷建议是：这类图片单击后适应屏幕的左右分辨率1080，而不是直接100%的显示2500这么宽。

不是图库里双击展示的单图窗口，的确，这个单图窗口浏览单图是挺完美的。

你说的这些选项我都勾选了，我的浏览器是搜狗浏览器，插件是TM插件，都是最新版本的。其他脚本均运行正常。

**Comment by hoothin** [comment]
我理解了，你的意思就是类似软瑟盘那样的二段放大吗？我明天加一下

**Comment by hoothin** [comment]
二级放大已经更新上去了，你可以测试一下

**Comment by Lion-hk** [comment]
好的，测试过了，鉴于我提出的观点和总体使用体验，我想提出更大点优化建议，意在给脚本完善完美体验感受。
1、二级放大铺屏完美啦，只是不能像3级放大一样上下抓图移动。
2、我提出的左右填充（二级放大）意在给如今的比如截图长图（1920x5000）使用，要是上下填充的宽图比如摄像全景图（5000x1080）的呢？（这只是根据我二级放大观点产生的，实用上一般用到的概率不是很大吧，作者酌情考虑）
3、[https://www.bilibili.com/read/cv16163093](url)，这个链接，这链接里边也有例子图，这网站不知道是bug还是网站参数不支持或者其他脚本干扰问题，抓图基本失效。
4、单图窗口的箭头放在图外减少对图片的遮挡，并加以透明隐藏，其他快捷方式也一样（抓取、旋转、关闭等），鼠标滑过再显示。图库里的箭头也一样透明隐藏。

**Comment by Lion-hk** [comment]
那个抓图失效或者是我搜狗浏览器的内核问题吗？
有时40x40、80x80的小图在图库里依旧显示，重新设置小图大小才能有效**该次**。
![image](https://user-images.githubusercontent.com/117522220/200765237-8c226c32-a336-4b66-b552-68a665111afb.png)
![image](https://user-images.githubusercontent.com/117522220/200765392-5ca65331-4f21-438c-81f5-65672de65e82.png)
![image](https://user-images.githubusercontent.com/117522220/200765537-8bf99243-8480-4757-b2f9-ad8dc6c95ca0.png)
![image](https://user-images.githubusercontent.com/117522220/200765635-838c9b00-8168-4e89-9b37-7d70bee847a2.png)

**Comment by hoothin** [comment]
感谢继续提供建议。
二级放大的拖动我有空加上。
你说的“上下填充”是已经实现了的，你可以改动窗口大小来测试。
至于bilibili的页面，你需要拖动滚动条浏览完整页，触发所有懒加载之后再抓取。
单图窗口切换箭头放里面是为了连续切换时箭头不隐藏，为了避免遮挡功能按钮，箭头是绑在主图片上的。不默认隐藏则是因为需要定位箭头位置，并且标识这个功能

**Comment by hoothin** [comment]
出现小图是因为这些是背景图，加载之前不能获取大小，因此点击显示然后获取大小之后才能筛选

**Comment by Lion-hk** [comment]
好的，看你回复，应该是你写的这套语法代码限制了，那就不勉强了，bilibili页面我拉动整个页面显示完成不再加载了再点击图库依旧不能拖动，不是bug那就是我的方面问题了。
也赞叹你优化制作有心了！
