### ISSUE TITLE
Need a rule for 1paipai

### ISSUE THREAD

**Issue by denniszzg** [hoothin/UserScripts#221]
Hi, hoothin

Your scripts is owesome! Thank you.
Could you please add a new rule for this website?
[京东夺宝岛](https://1paipai.jd.com/auction-list/%7B%22pageNo%22%3A1%2C%22pageSize%22%3A50%2C%22category1%22%3A%22%22%2C%22status%22%3A%222%22%2C%22orderDirection%22%3A1%2C%22orderType%22%3A1%2C%22groupId%22%3A1000005%7D?entryid=)

It cannot work as below:

```
[
    {
        "name": "夺宝岛列表-京东_拍拍",
        "url": "^https?://1paipai\\.jd\\.com/",
        "nextLink": ".btn-next>i"
    }
]
```

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "夺宝岛列表-京东_拍拍",
        "url": "^https?://1paipai\\.jd\\.com/",
        "nextLink": ".btn-next",
        "pinUrl": true
    }
</pre>

**Comment by denniszzg** [comment]
oops... It seems work now. 
Maybe I was too anxious to wait for few second.
Thanks anyway.

**Comment by denniszzg** [comment]
There is a little imperfection.
The last page always repeats, never end.
How to solve it?

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "夺宝岛列表-京东_拍拍",
        "url": "^https?://1paipai\\.jd\\.com/",
        "nextLink": ".btn-next",
        "pinUrl": true,
        "stopSign": [
            "",
            ".btn-next[disabled]"
        ]
    }
</pre>
