### ISSUE TITLE
请求给Steampy做适配

### ISSUE THREAD

**Issue by TimeTraveller-ZEN** [hoothin/UserScripts#228]
https://steampy.com/cdKey/cdKey

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "SteamPY_安全省钱的Steam游戏交易市场",
        "url": "^https?://steampy\\.com/",
        "pageElement": ".market-detail > div.ivu-tabs > div.ivu-tabs-content > div.ivu-tabs-tabpane div.flex-row > .gameblock",
        "nextLink": ".page-ul > li.active + li:not(.disabled)",
        "pinUrl": true
    }
</pre>
