### ISSUE TITLE
DownloadAllContent 网页目录抓取不全

### ISSUE THREAD

**Issue by csho** [hoothin/UserScripts#23]
测试网页：http://www.wenku8.com/novel/1/1715/index.htm
抓取后显示生成33页，实际有一百多页的子链接，其中大部分是包含正文文字的链接。例如第二卷第一章就没有抓取成功。
Chrome 65.0.3325.181

**Comment by hoothin** [comment]
的确抓不了，这些子链接不带“章节”，可以先用下面这段代码处理一下
`a=0;[].forEach.call(document.querySelectorAll(".ccss>a"),function(i){i.innerHTML="第"+(a++)+"篇"+i.innerHTML;})`

**Comment by csho** [comment]
可以了，感谢
