### ISSUE TITLE
How to import the base rules?

### ISSUE THREAD

**Issue by galantra** [hoothin/UserScripts#233]
I can't figure out how to do it. I go to https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json but what is the next step?

Firefox 106.0.5 (64-bit)
Tampermonkey 4.18.1

**Comment by hoothin** [comment]
Just need to open install page and click the line of base rule

**Comment by galantra** [comment]
I didn't see the “import” button. ![image](https://user-images.githubusercontent.com/52420923/207571034-ecb18820-8f36-429c-9fee-6fde40b7f573.png) Either it wasn't shown to me, or I was just blind. I've imported it now. Thank you for this amazing script.

**Comment by Korb** [comment]
> I can't figure out how to do it. I go to https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json

At https://pagetual.hoothin.com/rule.html, a different link is now displayed for base rules:

`https://hoothin.github.io/UserScripts/Pagetual/pagetualRules.json`
