### ISSUE TITLE
Load/process other userscripts on page - Pagetual

### ISSUE THREAD

**Issue by robertheadley** [hoothin/UserScripts#234]
**Is your feature request related to a problem? Please describe.**
When you are using a userscript to alter a page, they only work on the first page of pagetual results

**Describe the solution you'd like**
a per site toggle to enable processing userscripts individual on each pagetual page. 

**Describe alternatives you've considered**
Maybe this feature already exists and I am just not aware?

**Additional context**
![image](https://user-images.githubusercontent.com/1780455/202866681-57c2cc24-31ca-4102-81f9-c99e0328dab0.png)

**Comment by hoothin** [comment]
Paste URL here and I'll check.
Maybe one custom rule is needed.

**Comment by skofkyo** [comment]
看圖應該是RARGB安裝了顯示預覽圖的腳本
自定義規則需要添加"action": 1
已更新規則
![圖片 001](https://user-images.githubusercontent.com/5115423/202900303-7ecfe059-3412-46e3-8127-9c552984566a.png)

**Comment by robertheadley** [comment]
> 看圖應該是RARBG安裝了顯示預覽圖的腳本 還有RARBG - torrent and magnet links 需要"action": 2模式才能相容 已更新規則 ![圖片 003](https://user-images.githubusercontent.com/5115423/202903826-95c1a271-082a-4dfa-b85a-7531279f9148.png)
> 
>     {
>         "name": "RARBG",
>         "example": "https://rarbg.to/torrents.php?category=movies",
>         "url": "^https?://(proxy|unblocked)?rarbg([a-z0-9]+)?\\.(to|org|com)/",
>         "action": 2,
>         "include": "#pager_links",
>         "nextLink": "#pager_links>a[title='next page']",
>         "pageElement": "//table[tbody/tr[@class='lista2']/td/a/img]",
>         "replaceElement": "#pager_links",
>         "pageAction": "document.querySelectorAll('iframe[name]').forEach(iftame=>{iftame.style.margin='0 0 2px'});",
>         "sleep": 1000,
>         "css": "inIframe:body,table{margin:0!important;padding:0!important}table{width:100%!important}td[width='100']{display:none!important}body{background:none!important}"
>     }

That did it! Thank you.
