### ISSUE TITLE
Is there any way to prevent page number bars from repeating?

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#239]
I want the list to continue like a waterfall but it seems to also repeat the page numbers for each page and puts it in between the previous and next pages which is pretty annoying and detriments the experience. I tried to "exclude" it via the custom rules by adding the div to it but to no avail. Any tips?

Thanks in advance!

**Comment by hoothin** [comment]
Set opacity to '0', it means hide.

**Comment by Auditormadness9** [comment]
Sorry, didn't notice about the double open. And no, that's not what I mean.

I mean this:
![image](https://user-images.githubusercontent.com/71278545/206864152-be790b07-6021-42c7-bc4f-d5c444148daf.png)
It's the page bar from the website itself that appears at the top of each page.

**Comment by hoothin** [comment]
Sorry, I got it wrong.
You can make rule by yourself to change "pageElement" without that page number bar.
Just click the "edit rule for current" and move your mouse over elements.

**Comment by hoothin** [comment]
I means **"without"** the page number bar.
"pageElement" is for the elements that you want to insert which are located on next page.

And only "pageElement" is needed. "replaceElement" means replace the element on next page into current page.

**Comment by Auditormadness9** [comment]
> I mean **"without"** the page number bar. "pageElement" is for the elements that you want to insert which are located on next page.

How do I do that?

**Comment by Auditormadness9** [comment]
If by "without" you mean not include that element in the pagelement module then I did it like that here:

![image](https://user-images.githubusercontent.com/71278545/207462554-a2666ed1-8b9a-4d71-be28-0239817ece42.png)

Still shows up when I go back and refresh and try.

**Comment by hoothin** [comment]
Make sure the "pageElement" include no page num bar, otherwise, write a css selector use ":not()".
You'd better paste the target URL of steamcommunity here so I can make more suggestion.

**Comment by Auditormadness9** [comment]
> Make sure the "pageElement" include no page num bar, otherwise, write a css selector use ":not()". You'd better paste the target URL of steamcommunity here so I can make more suggestion.

https://steamcommunity.com/id/AM49/myworkshopfiles/?appid=4000&browsefilter=mysubscriptions

This is the target URL but it won't work for you since it's accessible from my account only, but if you have Steam you can just go to a workshop page where you have mods subscribed to, then go to subscribed items section and see the list.

The pagebar selector is `body > div.responsive_page_frame.with_header > div.responsive_page_content > div#responsive_page_template_content.responsive_page_template_content > div#BG_bottom_sharedfiles > div#mainContents_sharedfiles > div#tabs_basebg_workshop > div#profileBlock.clearfix > div#leftContents > div.workshopBrowsePagingWithBG` and i have absolutely no clue how to write that css thingy

**Comment by hoothin** [comment]
Just use `"pageElement": "#leftContents>.workshopItemSubscription"` instead

**Comment by hoothin** [comment]
Another way is to hide that page bar by `"css": ".workshopBrowsePaging{display:none}"`

**Comment by Auditormadness9** [comment]
> Just use `"pageElement": "#leftContents>.workshopItemSubscription"` instead

this worked, tysm!

But I still didn't learn what had been done. Basically you negate the pagebar selector's last directory with a dot or something?

**Comment by Auditormadness9** [comment]
> That's a simple css selector. You can learn [here](https://www.w3schools.com/cssref/css_selectors.php).

got it, thanks!
