### ISSUE TITLE
NFSW网站某一页无法正常翻页

### ISSUE THREAD

**Issue by liangxyz** [hoothin/UserScripts#243]
在这个NFSW网站的这一页 https://www.jpmn5.cc/XingYan/XingYan23895.html
我发现这一页不能正常翻页，体现在翻页动画显示在页面上部，自动翻页的内容不显示，手动点击第二页以后，这个页面就能正常翻页了

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "極品性感美女 - 看圖",
        "example": "https://www.jpmn5.com/Xiuren/Xiuren23112.html",
        "url": "^https?://www\\.\\w+\\.(com|cc|org|top)/\\w+/\\w+\\.html",
        "include": "body > section.container > div.content-wrap > div.content > article.article-content > p > img,.article-content>.pagination",
        "action": 1,
        "nextLink": ".current+a",
        "pageElement": ".article-content img:not([width])",
        "replaceElement": ".pagination",
        "css": ".article-content p img[width],.article-content br{display:none!important}"
    }
</pre>
