### ISSUE TITLE
東方永頁機 巴哈姆特網站超鏈接失效

### ISSUE THREAD

**Issue by Nevidebla** [hoothin/UserScripts#249]
https://acg.gamer.com.tw/index.php?p=ANDROID
在這個網站上，第二頁開始，詳情圖片的超鏈接就沒有了。

**Comment by hoothin** [comment]
點擊【强制拼接】-【拼接整頁】

**Comment by hoothin** [comment]
不過還是更加建議用picviewer ce+添加一條規則
替換
bahamut.com.tw/S
為
bahamut.com.tw/B
