### ISSUE TITLE
关于鼠标双击启用/停用的操作方式建议

### ISSUE THREAD

**Issue by JunwayGuo** [hoothin/UserScripts#251]
关于鼠标双击启用/停用翻页，能不能改用更自由方式，比如在设置中设置开关，对于浏览网页时喜欢鼠标双击的人来说，简直太难受了，误操作率非常高。

**Comment by hoothin** [comment]
1. 命令菜单”切换禁用状态“
2. 设置里添加功能键或者快捷键，藉此可通过类似 `ctrl + 双击`，或者 `ctrl + q` 的操作来禁用

**Comment by JunwayGuo** [comment]
大佬可能误会了我的意思，我不是想问如何禁用翻页，我明白禁用的方法有很多种，我是希望不使用鼠标双击来启用/停用翻页，因为这会误操作。说白了，我希望翻页是一直启用的，如果要禁用，我可以去设置里禁用。

**Comment by hoothin** [comment]
添加功能键之后，仅仅双击就不会触发操作。
或者直接在设置里取消双击禁用啊。

**Comment by JunwayGuo** [comment]
原来设置是可以设置的吗？为什么我的设置里没有相关项？
![image](https://user-images.githubusercontent.com/31336068/205299075-64d0efde-a68e-434c-8c3f-51e9a59ad759.png)

**Comment by JunwayGuo** [comment]
是在脚本设置里吗？没有相关项呢
![image](https://user-images.githubusercontent.com/31336068/205300152-195ddd28-59c0-481a-9a2f-71333b3b226d.png)
