### ISSUE TITLE
自定义规则问题

### ISSUE THREAD

**Issue by Midsh** [hoothin/UserScripts#252]
某个网站写了自定义规则，但是偶尔自定义规则里的元素没有出现，会自动匹配通用规则，之后就一直忽略自定义规则使用通用规则了，把hprules里的通用规则删除才能继续使用自定义规则。

**Comment by hoothin** [comment]
用pinUrl试试。不行的话把网址贴上来

**Comment by Midsh** [comment]
pinUrl有效。
