### ISSUE TITLE
Unix manuals

### ISSUE THREAD

**Issue by AHOHNMYC** [hoothin/UserScripts#256]
There is strong concept of formatting GNU/Unix/Linux manuals as multipage HTMLs. Tons of great sites are built using common structure:
https://tldp.org/LDP/abs/html/devproc.html
https://sourceware.org/binutils/docs/as/W.html
https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Standards.html
https://www.gnu.org/software/bash/manual/html_node/Command-Execution-Environment.html
https://www.linuxfromscratch.org/lfs/view/stable/prologue/package-choices.html
https://www.opennet.ru/docs/RUS/bash_scripting_guide/x1673.html

It would be great if script will be doing autoloading on these sites too out-of-the-box. Thanks!

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Standards DOC",
        "url": "\\.html$",
        "nextLink": ".header>p>[rel=next]",
        "pageElement": ".header~*"
    }
</pre>
