### ISSUE TITLE
CHH网站自动翻页以后不显示后面页面的图片

### ISSUE THREAD

**Issue by liangxyz** [hoothin/UserScripts#258]
作者你好，我经过测试发现在chh网站的帖子中，自动翻页以后，后面的页面不会显示图片，但是手动点击页码能正常显示该页的图片！
https://www.chiphell.com/thread-2446995-1-1.html  
这是测试页码，自动翻页下，第一页图片正常显示，但是第二页第32楼和以后的页面的图片都不能显示，除非你手动点击该页码

**Comment by hoothin** [comment]
命令菜单-强制拼接-不拼接整页。
以后遇到类似图片不显示的情况都可以这样操作。

**Comment by liangxyz** [comment]
> 命令菜单-强制拼接-不拼接整页。 以后遇到类似图片不显示的情况都可以这样操作。

谢谢大佬，Tampermonkey 只找到了强制拼接，没找到不拼接整页

**Comment by liangxyz** [comment]
懂了，在弹出的对框框中选择否就是不拼接整页，谢谢大佬的解答
