### ISSUE TITLE
请问能否增加一个隐藏浮动工具栏的设置

### ISSUE THREAD

**Issue by beautifulword** [hoothin/UserScripts#26]
有时候图片特别小，浮动工具栏会挡住图片，再比如
https://userstyles.org/styles/124770/tieba-maverick-2018
这个网址里设置背景图时浮动工具栏比较碍事。
所以rt，然后用快捷键个人感觉更好一点

**Comment by hoothin** [comment]
设置里有俩选项：“ 缩放图片，超过该尺寸，显示浮框 ”，“ 非缩放图片，超过该尺寸，显示浮框 ”。
另外按住alt键浮动工具栏就会隐藏

beautifulword <notifications@github.com> 于2018年6月11日周一 下午12:26写道：

**Comment by beautifulword** [comment]
感谢开发者大大回复
一直按住alt的话有点麻烦，而且按住alt时，快捷键就无法使用了。另外设置里的那两个选项感觉对我发的网址   贴吧样式里的customize setting中预览背景图时的不便并没有多大作用。以及，在图片旁多出一个悬浮窗有时候确实不太美观。
个人觉得如果有个隐藏浮动工具栏设置会更好。
再次感谢开发者大大的脚本。

**Comment by hoothin** [comment]
“监听背景图”取消勾选就行

beautifulword <notifications@github.com> 于2018年6月11日周一 下午1:44写道：

**Comment by hoothin** [comment]
另外 显示延时设为“99999999”，浮动工具栏就不会出现了

Hoothin <rixixi@gmail.com> 于2018年6月11日周一 下午4:50写道：

**Comment by beautifulword** [comment]
感谢开发者大大！太棒了！
