### ISSUE TITLE
[Pagetual] Moving content (gifs or videos) no longer move after page 1

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#262]
What causes this to happen? Any list that contains boxes of gifs or moving html elements or videos no longer play and become static images, is there a way to fix this?

Thanks in advance.

**Comment by hoothin** [comment]
Because they are playing by code on next page.
To replay them, you should make a custom rule or just click "force to join" & "join full body".

**Comment by Auditormadness9** [comment]
well join full body causes the entire next page html to be loaded while I just need the waterfall effect of a singular continous list, but the custom rule part is interesting, what kind of rule would make them play? Is there a module for it or is it going to be another specific css command?

**Comment by hoothin** [comment]
Yeah, all the same as before besides `"action": 2`. You can get more examples [here](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json)

**Comment by Auditormadness9** [comment]
Thanks! `"action": 2` is exactly what I needed, thank you!

Just one more thing, how do I fix the list inconsistency that it causes? Like action 0 and 1 are fine but with 2 a grid list that's supposed to have 6 columns now has 5 and is a bit smaller than on the original page. So the original page works fine, then on second and so on the list continues with 1 less column and a bit smaller than supposed to be thus makes the waterfall effect inconsistent. Of course the movable js is moving now but with such disrupted looks, but when I switch to action 0 or 1 where it becomes static again the list is once again flowing as intended with no disruptions.

I played around with the selector pathing randomly, trying different combinations of including and excluding elements in the selector path (trying the grids themselves, then the list only then other stuff etc) and I get random results each time but never the intended one.

Any tip would be appreciated but if it's not possible I'll understand. Tysm still!

**Comment by hoothin** [comment]
Maybe a [@media](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) should be set by some css like `"css": ".xxx{column-count: 6;}"`.

**Comment by Auditormadness9** [comment]
and what about the size?

**Comment by hoothin** [comment]
Same as the column-count, modify `width` or others in `media`.
There's another way for you to try. `"fitWidth": false`.

**Comment by Auditormadness9** [comment]
> "fitWidth": false

that worked but now the list moved a bit left

**Comment by hoothin** [comment]
So I suggest you to look at `css` prop. You can change everything about style on the page by that.
