### ISSUE TITLE
"下一篇"被错误地当作"下一页"拼接在页尾

### ISSUE THREAD

**Issue by yzuse** [hoothin/UserScripts#263]
部分网站文章正文底部的"下一篇"按钮被错误地当成"下一页"文章列表按钮，从而导致下一篇文章的正文被拼接在当前文章底部，干扰正常的阅读，出现此类错误的网站案例：
　www.runningcheese.com/enable-copy
　www.52txr.cn/2022/BaiduCapsule.html?replyTo=1166

烦请检查和修复，非常感谢！

**Comment by hoothin** [comment]
1. 你没有导入基础库，奶酪内页在基础库已经禁用了
2. 下一篇视为翻页是正确行为，你可以自行禁用

**Comment by hoothin** [comment]
禁用翻页有以下三种手段
+ 在访问网页时点击命令菜单内的“切换禁用状态”
+ 在配置页的黑名单输入框内填入网址，例如`https://www.52txr.cn/*`，其中`*`代表任意多个字符
+ 添加自定义规则，根据网站特征禁用，例如
```
{
    "name": "Wordpress 内页禁用",
    "url": ".",
    "pageElement": "section#scroll article.entry",
    "enable": 0
}
```

ps: 提问前先阅读使用说明，基础库都没有导入就发 issue 很不好
