### ISSUE TITLE
建议去掉"下一篇"的拼接

### ISSUE THREAD

**Issue by yzuse** [hoothin/UserScripts#264]
把"下一篇"文章拼接起来不符合一般人的思维和使用习惯：

下一页、下一节、下一章：
　是同一内容的多个组成部分，属于浏览者要获取的信息。
下一篇：
　是与当前文章内容完全不相关的另一篇文章，不属于浏览者要获取的信息。

如果查询一个问题时，把很多不相关的问题堆积在正确答案后面，不仅淡化了主要内容，而且相当于强迫用户打开很多篇自己完全不想看的文章，跟强推给用户的网络牛皮癣广告无异，不符合大多数人的浏览习惯。

恳请考虑，非常感谢！

**Comment by hoothin** [comment]
这跟“下一篇”没有任何关系，wordpress 的页脚链接就是 `a.next`。
之前已经回复过你了，特征规则也给你了，自己按说明禁用啊

**Comment by yzuse** [comment]
您脚本中设置了用innerText检测锚文本是否包含"下一篇"，可以在代码中把带"下一篇"的拼接排除掉，已经自行解决，还是非常感谢！

您这个脚本做得很好，感谢！

**Comment by hoothin** [comment]
……
在你的例子中，代码里的“篇”字没有用处，那只是抓取之后用来调整优先级的。

完全不听我说话啊，如此没法沟通，不再回复了
