### ISSUE TITLE
大佬大佬  寂月神社  怎么下资源啊 

### ISSUE THREAD

**Issue by xxxloli123** [hoothin/UserScripts#27]
大佬大佬  寂月神社  怎么下资源啊

**Comment by URGERKING** [comment]
建议这个[https://sleazyfork.org/zh-CN/scripts/23316-%E7%90%89%E7%A5%9E%E8%BD%89](url)配合[https://greasyfork.org/zh-CN/scripts/22590-%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD](url)

**Comment by URGERKING** [comment]
> 
> 
> 大佬大佬 寂月神社 怎么下资源啊

建议[https://sleazyfork.org/zh-CN/scripts/23316-%E7%90%89%E7%A5%9E%E8%BD%89](url)

**Comment by xxxloli123** [comment]
谢谢大佬


 
---原始邮件---
发件人: "URGERKING"<notifications@github.com&gt;
发送时间: 2020年4月20日 10:51:08
收件人: "hoothin/UserScripts"<UserScripts@noreply.github.com&gt;;
抄送: "xxxloli123"<1526830731@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [hoothin/UserScripts] 大佬大佬  寂月神社  怎么下资源啊  (#27)




  
大佬大佬 寂月神社 怎么下资源啊
  
建议https://sleazyfork.org/zh-CN/scripts/23316-%E7%90%89%E7%A5%9E%E8%BD%89
