### ISSUE TITLE
希望增加Steam创意工坊规则

### ISSUE THREAD

**Issue by pansuto** [hoothin/UserScripts#270]
https://steamcommunity.com/id/going2kilzu/myworkshopfiles/?appid=550
脚本在这种网页翻页功能正常但是ui会重叠

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Steam Community Workshop Items",
        "url": "^https?://steamcommunity\\.com/",
        "pageElement": "div.workshopBrowsePaging+div.workshopBrowseItems"
    }
</pre>
