### ISSUE TITLE
[Pagetual] Any way to fix this out of bounds issue?

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#287]
![image](https://user-images.githubusercontent.com/71278545/213931903-0448906d-2801-445f-9703-3d169ef9075e.png)

URL: https://steamcommunity.com/workshop/browse/?appid=4000&searchtext=%22follow+the%22&childpublishedfileid=0&browsesort=toprated&section=readytouseitems&requiredtags%5B0%5D=Courses&created_date_range_filter_start=0&created_date_range_filter_end=0&updated_date_range_filter_start=0&updated_date_range_filter_end=0&actualsort=toprated&p=2

Custom Rule: 

```     
{
"name": "Workshop",
        "url": "^https?://steamcommunity\\.com/",
        "pageElement": "body > div.responsive_page_frame.with_header > div.responsive_page_content > div#responsive_page_template_content.responsive_page_template_content > div#ig_bottom.default > div#mainContents > div#profileBlock.clearfix > div > div.workshopBrowseItems",
        "action": 2
    }
```

**Comment by skofkyo** [comment]
<pre name="user-content-pagetual">
    {
        "name": "steamcommunity.com",
        "url": "^https?://steamcommunity\\.com/",
        "include": ".workshopBrowsePaging",
        "nextLink": "a.pagebtn:last-child",
        "pageElement": ".workshopBrowseItems",
        "replaceElement": ".workshopBrowsePaging",
        "pageAction": "document.querySelectorAll('.workshopBrowseItems>script').forEach(e=>{eval(e.innerHTML)})",
        "css": ".pagetual_pageBar{margin-top:0px!important}"
    }
![swe2](https://user-images.githubusercontent.com/5115423/214035640-8b0f1c60-066a-49af-992d-981ff132cb39.jpg)

</pre>

**Comment by Auditormadness9** [comment]
lol thanks a ton! I tried to ask ChatGPT to solve this and fed it with the custom rules page info and it just spat lines of css rules that didn't fix anything but broke it more xd
