### ISSUE TITLE
Not working well on this website

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#288]
https://www.99images.com/celebrities/aisha-sharma

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by skofkyo** [comment]
<pre name="user-content-pagetual">
    {
        "name": "99images",
        "example": "https://www.99images.com/celebrities/aisha-sharma",
        "url": "^https?://www.99images.com/",
        "action": 1,
        "nextLink": "a[rel='next']",
        "pageElement": ".gallery-images-container",
        "replaceElement": ".pagination"
    }
</pre>
