### ISSUE TITLE
Please make it work on this website

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#290]
http://libgen.rs/search.php?&req=The+Way+Out&phrase=1&view=simple&column=def&sort=def&sortmode=ASC&page=1

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by skofkyo** [comment]
<pre name="user-content-pagetual">
    {
        "name": "libgen.rs",
        "example": "http://libgen.rs/search.php?&req=The+Way+Out&phrase=1&view=simple&column=def&sort=def&sortmode=ASC&page=1",
        "url": "^https?://libgen\\.rs/",
        "action": 1,
        "waitElement": [
            "//td[span/strong]"
        ],
        "nextLink": "//td[span/strong]/following-sibling::td[1]//a | //table/tbody/tr/td/font[@color]/a",
        "pageElement": "//tr[td[@nowrap]]",
        "replaceElement": "//div[contains(@class,'paginator')] | //table[tbody/tr/td/font[@color]]"
    }
</pre>
