### ISSUE TITLE
能否请大大添加一下次元姬的规则

### ISSUE THREAD

**Issue by CronusLM** [hoothin/UserScripts#291]
直接下载会下载出一个20多mb的文件，里面都是目录。
目录页
https://www.ciyuanji.com/b_d_5077.html
章节页
https://www.ciyuanji.com/chapter/5077_2228956.html
用下载器直接下载章节页的html，里面有完整的小说正文。
就是我不会用心法，写不出规则，只能麻烦大大你了。

**Comment by CronusLM** [comment]
章节页的html用vscode打开，光标留在正文部分，有显示一个路径html>body>div#_next>div.chapter_page__Mguyg.chapter_theme1__X8JLr>section.chapter_main__OShgg>article.chapter_article__vWEkb
我把body>div#_next>div.chapter_page__Mguyg.chapter_theme1__X8JLr>section.chapter_main__OShgg>article.chapter_article__vWEkb这个填进自定义下载里面下下来一个700多kb的全是目录的文件。

**Comment by skofkyo** [comment]
嘗試獲取第一話
<pre>
fetch('https://www.ciyuanji.com/chapter/5077_2227754.html')
    .then(res => res.text())//回傳的資料轉成文字
    .then((res) => {
    let doc = new DOMParser().parseFromString(res, 'text/html');//文字轉為Document
    let code = doc.querySelector('#__NEXT_DATA__').innerHTML;//取得網頁主要代碼
    let json = JSON.parse(code);//代碼轉為JSON
    let chapter = json.props.pageProps.chapterContent.chapter;//當前章節的資料
    let chapterName = chapter.chapterName;//小說章節名稱
    let textBase64 = chapter.chapterContentFormat;//小說章節文字編碼
    console.log(chapterName);//主控台輸出小說章節名稱
    console.log(textBase64);//主控台輸出小說章節文字編碼
})
</pre>
卡在小說主體的文字經過了編碼，用atob()解碼會變一堆亂碼，找不到正確解碼的方式。
等作者過完年假有空再幫忙解決吧

**Comment by skofkyo** [comment]
之前陷入了思考誤區，沒必要搞得那麼複雜，直接取元素的內容稍微替換一下文字就行。

fetch測試獲取
<pre>
fetch('https://www.ciyuanji.com/chapter/5077_2227754.html')
    .then(res => res.text())//回傳的資料轉成文字
    .then((res) => {
    let doc = new DOMParser().parseFromString(res, 'text/html');//文字轉為Document
    let text = doc.querySelector('.chapter_article__vWEkb').innerText;//小說章節正文文字
    let r = text.replace(/\s{2}/g,"\n");//將2空格替換為換行符
    console.log(r);//主控台輸出小說章節正文
})
</pre>
所以規則應該這樣寫
<pre>
a.book_detail_item__EMrK7 @@@@@@　data.querySelector('.chapter_article__vWEkb').innerText.replace(/\s{2}/g,"\n")
</pre>

**Comment by CronusLM** [comment]
> 之前陷入了思考誤區，沒必要搞得那麼複雜，直接取元素的內容稍微替換一下文字就行。
> 
> fetch測試獲取
> 
> fetch('https://www.ciyuanji.com/chapter/5077_2227754.html')
>     .then(res => res.text())//回傳的資料轉成文字
>     .then((res) => {
>     let doc = new DOMParser().parseFromString(res, 'text/html');//文字轉為Document
>     let text = doc.querySelector('article').innerText;//小說章節正文文字
>     let r = text.replace(/\s{2}/g,"\n");//將2空格替換為換行符
>     console.log(r);//主控台輸出小說章節正文
> })
> 所以規則應該這樣寫
> 
> 次元姬小说
> 
> a.book_detail_item__EMrK7 @@@@@@　data.querySelector('article').innerText.replace(/\s{2}/g,"\n")

感谢你的帮助
这条规则能下载到大部分的章节，但每次运行都会剩十几章卡在那里无法下载，前面也有一些章节只下载到章节名。
https://send.bgme.bid/download/80388428e36aaf3c/#oxyTSstIoZUiGVe2hgw6cQ
这是我运行下载的结果

**Comment by hoothin** [comment]
这个站有连接数限制，在小说下载器的设置里设置线程数为1跑了半小时测试了下，跑到了508章，暂时没有发现问题
