### ISSUE TITLE
Not working well on this Doctor finding website

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#292]
https://www.practo.com/search/doctors?results_type=doctor&q=%5B%7B%22word%22%3A%22ophthalmologist%22%2C%22autocompleted%22%3Atrue%2C%22category%22%3A%22subspeciality%22%7D%5D&city=delhi&sort_by=experience_years

Even though it shows 86 results but it shows only 10 more or less

 I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by hoothin** [comment]
Sorry I can't see what you are talking about.
I checked the page and found only "85 doctors available in Delhi" & two available results behind your filters.
