### ISSUE TITLE
[Pagetual] Keeps Scrolling and Loading Extra Pages Despite "Preload" and "Turn pages" Options Turned Off

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#297]
### **Describe the bug**

I encountered an issue with Pagetual where the app keeps scrolling down and loads additional pages even when the "preload" and "turn pages" options are turned off. The app loads approximately 20 to 30 extra pages, and when it reaches the end, it loops back to the beginning.

### **To Reproduce**

1. Open Pagetual
2. Turn off the "preload" and "turn pages" options
3. Scroll down through the pages
4. Observe that the extension continues to load additional pages and loops back to the beginning when it reaches the end.

### **Expected behavior**

It should not load additional pages and should stop at the end when those options are ticked off.

### **Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 1.9.33.40

**Comment by hoothin** [comment]
Have you entered "Amount for preload pages"?
If so, you can empty it to stop auto action.
That is exactly a bug and I will find a way to optimize it.

**Comment by Auditormadness9** [comment]
Thank you. Might you also know if the loop is a bug or am I doing something wrong? When it reaches the last page it still loads a next page and that next page turns out to be the very first and the cycle repeats.

**Comment by hoothin** [comment]
I think that's because the site itself is designed that way.
You can post the url here for me to check.
