### ISSUE TITLE
DownloadAllContent:能加入为章节添加序号的选项吗

### ISSUE THREAD

**Issue by CronusLM** [hoothin/UserScripts#298]
像po18等一些网站有很多小说不给章节名添加第\*章/第\*话，导致阅读器无法给这些小说分章节，下载下来后人工加也很麻烦，如果下载的时候添加了序号，后面用正则就能很容易添加第*章。不知道大大有时间吗。

**Comment by skofkyo** [comment]
提供一个先手动修改的方法
例如这个没有第n章
https://czbooks.net/n/pnpno1

目录先用正序排列章节，按F12到主控台，运行以下代码。
 <pre>
 let titles = document.querySelectorAll('#chapter-list>li>a');

 for (let i = 0; i < titles.length; i++) {
     let n = parseInt(i) + 1;
     let e = titles[i];
     e.innerText = '第' + n + '章 ' + e.innerText;
 };
 </pre>
简单的几行代码，这样就修改完成了。

需要根据不同的网站，替换目录章节文字所在的元素CSS选择器。
就是这部份#chapter-list>li>a需要换，其他不用动，'章'也能换成'话'。

**Comment by hoothin** [comment]
下载md格式的就行了，标题是h1，章节是h2

**Comment by CronusLM** [comment]
确实，md做epub也是比较好的方法
