### ISSUE TITLE
Not working on this website

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#299]
https://pcpph.in/dosearch?pname=ESPORTS+ICE-110

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by hoothin** [comment]
You can't load more page on this site as all page data are already loaded completely after page open.
To view more data, you can do these:
1. Change to desktop mode.
2. Change prop of jQuery-dataTables, like
<pre name="pagetual">
    {
        "name": "Parts search",
        "url": "^https?://pcpph\\.in/",
        "init": "$('#search_results')[0].dataset.pageLength=100;$('#search_results_length select').val(100).trigger('change');"
    }
</pre>
And you can find more props in [jQuery-dataTables](https://www.datatables.net/examples/advanced_init/html5-data-options.html)

**Comment by meiMingle** [comment]
Doesn't work here either

https://plugins.jetbrains.com/search?orderBy=downloads&products=androidstudio&products=appcode&products=aqua&products=clion&products=dataspell&products=dbe&products=go&products=idea&products=idea_ce&products=idea_edu&products=mps&products=phpstorm&products=pycharm&products=pycharm_ce&products=pycharm_edu&products=rider&products=ruby&products=webstorm

**Comment by hoothin** [comment]
> Doesn't work here either

这个是翻完主题翻插件的规则
<pre name="pagetual">
    {
        "name": "Search Results more themes",
        "url": "^https?://plugins\\.jetbrains\\.com/",
        "loadMore": "span.test_show-more"
    }
</pre>

这个是只翻插件的规则
<pre name="pagetual">
    {
        "name": "Search Results more plugins",
        "url": "^https?://plugins\\.jetbrains\\.com/",
        "loadMore": ".search-page>div:nth-child(4) .test_show-more"
    }
</pre>

**Comment by meiMingle** [comment]
你太好了，感谢感谢
