### ISSUE TITLE
[Picviewer CE+] Download resulting in json

### ISSUE THREAD

**Issue by Skcyte** [hoothin/UserScripts#300]
**Describe the bug**
Downloading images from Artstation artists page will saved as json instead jpg.
Batch download using Gallery View and downloading from homepage works as intended but it's in small resolution.

**To Reproduce**
1. Go to [artstation.com](https://www.artstation.com)
2. Go to any artist's page
3. Download any image using shortcut or toolbar

**Expected behavior**
It should download the image as jpg

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser : Firefox 
 - Version : 109

**Additional context**
If the artwork is a collection it should still download whatever image is shown.

**Comment by hoothin** [comment]
artstation need to get info from json. So If you want to batch download from artstation. Make sure all information of big images are loaded at first.

![image](https://user-images.githubusercontent.com/5361213/215986846-ccc50c39-752f-42f2-89dc-ea757526ca50.png)

**Comment by Skcyte** [comment]
^ Sorry about that 
Yes, using Gallery to download all images work fine.
What I meant is download individual image using the toolbar or shortcut.

[screen-recorder-wed-feb-01-2023-16-52-56.webm](https://user-images.githubusercontent.com/18594247/216011762-035b6bff-01a3-45be-9867-009a12e8eea2.webm)

**Comment by hoothin** [comment]
Ah, thank you! There is indeed a bug here.
It's fixed now. You can try again with the latest version.

**Comment by Skcyte** [comment]
It is working now. Thank you very much.
Closing this now.
