### ISSUE TITLE
Does not work on Pixiv anymore/ 在Pixiv上不工作 

### ISSUE THREAD

**Issue by HiddenMelonCat** [hoothin/UserScripts#301]
I can't download full novels at once from Pixiv anymore.  All I get in the .txt file is the novel title and this same message repeating all the way. For example it says all 59 pages are done downloading but I only get this in the file. 
```
"male

34

en

yes

no

no

no

no"

```
I can only down one page at a time with shift + CTRL + F9.  I can't download the whole book at once CTRL + F9 does not work. So downloading long books is hard. 

我不能再从Pixiv下载了。 我在.txt文件中得到的只是小说的标题和这个相同的信息，一直重复着。我只能用shift + CTRL + F9一次下来一页。 我不能一下子下载整本书，CTRL+F9不起作用。所以下载长的书很困难。

Sorry for the broken Mandarin I use DeepL

**Comment by hoothin** [comment]
You should read additional info of the script on the install page.
And download novels with "Custom to download"

**Comment by HiddenMelonCat** [comment]
> You should read additional info of the script on the install page. And download novels with "Custom to download"

Sorry for the bother, but I am still confused. Maybe I didn't understand the additional info. For example this novel, https://www.pixiv.net/novel/show.php?id=19218425. 

I right click. I click on "inspect" (in google chrome). Then I Ctrl-F in the inspect window "main>section" and get to <section class="sc-171jvz-1 sc-171jvz-2 fXmjBM ZqjkC"> Then I click on custom download and paste it in the box, and click OK, but nothing happens. I will post a video of me doing it to better explain.


https://i.imgur.com/8SXlcuV.mp4

**Comment by hoothin** [comment]
Follow this step-by-step:
1. Open https://www.pixiv.net/novel/series/9870425
2. Click "Custom to download"
3. Enter "main>section ul>li>div>a@@@@@@var noval=JSON.parse(data.querySelector("#meta-preload-data").content).novel;noval[Object.keys(noval)[0]].content;"

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/216234930-5f30aef5-d6b1-4181-836b-69a64137459a.png)

**Comment by HiddenMelonCat** [comment]
> Follow this step-by-step:
> 
> 1. Open https://www.pixiv.net/novel/series/9870425
> 2. Click "Custom to download"
> 3. Enter "main>section ul>li>div>a@@@@@@var noval=JSON.parse(data.querySelector("#meta-preload-data").content).novel;noval[Object.keys(noval)[0]].content;"

Thank you this worked. I thought the above was just a template example, and we had to source our own from the page source. Thank you again.
