### ISSUE TITLE
永页机在 Firefox 附加组件和小众软件表现异常

### ISSUE THREAD

**Issue by wordpure** [hoothin/UserScripts#303]
**Describe the bug**
在 Fireofx 附加组件，永页机加载下一页后更换搜索结果的排序方式，新的搜索结果会从第二页开始显示。

**To Reproduce**
1. 打开 `about:config`，将 `privacy.resistFingerprinting.block_mozAddonManager` 的值改为 `true`，并从 `extensions.webextensions.restrictedDomains`  的值中移除 `addons.mozilla.org` 以支持在 Firefox 附加组件启用扩展程序
2. 打开 [最近更新](https://addons.mozilla.org/zh-CN/firefox/extensions/category/web-development/?sort=updated)，等待永页机加载下一页
![图片](https://user-images.githubusercontent.com/68013962/216805945-8c0195d7-5c4a-47ca-a5cf-91cda9bfa470.png)
3. 切换排序方式为「相关性」后，搜索结果会从第 2 页开始展示
![图片](https://user-images.githubusercontent.com/68013962/216805951-8e64a151-10c4-44c5-b0e2-a38fd180602e.png)
4. 刷新页面，页面搜索结果恢复从第一页开始展示
![图片](https://user-images.githubusercontent.com/68013962/216805967-4259ff1b-5fb9-44cc-a71b-f433d1b32fa6.png)

**Desktop (please complete the following information):**
 - OS: Windows 22H2
 - Browser: Firefox 110.0b9
 - 脚本管理器：Violentmonkey 2.13.9.1

**Comment by wordpure** [comment]
**Describe the bug**
在 [遇见大家的 Obsidian - 小众软件官方论坛](https://meta.appinn.net/t/topic/37042) 页面，启用永页机会导致页面无法滚动。

**To Reproduce**
1. 在小众软件官方论坛启用永页机
2. 打开 [遇见大家的 Obsidian - 小众软件官方论坛](https://meta.appinn.net/t/topic/37042) 这个帖子
3. 异常发生，页面无法滚动
![图片](https://user-images.githubusercontent.com/68013962/216806607-3fbae401-b844-4be7-a8f4-6a84f0482fce.png)

**Desktop (please complete the following information):**
- OS: Windows 22H2
- Browser: Firefox 110.0b9
- 脚本管理器：Violentmonkey 2.13.9.1

**Comment by hoothin** [comment]
感谢反馈，已经在1.9.33.45 修复了。
但是Discourse这个很奇怪，我是写死了不在Discourse上运行的。

**Comment by wordpure** [comment]
更新后两个问题都解决了，感谢🌹

**Comment by wordpure** [comment]
Firefox 附加组件等 [分类](https://addons.mozilla.org/zh-CN/firefox/extensions/) 加载出第二页，再页内跳转到 [首页](https://addons.mozilla.org/zh-CN/firefox/) 的话，会翻到分类第三页😂

https://user-images.githubusercontent.com/68013962/216832184-f41c5f81-3f3c-4e00-b4d2-47b7f4449d6b.mp4

**Comment by hoothin** [comment]
我本地未能复现，能否把你的设置截图一份给我？也许是预读多页导致的

**Comment by wordpure** [comment]
> 尝试修复了一下，你试试。

更新到 1.9.33.48 之后，翻页还是会出现上面的情况。

这是我的设置截图，开了「打开页面后立即尝试翻页」和「翻页前预读下一页」。

奇怪的是，从地址栏直接打开 [网页开发分类](https://addons.mozilla.org/zh-CN/firefox/extensions/category/web-development/) 的时候，永页机会自动加载下一页，但从 [扩展](https://addons.mozilla.org/zh-CN/firefox/extensions/) 页面打开 「网页开发分类」的时候，必须要滚动到页面底部才会加载下一页。

![图片](https://user-images.githubusercontent.com/68013962/217016868-2f700aad-91de-4506-bc7d-58326560fb2a.png)

**Comment by hoothin** [comment]
测试了一下，似乎现在火狐+暴力猴没法覆写window下的history了。还没测试是否仅在addons.mozilla.org这种页面有限制。所以暂时先换成定时器检测了。

**Comment by wordpure** [comment]
更新到 1.9.33.50 之后，问题解决🌹
