### ISSUE TITLE
Download from webnovel , wuxia like site

### ISSUE THREAD

**Issue by killerlearner** [hoothin/UserScripts#304]
I am using Android device and trying to download full webnovel from "https://m.webnovel.com/book/the-eminence-in-the-shadow_13936627605424605" But it only download some words how can I make it download full novel.

**Comment by hoothin** [comment]
Sorry but I won't provide support for the site which have plenty of resources with lawyers.
You can seek help from other script which support 起点网 as webnovel.com is just a substitute of that.
