### ISSUE TITLE
[Picviewer CE+] full size images for nsfw.xxx

### ISSUE THREAD

**Issue by WillHawker** [hoothin/UserScripts#305]
The images that show up are just the thumbnails, not the full images that you get by clicking on them.
I'm not sure how to do this myself since the images have a hash on the end that is different between the thumbnail and the full image so it's not as easy as changing "thumbnails" to "images" in the URL

I'd also like to be able to turn on the "auto load page" option permanently so I don't have to click it again every time I open a new page or refresh

**Comment by hoothin** [comment]
<pre>
{
 name:"nsfw.xxx",
 url:/^https?:\/\/nsfw\.xxx/,
 src: /thumbnails/,
 getImage: function(a,p) {
     if (a && a.className==='slider_init_href' && a.href) {
         return a.href;
     }
 },
 xhr: {
     q: '.sh-section__image>img',
 }
}
</pre>

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/217400106-5d0d6d2b-0529-4549-a100-a354ddb32948.png)
