### ISSUE TITLE
Pagetual: causing web rendering incorrect

### ISSUE THREAD

**Issue by touch-feel** [hoothin/UserScripts#307]
**Describe the bug**
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors
![image](https://user-images.githubusercontent.com/73594022/218447284-79f914f4-3450-4b53-948e-ea48b9ad4b38.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by touch-feel** [comment]
火狐开发者版本中显示异常
chrome显示正常

**Comment by hoothin** [comment]
永页机的版本号，控制台输出贴一下

**Comment by touch-feel** [comment]
https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-2.html
这个在chrome和firefox开发版中都显示异常
![image](https://user-images.githubusercontent.com/73594022/218534170-58120300-bbaf-4a98-9ca5-ed4a647f6c04.png)

**Comment by touch-feel** [comment]
重新安装最新版`1.9.33.58`后，mozilla.com中显示正常，oracle.com中问题仍然存在

oracle控制台信息
```
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. jvms-2.html
Cookie “bm_sv” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite jvms-2.html
unreachable code after return statement eval:4183:8
【Pagetual v.1.9.33.58】 Next link: 
<a accesskey="n" href="jvms-3.html">
Pagetual.user.js:564:21
【Pagetual v.1.9.33.58】 Page element: body > div.chapter>* Pagetual.user.js:564:21
Loading failed for the <script> with source “https://consent.truste.com/notice?domain=oracle.com&c=teconsent&js=bb&noticeType=bb&text=true&gtm=1&cdn=1&pcookie”. jvms-2.html:1:1
Loading failed for the <script> with source “https://www.oracleimg.com/us/assets/metrics/ora_docs.js”. jvms-2.html:1:1
Loading failed for the <script> with source “https://c.oracleinfinity.io/acs/account/wh3g12c3gg/js/oracledocs/odc.js?_ora.context=analytics:production”. jvms-2.html:1:1
```

**Comment by skofkyo** [comment]
developer.mozilla.org
Firefox 109.0.1
chrome 110.0.5481.77
Tampermonkey 4.18.1
Pagetual 1.9.33.58
正常，沒有元素重疊。

docs.oracle.com
<pre>
div.chapter div.toc {
    position: absolute;
    left: 10px;
    top: 120px;
    width: 250px;
    line-height: 125%;
    font-size: 90%;
}
</pre>
CSS樣式導致翻頁後元素重疊，應該需要寫點代碼調整新插入的.toc的top。

**Comment by hoothin** [comment]
toc 的 top 改成 auto 也是可以的
`"css": "div.chapter div.toc{top: auto;}"`
