### ISSUE TITLE
https://lrepacks.net 翻页不正常，显示空白

### ISSUE THREAD

**Issue by github-xihe** [hoothin/UserScripts#308]
![image](https://user-images.githubusercontent.com/53401671/219390218-d1d07f99-6306-4605-88a4-eaf5491d0f99.png)

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "REPACK скачать",
    "url": "^https?://lrepacks\\.net/",
    "css": ".animated .slideUp{opacity:1}"
}
</pre>

**Comment by hoothin** [comment]
也可以直接【强制拼接-拼接整页】

**Comment by github-xihe** [comment]
> {
>     "name": "REPACK скачать",
>     "url": "^https?://lrepacks\\.net/",
>     "css": ".animated .slideUp{opacity:1}"
> }
> 导入

可以翻页了，第2页的分页隔条显示正常，但后面的会出现分页隔条重叠
![image](https://user-images.githubusercontent.com/53401671/219720018-f184453e-96dc-4385-bfed-1ccd3c29cf24.png)
不过问题也不大

**Comment by hoothin** [comment]
<pre name="pagetual">{
    "name": "REPACK скачать",
    "url": "^https?://lrepacks\\.net/",
    "css": ".animated .slideUp{opacity: 1;transform: translateY(0);}"
}
</pre>

**Comment by github-xihe** [comment]
> {
>     "name": "REPACK скачать",
>     "url": "^https?://lrepacks\\.net/",
>     "css": ".animated .slideUp{opacity: 1;transform: translateY(0);}"
> }
> 导入

感谢大大，正常翻页又美观了
