### ISSUE TITLE
谷歌和百度的相关搜索是否可以放在右侧，这样拼页的时候也不影响看相关搜索

### ISSUE THREAD

**Issue by k650dg4d2** [hoothin/UserScripts#313]
![image](https://user-images.githubusercontent.com/32454224/219955770-02d459ea-7273-44f3-bfb6-58b736174e4a.png)

**Comment by skofkyo** [comment]
加点浮动CSS就行了
<pre name="user-content-pagetual">
    {
        "name": "Google Search",
        "url": "^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)",
        "nextLink": [
            "id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
            "id('pnprev')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a"
        ],
        "pageElement": "id('rso')|id('center_col')/style[contains(.,'relative')][id('rso')]|id('search')/div/div/style[1]",
        "action": 1,
        "pageNum": "&start={10*($p-1)}",
        "pageBarTop": 55,
        "replaceElement": "[role='navigation']>[role='presentation']",
        "css": ".pagetual_pageBar{margin-top:-25px!important}#res{margin-top:0px!important;line-height:-0!important}.g{margin-bottom:10px!important}#bres{position:fixed;width:650px;height:auto;border-radius:5px;z-index:999;right:40px;bottom:80px;box-shadow:0 0 5px rgba(0,0,0,0.6)}#bres>div:last-child{padding:20px;margin:0}"
    },
    {
        "name": "Baidu",
        "css": "span.c-img-radius-large.c-img-border,.result-molecule[tpl='app/rs']{pointer-events: none}.result-molecule[tpl='app/rs']>div{pointer-events: all}#rs_new{position:fixed;width:auto;height:auto;border-radius:5px;z-index:999;right:40px;bottom:50px;box-shadow:0 0 5px rgba(0,0,0,0.6)}#rs_new>div{padding:20px 20px 0 20px}#rs_new>table{padding:0 20px 20px 20px;margin:0}",
        "insertPos": 1,
        "nextLink": [
            "//*[@id=\"page\"]/div/a[contains(text(),'下一页')]",
            "//*[@id=\"page\"]/div/a[contains(text(),'上一页')]"
        ],
        "pageElement": "//*[@id=\"content_style\"]|//*[@id=\"content_left\"]/*",
        "type": 0,
        "pageNum": "&pn={10*($p-1)}",
        "url": "^https?://www\\.baidu\\.com/(s|baidu)",
        "pageBarTop": 75,
        "init": "let rs=document.querySelector('div.result-molecule[tpl=\\'app/rs\\']');if(!rs)return;(document.querySelector('#con-ceiling-wrapper')||document.querySelector('#content_right')).appendChild(rs);let tp=document.querySelector('.c-font-medium>div');let t;if(tp)t=tp.children[0];[].forEach.call(rs.querySelectorAll('tr>td'),rp=>{if(tp&&t){rp.className=tp.className;rp.children[0].className=t.className}})",
        "replaceElement": "#page"
    }
</pre>
![g004](https://user-images.githubusercontent.com/5115423/219967765-6ab2caec-026e-4a6e-934b-5aff5576d066.jpg)
![g005](https://user-images.githubusercontent.com/5115423/219967786-4deb39ce-0b4b-489a-b335-29663399e018.jpg)

**Comment by k650dg4d2** [comment]
> 加点浮动CSS就行了
> 
>     {
>         "name": "Google Search",
>         "url": "^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)",
>         "nextLink": [
>             "id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
>             "id('pnprev')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a"
>         ],
>         "pageElement": "id('rso')|id('center_col')/style[contains(.,'relative')][id('rso')]|id('search')/div/div/style[1]",
>         "action": 1,
>         "pageNum": "&start={10*($p-1)}",
>         "pageBarTop": 55,
>         "replaceElement": "[role='navigation']>[role='presentation']",
>         "css": ".pagetual_pageBar{margin-top:-25px!important}#res{margin-top:0px!important;line-height:-0!important}.g{margin-bottom:10px!important}#bres{position:fixed;width:650px;height:auto;border-radius:5px;z-index:999;right:40px;bottom:80px;box-shadow:0 0 5px rgba(0,0,0,0.6)}#bres>div:last-child{padding:20px;margin:0}"
>     },
>     {
>         "name": "Baidu",
>         "css": "span.c-img-radius-large.c-img-border,.result-molecule[tpl='app/rs']{pointer-events: none}.result-molecule[tpl='app/rs']>div{pointer-events: all}#rs_new{position:fixed;width:auto;height:auto;border-radius:5px;z-index:999;right:40px;bottom:50px;box-shadow:0 0 5px rgba(0,0,0,0.6)}#rs_new>div{padding:20px 20px 0 20px}#rs_new>table{padding:0 20px 20px 20px;margin:0}",
>         "insertPos": 1,
>         "nextLink": [
>             "//*[@id=\"page\"]/div/a[contains(text(),'下一页')]",
>             "//*[@id=\"page\"]/div/a[contains(text(),'上一页')]"
>         ],
>         "pageElement": "//*[@id=\"content_style\"]|//*[@id=\"content_left\"]/*",
>         "type": 0,
>         "pageNum": "&pn={10*($p-1)}",
>         "url": "^https?://www\\.baidu\\.com/(s|baidu)",
>         "pageBarTop": 75,
>         "init": "let rs=document.querySelector('div.result-molecule[tpl=\\'app/rs\\']');if(!rs)return;(document.querySelector('#con-ceiling-wrapper')||document.querySelector('#content_right')).appendChild(rs);let tp=document.querySelector('.c-font-medium>div');let t;if(tp)t=tp.children[0];[].forEach.call(rs.querySelectorAll('tr>td'),rp=>{if(tp&&t){rp.className=tp.className;rp.children[0].className=t.className}})",
>         "replaceElement": "#page"
>     }
> 导入
> ![g004](https://user-images.githubusercontent.com/5115423/219967765-6ab2caec-026e-4a6e-934b-5aff5576d066.jpg) ![g005](https://user-images.githubusercontent.com/5115423/219967786-4deb39ce-0b4b-489a-b335-29663399e018.jpg)
> 
> Google Search CSS 谷歌搜索 CSS
> 
> #bres {
>     position: fixed;
>     width: 650px;
>     height: auto;
>     border-radius: 5px;
>     z-index: 999;
>     right: 40px;
>     bottom: 80px;
>     box-shadow: 0 0 5px rgba(0, 0, 0, 0.6)
> }
> #bres>div:last-child {
>     padding: 20px;
>     margin: 0
> }
> Baidu Search CSS 百度搜索 CSS
> 
> #rs_new {
>     position: fixed;
>     width: auto;
>     height: auto;
>     border-radius: 5px;
>     z-index: 999;
>     right: 40px;
>     bottom: 50px;
>     box-shadow: 0 0 5px rgba(0, 0, 0, 0.6)
> }
> #rs_new>div {
>     padding: 20px 20px 0 20px
> }
> #rs_new>table {
>     padding: 0 20px 20px 20px;
>     margin: 0
> }
> right为右侧距离bottom为底部距离，看需求自己调整。

我想修改谷歌相关搜索的大小，为什么我在脚本里搜不到您给的关键字呢，用的暴力猴。

![QQ截图20230224123520](https://user-images.githubusercontent.com/32454224/221093356-282da269-af36-4a41-8853-a595b90069d7.png)

**Comment by hoothin** [comment]
你需要打开配置页，在自定义规则框内修改css
