### ISSUE TITLE
color problem

### ISSUE THREAD

**Issue by AinloDiven** [hoothin/UserScripts#315]
In the "dark mode" of the browser, visiting www.google.com and opening this script after searching will cause the link area to be white

**Comment by hoothin** [comment]
Do not use pagetual under InPrivate mode.

**Comment by hoothin** [comment]
If you still want to run under InPrivate mode. Click [Force to join next page] or use this rule instead.
<pre name="pagetual">
{
    "name": "Google Search",
    "nextLink": [
        "id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
        "id('pnprev')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a"
    ],
    "pageElement": "id('rso')",
    "action": 1,
    "pageNum": "&start={10*($p-1)}",
    "pageBarTop": 55,
    "url": "^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)",
    "replaceElement": "[role='navigation']>[role='presentation']"
}
</pre>
But you will lose some style in next page with this rule.
