### ISSUE TITLE
[Pagetual] Collaboration suggestion

### ISSUE THREAD

**Issue by githubbapoopa** [hoothin/UserScripts#319]
Could you two come together somehow and bundle your excellent work?

https://github.com/sixcious/infy-scroll

https://github.com/sixcious/infy-scroll/issues/54#issue-1614812407

Cheers

**Comment by hoothin** [comment]
https://github.com/sixcious/infy-scroll/issues/20

As you see, I am also a long-term user of infy-scroll. But they are totally different works and used in different ways.

**Comment by githubbapoopa** [comment]
Ok thanks for the info.

Worth the try.

I also made the change towards Pagetual.

Excellent work btw. !!!

Don't know how I could live without it. Saves me so much time and effort.
