### ISSUE TITLE
[Pagetual] https://anime1.me/ 報錯

### ISSUE THREAD

**Issue by skofkyo** [hoothin/UserScripts#320]
https://anime1.me/
需要將版本降至[1.9.34.8]才能正常翻頁

**Comment by skofkyo** [comment]
沒事了
需要更新規則
<pre>
    {
        "name": "anime1.me",
        "example": "https://anime1.me/",
        "url": "^https?://anime1\\.me/",
        "nextLink": "a.next",
        "pageElement": "#table-list>tbody"
    }
</pre>
改成#table-list>tbody>tr

**Comment by hoothin** [comment]
感謝反饋，修復了
