### ISSUE TITLE
[Pagetual] Not working on this website

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#321]
https://streamable.com/
![Screenshot from 2023-03-10 17-19-55](https://user-images.githubusercontent.com/64612555/224309095-9bfd4926-f834-4e6e-b51a-e200da8f2921.png)

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by hoothin** [comment]
You can get video info from https://ajax.streamable.com/api/v1/videos?sort=date_added&sortd=DESC&count=12&page=2 but can not add operation for them with simple code.

If you do not want to operate the video, you can try to install this extension to enable pagetual [ignore-x-frame-headers](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe)

**Comment by rakitanc** [comment]
Wow...it worked man

i installed the extension
