### ISSUE TITLE
当网页数过大，网站停止响应，希望能够指定页数刷新或者继续允许设置预留缓冲时间。

### ISSUE THREAD

**Issue by X012C** [hoothin/UserScripts#323]
希望能够得到实现。（不会是已经做了的功能，只是我没发现。捂脸。）

**Comment by hoothin** [comment]
哪个脚本？

**Comment by X012C** [comment]
> 哪个脚本？

東方永頁機。不好意思，没发现这个是脚本合集的。

**Comment by hoothin** [comment]
有范例网站吗？照理说如果没有开启“强制拼接”，塞入新内容并不会对性能造成影响。
我的确想过拼接时删除一定页数之前的内容，只是这样没法重新取回。
你可以把网址贴上来，也许这个网站的停止响应可以通过其他方法优化。

**Comment by hoothin** [comment]
另外，目前有个选项【禁用拼接，滚动至页尾时自动点击下一页】，滚动至页尾会自动点击下一页。也可以通过规则项`clickMode: true`来在个别网站启用

**Comment by X012C** [comment]
> 

我没有使用强制拼接，在设置自动翻页且翻页数大于一定数，然后就会出现响应过快，最新一页就被刷入了一个提示页面，后续就无法继续加载了。网址是south-plus.net。

**Comment by hoothin** [comment]
原来你说的是这个“停止响应”，南北加我应该已经添加到规则库了，需要添加一个sleep属性

**Comment by hoothin** [comment]
刚刚确认了一下，的确加过了 https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L8532，难道现在一秒间隔也不够了吗？你试试看编辑站点规则，把sleep改大到2000

**Comment by X012C** [comment]
> 刚刚确认了一下，的确加过了 https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L8532 ，难道现在一秒间隔也不够了吗？你试试看编辑站点规则，把sleep改大到2000
> 
> ![image](https://user-images.githubusercontent.com/5361213/224589186-e724e83e-60be-48bb-8094-b9bdb73c5bef.png)

好的，谢谢解答。

**Comment by hoothin** [comment]
也许是因为你没有手动导入我的规则库？我的规则库默认是没有内置的，如果要用的话需要手动点击导入。否则那些个站点都需要自己写规则。

**Comment by X012C** [comment]
> 也许是因为你没有手动导入我的规则库？我的规则库默认是没有内置的，如果要用的话需要手动点击导入。否则那些个站点都需要自己写规则。

~~早上切换回south之后，我没在设置里里面发现截图里面的规则，但是加载测试确实变成功了。现在再进入的时候已经显示了那行sleep的代码。是不是那个更新规则跳转到git，就已经算是自动更新导入了？~~
我开始用的网址准确来说是east-plus，没有严谨报告这点，我有罪。

**Comment by hoothin** [comment]
啊，这小破站ε=( o｀ω′)ノ，除了east还有其他域名吗？我一并加进规则库里去

**Comment by X012C** [comment]
> 啊，这小破站ε=( o｀ω′)ノ，除了east还有其他域名吗？我一并加进规则库里去

这是站内帖子记录的：
bbs.imoutolove.me
www.east-plus.net
www.south-plus.net
www.north-plus.net
east-plus.net
www.spring-plus.net
north-plus.net
www.snow-plus.net
bbs.south-plus.org
south-plus.net
level-plus.net
bbs.level-plus.net
www.level-plus.net
www.summer-plus.net
south-plus.org
summer-plus.net
white-plus.net
bbs.north-plus.net
spring-plus.net
snow-plus.net
www.white-plus.net
bbs.white-plus.net
bbs.south-plus.net
bbs.east-plus.net
bbs.summer-plus.net
www.south-plus.org
bbs.spring-plus.net
assets.south-plus.org
https://south-plus.net/

还检索到相关正则：
(?:(?:www\.|bbs\.)?(?:south|north|level|white|soul|snow|east|spring|summer)-plus\.(?:net|org)|bbs.imoutolove.me|bbs.east-plus.net)/(.*)

还有个新域名：
https://www.blue-plus.net/
（扶额）

**Comment by hoothin** [comment]
感谢反馈，省事不少。已经一网打尽了，你更新下在线规则就可以了
