### ISSUE TITLE
Bug in Pagetual script

### ISSUE THREAD

**Issue by NguyenASang** [hoothin/UserScripts#324]
**Describe the bug**
Auto expansion make it hard to scroll up

**To Reproduce**
1. Go to [this site](https://learn.microsoft.com/en-us/cpp/cpp/one-s-complement-operator-tilde?view=msvc-170)
2. Scroll down to the bottom of the page
3. Try to scroll up and you will see the bug

**Expected behavior**
You can scroll up easily.

**Recording of the bug**
[Link](https://streamable.com/3jt61e)

**Desktop:**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 110.0.1587.69

**Additional context**
Thank you for your powerful script, hope you can fix this bug.

**Comment by hoothin** [comment]
Thanks, it's fixed.

**Comment by NguyenASang** [comment]
But it doesn't expand anymore, I want it to be expanded without the bug when scroll up

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Microsoft Learn",
    "url": "^https?://learn\\.microsoft\\.com/en-us/",
    "loadMore":".show-more-button"
}
</pre>

**Comment by NguyenASang** [comment]
thank you very much.

**Comment by hoothin** [comment]
`"autoClick": ".show-more-button"` will be better.
[autoClick](https://pagetual.hoothin.com/en/rules/autoClick.html) will click only once while `loadMore` will click that button constantly.

**Comment by NguyenASang** [comment]
But it will automatically scroll to the "show more" section, I think "loadMore" is enough.
