### ISSUE TITLE
百度贴吧自动翻页后，头像和回复（楼中楼）无法加载出来

### ISSUE THREAD

**Issue by FxmlesXD** [hoothin/UserScripts#328]
**Describe the bug**
百度贴吧自动翻页后，头像和回复（楼中楼）无法加载出来，头像就显示一个人头，楼中楼就一直显示那个加载的图标。

**To Reproduce**
1. 打开百度贴吧，并且随便打开一个帖子。
2. 往下翻，直到自动拼接下一页。
3. 看到该bug。

**Expected behavior**
希望能够加载出头像和楼中楼并且正常回复楼中楼

**Screenshots**
![image](https://user-images.githubusercontent.com/79508714/224610790-84403c23-d998-467d-99b9-d3e7896868bf.png)
![image](https://user-images.githubusercontent.com/79508714/224610827-81ba72db-b322-4000-a6b6-6b78b1be0361.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser firefox nightly 
 - Version 112.0a1 (2023-03-11) (64-bit)

**Additional context**

**Comment by hoothin** [comment]
你没导入规则库吗？

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/224613949-4a82a9fe-e775-4832-a852-c703ce86cc5f.png)

**Comment by FxmlesXD** [comment]
> ![image](https://user-images.githubusercontent.com/5361213/224613949-4a82a9fe-e775-4832-a852-c703ce86cc5f.png)

不好意思，我现在就关闭issues

**Comment by FxmlesXD** [comment]
谢谢你
