### ISSUE TITLE
the problem in yandex search with site shortcuts

### ISSUE THREAD

**Issue by zenko2** [hoothin/UserScripts#330]
when searching in Yandex, the site icons appear for a second, and then disappear when you turn everything off

![Скриншот 14-03-2023 165719](https://user-images.githubusercontent.com/68221131/225025814-0c6e6abf-86a6-4b33-ac52-92273add1813.jpg)

![Скриншот 14-03-2023 170820](https://user-images.githubusercontent.com/68221131/225027379-dd828a7c-90ce-4c63-a2e1-89f15d0be58b.jpg)

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Yandex",
    "url": "^https?://yandex\\.com/search/",
    "pageElement": "#search-result>li",
    "css": "#search-result>li{content-visibility:visible!important}"
}
</pre>

**Comment by zenko2** [comment]
the import did the problem remained, did not help

**Comment by zenko2** [comment]
https://user-images.githubusercontent.com/68221131/225301444-1591c5fd-4305-4a0f-bb2d-cceaa762eb2f.mp4

**Comment by hoothin** [comment]
Open your developer tools 【ctrl+shift+j】and copy the output log here.

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/225305547-6f395990-c817-4648-baa5-ad0f64219506.png)


Maybe yandex has a different domain you are using besides `^https?://yandex\\.com/search/`?

**Comment by zenko2** [comment]
here's the link

https://yandex.ru/search/?text=%D0%B3%D0%BE%D1%80%D1%8F%D1%87%D0%B0%D1%8F+%D0%B4%D0%B5%D0%B2%D1%87%D0%BE%D0%BD%D0%BA%D0%B0+%D0%B4%D0%BE%D1%80%D0%B0%D0%BC%D0%B0+%D0%BA%D0%B8%D1%82%D0%B0%D0%B9&lr=191

**Comment by hoothin** [comment]
Try this
<pre name="pagetual">
{
    "name": "Yandex",
    "url": "^https?://yandex\\.ru/search/",
    "pageElement": "#search-result>li",
    "css": "#search-result>li{content-visibility:visible!important}"
}
</pre>

**Comment by zenko2** [comment]
thanks a lot the problem is solved everything works as before
