### ISSUE TITLE
【Picviewer CE+】功能请求 1鼠标X毫秒后可以自动显示当前图片大图、2点击图片以外的区域自动关闭

### ISSUE THREAD

**Issue by HookCode** [hoothin/UserScripts#332]
1鼠标X毫秒后可以自动显示当前图片大图、
像 [imagus](https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab) 或 [浮图秀](https://github.com/Mr-VincentW/PhotoShow/issues/49)这样鼠标悬停在图片多少秒以后自动显示当前图片大图，不用再点击菜单图标省一步操作
![image](https://user-images.githubusercontent.com/90203620/225208078-7d139152-ef95-4fe1-9371-ff80571e7960.png)

2点击图片以外的区域自动关闭
![image](https://user-images.githubusercontent.com/90203620/225208224-b337e371-b36b-447b-8419-9d4642193818.png)
每次都要找到关闭按钮才能关闭图片悬浮有些麻烦

**Comment by hoothin** [comment]
设置里都有

**Comment by hoothin** [comment]
那是Imagus的操作逻辑，继续用Imagus。我认为在图片预览方面它比我的脚本更强大
