### ISSUE TITLE
`"Action": 2` does not work on this particular tile set

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#336]
The page: https://www.nexusmods.com/fallout4/mods/36254?tab=images&BH=1
The rule:

```json
[
    {
        "name": "Fallout 4 Nexus - Mods and community",
        "url": "^https?://www\\.nexusmods\\.com/",
        "pageElement": "body > div#mainContent.wrapper > section#section.modpage > div.wrap.clearfix > div.wrap.flex > div.col-1-1 > div.tabs > div.tabcontent.tabcontent-mod-page > div#tab-modimages.container.tab-images > div#list-modimages-2.mod-image-list > ul#mod_images_list_2.tiles.tile-flex.lg-mod-image-list",
        "action": 2
    }
]
```

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Nexus - Mods and community",
    "url": "^https?://www\\.nexusmods\\.com/",
    "init": "let first=document.querySelector('#list-modimages-2 ul>.prev+li>a');if(first)first.click()",
    "pageElement": "#mod_images_list_2",
    "nextLink": "//div[@id='list-modimages-2']//li[a[contains(@class, 'page-selected')]]/following-sibling::li[1]/a"
}
</pre>

There are two pagination, this rule is for the "user-images"
