### ISSUE TITLE
[pagetual] not working on this website

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#340]
https://breakingmuscle.com/?s=lateral+raises

I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Breaking Muscle",
    "url": "^https?://breakingmuscle\\.com/",
    "nextLink": ".pagination-next>a"
}
</pre>
