### ISSUE TITLE
可以添加自定义拼接页面的内容是在新标签打开还是当前标签打开的功能吗

### ISSUE THREAD

**Issue by Sizisa** [hoothin/UserScripts#341]
搜索引擎的页面一般在新标签打，但是有些论坛的在本标签比较好，不知道可以支持不

**Comment by hoothin** [comment]
[openInNewTab](https://pagetual.hoothin.com/en/rules/openInNewTab.html)
`true: 强制在新标签页打开`
`false: 强制在当前页打开`

**Comment by Sizisa** [comment]
> 






> [openInNewTab](https://pagetual.hoothin.com/en/rules/openInNewTab.html) `true: 强制在新标签页打开` `false: 强制在当前页打开`

可以针对网址单独设置嘛

**Comment by hoothin** [comment]
可以的，这个是自定义规则属性

**Comment by Sizisa** [comment]
> 可以的，这个是自定义规则属性
> 
> ![image](https://user-images.githubusercontent.com/5361213/227421096-8f8113cd-1b3a-4736-9689-2751193ed179.png) 在这里插入属性项，形如
> 
> ```
> "action": 0, //<-插入时注意逗号
> "openInNewTab": false
> ```

好嘞，谢谢大佬

**Comment by hoothin** [comment]
注意脚本需要更新到1.9.34.36或者以上版本
