### ISSUE TITLE
反馈些翻页导致显示不正常的网站

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#342]
1，起点章节页造成本章说不显示。短暂显示一下就被隐藏掉。
https://read.qidian.com/chapter/y6QZ6vcuJnJH9vdK3C5yvw2/_dtqtnyV7rvgn4SMoDUcDQ2/

2，在这个漫画站会让图片放大填充窗口宽度，而变得不适宜观看。
http://www.manmanju.com/comiclist/4/106623/1.htm

**Comment by hoothin** [comment]
这两个站需要修改规则，把css项删除就可以了
![image](https://user-images.githubusercontent.com/5361213/227669435-598c8e93-99c5-48cb-92bb-57066da23ea4.png)

**Comment by hoothin** [comment]
建议开启“在侧边显示翻页控制栏”，然后右击太极图标就可以直接修改。修改完点击软盘图标保存

**Comment by Frozen1084** [comment]
谢谢。顺便一提，太极图标真的和很多网站的风格不搭，我是极力避免这个图标显示出来的，要是能用个常规的工具图标就好了。。。

**Comment by hoothin** [comment]
有推荐的图标吗？我待会做个自定义

**Comment by DeepTulip** [comment]
越简洁越好，在所有网页都不显眼不突兀的就好。甚至用些特殊字符也可以。比如"✿"，我觉得都过于花哨，"◎●"倒是不错。以前的超级翻页的设置界面就是一个像素块，那个也不错。

**Comment by Frozen1084** [comment]
图标越简洁越好吧，在所有网页都不显眼不突兀的就行。用◎●这些特殊字符似乎也可以；像以前超级翻页那种用像素块作为设置界面的也不错。

**Comment by hoothin** [comment]
已经加上了，用文字、base64、图片网址都可以
