### ISSUE TITLE
【BUG反馈】百度贴吧页楼中楼翻页bug

### ISSUE THREAD

**Issue by japengwu** [hoothin/UserScripts#345]
**bug页面**：百度贴吧帖子页
**页面链接**：[该链接为我遇到的bug的页面，其它帖子也有相同的问题](https://tieba.baidu.com/p/4902344814)
**bug描述**：点击楼中楼的翻页链接会使整个帖子翻页，例如点击图中的翻页下一页或者具体页码后，楼中楼评论区会先翻页，评论区翻到该页并加载完毕之后（我电脑基本都是0-2秒以内）整个帖子会翻页到相应的页码
**个人猜测**：脚本代码中相应翻页函数里的选择器不够精确（我很菜，别信）
**个人想法**：不知道是否能够通过设置某些规则来解决，我没弄明白，这里只是反馈，作者大大不管我也可以XD
![截图](https://user-images.githubusercontent.com/53229453/227763817-078bfcdf-e4de-4578-9a7e-a34dad89bd65.png)

**Comment by hoothin** [comment]
感谢报错。有更多信息吗？控制台输出是什么？是否已经导入规则库了？
这个网页我测试了一下，没有复现问题。

**Comment by japengwu** [comment]
控制台输出如图所示，但是我也看不懂……我记得是已经导入规则库了，运行环境是Edge浏览器 版本 111.0.1661.51 (正式版本) (64 位)。黑色油猴插件，v14.8.1。刚才我禁用了其他所有的脚本试了一下，还是存在这个问题，但禁用东方永页机后就没事了。
![截图](https://user-images.githubusercontent.com/53229453/227831495-761edb73-7f24-4f85-821c-4c3ce1289253.png)

**Comment by hoothin** [comment]
上翻应该还有一条输出，标明了指向的规则项。也贴上来给我看看呢

**Comment by hoothin** [comment]
类似于这个样子的
![image](https://user-images.githubusercontent.com/5361213/227836860-65b310b5-72f2-4949-b9fa-64f045844db2.png)

**Comment by japengwu** [comment]
抱歉网络不太稳。
这个是完整版的，是 打开页面->楼中楼翻页->整篇帖子自动跳转到第二页 的过程
图片共两页，中间用黑色的横线隔开了
![截图1](https://user-images.githubusercontent.com/53229453/227841441-8dc7b100-d81f-4e5d-8fd1-adc9225ec7fb.png)

**Comment by hoothin** [comment]
看样子似乎是你开启强制拼接了？

**Comment by hoothin** [comment]
rule那个object可以展开。另外我还是不太明白你的描述，可否录个屏呢？

**Comment by japengwu** [comment]
没有开启强制拼接。
刚才我又试了一下chrome浏览器也存在相同的问题
不清楚什么原因，如果实在不行我就先把贴吧页禁用一下吧 >_<
感谢大佬的耐心指点
![微信截图_20230327142214](https://user-images.githubusercontent.com/53229453/227858099-c400fdd9-c166-413a-a195-c42bf0401e5d.png)
下面是录屏，录屏的时候我好像发现了不一样的东西，我开启了写入历史记录设置（不然看小说经常不知道自己看到第几章了），浏览的时候实际上地址栏网址已经切换到了p=3，但是我还在浏览第2页，这个时候当我点击楼中楼的翻页链接，成功翻页后会让当前网页刷新。
![GIF](https://user-images.githubusercontent.com/53229453/227864656-aba34458-4e1d-4bf5-80ca-b6b24d478ac0.gif)

**Comment by hoothin** [comment]
感谢反馈，应该就是这个原因了。可以用这一条在贴吧页面禁用历史记录写入，待会我更新到库中去
<pre name="pagetual">
{
    "name": "百度贴吧看贴",
    "pageBar": "pageBar.classList.add('l_post')",
    "nextLink": "//div[@class=\"pb_footer\"]//a[starts-with(text(), '下一页')]",
    "pageElement": "//div[@class=\"p_postlist\"]/div[starts-with(@class, 'l_post')]",
    "action": 1,
    "pageNum": "&pn={$p}",
    "url": "^https?://tieba\\.baidu\\.com/p/.+",
    "wait": "if(doc==document)return true;let lzl=doc.querySelector('div.hideLzl');if(lzl){var actualTop=lzl.offsetTop;var current=lzl.offsetParent;while(current!==null){actualTop+=current.offsetTop;current=current.offsetParent;}doc.body.scrollTop=actualTop;doc.documentElement.scrollTop=actualTop;return false}else{return true}",
    "history": 0
}
</pre>

**Comment by japengwu** [comment]
完美解决了，感谢大佬的耐心指点
