### ISSUE TITLE
[Picviewer] Mouse Over Zoom Doesn't Work On Instagram

### ISSUE THREAD

**Issue by megamorphg** [hoothin/UserScripts#353]
**Describe the bug**
Zoom in doesn't work on profile pages and related images at the bottom of a post.

**To Reproduce**
1. Go to a profile page
2. Enable mouse-over zoom
3. Mouse over an image
4. Observe doesn't work

**Expected behavior**
Mouse-over zoom doesn't work on profile pages and related images at the bottom of a post.

**Screenshots**
For example:
https://www.instagram.com/justinbieber/

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox
 - Version: 111.0.1 (64-bit)

**Additional context**
This happened before here and was fixed.
https://greasyfork.org/en/scripts/24204-picviewer-ce/discussions/140570

**Comment by hoothin** [comment]
Can't reproduce on firefox v.111.0.1.
this is the target rule for instgram
```
{
 name:"instagram",
 url:/^https?:\/\/[^.]+\.instagram.com/i,
 ext: function(target) {
    if(target && target.previousElementSibling){
        let imgs=target.previousElementSibling.querySelectorAll("img");
        if(imgs && imgs.length==1)return imgs[0];
    }
 }
}
```
try to check your domain of instgram or modify in 【Settings - Other - Custom rules for large image】 to suit yourself.

**Comment by hoothin** [comment]
Open setting and take a look at the option "Method to enable preview". Maybe you have selected altkey for function key? Alt means global menu under windows. So you will lose your focus after pressed alt.

**Comment by hoothin** [comment]
So can you see the float icons bar when your mouse over the images? If not, can you check the console and paste the error here?

**Comment by hoothin** [comment]
Have you updated to the latest version?

**Comment by hoothin** [comment]
Try the version 2023.4.4.1. I can not check as my instgram account is banned.

**Comment by hoothin** [comment]
You can try to modify this rule to suit yourself
```
{
 name:"instagram",
 url:/^https?:\/\/[^.]+\.instagram.com/i,
 ext: function(target) {
    if (target && target.previousElementSibling) {
        let imgs = target.previousElementSibling.querySelectorAll("img");
        if (imgs && imgs.length == 1) return imgs[0];
    }
 }
}
```
I have no idea why it did not work for you.
You can open developer tool and find the real target when your mouse pointer over the image. and then use `ext` to connect the target element with image you want to show.

**Comment by hoothin** [comment]
No, The instgram rule is modified on 2023.4.4.1. I'll mark this issue as closed. You can reopen it if you find sth other wrong.
