### ISSUE TITLE
Disable the "Double Click Disables Pagetual for this Site" feature.

### ISSUE THREAD

**Issue by anoduck** [hoothin/UserScripts#356]
### Thanks

First off, thanks for creating this project. I have missed a working auto page loading feature for my browser for quite some time. It is a pleasure getting this ability back.

-----

From here on, "DC2D" will refer to the feature "Double Click to Disable Pagetual for this Site"

The "DC2D" feature is interfering with other extensions that use the double click to perform actions. Even if the double click is not being used to perform an action with another extension, then the use of a double click is too invasive of a trigger to be implemented. People double-click their screens all the time, if nothing else than to find out where their cursor is at. You can blame microsoft windon't for this, because by growing up with windows, you are habitually taught to double-click for everything. This habit is so engrained, many people have developed a habit to double-click as a nervous tick unconsciously.

If there is a way to disable the "DC2D" feature without digging through the script and commenting it out, then I am unaware of it. If this ability doesn't exist, it really needs to. I would advise choosing a different trigger to activate the "DC2D" feature.

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/230600529-29fd3199-dcad-4905-b71b-65ed70231655.png)

**Comment by anoduck** [comment]
@hoothin This explains SO MUCH, I am not able to open the configuration menu. Clicking the configuration label in the script menu, opens a newtab with the wiki configuration page.
