### ISSUE TITLE
Configuration page does not open

### ISSUE THREAD

**Issue by anoduck** [hoothin/UserScripts#357]
**Describe the bug**
As discovered in issue #356, the configuration menu does not open. Instead, a new tab is opened up and the project github repo is loaded. 

**To Reproduce**
1. Go to a page that should work for pagetual.
2. Click on the tampermonkey icon. 
3. Click under pagetual on the configuration label.
4. Pagetual loads project repository rather than configuration page

**Expected behavior**
I expected a menu or page to load, containing the settings needed for configuration of the plugin.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OpenBSD 7.3 SnapShot
 - Browser: Mozilla Firefox
 - Version: 111.0

**Additional context**

* I have two versions of firefox on my desktop. One is the current release in the ports tree. The other is firefox-esr, which is the LTR. I will attempt to see if pagetual works in firefox-esr.
* I have also tried to debug the script by enabling debugging in tampermonkey. A break in line number sixty was received upon execution. Unfortunately, this provided no insight, due to line sixty being the beginning of the script.

**Comment by hoothin** [comment]
Project repository is the config page.
Why not try to scroll down?

**Comment by anoduck** [comment]
@hoothin It wasn't like that last night, I swear. 😖 Maybe I just needed to unload some cache or something. Anywho, big mystery solved there. Glad I spent all that time troubleshooting. 🤣
