### ISSUE TITLE
[Pagetual] support for other iOS script managers?

### ISSUE THREAD

**Issue by radiochild577** [hoothin/UserScripts#359]
I'm unable to import the rules using [Stay - Userscripts Extension](https://apps.apple.com/us/app/stay-userscripts-extension/id1591620171). The  overlay alert shows but none of the settings or Import button appear when the proper [URL](https://github.com/hoothin/UserScripts/tree/master/Pagetual) is visited. 

 It works fine with this app - [Userscripts](https://apps.apple.com/us/app/userscripts/id1463298887) (the suggested app to use). 

However, I really prefer [Stay](https://apps.apple.com/us/app/stay-userscripts-extension/id1591620171) as my Userscripts manager on iOS as it has a functional UI for the app itself and can update, activate/deactivate, and tweak settings without having to go through Safari. Also, this app allows you to disable scripts on a site-by-site basis, while the suggested Userscripts app can only enable/disable them globally (no site-specific settings).

Is there any way to look into supporting Stay on iOS to import rules and settings?

**Comment by hoothin** [comment]
The IOS is hard to debug, so I just run my Pagetual with Userscripts. After I have more spare time, I will try to debug with stay. Sorry but not now.

**Comment by hoothin** [comment]
I tried to run pagetual on stay and it works well.
It seems that stay can't bypass security restrictions of github, so you should use this [config page](https://hoothin.github.io/UserScripts/Pagetual/) instead

**Comment by radiochild577** [comment]
Great just tried on that page and it worked perfectly - thank you!
