### ISSUE TITLE
Picviewer CE+ 图库不能加载图片

### ISSUE THREAD

**Issue by aaazz47** [hoothin/UserScripts#36]
系统：win10
浏览器：火狐68.0.1 (64 位)  chrome 比较新的一个版本也试过
油猴客户端：Tampermonkey 4.9.5941
脚本版本：2019.7.18.1
症状：
单位的电脑和家里的电脑都试了一下，「查看当前」都是没有问题的，但是点开「图库」之后就是什么图片都不显示（包括缩略图）感觉就像是没有找到图片一样，类似下图。试了很多网站都是如此。

![TIM截图20190725110418](https://user-images.githubusercontent.com/19562000/61843228-825a5e80-aecd-11e9-800f-05a0b19967d4.png)

**Comment by hoothin** [comment]
试了下chrome 75.0.3770.142是没问题的，至少在cnbeta首页是这样

在 2019年7月25日星期四，aaazz47 <notifications@github.com> 写道：
