### ISSUE TITLE
求可用下载规则https://haitbook.com/

### ISSUE THREAD

**Issue by lovol1** [hoothin/UserScripts#362]
求网站：https://haitbook.com/的下载规则，您之前给出的规则：

.uk-list>li>a@@@@@@let contentMatch=data.body.innerHTML.match(/url: '\/showpapercolor\.php',[\s\S]*?paperid:\s*'(\w+)',\s*vercodechk:\s*'(\w+)'/);if(!contentMatch)return "";$.ajax({url: '/showpapercolor.php',type: 'POST',data: { paperid: `${contentMatch[1]}`, vercodechk: `${contentMatch[2]}`},error: function (xhr) {cb("");},success: function (colorresponse) {cb(colorresponse.replace(/<img.*?>/,"").replace(/<br \/>/g,""))}});return false;

无法正常下载，章节总数正确，但下载非小说正文，而是每章相同内容，
如下图：
![image](https://user-images.githubusercontent.com/114041917/233149355-a75dcd82-1d40-4ec0-b7e7-bd5cb5db44d9.png)

**Comment by hoothin** [comment]
没有问题啊，是不是邮件里转码了？你到github上来复制规则后再去下载试试。
![image](https://user-images.githubusercontent.com/5361213/233223686-81b03aaa-fd14-4cd1-b39a-2f4aa03ec8da.png)

**Comment by lovol1** [comment]
> 没有问题啊，是不是邮件里转码了？你到github上来复制规则后再去下载试试。 ![image](https://user-images.githubusercontent.com/5361213/233223686-81b03aaa-fd14-4cd1-b39a-2f4aa03ec8da.png)

好的！能用啦，之前是邮件的问题，现在能用啦，谢谢大佬！打扰您啦，太感谢啦！
