### ISSUE TITLE
Please add "open image in new tab" button and/or keyboard shortcut

### ISSUE THREAD

**Issue by billza7** [hoothin/UserScripts#364]
While the 'Current' or 'Gallery' view is nice, sometimes it's better if I can open the image in a new tab.

**Comment by hoothin** [comment]
Nice idea. I'll try to add this feature later.

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/234819091-7f64b61d-6636-4555-a384-ea978d210bfb.png)
Open settings and check these.
You can open current or actual big image in new tab by holding Alt key, or invert that to open in new tab by default.
