### ISSUE TITLE
[Picviewer CE+] 火狐中无法拖拽、无法移动位置

### ISSUE THREAD

**Issue by ixzhaoo** [hoothin/UserScripts#367]
火狐 112.0.2
Picviewer CE+ v2023.4.28.1
tampermonkey v4.18.1

![动画](https://user-images.githubusercontent.com/127864725/235277622-0b8404ac-a279-46b8-8ce2-9dbea94ef9a5.gif)

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/235277958-7b9f0716-2d48-4ecf-bfc9-1cbe3535a47a.png)

没有复现，是否和某些鼠标手势扩展冲突了？

**Comment by hoothin** [comment]
![12345](https://user-images.githubusercontent.com/5361213/235278356-0f50aae5-d63c-467d-a566-186fb2ec7589.gif)

检查下你安装的贴吧优化脚本。可能是某个脚本把鼠标事件拦截了

**Comment by ixzhaoo** [comment]
感谢回复。
排查到了，是与[网页限制解除](https://github.com/Cat7373/remove-web-limits)冲突，改用[网页限制解除(改)](https://greasyfork.org/zh-CN/scripts/28497-%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4-%E6%94%B9)后解决。

另外，能否加入设置项控制图片左上角分辨率的显示与隐藏？

**Comment by hoothin** [comment]
暂时没有打算加这个选项。鼠标放图片中间就能隐藏，或者点击图片外部

**Comment by ixzhaoo** [comment]
好的了解
