### ISSUE TITLE
[Pagetual] www.simply-hentai.com 報錯

### ISSUE THREAD

**Issue by skofkyo** [hoothin/UserScripts#369]
需降至 v1.9.36.6 才能正常翻頁，不論是自驅動還是我提交的自定義規則。

測試鏈接
https://www.simply-hentai.com/1-mangas

**Comment by hoothin** [comment]
感謝報錯，我本地測試沒有發現問題，控制臺有什麽報錯輸出嗎？

**Comment by skofkyo** [comment]
奇怪了居然正常了，我當時明明3種瀏覽器交叉測試都報錯啊...
當時忘記截圖了，抱歉打擾了。

**Comment by skofkyo** [comment]
chrome
![ch001](https://user-images.githubusercontent.com/5115423/236593416-7a54d9e0-c220-40c7-acb3-73fbc2a17e9e.jpg)
![ch002](https://user-images.githubusercontent.com/5115423/236593417-5aa755a2-f8bc-4d9c-bb06-d323f30c0ef1.jpg)
Firefox
![ff001](https://user-images.githubusercontent.com/5115423/236593418-0126cffb-eb12-49ac-a4e2-4e621d2e5842.jpg)
![ff002](https://user-images.githubusercontent.com/5115423/236593420-50a5c424-5784-4a40-ad0f-7e5f8711821a.jpg)

報錯鏈接
https://steamcommunity.com/id/officialSqueak/myworkshopfiles/?appid=431960

更新至v1.9.36.6之後的版本就會出現這個情況
看了更新的代碼搞不懂為什麼會這樣
難道就只有我會遇到這種情況

**Comment by hoothin** [comment]
是不是最後多了一個回車？

**Comment by skofkyo** [comment]
嘗試了重設成出廠狀態
重新導入官方線上規則
變成1.9.36.12之後的版本不明原因卡住

1.9.36.12
![ch003](https://user-images.githubusercontent.com/5115423/236594919-20e2f3fc-1098-4b82-b453-4f0fad0df2c5.jpg)
之後的版本就沒有出現下一頁元素
![ch004](https://user-images.githubusercontent.com/5115423/236594923-de26bbe0-4944-489b-a6ec-90685dd0a5c4.jpg)

**Comment by hoothin** [comment]
感謝報錯，找到原因了，你更新試試

**Comment by skofkyo** [comment]
兩種情況都沒發生了，排錯辛苦了，感謝您。
