### ISSUE TITLE
[Pagetual] Not working on Scribd

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#378]
I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

https://www.scribd.com/search?query=%22kotak+private%22&content_type=documents&page=1

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Search | Scribd",
        "url": "^https?://www\\.scribd\\.com/search",
        "example": "https://www.scribd.com/search?query=%22kotak+private%22&content_type=documents&page=1",
        "waitElement": [
            "[data-testid='search-results'] ul",
            "!.atAndBelow [class^='LazyImage-module_image']:not([class*='LazyImage-module_loaded'])"
        ],
        "action": 1
    }
</pre>

**Comment by hoothin** [comment]
Just click it.
![Uploading image.png…]()

**Comment by rakitanc** [comment]
> Just click it.
> 
> ![image](https://user-images.githubusercontent.com/5361213/239512223-7559486c-7ea9-45c9-a943-f14949baa58e.png)

Thanks mate, Now it's visible
