### ISSUE TITLE
1688店铺商品展示页面有错误，瀑布流加载后有3行产品展示不显示。望修整。感谢

### ISSUE THREAD

**Issue by KKKFFFLLL** [hoothin/UserScripts#379]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KKKFFFLLL** [comment]
<img width="444" alt="image" src="https://github.com/hoothin/UserScripts/assets/134064604/38d4d546-ddd9-4c58-8c47-d9b84b088a7a">

**Comment by hoothin** [comment]
网址给我一下

**Comment by hoothin** [comment]
你确认一下你是否已经成功导入规则库并且更新成功了，如果已经正常导入了，给我一个具体的网址

**Comment by hoothin** [comment]
收到你的额外信息了，你试试这个规则
<pre name="pagetual">
{
    "name": "1688全部商品页",
    "url": "^https://.*\\.1688\\.com/page",
    "pageElement": "#bd_1_container_0 > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(6) > div",
    "pageAction": "window.setUrl=null;window.index=0;eles.forEach(e=>{e.onclick=()=>window.open(e.dataset.url,'_blank');})",
    "pageInit": "if(!window.index)window.index=0;if(!window.setUrl){window.setUrl=()=>{setTimeout(()=>{if(window.url){eles[window.index++].dataset.url=window.url;window.url=null;}if(eles[window.index]){eles[window.index].click();window.setUrl()}},1)};Object.defineProperty(doc.defaultView, 'open', { get: function () { return (s)=>window.url=s; } });window.setUrl();}if(eles.length<=window.index)return true;else return false;",
    "waitElement":"!.main-picture[src^=data]"
}
</pre>
