### ISSUE TITLE
[Pagetual] Not working on Upwork

### ISSUE THREAD

**Issue by rakitanc** [hoothin/UserScripts#380]
I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

https://www.upwork.com/ab/profiles/search/?loc=india&q=Market%20Research%20Competitive%20Analysis

**Comment by hoothin** [comment]
Upwork do not support iframe.
You should write a rule by yourself to post message to `https://www.upwork.com/api/graphql/v1` with request like
```
{
    "paging": {
        "start": 10,
        "rows": 10
    },
    "facets": [
        "hourly_rate"
    ],
    "userQuery": "Market Research Competitive Analysis",
    "usOnly": false,
    "countries": [
        "India"
    ]
}
``` 
Use [pageAction](https://pagetual.hoothin.com/PagetualGuide/en/rules/pageAction.html).
Sorry but I won't write that for you as I have work matters more.

**Comment by rakitanc** [comment]
Sorry brother..but i have no idea about code and how to use it🥺

**Comment by hoothin** [comment]
It's easy, otherwise, write an independent script to run in iframe to set `window.self = window.top` is a way. Sorry but I can't spend my time more than enough for you.
You should learn to write custom rule as I make this script just to do this thing.
