### ISSUE TITLE
Open with Video Player

### ISSUE THREAD

**Issue by rahaaatul** [hoothin/UserScripts#382]
### The Problem

I'm always frustrated when I have to play a video on my android browser (eg. ThisAV 🤫😅)  and it gets stuck and I have to refresh or something else happens and I can't able to open it with my video players. I would like to open media with my media players.

### The Solution

An userscript that will automatically show a pop up when it detects a media or a media playing, and it will say, "Open with [player]". 

This player should be configurable in the userscript settings, eg. package name: `com.mxtech.videoplayer.pro` and the name for simplification in the pop-up, eg. "MX".

Also, it should detect the device if it's Android or Desktop. If it's Android it will redirect for Android apps and if it's Desktop, it will redirect for Desktop apps. Or the user can manually choose, which one to keep.

When you click on the pop-up, it'll show media resolution like 1080p/720p etc (kinda like IDM). and when you click on one of them, it'll send the media link to the media player and hopefully it'll start playing the media.

A special request, make the pop-up look really nice, modern and sleek design. It should pop from bottom if it's Android device or IF YOU CAN, like add extra button in the web player to open with media player that'd be sick!

Thank you, and hope you're doing well BTW @hoothin .

**Comment by hoothin** [comment]
Good day. You can try Quark Browser. Or add URL protocol to call local app with my [SearchJumper](https://hoothin.github.io/SearchJumper/). Sorry but I do not accept creation request as I write script just for myself.

**Comment by rahaaatul** [comment]
Ah, well, if you ever change your mind then...
