### ISSUE TITLE
希望适配新版淘宝网页搜索

### ISSUE THREAD

**Issue by qq392784506** [hoothin/UserScripts#383]
**Describe the bug**
淘宝网页版更新以后，第1页图片正常，自动翻页后的第2页及之后无法显示图片。
确认网络无任何问题，关闭自动翻页后，手动翻页正常。

**Expected behavior**
希望更新规则适配https://s.taobao.com/search?_

**Screenshots**
![QQ截图20230529112142](https://github.com/hoothin/UserScripts/assets/6705867/e11a6b96-aee6-4f0d-a09e-f2a9450ac70a)

**Desktop (please complete the following information):**
 - OS: WIN10 22h2
 - Browser ：EDGE 113.0.1774.57 
 - Version ：tampermonkey最新版，东方永页机最新版（内置两条规则已经更新），

**Additional context**

**Comment by hoothin** [comment]
我从来没为淘宝搜索页写过规则。这些大厂养那么多吃干饭的前端，一天不改版就闲得蛋疼。所以我不打算追着这些大厂的改版更新规则。
你想要支持的话可以自己写规则，在智能规则的基础上添加 [waitElement](https://pagetual.hoothin.com/PagetualGuide/en/rules/waitElement.html) 指向图片占位符或者加载完成后的元素。
