### ISSUE TITLE
pixiv站imagus扩展和本脚本的适配有点小bug

### ISSUE THREAD

**Issue by Franinc** [hoothin/UserScripts#384]
https://www.pixiv.net/users/25555102/artworks
以上面链接为例，imagus对第一页的作品正常工作，鼠标停在图上时imagus的加载图标和最终图片显示都跟着鼠标走。
但对于永頁機自动加载出的第二页，imagus出现问题，加载图标和图片显示都固定在浏览器左上角。而且当原图大到会盖住鼠标时，imagus加载的最终图片会闪烁一下消失。

其它网站看起来正常，比如e站画廊无论自动加载多少页，imagus会一直跟着鼠标。

![Snipaste_2023-05-29_22-58-43](https://github.com/hoothin/UserScripts/assets/26399054/cfb707a2-8b32-46d5-a254-fa73888fe0c0)

版本：
win10
Cent Browser 版本 5.0.1002.354（正式版本）（64 位） (Chromium 102.0.5005.167)

永頁機规则：
```
https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json
http://wedata.net/databases/AutoPagerize/items_all.json
```

**Comment by hoothin** [comment]
因为pixiv的翻页是在iframe里模拟的，并不在当前页面上。imagus可能没考虑到这种情况。你可以用我写的picviewer ce+来看大图

**Comment by Franinc** [comment]
好的多谢
