### ISSUE TITLE
bing搜索，会自动返回顶部

### ISSUE THREAD

**Issue by qq392784506** [hoothin/UserScripts#385]
**Describe the bug**
使用cn.bing.com网页搜索的时候，如果离开当前cn.bing.com网页搜索的标签页一段时间，搜索页面会自动返回顶部。
已经排除其他其他扩展和脚本的干扰。

**Expected behavior**
希望能够修复

**Desktop (please complete the following information):**
 - OS: win10 22h2
 - Browser：edge 113.0.1774.57 
 - Version 東方永頁機 v.1.9.36.32（规则https://ghproxy.com/https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json
https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json
http://wedata.net/databases/AutoPagerize/items_all.json）

**Additional context**

**Comment by hoothin** [comment]
这是必应自己加的代码
```
sj_be(_w, "focus", function() {
    sj_evt.fire("focusTopScrollStart")
});
```
想要取消，自己写个脚本，解绑 Window 的 focus 事件监听
