### ISSUE TITLE
求大佬给下载https://www.5yydstxt426.com/里面小说的规则

### ISSUE THREAD

**Issue by apprenticeofC** [hoothin/UserScripts#389]
试过用东方永夜机加自定义章节来下载，但是不全，因为章节里面有分页。
并且试过博主发的其它网站有分页的那些规则，但是运行不了。
诚心求大佬给个解决方案，感谢！

**Comment by hoothin** [comment]
下载下来也没有用，有字体加密 https://www.5yydstxt426.com/font/font.ttf 和图片加密 https://www.5yydstxt426.com/toimg/data/3691658535.png 没人会愿意为这破站整理对照表

**Comment by apprenticeofC** [comment]
好吧，还是感谢你的解答
