### ISSUE TITLE
【bug】在GitHub官网搜索，从第二页开始点击star没反应

### ISSUE THREAD

**Issue by ahwgit** [hoothin/UserScripts#391]
- Device: [HP envy4 笔记本]
 - OS: [win11 IoT]
 - Browser [百分浏览器最新便携版，内核版本102]

**Comment by hoothin** [comment]
正常的吧，新版github改成spa了，而且禁止嵌入iframe。
想要插入的元素有对应功能，要么自己在pageAction写代码加onclick，要么安装解除cors的插件（不推荐，有安全风险）

**Comment by ahwgit** [comment]
明白了，谢谢！搜索了下，有几个插件可以解除CORS限制并配置解除限制的范围，如Moesif Origin & CORS Changer、CORS Everywhere，不过还是有风险
