### ISSUE TITLE
你好，能帮我适配一下这个网站吗？

### ISSUE THREAD

**Issue by s990649505** [hoothin/UserScripts#397]
https://www.69shu.com/
这个网站启用小说下载器，下载下来的小说有三个重复章节名，我喜欢听小说，所以每次都得听三遍章节名。
可以适配一下，只有一个章节名吗？不含日期及作者
谢谢

**Comment by hoothin** [comment]
选项设置-文本干扰码，输入`.hide720`，其余选项都选否
