### ISSUE TITLE
在KiwiBrowser上似乎不起作用

### ISSUE THREAD

**Issue by ss1969** [hoothin/UserScripts#399]
**Describe the bug**
在KiwiBrowser上似乎不起作用
测试网站：www.baidu.com

**To Reproduce**
Goto www.baidu.com and search anything

**Expected behavior**
应该自动拼接页面但是没有

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 一加Ace
 - OS: ColorOS 13.1（Android 13， PGKM10 Build/TP1A.220905.001)
 - Browser  KiwiBroswer 
 - Version  116.0.5845.22
 - TamperMoney: v4.19.0

**Additional context**

**Comment by hoothin** [comment]
![Screenshot_20230721_172704](https://github.com/hoothin/UserScripts/assets/5361213/8c502b7b-ced6-4568-97ad-fed8e9664ab8)
在配置页检查下规则有没有成功导入，以及导入规则是否有条数显示

**Comment by ss1969** [comment]
后续测试：m.baidu.com没问题能拼接，但是百度有时候不自动跳转，当网址仍然是baidu.com开始的时候，会刷“少女祈祷中”，然后提示“没有检测到有效内容，请点击查看”。
不过百度不是重点。在这个漫画网站 https://cocomanga.xyz/comic/35652/487852.html 上，Win10+Edge+东方一切正常，安卓+Kiwi+篡改猴，无法拼接。但我觉得这有可能是Kiwi的问题就是了。。。

**Comment by hoothin** [comment]
感谢反馈，关于第一个问题，大概率是撞上百度以wappass开头的人机校验的页面了。你可以在“没有检测到有效内容”出现的时候点击这个提示手动进行校验。
第二个问题我待会有空帮你看看。

**Comment by hoothin** [comment]
稍稍看了下，这个站是有`X-Frame-Options:DENY`响应头的，而我并没有为这个站写过规则，因此不论在 windows 还是 android，这个站都不应该能正常翻页。
如果你想要实现翻页，可以尝试自行安装[ignore-x-frame-headers](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe) ，然后就能绕过响应头限制，效果如下
![image](https://github.com/hoothin/UserScripts/assets/5361213/83557a80-697f-444f-a55a-988b79236162)
