### ISSUE TITLE
在国际版Bing下工作不正常

### ISSUE THREAD

**Issue by MartPeggy** [hoothin/UserScripts#401]
**Describe the bug**
在国际版bing.com下触发翻页会导致重复的页面
**To Reproduce**
1. 使用魔法
2. 打开脚本，默认设置
3. 进入bing搜索，搜索任意关键字

**Expected behavior**
正常翻页

**Screenshots**
![image](https://github.com/hoothin/UserScripts/assets/88977170/813a2cb4-a6c0-49dd-a031-f77d6c389821)
![image](https://github.com/hoothin/UserScripts/assets/88977170/ee3e0f94-dfa1-46a3-9ec3-7f5ecaebfb3a)
（已进入隐私模式，关闭所有扩展和其他脚本）
**Desktop (please complete the following information):**
 - OS: win10 22H2
 - Browser: edge
 - Version 114.0

**Additional context**
谢谢大佬，脚本很好用

**Comment by hoothin** [comment]
测试了没问题，你没开全局代理吧？如果是通过脚本管理器来获取下一页，而脚本管理器没挂代理，那www.bing.com肯定会被重定向到cn.bing.com 。
你可以尝试开启强制拼接，这样下一页就不是通过脚本管理器加载，而是在当前页获取了。
