### ISSUE TITLE
申请适配kaggle

### ISSUE THREAD

**Issue by l438370226** [hoothin/UserScripts#402]
大佬有时间适配一下kaggle吗，谢谢
https://www.kaggle.com/

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "General | Kaggle",
    "url": "^https?://www\\.kaggle\\.com/discussions/",
    "example": "https://www.kaggle.com/discussions/general",
    "pageElement": "ul.km-list--avatar-list>li",
    "nextLink": "[title=\"Next Page\"]",
    "wait": 1000
}
</pre>
因为是单页应用，所以可能需要 [include](https://pagetual.hoothin.com/en/rules/include.html) 和 [exclude](https://pagetual.hoothin.com/en/rules/exclude.html) 排除下

**Comment by hoothin** [comment]
也可以通过 [nextLinkByUrl](https://pagetual.hoothin.com/en/rules/nextLinkByUrl.html) 来构造`?page=xx` 的url, 然后 action:1 插入
