### ISSUE TITLE
Doesn't work on https://steampeek.hu/

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#403]
Please test. I did all possible rules, including the default.

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "SteamPeek",
        "url": "^https?://steampeek\\.hu/",
        "example": "https://steampeek.hu/?from=108&tagid=86",
        "pageElement": "#lister_result_container>article",
        "nextLinkByUrl": [
            "\\?(from=(\\d+)&)?",
            "?from={$2+36}&"
        ]
    }
</pre>

**Comment by Auditormadness9** [comment]
lotta images look like this
![image](https://github.com/hoothin/UserScripts/assets/71278545/02afd50d-2bd1-4e8c-b84d-ff14bae5565d)

**Comment by hoothin** [comment]
Try to take a look at lazyImgSrc
