### ISSUE TITLE
【Picviewer CE+】工具栏删除不想要的功能图标会消失

### ISSUE THREAD

**Issue by Noah1995** [hoothin/UserScripts#404]
1丶工具栏删除不想要的功能图标会消失
(文字和功能还在...没有图标)
![image](https://github.com/hoothin/UserScripts/assets/25548230/7ab64ca1-b915-443e-aecc-c06d163a271b)

2丶点击外部覆盖层关闭无效....(这个问题已经很久了)
![image](https://github.com/hoothin/UserScripts/assets/25548230/96ea9eb2-8a78-4f0f-9271-59ec43db91a3)

**Comment by hoothin** [comment]
你没开覆盖层当然无效
