### ISSUE TITLE
Pagetual: failed to load

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#405]
Pagetual  1.9.36.43

https://www.wplocker.com/index.php?do=search

![image](https://github.com/hoothin/UserScripts/assets/19517680/a16c88e2-b8ff-4720-a351-e51a8015ea74)

**Comment by hoothin** [comment]
You can make post param like `#p{}`
<pre name="pagetual">
    {
        "name": "WPLOCKER.COM - GPL LICENSED WORDPRESS THEMES & PLUGINS",
        "url": "^https?://www\\.wplocker\\.com/",
        "example": "https://www.wplocker.com/index.php?do=search",
        "nextLinkByJs": "let kw=document.querySelector('#searchinput').value,page=doc.querySelector('.navigations>span');page=parseInt(page.innerText)+1;return location.href+`#p{do=search&subaction=search&search_start=${page}&full_search=0&result_from=${(page-1)*16+1}&story=${kw}}`",
        "pageElement": ".row>.col-xs-12",
        "wait": 1000
    }
</pre>
