### ISSUE TITLE
能设置picviewer ce+的预览图片相对窗口固定吗

### ISSUE THREAD

**Issue by actforjason** [hoothin/UserScripts#406]
目前的picviewer预览图片是相对页面固定，翻页后会消失，虽然可以拖拽但比较麻烦，不利于文字和图片对比参考。希望可以添加一个类似position为fixed的功能。

**Comment by hoothin** [comment]
多谢提供idea，是个好建议

**Comment by hoothin** [comment]
已经添加上了，开关在`设置-图片窗口-固定位置`，你测试看看有什么bug没有
