### ISSUE TITLE
一个改变网页宽度的需求

### ISSUE THREAD

**Issue by DeepTulip** [hoothin/UserScripts#407]
不好意思，这可能是个比较宽泛的请求。当我换上高分屏之后，发现大多数的网站无法适配高分屏的宽度，网页呈柱状，大量显示面积被浪费。常用的网页如果简单我会写个调整宽度的css，复杂的我就无能为力了。

和自动翻页一样，这个需求有着普遍性，应该有很多人有这样的需求。大佬能在这个问题上想想办法吗？

这是B站的定阅主页，作为住在B站的老用户，这个信息密度让人绝望，一排只显示一项，整个页面也只显示5项：
![20230810121640](https://github.com/hoothin/UserScripts/assets/125360690/0b6fa08c-ddbb-4622-8f15-e7a88a2ec706)
与之对比的油管主页，就没必要贴图了，不管多宽都塞的满满当当，信息密度是B站10倍。

这是solidot
![20230810115814](https://github.com/hoothin/UserScripts/assets/125360690/679d35e2-999b-458d-9026-3d29bad87af6)

这是solidot所山寨的原版 slashdot
![20230810120328](https://github.com/hoothin/UserScripts/assets/125360690/6fada423-2189-4463-8ba9-9c3e88df61b4)

这是卡饭，我发现这类论坛最好调整宽度，只要将wp元素设置为页面宽度的85%就行，这类论坛最具调整价值：
![20230810122015](https://github.com/hoothin/UserScripts/assets/125360690/a7b05a55-ff2c-4d20-9e4d-57b21b91df6d)

**Comment by DeepTulip** [comment]
这个请求非常冒昧，与这个库的脚本无关，不过我用得最多最重要的几个脚本都来自这个库，就厚颜提出请求了。

**Comment by hoothin** [comment]
我想这个需求没有什么通用的解决方案，只能单独写css。例如 discuz 限制宽度是通过 max-width，而 b 站是通过 flex。
开始我还觉得通过使用简悦提取主体内容再重新布局是个好办法，但测试后发现，对于列表信息，提取主体内容后由于样式丢失，基本无法正常阅读。
所以，解决方案只有单独适配一种，推而广之的通用方案我暂时想不到。

**Comment by DeepTulip** [comment]
好的，谢谢。
