### ISSUE TITLE
東方永頁機 页面无法适配

### ISSUE THREAD

**Issue by Nevidebla** [hoothin/UserScripts#408]
游民星空网站 排版错位
http://wt.gamersky.com/201503/537537.shtml
![image](https://github.com/hoothin/UserScripts/assets/54260027/1e333b2d-e207-45a2-8dbe-03a9abee4f99)

**Comment by hoothin** [comment]
永页机更新到最新版了吗？我本地测试没有问题。你是不是自行修改主体元素到`p>a`了？
![image](https://github.com/hoothin/UserScripts/assets/5361213/7555fc90-0904-49d5-850f-3592e0cf1227)
