### ISSUE TITLE
pagetual: msn.com

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#409]
https://www.msn.com/en-us/news/world/iran-releases-four-americans-from-evin-prison/ar-AA1f6fIx

![image](https://github.com/hoothin/UserScripts/assets/19517680/44dba347-ee6f-45cb-9120-d7b3108efe6e)

need load automatically

**Comment by hoothin** [comment]
It's easy to make one by yourself. [loadMore](https://pagetual.hoothin.com/en/rules/loadMore.html)
<pre name="pagetual">
    {
        "name": "MSN news",
        "url": "^https?://www\\.msn\\.com/.*/news/",
        "example": "https://www.msn.com/en-us/news/world/iran-releases-four-americans-from-evin-prison/ar-AA1f6fIx",
        "loadMore": "button[data-test-id=continue-reading-button]"
    }
</pre>
