### ISSUE TITLE
pagetual: trends.google.com

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#410]
https://trends.google.com/trends/trendingsearches/realtime?geo=JP&hl=en-GB&category=all

![image](https://github.com/hoothin/UserScripts/assets/19517680/e60ccb71-6475-448b-b1b9-8200260d8a0b)

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/c857af52-ebe0-4d47-aff5-c6fbc874eb0c)
Add [loadMore](https://pagetual.hoothin.com/en/rules/loadMore.html) on this way. 
Then you'll get `"loadMore":".feed-load-more-button"`
