### ISSUE TITLE
pagetual: the script is outdated, update to the latest version in time! [weird notice]

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#411]
**Describe the bug**
weird behaviour notice

**Screenshots**
![image](https://github.com/hoothin/UserScripts/assets/19517680/53a4df0c-8fa7-4b65-896b-0ed67043755c)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome stable

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/34d2d1d9-fdf7-42bd-8f20-9c11855583f5)

**Comment by hoothin** [comment]
So why not upgrade to the latest version?

**Comment by 3xploiton3** [comment]
thanks, issue has been solved

usually i  use check update from tampermonkey,
![image](https://github.com/hoothin/UserScripts/assets/19517680/4d9fa2c5-dd57-45ca-86b6-97099c29eca6)
