### ISSUE TITLE
pagetual: ipinfo.io

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#414]
https://ipinfo.io/countries/id#section-asns

![image](https://github.com/hoothin/UserScripts/assets/19517680/68aa94dd-476e-457c-90aa-9689d16aad3d)

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "IPinfo.io",
    "url": "^https?://ipinfo\\.io/countries/",
    "example": "https://ipinfo.io/countries/id#section-summary",
    "loadMore": "//button[text()='View more']"
}
</pre>
