### ISSUE TITLE
B站关注列表按钮失效

### ISSUE THREAD

**Issue by HOR53** [hoothin/UserScripts#415]
第一页正常显示菜单
第二页开始不显示菜单且点击无响应，只有名字可以正常点击进入up主空间
![page 2](https://github.com/hoothin/UserScripts/assets/142051860/a9109eef-b88c-4919-83e0-8e204277203e)
![page 1](https://github.com/hoothin/UserScripts/assets/142051860/00dc4d11-b768-44fe-afba-d4c9e797f5c7)

**Comment by HOR53** [comment]
电脑系统win7 使用edge浏览器 永页机规则是fork上您提供的规则库

**Comment by hoothin** [comment]
我很少用b站，加上b站前端改版太频繁，所以不会为它去写规则。
你实在想要发消息功能的话，可以参照规则库里的范例，自行添加[pageAction](https://pagetual.hoothin.com/cn/rules/pageAction.html)

**Comment by HOR53** [comment]
好的 谢谢
