### ISSUE TITLE
无规则的自动翻页失效

### ISSUE THREAD

**Issue by Frozen1084** [hoothin/UserScripts#417]
这几个H漫画网站，以前都是可以自动翻页的，现在一个都不行了。大概几个月前还是正常的。

http://www.177picyy.com/html/2023/08/5671621.html
https://18h.mm-cg.com/zh/18H_content/9199/content.html
https://123548.xyz/e/action/ShowInfo.php?classid=1&id=28294

希望不写网站规则，用通用规则进行翻页。

**Comment by Frozen1084** [comment]
不好意思，你指的自定义规则确切是指哪里？我在"编辑站点规则"和翻页器设置界面都没找到“pageInit”相关的选项。

**Comment by Frozen1084** [comment]
另外，这几个网站都有明显的翻页特征，比如"1，2，3，4"这个递增的页码，或者"下一页"这样的关键字，当自定义规则无效时，能自动使用这样的通用规则吗？

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/afe1b91c-e90b-4c2e-b12e-7abb633245ee)

**Comment by Frozen1084** [comment]
抱歉我看的是18h.mm-cg.com的站点规则。其他两个网站没有办法吗？

刚把Super_preloaderPlus_one_改(19年的老版本)打开试了下，在177picyy.com强制拼接仍旧有效。
能增强"强制拼接"来实现Super_preloaderPlus类似的效果吗？感觉这个脚本的强制拼接比永页机强大很多，很多永页机无效的页面它都能正常工作。
遇到不支持的站点只能发帖请求支持，太不好意思了，有强大的强制拼接就一劳永逸了。

**Comment by hoothin** [comment]
我之前解释过很多次了，没有链接的话是没可能强制拼接的。
至于另外两个站，你不想写规则的话更新下脚本就支持了。
