### ISSUE TITLE
在google弹窗 "没有检测到有效内容，点击查看"

### ISSUE THREAD

**Issue by fir05** [hoothin/UserScripts#420]
不知道为何有这个弹窗，关闭永页机就消失了。看控制台，好像访问了一个AV网站

<img width="1264" alt="20230823053953" src="https://github.com/hoothin/UserScripts/assets/96730278/88735f84-b87b-420d-8cbc-feeead2fba06">

<img width="1020" alt="20230823054659" src="https://github.com/hoothin/UserScripts/assets/96730278/cf8299fa-b33b-4d22-b62f-fea9003dfee2">

**Comment by hoothin** [comment]
你搜索结果里有missav的这个链接吗？

**Comment by fir05** [comment]
不好意思，我不知道移动端是什么。或者是其他扩展或者脚本导致了切换移动端？

https://www.google.com/search?num=50&safe=off&filter=0&newwindow=1&hl=zh-CN&safe=off&filter=0&q=%E5%AE%89%E9%BD%8B%E3%82%89%E3%82%89

**Comment by hoothin** [comment]
就是点击控制台左侧的手机图标出现的模拟手机视图。
你试试更新一下内置的在线规则。我给移动端规则新加了exclude，可以在桌面端排除移动端规则。

**Comment by fir05** [comment]
没有打开手机视图。
更新后问题消失了，不过我看规则，触发的仍旧是手机规则，只是不再预读那个网站了。

<img width="269" alt="20230823093931" src="https://github.com/hoothin/UserScripts/assets/96730278/f7d9b6f6-06ed-4583-b3fe-bd1433420eaf">

**Comment by hoothin** [comment]
这个规则下方有exclude项吗？

**Comment by fir05** [comment]
能否在配置页增加一个更新 pagetual.user.js  文件的按钮？我有很多次是打开它的raw链接手动更新的，感觉添加一个按键方便很多。或者有手动更新的方法，只是我没发现？

**Comment by fir05** [comment]
有
```
{
    "name": "google search mobile",
    "action": 0,
    "url": "^https://(?:www\\.)?google\\..*/search",
    "pageElement": "id('rso')/div|id('rso')/style",
    "insert": "//div[@role=\"progressbar\"]/following-sibling::a[@role=\"button\"]|id(\"extrares\")//span[count(a)>0]/span/following-sibling::a",
    "nextLink": 0,
    "loadMore": "div[role='progressbar']+a[role='button']",
    "exclude": "id('pnnext')"
}
```

**Comment by hoothin** [comment]
奇怪，你的这个搜索结果页下方有页码吗？
![image](https://github.com/hoothin/UserScripts/assets/5361213/c1b53289-41dd-4d3c-8d4d-9eff43a01e4c)

**Comment by fir05** [comment]
没有，是奇怪，我把篡改猴禁用了，网页似乎也在预读。底部显示的是：

<img width="580" alt="20230823094928" src="https://github.com/hoothin/UserScripts/assets/96730278/dc4386e8-f5a3-48d4-8bb8-52b03dfe22ee">

**Comment by fir05** [comment]
哦，不是预读，是我本来就请求了50个结果

**Comment by hoothin** [comment]
那可能是谷歌在 firefox 试验新版页面吧，这个新版的确和 mobile 页面一致，匹配到 mobile 规则也没问题

**Comment by fir05** [comment]
那好吧，我暂时禁用了翻页脚本，网页也正常预读
