### ISSUE TITLE
自定义分隔条类型

### ISSUE THREAD

**Issue by fir05** [hoothin/UserScripts#422]
能否添加一个用水平线作为分隔条的选项？

我都是隐藏分隔条的，在某些链接连续但内容不相关的网站，会出现内容混淆。比如一些类似博客网站，当前内容看着看着忽然出现了不相关的内容，再仔细看，原来是拼接到下一页了。
比如这个新闻网：
https://arstechnica.com/gadgets/2023/08/project-moohan-is-google-and-samsungs-inevitable-apple-vision-pro-clone/

而我又不希望显示分割条，这时我就只能让这个网站强制拼接来避免这种混淆。
但如果是显示一个水平线，我觉得可以接受，不会影响美观，又足够显眼。

**Comment by hoothin** [comment]
目前默认分隔条已经是水平线了。如果隐藏分隔条后需要提示，可以开启侧边栏，翻页时侧边栏会显示。单击暂停，双击隐藏。
更精细的傻瓜式自定义分隔条我不打算加，如果实在有需要可以自行通过自定义 css 功能实现。

**Comment by hoothin** [comment]
你需要用{}包裹并且指定选择器，具体步骤与stylus类似。你可以自行寻找相应教程

**Comment by fir05** [comment]
好的谢谢。我让GPT修改脚本，它直接改成不显示了。再修改，分隔条变成线了，但 "page"字符和悬停太极图标仍旧显示。
最后，我还是选择开启隐藏分隔条。
