### ISSUE TITLE
东方永业机自动翻页把百度搜索结果第一页干掉了

### ISSUE THREAD

**Issue by benzBrake** [hoothin/UserScripts#424]
**Describe the bug**
东方永业机自动翻页把百度搜索结果第一页干掉了

**To Reproduce**
百度搜索任意关键字，等待翻页即可

**Expected behavior**
正常拼接页面

**Screenshots**

https://github.com/hoothin/UserScripts/assets/11323774/e497d61c-5054-4754-9d71-3a7bdb410809

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Floorp
 - Version: 11.2.0

**Additional context**

**Comment by hoothin** [comment]
看起来更有可能是类似”屏蔽垃圾农场“之类的扩展干掉的

**Comment by benzBrake** [comment]
> 看起来更有可能是类似”屏蔽垃圾农场“之类的扩展干掉的

不是，是广告过滤的问题，adguard 和 ublock 都有这个问题，所以我把 issue 关掉了
