### ISSUE TITLE
github.com 有奇怪弹窗

### ISSUE THREAD

**Issue by fir05** [hoothin/UserScripts#427]
![20230903002008](https://github.com/hoothin/UserScripts/assets/96730278/2ec0dfee-78bc-4db3-adf7-bffb479f56db)

https://github.com/search?q=98wubi&type=repositories&p=2

触发的规则是
```
{
    "name": "Repository search results · GitHub",
    "url": "^https?://github\\.com/search",
    "example": "https://github.com/search?q=C%2B%2B",
    "nextLinkByUrl": [
        "(&p=(\\d+))?$",
        "&p={$2+1}"
    ],
    "pageElement": "[data-testid='results-list']",
    "action": 0,
    "include": "[rel='next']"
}
```

![20230903002030](https://github.com/hoothin/UserScripts/assets/96730278/f3ca2110-5afd-4053-8957-c6ed5cb2e508)

请问为何总是有弹窗呢？不能换个方式或者说禁止吗，从我的角度来说，我情愿它毫无作为也不想看到这样的弹窗

**Comment by hoothin** [comment]
不是提示”点击查看“了吗？
因为下一页是 nextLinkByUrl 生成的，所以生成到第4页就是`https://github.com/search?q=98wubi&type=repositories&p=4`了，这一页存在但不包含results-list。
想要不产生提示的话，可以自定义规则添加 stopSign，把`.chXkIK[aria-current]`作为停止翻页标记。

**Comment by fir05** [comment]
[不是提示”点击查看“了吗？] 我点击了，跳到一个空白页，然后呢？

感觉不是这个逻辑，我就是不想看到不想点击才提问题的。
它不包含results-list就不显示呗，怎么就成了不会写规则就必须显示呢。
就像浏览器打不开一个网页，打不开就打不开得了，跳出个360红色弹窗警告你"点击查看"，殊无必要。

**Comment by hoothin** [comment]
通常不会撞上这个提示，因为大部分网页不存在下一页时，指向下一页的链接或者按钮是不存在的。
但是，如果下一页是通过 nextLinkByUrl 生成的，它始终存在，这比较特殊。我在上面解释过了，你可以自己自定义规则，添加 stopSign。这样就能避开提示。
而这个提示是为了部分网站的 cc 墙和人机校验准备的。

最后，从你上个 issue 开始，你的发言就令我感到不适了。有问题可以多看 wiki，不必来发 issue。

**Comment by fir05** [comment]
OK，我只能说我无恶意，认为是BUG才提的。问题一开始通过删改源码解决了。
