### ISSUE TITLE
Pagetual doesn't support google.com or there is a bug current version?

### ISSUE THREAD

**Issue by Reid00** [hoothin/UserScripts#428]
google.com do not work, is this a bug?

**Comment by Reid00** [comment]
试了下，我这边用google 中文也不行，没有页码显示的设置，还有什么办法吗

**Comment by Reid00** [comment]
不太对，我登陆之后有页码显示了， 但是没有work
![image](https://github.com/hoothin/UserScripts/assets/38450639/b6c6b971-85c3-4acb-9000-a58c55e1a817)

**Comment by hoothin** [comment]
你该检查一下自己的配置
