### ISSUE TITLE
[Pagetual] Does not work when on hoothin/UserScript's issue page

### ISSUE THREAD

**Issue by zhon12345** [hoothin/UserScripts#430]
**Describe the bug**
Pagetual specifically does not automatically load the next issue page when on hoothin/Userscripts repo but works file with every other  github repo. 

**To Reproduce**
1. Go to 'https://github.com/hoothin/UserScripts/issues'
2. Click on 'Closed' to get more pages
3. Scroll down to bottom 
4. Pagetual does not load next page

**Expected behavior**
When on hoothin/UserScripts's issues page, Pagetual automatically loads next page too.

**Tried on the following devices using the same [config](https://gist.github.com/zhon12345/fe5e1afc982f3b9ea89ca604b43e7aac):**

**Desktop:**
 - Windows 11 Pro 22H2
 - Brave 
 - Version 1.57.62 Chromium: 116.0.5845.180

**Desktop:**
 - Windows 11 Pro 22H2
 - Edge
 - Version 116.0.1938.76

**Mobile**
 - Redmi 9A
 - CrDroid 8.12
 - Brave with ChromeXt xposed module
 - Version 1.57.60, Chromium: 116.0.5845.163

**Comment by hoothin** [comment]
Thanks for report, that's already a known issue, and it's fixed in v.1.9.36.54.

**Comment by zhon12345** [comment]
Got the update and can confirm it's fixed, thanks for the hard work!
