### ISSUE TITLE
Floating window keeps popping up when drag screen

### ISSUE THREAD

**Issue by twlz0ne** [hoothin/UserScripts#431]
**Describe the bug**

The floating image window keeps popping up when drag the screen.

**To Reproduce**
1. Visit a big picture or a map (e.g. https://tf.istrongcloud.com/ )
2. Drag on screen.

**Expected behavior**
Don't popup the floating image window.

**Screenshots**

![image](https://github.com/hoothin/UserScripts/assets/2653486/bb4aab81-c0d9-4954-8578-a2cdaebac7de)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: Firefox 15.2.0esr (64-bit)
 - Version: 2023.9.3.1

**Comment by twlz0ne** [comment]
My current solution:

```js
 22880             if (floatBar && floatBar.shown && isKeyDownEffectiveTarget(event.target)) {
 22881                 Object.keys(prefs.floatBar.keys).some(function(action) {
 22882                     if (action == 'enable') return;
 22883                     // if (key == prefs.floatBar.keys[action]) {
 22884                     //     floatBar.open(event, action);
 22885                     //     event.stopPropagation();
 22886                     //     event.preventDefault();
 22887                     //     return true;
 22888                     // }
 22889                 });
```

**Comment by hoothin** [comment]
感谢反馈。这是因为你本机某个扩展在拖拽时发送了c或者a的按键事件。你可以在picviewer ce+的设置里把c/a这个快捷键改成其他按键。
如果你愿意的话，可以把冲突扩展整理出来提交给我，我在脚本里做一下排除。

**Comment by twlz0ne** [comment]
@hoothin

1. 我禁掉了其他所有扩展和脚本，只保留 Tampermonkey 和 Picviewer CE+ 仍然会在拖拽的时候弹出浮动窗，并且在我拖动浮动窗的时候再弹出一个：
![image](https://github.com/hoothin/UserScripts/assets/2653486/83b40c2d-f11f-44e5-adcc-1e3702dd224e)
![image](https://github.com/hoothin/UserScripts/assets/2653486/870ad24f-ad59-45f8-b96d-2dd0517730e1)

2. 更改快捷键 c 的确有效。

**Comment by hoothin** [comment]
不一定是浏览器里的，这篇文章或许对你有帮助 https://blog.csdn.net/weixin_45413689/article/details/129050355

**Comment by hoothin** [comment]
我尝试着排除了 Command+c，现在设置为 c 应该也不会因为取词而弹出了，你试试。

**Comment by twlz0ne** [comment]
原来是词典捣的鬼，我安装了欧陆词典并开启了**划词搜索**。

2023.10.3.1版本可以了 👍🏻。
