### ISSUE TITLE
大佬大佬 Picviewer CE+ 可以做个ios手机专版吗？

### ISSUE THREAD

**Issue by Yumega** [hoothin/UserScripts#437]
Picviewer CE+通过stay插件安装在苹果手机上，经常看的图片网站正好可以使用，但是并不完全适配手机。
图库模式顶端栏挤在一起占用很多空间（无法全屏隐藏），但可以自动播放图片。
希望大佬做个手机专版，在图库模式中，砍掉分享、砍掉搜图、砍掉类别、砍掉图片数量、砍掉尺寸、砍掉加载更多页等功能，disable底部侧边栏功能，只保留幻灯片功能。
只想进入图库模式后，自动开启幻灯片功能，时间间隔可调整

非常感谢

![IMG_9244(1)](https://github.com/hoothin/UserScripts/assets/61570667/280cc4cb-ac74-4498-9ba0-f6b16d809347)

![IMG_9246(1)](https://github.com/hoothin/UserScripts/assets/61570667/3fdc4825-5543-4327-878b-cbb1ec1c8542)

**Comment by hoothin** [comment]
这又。。。何苦
如果想要存图，用这个捷径就好了 https://www.icloud.com/shortcuts/0763386bdc204b53bab94ab060973adb

**Comment by hoothin** [comment]
没有鼠标的话，这个脚本就基本上残废了。
如果你执意要在手机上用的话，可以试一下最新版，底下会有个放大了的下拉按钮，点击一下就能隐藏多余元素。
