### ISSUE TITLE
某些论坛只能下载1楼内容，即使使用永动机全部加载出来也无法下载。之前的版本是没问题的

### ISSUE THREAD

**Issue by guyeu9** [hoothin/UserScripts#439]
使用直接下载只下载第一楼，使用自定义下载也只下载每一页的第一楼。无法下载全部楼层文章

**Comment by guyeu9** [comment]
@Hoothin  更新后，目前无法下载论坛正文，使用Ctrl+f9下载为空，使用自定义下载可以下载，但是有的时候只能下载第一页，无法下载后续。下载为空文件打开提示：
, Processed in 0.053399 second(s), 16 queries

, Gzip On, Xcache On.

>>>>


, Processed in 0.037304 second(s), 16 queries

, Gzip On, Xcache On.

**Comment by guyeu9** [comment]
@hoothin 更新后，目前无法下载论坛正文，使用Ctrl+f9下载为空，使用自定义下载可以下载，但是有的时候只能下载第一页，无法下载后续。下载为空文件打开提示：
, Processed in 0.053399 second(s), 16 queries

, Gzip On, Xcache On.

>>>>


, Processed in 0.037304 second(s), 16 queries

, Gzip On, Xcache On.

**Comment by hoothin** [comment]
抱歉，请按规范提issue吧。网址案例都没有我很难提供帮助
