### ISSUE TITLE
大佬能否提供个选项取消TTS，贼吓人

### ISSUE THREAD

**Issue by qiansen1386** [hoothin/UserScripts#44]
第一次听的时候，我查了2个小时木马……

**Comment by hoothin** [comment]
在脚本生效且页面焦点不在文本框时键盘输入“hazukashii”，就能禁用了

在 2020年7月13日星期一，东方孤思子 Paris·QianSen <notifications@github.com> 写道：

**Comment by qiansen1386** [comment]
这也太二次元了哈哈哈哈哈。

**Comment by XiandaLyu** [comment]
这真是骚操作啊。
