### ISSUE TITLE
anilist https://anilist.co/search/anime/trending support

### ISSUE THREAD

**Issue by MaiSan9999** [hoothin/UserScripts#441]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MaiSan9999** [comment]
is it possible?

**Comment by hoothin** [comment]
What for?

**Comment by MaiSan9999** [comment]
> What for?

Newly Added Anime feed

**Comment by MaiSan9999** [comment]
https://github.com/hoothin/UserScripts/assets/89659009/f84fbd64-3c51-4009-b133-cff5a3247546

**Comment by hoothin** [comment]
?? I didn't see any page action on that site.
If you need to scroll automatically, click the "Toggle Auto Scroll"
