### ISSUE TITLE
Problem with Duckduckgo.com (Video & Shopping)

### ISSUE THREAD

**Issue by Dean-Corso** [hoothin/UserScripts#442]
Hi @hoothin,

so I found some issue when using Duckduckgo website and using your script. The problem happens already for a longer time also with older script versions so maybe you can check this out and tell us how to fix it if possible etc. Thanks.

**Describe the bug**
The Pagetual script seems to change / switch back from Video view tab page of duckduckgo to All search results tab page when playing a video in ddg or just trying to scroll down to load next page. Also same problem happens with the "Shopping" tab.

**To Reproduce**
1. Go to [duckduckgo](https://duckduckgo.com/)
2. Enter anything to search for and press enter
3. Now press on Video tab to show all video results
4. Click on any video to play in ddg or just scroll down to load net page
5. Error: The website does switch back to the text results page

**Expected behavior**
Pagetual should not switch back from Video or Shopping results tab to All results tab when playing a video in Duckduckgo or scrolling down to next page.

**Desktop (please complete the following information):**
 - OS: Windows 22H2 x64
 - Browser: Firefox & Brave (same problem)
 - Version: Latest Browser Versions
 - Script Version: 1.9.36.63

**Additional context**
A rule is used and found in [pagetualRules.json file](https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json)

```
{
    "name": "Duckduckgo",
    "url": "^https://duckduckgo\\.com/\\?",
    "loadMore": ".result--more>a,#more-results"
}
```

**Comment by hoothin** [comment]
<pre name="pagetual">
    {
        "name": "Duckduckgo",
        "url": "^https://duckduckgo\\.com/\\?",
        "loadMore": ".result--more>a,.content-wrap:not(.is-hidden) #more-results"
    }
</pre>
The update of Duckduckgo is too frequent ;(

**Comment by Dean-Corso** [comment]
Hi again,

thanks for that rule update. Just a question about it, where did you read the .results--more class from? I don't find that class! I just see this...

`<button id="more-results" class="wE5p3MOcL8UVdJhgH3V1 ffON2NH02oMAcqyoh2UU hUUdRtuaOUx7mcSwc56s q7VhSk71XgyB1xYfeChb VVwKmb7llplcxyVXzHz9">Mehr Resultate</button>`

...the class names are encrypted with anything etc. Could you explain that elements / rule you did use etc? Thanks.

**Comment by hoothin** [comment]
That's just a className of older version of ddg. It can be deleted safely. like: `.content-wrap:not(.is-hidden) #more-results`.
I leave this to prevent potential rollback of ddg.
