### ISSUE TITLE
pagetual: google.com [images]

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#443]
![image](https://github.com/hoothin/UserScripts/assets/19517680/2a458501-5cae-4ae7-b677-f6d500ede9f0)

https://www.google.com/search?q=iphone+generation&tbm=isch&ved=2ahUKEwiwzYDO7vGBAxV9vGMGHdmoDbcQ2-cCegQIABAA&oq=iphone+generation&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgARQAFgAYKsHaABwAHgAgAGJAYgBiQGSAQMwLjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=OJwoZbDRKv34juMP2dG2uAs&bih=821&biw=1600&rlz=1C1GCEA_enID1068ID1068#imgrc=VITPMe0ivQLKlM

**Comment by hoothin** [comment]
fixed
