### ISSUE TITLE
pagetual: freepik.com

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#444]
![image](https://github.com/hoothin/UserScripts/assets/19517680/89740078-ebed-4752-af9a-a07a27aeb1df)

https://www.freepik.com/premium-psd/3d-rendering-drawing-tablet-hand-gesture-3d-icon_71592936.htm#&position=25&from_view=author

**Comment by hoothin** [comment]
Can't reproduce
![image](https://github.com/hoothin/UserScripts/assets/5361213/e5e73561-383b-412b-9ed6-41fb80bab901)

**Comment by 3xploiton3** [comment]
sorry wrong link

take a look
https://www.freepik.com/author/kentung3d

**Comment by hoothin** [comment]
I mean that you should import online rule. The rule of freepik.com is already there.

**Comment by 3xploiton3** [comment]
thanks, it worked, 

hard to understand for me, is this setup right?
![image](https://github.com/hoothin/UserScripts/assets/19517680/75f1c9f6-fed1-41f8-82db-0c7c4c360865)

**Comment by hoothin** [comment]
Yes, it is.
