### ISSUE TITLE
Can anyone Help me get the rule for MYVIDSTER (subscriptions nor working

### ISSUE THREAD

**Issue by saoemilio** [hoothin/UserScripts#445]
**The url of site**
https://www.myvidster.com/subscriptions/Shagwell&page=2

**Describe the result you'd like with the rule**
load next pages automatically

**Custom rule you've tried**
   {
        "name": "MyVidster - Subcriptions for Shagwell",
        "url": "^https?://www\\.myvidster\\.com/subscriptions/",
        "example": "https://www.myvidster.com/subscriptions/Shagwell&page=2",
        "pageElement": "body > div.container2 > table > tbody > tr > td > div.container3 > table > tbody > tr > td:nth-of-type(1)"
    },

**Comment by hoothin** [comment]
I am not user of that site, so I can't test this rule. You can try by yourself
<pre name="pagetual">
    {
        "name": "MyVidster - collect the videos you love",
        "url": "^https?://www\\.myvidster\\.com/",
        "example": "https://www.myvidster.com/page/3",
        "nextLink": "[align='right']>.pagination>a",
        "pageElement": ".container3 > table > tbody > tr > td:nth-of-type(1) > table > tbody > tr:nth-of-type(7) > td > table"
    }
</pre>

**Comment by saoemilio** [comment]
It worked..... Thank you so much!!!!

**Comment by saoemilio** [comment]
❤️❤️❤️
