### ISSUE TITLE
图片预览无法正常显示

### ISSUE THREAD

**Issue by Enmmma** [hoothin/UserScripts#446]
**Describe the bug**
必应搜索结果和其他一些网站，图片预览无法显示，只有第一页图片可以正常加载
**Expected behavior**
预览图片可以显示

**Screenshots**

![IMG_20231018_143509.jpg](https://github.com/hoothin/UserScripts/assets/138614380/d3752a85-b003-4c97-a38e-44613964b5a9)

![IMG_20231018_141810.jpg](https://github.com/hoothin/UserScripts/assets/138614380/9f289a90-c507-48fb-a6ea-6b8ccdfb6674)

**Smartphone (please complete the following information):**
 - Device: huawei mate30
 - OS:鸿蒙4
 - Browser kiwi
 - Version最新版

**Additional context**

**Comment by hoothin** [comment]
必应需要加”waitElement“或者用action:2强制拼接。
色图站先贡献出来

**Comment by hoothin** [comment]
好图
<pre name="pagetual">
{
    "name": "辉夜白兔图库",
    "url": "^https?://47\\.101\\.137\\.235:8099/",
    "example": "http://47.101.137.235:8099/?s=r18",
    "waitElement": "![lazy='loading']"
}
</pre>
底下这个是picviewer ce+的大图规则
```
{
  name:"辉夜白兔",
  url:/47\.101\.137\.235/,
  r:"thumb",
  s:"regular"
}
```
