### ISSUE TITLE
Performance/Hanging Issue in Firefox

### ISSUE THREAD

**Issue by megamorphg** [hoothin/UserScripts#448]
**Describe the bug**
Loading certain pages like Reddit or Slickdeals causes the extension to slow down the page to the point that Firefox gives the warning:
![image](https://github.com/hoothin/UserScripts/assets/1782353/c91961ec-9581-466c-adc9-24775040ffae)

**To Reproduce**
1. Go to a [SlickDeals search](https://slickdeals.net/newsearch.php?q=monitor+32%22&searcharea=deals&searchin=first&isUserSearch=1) in Firefox with this script enabled in Firefox with Tampermonkey.

**Expected behavior**
No slow-down of page and warning.

**Screenshots**
Added above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 118.0.2

**Additional context**
I troubleshooted this by disabling the script in Tampermonkey. The warning no longer existed for Reddit nor SlickDeals.
I noticed this behavior after the recent script update 1.9.36.66.

**Comment by hoothin** [comment]
There is a bug in 1.9.36.66, Why not update to latest?
