### ISSUE TITLE
[PicviewerCE+] Toolbar issue on Youtube

### ISSUE THREAD

**Issue by iG8R** [hoothin/UserScripts#449]
**Describe the bug**
The toolbar appears in the wrong places and sometimes shows irrelevant images on the YouTube website.

**To Reproduce**
1. Go to [youtube.com](url)
2. Try using PicviewerCE+ for video preview images.
3. See the aforementioned issue.

**Expected behavior**
The toolbar has to appear near and show corresponding its place image.

**Screenshots**

[PicviewerCE-Video_2023-10-20_010635_1.webm](https://github.com/hoothin/UserScripts/assets/11407417/b62d8ac8-fd33-4b26-b8c0-aeaee4a0d50c)

<img src="https://github.com/hoothin/UserScripts/assets/11407417/85743c29-e88d-404c-923e-2acd068f8f56" width="250">

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 118.0.2 64bit
 - PicviewerCE+ Version: 2023.10.19.1

**Comment by hoothin** [comment]
You should use "top left" in youtube. The "beside" or "bottom" are not solid.

**Comment by iG8R** [comment]
Thanks for your answer.
Yes, with the "top left" setting, the issue with toolbar placement is gone, but displaying irrelevant images - not.

PS. Is there a way to apply different toolbar placement styles for different websites, e.g. "top left" for YouTube, but "beside picture" for all others?


[PicviewerCE-youtube-Video_2023-10-20_154030.webm](https://github.com/hoothin/UserScripts/assets/11407417/5714e664-79ce-43c7-905f-2165f8f77fab)

**Comment by hoothin** [comment]
Sorry but I can't reproduce the issue of displaying irrelevant images. I am a heavy user of youtube so I'll notice if there is sth.
So more information are needed.

**Comment by iG8R** [comment]
How can I provide you with additional information?
Any logs or any other things - ask and I do my best.

**Comment by iG8R** [comment]
Here are the console logs.
[PicviewerCE-console-export-2023-10-20_18-2-38.log](https://github.com/hoothin/UserScripts/files/13055765/PicviewerCE-console-export-2023-10-20_18-2-38.log)

<details><summary>Screenshot</summary>

![PicviewerCE-console-log-2023-10-20_180539-resized](https://github.com/hoothin/UserScripts/assets/11407417/9734ea91-1370-4a07-8f52-203c9416f73f)

</details>

**Comment by hoothin** [comment]
Check your "Aliexpress-remove-localized-links". Disable it and retry

**Comment by iG8R** [comment]
Unfortunately, disabling "Aliexpress-remove-localized-links" didn't solve the issue:(

[PicviewerCE-youtube-Video_2023-10-21_040411_1.webm](https://github.com/hoothin/UserScripts/assets/11407417/32e73792-26d3-4cdc-9201-5b899a4e4d9b)

**Comment by hoothin** [comment]
```
{
 name: "Youtube",
 url: /youtube\.com/,
 ext: function(target) {
     if (target.tagName == "ytd-thumbnail") {
        return target.querySelector("img");
     }
 },
 getExtSrc: function() {
    let newsrc = "";
    if (this.id == "thumbnail-container" && this.children[0].hasAttribute("loaded")) {
        let img = this.querySelector('img');
        if (!img) return;
        newsrc = img.src;
    }
    return newsrc.replace(/\?.*$/i,"");
 },
 getImage: function(a, p) {
     var newsrc=this.src;
     if(p[2] && this.classList.contains('ytd-moving-thumbnail-renderer')){
         newsrc = p[2].querySelector("img").src;
     }
     if(!newsrc || newsrc.indexOf("i.ytimg.com") == -1) return;
     return newsrc.replace(/\?.*$/i,"");
 }
}
```
Try this custom rule

**Comment by iG8R** [comment]
Thanks a lot!
Everything seems to work perfectly, even the toolbar appears faster.
