### ISSUE TITLE
[PicviewerCE+] Rotate function in the gallery can't be used

### ISSUE THREAD

**Issue by iG8R** [hoothin/UserScripts#450]
**Describe the bug**
When using the gallery, the rotation angle in the "Command" menu cannot be changed from 0, as moving the cursor to the desired angle leads to closing the "Command" menu.

**To Reproduce**
1. Call the PicviewerCE+ gallery function on any website.
2. In the "Command" menu, try using the mouse to change the value of "Rotate" to anything but 0.
3. See that the "Command" menu will be collapsed.

**Screenshots**

[PicviewerCE-gallery-rotate-Video_2023-10-21_054946.webm](https://github.com/hoothin/UserScripts/assets/11407417/2629d055-1925-4f3a-9168-5ebed798dc8b)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 118.0.2 64bit
 - PicviewerCE+ Version: 2023.10.19.1

**Comment by iG8R** [comment]
**Offtopic**
Could you please clarify, is pvcep_rules.js already included in PicviewerCE+ or does the user need to add these rules manually?

**Comment by hoothin** [comment]
Thanks for report, seems like a firefox feature. I'll fix it later. If you need to rotate right now, just double click the image.

Yes, pvcep_rules is already included, you don't need to import manually.

**Comment by iG8R** [comment]
Thank you.

**Comment by hoothin** [comment]
I've updated to fixed this issue on firefox.

**Comment by iG8R** [comment]
Thanks a lot.
