### ISSUE TITLE
chartjs.org: broken

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#454]
https://www.chartjs.org/docs/latest/samples/bar/border-radius.html

![image](https://github.com/hoothin/UserScripts/assets/19517680/261915db-62e1-4421-9289-f5c964a91926)

should be:
![image](https://github.com/hoothin/UserScripts/assets/19517680/d4581de8-9097-4189-b1ac-c078ae9cb724)

**Comment by hoothin** [comment]
Thanks for report, it's fixed.
