### ISSUE TITLE
pagetual: tokopedia.com

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#455]
https://www.tokopedia.com/search?ob=3&pmin=1700&rt=4%2C5&srp_component_id=04.06.00.00&utm_campaign=OpenSearch&utm_medium=wb&utm_source=ops&q=sikat%20keyboard

![image](https://github.com/hoothin/UserScripts/assets/19517680/d1885431-419a-45a1-a057-dda047237f44)

**Comment by hoothin** [comment]
I think this site will change very frequently. So you should learn to write rule by yourself.
<pre name="pagetual">
{
    "name": "Tokopedia",
    "url": "^https?://www\\.tokopedia\\.com/",
    "pageElement": "[data-testid='divSRPContentProducts']>*",
    "nextLink": "[aria-label='Laman berikutnya']"
}
</pre>
This rule is work right now, but not forever.

**Comment by 3xploiton3** [comment]
> I think this site will change very frequently. So you should learn to write rule by yourself.
> 
> {
>     "name": "Tokopedia",
>     "url": "^https?://www\\.tokopedia\\.com/",
>     "pageElement": "[data-testid='divSRPContentProducts']>*",
>     "nextLink": "[aria-label='Laman berikutnya']"
> }
> This rule is work right now, but not forever.

this rule doesn't work

![image](https://github.com/hoothin/UserScripts/assets/19517680/0e215114-00d4-47aa-b08f-c601ba8b6e5a)

**Comment by hoothin** [comment]
property: [wait](https://pagetual.hoothin.com/en/rules/wait.html)

**Comment by 3xploiton3** [comment]
![image](https://github.com/hoothin/UserScripts/assets/19517680/c7557aa4-5b5a-492a-bf2c-b25a72707044)

**Comment by hoothin** [comment]
You miss a "," after 500

**Comment by hoothin** [comment]
... Do not use force join
![image](https://github.com/hoothin/UserScripts/assets/5361213/d696da78-2e8e-4fd4-b6e3-70821708644a)

**Comment by 3xploiton3** [comment]
what does it mean?
there is no button  to disable 'force join'

![image](https://github.com/hoothin/UserScripts/assets/19517680/7858bf2d-713c-413a-977c-75943c5b1f19)
![image](https://github.com/hoothin/UserScripts/assets/19517680/909ecd06-4d1c-4000-9e10-1a065a32dfc0)

**Comment by hoothin** [comment]
Make sure that pageElement matched. I give you example just for the page you post. But from what I can see, this website has multiple sets of pages with different styles.
You should change pageElement and url (maybe also waitElement) for different pages.
