### ISSUE TITLE
请求帮适配：MDL论坛 https://forums.mydigitallife.net

### ISSUE THREAD

**Issue by Wuyouzi067** [hoothin/UserScripts#457]
**The url of site**
https://forums.mydigitallife.net/threads/windows-editions-reconstruction-project.80939

**Is your request related to a problem? Please describe.**
1. 贴中有大量的 SPOILER 按钮，内含文件链接或图片，左键点击将显示或隐藏。目前问题是在后面加载的页面  SPOILER 按钮变成无效，不能显示里面的内容。
2. 贴中有大量的 click to expand 按钮，左键点击将展开更多引用的内容。

**Describe the result you'd like with the rule**
1. 默认显示 SPOILER 按钮内含的内容。
2. 默认展开 click to expand 按钮的内容。

**Custom rule you've tried**
我还没尝试自定义规则，在 Elements 中执行了下面 JavaScript code
1. 自动点击 SPOILER 按钮，不能显示 SPOILER 按钮里面的内容
var inputs = document.getElementsByClassName('button bbCodeSpoilerButton ToggleTrigger Tooltip JsOnly'); 
for(var i=0; i<inputs.length;i++)
{ 
	inputs[i].click(); 
}
2. 自动点击 click to expand 按钮，能展开更多引用的内容
var inputs = document.getElementsByClassName('quoteExpand quoteCut'); 
for(var i=0; i<inputs.length;i++)
{ 
	inputs[i].click(); 
}

**Additional context**
谢谢！

**Comment by hoothin** [comment]
打开强制拼接就可以了

**Comment by Wuyouzi067** [comment]
<img width="1280" alt="tmp" src="https://github.com/hoothin/UserScripts/assets/12706716/8286e425-01bf-42dc-9070-9678300fa7bd">
帮确认下图中是否打开了强制拼接，目前还是不能显示 SPOILER 按钮里面的内容。

**Comment by hoothin** [comment]
你直接点击强制拼接那个按钮就行了

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/6ff0dd3b-48c4-4aa4-898d-88bdb0043018)

**Comment by Wuyouzi067** [comment]
谢谢！
使用上图的强制拼接，在 Console 中执行
`var inputs = document.getElementsByClassName('quoteExpand quoteCut'); 
for(var i=0; i<inputs.length;i++)
{ 
	inputs[i].click(); 
	console.log(inputs.length); 
}
var inputs = document.getElementsByClassName('button bbCodeSpoilerButton ToggleTrigger Tooltip JsOnly'); 
for(var i=0; i<inputs.length;i++)
{ 
	inputs[i].click(); 
	console.log(inputs.length); 
}`
只对当前页有效，请教该怎么做能对所有页都有效？
动态加载能自动加载多页更方便简洁，是否也能做到？

**Comment by hoothin** [comment]
你是想要默认展开？那直接加个css就行了
```
{
    "name": "forum - showthread.php",
    "url": "^https?://.*(showthread\\.php\\?|forum|threads?)",
    "pageElement": "//div[@id='posts' or div//td/@class='postContent']/*[.//*[starts-with(@id,'post')]]|//table[@class='bordercolor']//tr[.//tr/td[starts-with(@class,'windowbg')]]|(id('posts messageList')|//ul[starts-with(@class,'conversation-list')])/li[starts-with(@id,'post') or contains(@class,'js-post')]|id('quickModForm')/div[contains(@class,'windowbg') or @class='bordercolor']\r\n|//article[translate(@id, '1234567890', '')='js-post-']\r\n|//section[@class='thread_posts']/article[contains(concat(' ', @class, ' '), ' post ')]\r\n|id('content')/div[translate(@id, '1234567890', '')='msg'][@data-id]",
    "nextLink": "(//link[contains(concat(' ', @rel, ' '), ' next ')][1][@href=//a/@href]\r\n|//a[@rel='next' or .='>' or .='Next ›' or .='Next >' or .='Next']\r\n|(//td[@class='middletext']|//div[starts-with(@class,'pagelinks') or contains(@class,'pagesclass')])/text()[contains(.,']')]/following-sibling::a[@class='navPages'][1]\r\n|(//span|//a)[contains(@class,'current')][number()>0]/following-sibling::a[not(@class='go_page')][1][not(ancestor::*[contains(@style, 'display: none')])]\r\n|//span[contains(@class,'selected')][number()>0]/following-sibling::span[1]/a\r\n|//li[starts-with(@class,'pager-next')]/a\r\n|//div[@class='pages']/text()[number(translate(., '[] ', ''))>0]/following-sibling::a[1][number()>0])[string(@href) and not(starts-with(@href, '#') or starts-with(@href, 'javascript'))]",
    "css": ".hasJs .bbCodeSpoilerText{display:block}.bbCodeQuote .quoteContainer .quote{max-height: none;}.bbCodeQuote .quoteContainer .quoteExpand.quoteCut{display: none;}"
}
```

**Comment by Wuyouzi067** [comment]
这正是我想要的，谢谢！
若想手动点击又该怎么做？

**Comment by hoothin** [comment]
pageAction 里面可以加代码，传入 doc （即为下一页的 document），抓取 .bbCodeSpoilerButton 绑定 onclick，点击后切换下一个元素的 display 。这样就不用强制拼接了。要默认展开的话就额外预先把下一个元素的 display 设为 block

**Comment by hoothin** [comment]
不过我不是很推荐，因为很容易随着网站改版失效

**Comment by Wuyouzi067** [comment]
目前已达到我的需求了，以后有空我再试试。谢谢！
