### ISSUE TITLE
working except the images

### ISSUE THREAD

**Issue by gabri25ele** [hoothin/UserScripts#458]
in some site
from the second page, the images are not visible.

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "SoftArchive",
    "url": "^https?://sanet\\.st/search/",
    "example": "https://sanet.st/search/?q=too",
    "nextLink": ".pagination>.active+li>a",
    "pageElement": "tr.filerow",
    "pageAction": "eles.forEach(ele=>{if(ele.classList.contains('show_poster_preview')){ele.onmouseenter=e=>{document.querySelector('#pop_poster_preview_box').innerHTML=`<img style='width: 100%; height: auto; display: block;' src='${ele.dataset.poster_url}' border='0'>`;document.getElementById('pop_poster_preview_box').style.display='block'};ele.onmouseleave=e=>{document.getElementById('pop_poster_preview_box').style.display='none'}}})"
}
</pre>

**Comment by gabri25ele** [comment]
do I have to do something with this code? 🙄

**Comment by hoothin** [comment]
No. That's custom rule, you need to paste it into the textarea of custom rule.

**Comment by gabri25ele** [comment]
ah I thought it might be useful to fix the script and make it more compatible with sites that have this problem... instead is it just a specific rule for the individual site to be set manually?
so another site that will have this behavior will need the same rule to be added manually?

anyway it tells me this
![Senza titolo](https://github.com/hoothin/UserScripts/assets/33927879/0907e238-75ef-4f09-ac8c-2b31517813bd)

**Comment by hoothin** [comment]
...Array means [], like 
```
[
 {
   ...
 }
]
```
If you don't know what to do, just open that site sanet.st and click "edit current rule" and paste

**Comment by gabri25ele** [comment]
ok, ma images still missing

![sshot-1](https://github.com/hoothin/UserScripts/assets/33927879/27eb8537-fb20-44b6-b5df-9c626ec9673c)

**Comment by hoothin** [comment]
...They are different pages, man. I just wrote you the search page.
You need to read guide at first.

**Comment by gabri25ele** [comment]
I actually hoped it would help you, for multiple sites, fix it, make it more compatible, I'm not interested in the specific site

**Comment by hoothin** [comment]
No, there are no general technique for handling that.
