### ISSUE TITLE
观察者网开启自动翻页以后，右侧的信息会被过滤掉，影响体验。

### ISSUE THREAD

**Issue by chjchen** [hoothin/UserScripts#460]
https://www.guancha.cn/economy/2023_10_27_713575_2.shtml
网址如上。

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "观察者网",
    "url": "^https?://www\\.guancha\\.cn/",
    "example": "https://www.guancha.cn/economy/2023_10_27_713575_2.shtml",
    "nextLink": "a.next",
    "pageElement": ".comment-list > ul.list-body.list-body-all > li.comment-item.cmt-item",
    "include": "#comments-container",
    "waitElement": "a.next"
}
</pre>

**Comment by chjchen** [comment]
谢谢。
