### ISSUE TITLE
not update basic rules

### ISSUE THREAD

**Issue by gabri25ele** [hoothin/UserScripts#461]
it keeps telling me I haven't updated the base rules.

when clich here
![sshot-1](https://github.com/hoothin/UserScripts/assets/33927879/c6973a01-2f27-46c9-be2d-a3738d320f6b)

error message
![sshot-12](https://github.com/hoothin/UserScripts/assets/33927879/6d5eb67d-6ae4-4574-afa3-a21ed0787335)

**Comment by hoothin** [comment]
So which platform are you using?
And why not switch as it told you?

**Comment by gabri25ele** [comment]
clicked che change wedate address, but message ever present.
Platform using? Firefox, 119, Violentmonkey 2.15, Windows 11

>  And why not switch as it told you?
I don't even know what the program is asking me

**Comment by hoothin** [comment]
I'm using Firefox, 119, Violentmonkey 2.15, Windows 11 too, that's weird.
Where are you from? Can't you visit http://wedata.net/databases/AutoPagerize/items_all.json ?
