### ISSUE TITLE
v.1.9.36.77

### ISSUE THREAD

**Issue by GoroFourArms** [hoothin/UserScripts#462]
Random sites that use to work don't load pages since [v.1.9.36.77] 
This is one. https://www.scribblehub.com/read/75394-america-in-another-world/chapter/556669/
    {
        "url": "^https://www\\.scribblehub\\.com/read/",
        "pageElement": "#chp_raw",
        "nextLink": "a.btn-next",
        "action": 0,
        "stopSign": [
            "a.btn-next",
            ".disable"
        ],
        "pageAction": "eles.forEach(ele=>{[].forEach.call(ele.querySelectorAll('.sp-head'),sp=>{sp.onclick=e=>{sp.nextElementSibling.classList.toggle('folded')}})})"
    }

windows 10 firefox  violentmonkey

**Comment by hoothin** [comment]
Have you double clicked and paused?

**Comment by GoroFourArms** [comment]
Can you make it an option? I prefer the old style. I use an addon that makes the bar hard to see.

**Comment by hoothin** [comment]
update to 1.9.36.78 and close side controller. pagetual will not save pause state then.
