### ISSUE TITLE
在该网站下使用会发生错误

### ISSUE THREAD

**Issue by ning-zero** [hoothin/UserScripts#464]
东方永页机
如图，原本正常的字变成了乱码
网站 https://jiuyh.com/forum-2-1.html
![捕获](https://github.com/hoothin/UserScripts/assets/93832587/d1e30c5d-7f1d-4015-af14-10c421dd5039)
![1](https://github.com/hoothin/UserScripts/assets/93832587/d316d0fd-0b6b-4df4-a6d2-0fa33b941709)

**Comment by hoothin** [comment]
感谢反馈，已经修复了
