### ISSUE TITLE
pagetual: 启用插件后Content Security Policy不工作

### ISSUE THREAD

**Issue by junyu33** [hoothin/UserScripts#466]
**Describe the bug**
启用插件后Content Security Policy（CSP）不工作，即使不在CSP白名单中的url也会被加载。

**To Reproduce**
可以通过任何一个配置了CSP的网站进行对比，或者按照以下步骤搭建一个包含CSP的最小环境：
1. 下载[这个链接](https://seedsecuritylabs.org/Labs_20.04/Files/Web_XSS_Elgg/Labsetup.zip)的附件
2. 进入目录，使用`docker-compose build && docker-compose up`启动环境
3. 将以下内容写入`/etc/hosts`
```
10.9.0.5 www.seed-server.com
10.9.0.5 www.example32a.com
10.9.0.5 www.example32b.com
10.9.0.5 www.example32c.com
10.9.0.5 www.example60.com
10.9.0.5 www.example70.com
```
4. 访问 http://www.example32b.com/

**Expected behavior**
根据docker镜像中`/etc/apache2/sites-available/apache_csp.conf`的内容，CSP只允许运行自身或`*.example70.com`中的脚本，也就是只有第四行或第六行为`OK`。

但实际上启用插件后所有项均为`OK`。

**Screenshots**

启用插件前：

![image](https://github.com/hoothin/UserScripts/assets/37526026/bf610fc6-f635-401d-9beb-315f44980c2c)

启用插件后：

![image](https://github.com/hoothin/UserScripts/assets/37526026/4759a157-6224-4743-bdcb-033a1889d691)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 6.5.9-arch2-1
 - Browser: librewolf 119.0-5
 - Tampermonkey 4.19.0
 - Pagetual 1.9.36,81

**Comment by hoothin** [comment]
你问错地方了，脚本没有权限改csp 。但tm有个选项设置是自动去除任意网页的csp限制，换用暴力猴就没问题了

**Comment by junyu33** [comment]
好的，在tm里找到那个选项了，问题解决，谢谢。
