### ISSUE TITLE
曾经能正常使用，https://f95zone.to/sam/latest_alpha/#/cat=games/page=1/notags=360，后不知何原因在此页面不工作了。

### ISSUE THREAD

**Issue by James007ss** [hoothin/UserScripts#467]
如题，浏览器是EDGE，管理器是篡改猴。

**Comment by hoothin** [comment]
你是不是双击暂停了？你看下侧边栏颜色

**Comment by James007ss** [comment]
按过侧边栏的向下箭头后，侧边栏消失了，现在怎么设在那页面都不显示。而且我通过管理器禁用/启用，虽然有对应提示，但实际没效果。

**Comment by hoothin** [comment]
我测试了一下是正常的，有控制台报错吗？
![image](https://github.com/hoothin/UserScripts/assets/5361213/95248cbd-e76a-4628-a363-06811cb5611b)

**Comment by hoothin** [comment]
当你按下侧边栏的置底按钮后，侧边栏应该会反色，而不是消失，此时再点击一次侧边栏就能恢复翻页才对

**Comment by James007ss** [comment]
按太极图是如你所说，但按下箭头就消失了，请问控制台从哪里进入？我似乎没找到人口。

**Comment by hoothin** [comment]
ctrl+shift+j

**Comment by James007ss** [comment]
![image](https://github.com/hoothin/UserScripts/assets/62430706/1e3b36d4-bdea-490c-8dc6-5683c02d5ab5)
确实报错了，请问是什么问题？跟其它插件冲突？

**Comment by hoothin** [comment]
看起来是 iframe 里的内容被阻止了，获取的时候内容为空，具体原因不知，你得自己排查。
另外，74是一个星期前的版本了，你可以升级脚本试试。

**Comment by James007ss** [comment]
升级然后又瞎鼓捣半天，然后不知怎么的又好了。(*￣rǒ￣)
