### ISSUE TITLE
外置规则更新取消了吗

### ISSUE THREAD

**Issue by laptop-lace** [hoothin/UserScripts#468]
请问一下外置规则更新是取消了吗还是整合到在线规则更新里了啊

**Comment by hoothin** [comment]
沒有，規則更新一直不區分外部和内置

**Comment by laptop-lace** [comment]
> 沒有，規則更新一直不區分外部和内置

可是之前在https://greasyfork.org/ja/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/discussions/127867里提到过的脚本菜单<更新外置翻页规则>现在没有这个选项了

**Comment by hoothin** [comment]
抱歉，你似乎找错反馈区了，这是不同的脚本

**Comment by laptop-lace** [comment]
> 抱歉，你似乎找错反馈区了，这是不同的脚本

抱歉抱歉抱歉

**Comment by hoothin** [comment]
没事：）
