### ISSUE TITLE
please help the website(https://page.kakao.com/)

### ISSUE THREAD

**Issue by LilyYu123456** [hoothin/UserScripts#470]
**The url of site**
[The example urls of site. Do not paste only domain without pathname.](https://page.kakao.com/)

**Is your request related to a problem? Please describe.**
The content on this website cannot be copied and pasted, but it can be translated by Microsoft's automatic translation, so it's probably not encrypted. Use this script to return a numeric string txt.

**Describe the result you'd like with the rule**
A txt text divided into chapters, including the unlocked chapters after purchase

**Custom rule you've tried**
The rule you've made before.

**Additional context**
![image](https://github.com/hoothin/UserScripts/assets/127484430/0d7e06d3-623d-49f6-b693-17b077dcaf73)

**Comment by hoothin** [comment]
This website does not have pagination in the usual sense.
You can use the following code to display the loaded content on the same page:

``` js
let style=document.createElement("style");style.innerHTML='div.DC2CN{width: 100%; overflow: auto; height: 100%; column-width: auto;}';document.querySelector(`.flex-auto>div>div`).shadowRoot.appendChild(style);
```
