### ISSUE TITLE
I hope to optimize the recognition of the picture works of the web version of Douyin

### ISSUE THREAD

**Issue by zjh16** [hoothin/UserScripts#471]
In the graphic work of the web version of Douyin, the script can only recognize the image of the cover, but not the current image

**Comment by hoothin** [comment]
抖音除了封面哪里有图？不都是视频吗？

**Comment by zjh16** [comment]
> 抖音除了封面哪里有图？不都是视频吗？

不是的，有图文作品哈！
1.20 dNw:/ 01/28 Q@K.WZ 畅音阁里终一叙 六百年一粟沧海一梦。来呀，回到傍晚的紫禁城# 故宫 # 古建筑之美 # 北京 # 摄影 # 历史  https://v.douyin.com/iRQvupM2/ 复制此链接，打开Dou音搜索，直接观看视频！

**Comment by hoothin** [comment]
我测试了下，都是可以抓取的呀，你是指哪一张图？
![image](https://github.com/hoothin/UserScripts/assets/5361213/a0e003b8-d9fa-4868-82dc-4edbb1b13b41)

**Comment by zjh16** [comment]
> 我测试了下，都是可以抓取的呀，你是指哪一张图？ ![image](https://user-images.githubusercontent.com/5361213/284751676-a0e003b8-d9fa-4868-82dc-4edbb1b13b41.png)

感谢你的回复，我说的不是打开图库然后在里面找，而是按 “打开大图” 的快捷键时可以直接弹出对应的图片哈~

**Comment by hoothin** [comment]
快捷键测试下来也是没问题的呀，你的 t 是不是被其他扩展接管了？

**Comment by zjh16** [comment]
> 快捷键测试下来也是没问题的呀，你的 t 是不是被其他扩展接管了？

我说的不是按键失效，我在个人喜欢页面收藏了一个图文作品，我点击播放以后，翻过了几张图片，当我按下 “查看当前图片” 时，他只显示封面的图片，不显示当前的图片

**Comment by zjh16** [comment]
> 快捷键测试下来也是没问题的呀，你的 t 是不是被其他扩展接管了？

不好意思，是我这边的问题，我是在个人喜欢页面点开的图文作品，其实在普通页面是可以识别到的

感谢作者制作了这个插件！！
