### ISSUE TITLE
易搜网站请求适配

### ISSUE THREAD

**Issue by freedomspiritJohn** [hoothin/UserScripts#472]
**The url of site**
https://yiso.fun/info?searchKey=%E5%A5%A5%E6%9C%AC%E6%B5%B7%E9%BB%98

我自己不会制作规则，希望添加上，或者教我也行

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "易搜-网盘搜索",
    "url": "^https?://yiso\\.fun/",
    "nextLink": ".card>.card-body>.el-pagination>.btn-next"
}
</pre>

**Comment by freedomspiritJohn** [comment]
> {
>     "name": "易搜-网盘搜索",
>     "url": "^https?://yiso\\.fun/",
>     "nextLink": ".card>.card-body>.el-pagination>.btn-next"
> }
> 导入

没有效果，大佬。
![image](https://github.com/hoothin/UserScripts/assets/129288685/f0ee1d9d-1e49-4cb4-996b-e857322360cf)

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/8a435de6-82ed-4a03-bc8c-65c396a0238f)
没问题，这网站要登录

**Comment by hoothin** [comment]
另外，这个网站事件绑在页内，把元素取出来是不会保留任何交互（例如点击打开链接）的，可以自行用`hookUrl`钩住点击。下面的范例是钩住“打开此分享”这个按钮的，你也可以添加其他的
<pre name="pagetual">
    {
        "name": "易搜-网盘搜索",
        "url": "^https?://yiso\\.fun/",
        "nextLink": ".card>.card-body>.el-pagination>.btn-next",
        "wait": 500,
        "hookUrl": "//a[contains(text(),'打开此分享')]"
    }
</pre>

**Comment by freedomspiritJohn** [comment]
> 另外，这个网站事件绑在页内，把元素取出来是不会保留任何交互（例如点击打开链接）的，可以自行用`hookUrl`钩住点击。下面的范例是钩住“打开此分享”这个按钮的，你也可以添加其他的
> 
>     {
>         "name": "易搜-网盘搜索",
>         "url": "^https?://yiso\\.fun/",
>         "nextLink": ".card>.card-body>.el-pagination>.btn-next",
>         "wait": 500,
>         "hookUrl": "//a[contains(text(),'打开此分享')]"
>     }
> 导入

好哒，谢谢大佬，但是听不懂。
