### ISSUE TITLE
Picviewer CE+:The floating preview image conflicts with the shortcut key.

### ISSUE THREAD

**Issue by Gloryandel** [hoothin/UserScripts#474]
**Describe the bug**

The floating preview image conflicts with the shortcut key.Enable the following functions, place the mouse over the image, and successfully pop up a photo preview. At this time, the default shortcut keys will become invalid.
Due to the fact that shortcut keys can only take effect when the mouse is placed, floating preview conflicts with shortcut keys

**Screenshots**

![image_6](https://github.com/hoothin/UserScripts/assets/51497852/f6dd1b03-603a-41d6-b414-7ba0c8126ef4)

 - OS: Windows（Violentmonkey）
 - Browser: Vivaldi(Chromium)

**Comment by hoothin** [comment]
只有图库跟功能键有关系。其他快捷键都和功能键没有关系。
预览中是不允许新开窗口的，这和快捷键没有关系。

我说ID怎么很眼熟，原来是搜索酱的用户😀

**Comment by Gloryandel** [comment]
> 只有图库跟功能键有关系。其他快捷键都和功能键没有关系。 预览中是不允许新开窗口的，这和快捷键没有关系。
> 
> 我说ID怎么很眼熟，原来是搜索酱的用户😀

哈哈哈，没办法，大佬开发的众多脚本实在太强了！！！

预期是：**鼠标放置在图片上**，出现悬浮图，按 g 进入图库/c 查看图片（悬浮图并不允许对当前鼠标下的照片更多操作）

目前的解决办法：按 预览功能键取消预览+快捷键，根据脚本描述，仅图库有加功能键变全局快捷键的功能。

可能在悬浮图弹出时仍然响应快捷键或者弄个回调，检测到快捷键关闭预览执行快捷键功能吗？😂😂，受限于框架就算了😊

**Comment by Gloryandel** [comment]
还有，针对于 bilibili 评论区：鼠标放置于评论区会触发预览头像（加载中的视频也会触发图像，但是并未看到预览的对象在哪（奇怪）），但是又想要预览视频图像，所以能排除，不知道如何处理。。。😅

**Comment by Gloryandel** [comment]
关于图像显示尺寸比实际尺寸还大时，预览改进建议：
1. 运用照片窗口-适应屏幕，并且水平垂直居中等策略，对于超长/已经放大的照片可以缩放至查看全局，可以解决图像需要滚动才能看到全局的情况。
2. 直接不悬浮（但是不知道的人可能会认为没有生效。。。）
![image_7](https://github.com/hoothin/UserScripts/assets/51497852/3dce9e6f-57a5-4175-a83d-ddae074ccdd0)

[测试连接](https://photo.sina.cn/album_4_704_389542.htm)

🤐

**Comment by hoothin** [comment]
> 预期是：**鼠标放置在图片上**，出现悬浮图，按 g 进入图库/c 查看图片（悬浮图并不允许对当前鼠标下的照片更多操作）
> 
> 目前的解决办法：按 预览功能键取消预览+快捷键，根据脚本描述，仅图库有加功能键变全局快捷键的功能。
> 
> 可能在悬浮图弹出时仍然响应快捷键或者弄个回调，检测到快捷键关闭预览执行快捷键功能吗？😂😂，受限于框架就算了😊

可以的，但是这样改的话，在你的方案里，已经有大图窗口打开的情况下，是否还能显示预览呢？

**Comment by Gloryandel** [comment]
> > 预期是：**鼠标放置在图片上**，出现悬浮图，按 g 进入图库/c 查看图片（悬浮图并不允许对当前鼠标下的照片更多操作）
> > 目前的解决办法：按 预览功能键取消预览+快捷键，根据脚本描述，仅图库有加功能键变全局快捷键的功能。
> > 可能在悬浮图弹出时仍然响应快捷键或者弄个回调，检测到快捷键关闭预览执行快捷键功能吗？😂😂，受限于框架就算了😊
> 
> 可以的，但是这样改的话，在你的方案里，已经有大图窗口打开的情况下，是否还能显示预览呢？
大图窗口一版需要看图更多操作。打开后可以不用特意关闭，还能保证连贯性，目前已经做到了。不关闭也能滚动网页。

**已经有大图窗口打开的情况下，是否还能显示预览呢？**，目前无法测试，鼠标放置于图上，预览弹出的同时，**浮动工具栏消失，同时不响应快捷键** ，所以**自动浮动预览**时无法触发看图窗口

**以上是我配置成默认自动预览出现的问题。重制配置后**发现：
- 默认：按住快捷键浮动预览，放开后自动打开看图窗口，**浮动工具栏还在，仅不响应快捷键** ，仍然可以由预览窗口切换到大图窗口。
- 配置成默认自动预览（勾选**反转快捷键，默认显示预览**）：自动预览，但是**浮动工具栏消失，同时不响应快捷键** ，所以**无法**切换到窗口。同时，必须鼠标移出图像，**按住切换键再移入才能切换到大图窗口**（很别扭）
![image_8](https://github.com/hoothin/UserScripts/assets/51497852/bfd6dd03-e039-4404-ab8e-b0c8bcb1b2ed)

综上：

配置成默认**自动预览时，显示浮动工具栏，能响应快捷键就行**，按住浮动预览正常，其他都很好了！

**Comment by hoothin** [comment]
新版改成了：未缩放的图片，如果尺寸小于当前浏览器窗口，则不预览。
然后如果设置里没有隐藏浮动工具栏，则预览时也不会隐藏工具栏，预览和大图窗口允许同时存在。

**Comment by Gloryandel** [comment]
问题已优化或已提供解决方案
