### ISSUE TITLE
网页未翻到底部就显示已经是最后一页，并停止翻页

### ISSUE THREAD

**Issue by anita739** [hoothin/UserScripts#475]
**The url of site**
https://vrchive.nomieze.com/avatars/

**Is your request related to a problem? Please describe.**
网页未翻到底部（通常只加载了一页或两页后）就显示已经是最后一页，并停止翻页，右侧插件UI也关闭

**Describe the result you'd like with the rule**
能正常加载完整页面

**Custom rule you've tried**
```
{
    "name": "VRChive :: Avatars",
    "url": "^https?://vrchive\\.nomieze\\.com/",
    "example": "https://vrchive.nomieze.com/avatars/",
    "nextLink": "#next-btn",
    "pageElement": ".card",
    "stopSign": "false"
}
```

**Additional context**
【Pagetual v.1.9.36.81】 debug: Stop as next hide when emu

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "VRChive :: Avatars",
    "url": "^https?://vrchive\\.nomieze\\.com/",
    "example": "https://vrchive.nomieze.com/avatars/",
    "nextLink": "#next-btn",
    "pageElement": ".card",
    "include": "#content-container",
    "waitElement": "!.card.scale-0",
    "insert": "#content-container",
    "insertPos": "in"
}
</pre>
停止翻頁時，控制臺輸出的原因是什麽？發給我看看

**Comment by hoothin** [comment]
那应该是翻页的时候下一页按钮隐藏了，这种情况可以用 waitElement 来等待加载完成再取元素，前面的 ! 代表在 `.card.scale-0` 不应该存在
