### ISSUE TITLE
Pagetual: add https://www.asmr.one/works support

### ISSUE THREAD

**Issue by TheKingTermux** [hoothin/UserScripts#477]
**The url of site**
_Not With Filter_
https://www.asmr.one/works
https://www.asmr.one/works?page=2 (next page)
https://www.asmr.one/works?page=3 (next page again)
Etc.....
_With Filter_
https://www.asmr.one/works?keyword=%24tag%3AASMR%24
_Multi Filter_
https://www.asmr.one/works?keyword=%24tag%3AASMR%24%0A%24tag%3ABinaural%24

**Is your request related to a problem? Please describe.**
[I have explained it here](https://greasyfork.org/id/scripts/438684-pagetual/discussions/212983)
Maybe if it could be explained more it would be like this
Pagetual will load the next page on the website, but pagetual only duplicates the first page and will be used again for the second, third and so on pages. I don't know what the mechanism is, what I know is that pagetual only duplicates the first page and duplicates the first page to the next page 

**Describe the result you'd like with the rule**
Pagetual does not just duplicate the first page

**Custom rule you've tried**
Sorry I can't make rules because I can't make them

**Additional context**
I hope that the pagetual doesn't just duplicate the first page, Sorry if it's burdensome

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/c9fcf4dc-5c44-4b10-9af0-f1c10fb29ed1)
I can't reproduce your issue.

**Comment by hoothin** [comment]
If you still can't make it work, try this rule
<pre name="pagetual">
{
    "name": "ASMR Online",
    "url": "^https?://www\\.asmr\\.one/",
    "example": "https://www.asmr.one/works?keyword=%24tag%3AASMR%24",
    "pageElement": "main>.row+.row",
    "nextLink": ".ant-pagination-next>a",
    "waitElement": [
        "main>.row+.row>div",
        ".q-img__loading"
    ]
}
</pre>

**Comment by TheKingTermux** [comment]
> If you still can't make it work, try this rule
> <pre name="pagetual">
> {
>     "name": "ASMR Online",
>     "url": "^https?://www\\.asmr\\.one/",
>     "example": "https://www.asmr.one/works?keyword=%24tag%3AASMR%24",
>     "pageElement": "main>.row+.row",
>     "nextLink": ".ant-pagination-next>a",
>     "waitElement": [
>         "main>.row+.row>div",
>         ".q-img__loading"
>     ]
> }
> </pre>

It works now after removing '?keyword=%24tag%3AASMR%24` And it's a little laggy, but that's okay as long as can still preload and don't just duplicate the first page
Thanks for helping me

**Comment by TheKingTermux** [comment]
Hhmm it work but at the second page and so on the website features is not working properly, like the tag button if you press it for a while it will bring up 3 menus related to that tag, and also the favorites section (where the button is at the top right of each cover) also cannot be used and goes straight to ASMR if you click it, even though on the first page the website feature is still fine, but on the 2nd page and so on it starts to become unusable

**Comment by hoothin** [comment]
No, you can't do that because it's a single page application. To achieve that functionality, you would need to use the pageAction in the rule and write the code yourself.

**Comment by TheKingTermux** [comment]
> No, you can't do that because it's a single page application. To achieve that functionality, you would need to use the pageAction in the rule and write the code yourself.

Can you give me some example for this ?

**Comment by hoothin** [comment]
Alright, these are [all the rules](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json), and you can search for 'pageAction' to refer to them.
However, I want to remind that it might not be easy for you because it requires a lot of effort, which is why I didn't provide more assistance.
