### ISSUE TITLE
字体网站，页面是翻了，但到第7页大部分就不显示了。

### ISSUE THREAD

**Issue by Connor-yang96** [hoothin/UserScripts#478]
**Describe the bug**

**To Reproduce**
1. Go to https://www.1001fonts.com/
2. 输入 “ A a ”
3. 每页个数调整到 50 。

![image](https://github.com/hoothin/UserScripts/assets/81000027/a516f7ee-c944-4f65-be87-ae7f8d8ee4e3)

5. 往下滚动到第 7页以后 
6. See error

**Expected behavior**
![image](https://github.com/hoothin/UserScripts/assets/81000027/b41aee4a-9f49-4534-a233-f540559e69ce)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [Edge]
 - Version (118.0.2088.57 (Official build) (64-bit)]

**Additional context**

**Comment by hoothin** [comment]
估计服务器过载了，控制台看下图片是不是返回503了
