### ISSUE TITLE
网站做了禁灰,怎么解决.抱大佬腿

### ISSUE THREAD

**Issue by Socialfear** [hoothin/UserScripts#479]
网址;http://www.momxs.com/mom.asp?id=35712
网站好像做了禁灰,我说下载老是缺失
但是从上一章可以跳转到那一章,这个心法有提到吗?如果提到了可能是我脑瓜太笨没看懂,这种情况怎么解决
感谢大佬!
https://github.com/hoothin/UserScripts/assets/126323029/caebdef5-bf5c-4e9e-9091-4250c7ca5692)

**Comment by hoothin** [comment]
选项里开启“保存图片网址”，然后安装怠惰小说 zip 扩展，下载的时候就会把缺失的图片文字保存到 markdown 文件，你随便用个支持 markdown 的阅读器就能看到文字了。
