### ISSUE TITLE
如何在规则里设置 "使用 iframe"

### ISSUE THREAD

**Issue by atbsi** [hoothin/UserScripts#480]
尝试写了一个页面规则，但页面并未完整显示，以前使用Super_preloaderPlus的经验来说，这个启用 "使用 iframe" 选项就可以正常加载了。
但我查看了文档，没有相关的选项，请问要如何启用？
规则类似这样：
```
  {
    "name":"yande",
    "url":"^https://yande\.re/",
    "pageElement":"body"
  }
```

**Comment by hoothin** [comment]
具体网址呢？一般情况下不用写规则，切换至动态加载模式就行
如果要用规则的话，永页机没有 iframe 选项，但有个 [action](https://pagetual.hoothin.com/en/rules/action.html)

**Comment by atbsi** [comment]
谢谢，没有具体网址，我就是想学习下规则。因为我使用的是Greasemonkey，这个脚本好像没适配它，无法像tampermonkey那样在菜单里定义，只好手写规则。

**Comment by hoothin** [comment]
沒有命令菜單的話可以這麽做：在永頁機的配置頁打開側邊欄，然後右擊側邊欄的太極圖標

**Comment by atbsi** [comment]
原来菜单在这里，我一直想当然认为在脚本的箭头菜单了，太感谢了。
