### ISSUE TITLE
规则文件的优先级丢失

### ISSUE THREAD

**Issue by atbsi** [hoothin/UserScripts#483]
把我的自定义规则文件调整到最上面，一开始是比其他规则优先触发，但过不久这种优先就失效了，items_all.json和 pagetualRules.json 的规则开始先触发。
这期间有可能影响的操作是我在Greasemonkey禁用了Pagetual，然后启用了Super_preloaderPlus_one_New。等我切换回来，就发现优先级失效了。

然后我把所有规则删除，更新，再重新添加，再调整到最上，我的自定义规则又生效了。但我过了几个小时再打开那个网站，优先级又失效了。
当然，我无法确定是优先级丢失了，还是我自定义的规则丢失了。

**Comment by hoothin** [comment]
优先级变更之后需要下次更新才会生效。
你所观察到的生效可能是自定义规则框内的规则吧？

另外，因为有缓存存在，如果 url 没有彻底覆盖，则没兜住的网址可能会插入缓存最前。
你可以把具体网址和你所编辑的规则发给我看看。

**Comment by hoothin** [comment]
你看看匹配到的是不是`Moebooru:Danbooru clones`？如果是的话，更新脚本，再更新规则试试

**Comment by atbsi** [comment]
都更新后，重启浏览器，现在目测正常了

**Comment by hoothin** [comment]
1、命令菜单
2、每48小时自动更新
