### ISSUE TITLE
页面不加载的情况下 ，滚动条无限缩小

### ISSUE THREAD

**Issue by fir05** [hoothin/UserScripts#485]
默认规则对这个网站无效，于是我尝试强制拼接。加载到第二页也就是最后一页时，滚动到底部，滚动条开始快速缩小，但页面并未变化。
https://db.msin.jp/jp.page/actress?id=1048135

**Comment by hoothin** [comment]
这是页面内 js 自动修改 `center_left` 的 padding-top 导致的。强制拼接的时候是插入页尾，所以页内会不断拉长。
我测试了一下，这个页面默认的自动规则是可以生效的呀，也不会有拉长的问题。你是如何判断默认规则无效的呢？

**Comment by fir05** [comment]
我在Window firefox 120.0.1 下，默认规则生效，但一直处于加载中，不会显示下一页。
为何在其他强制拼接的页面不会有这种页面不变，滚动条疯狂拉长的现象呢？也就是说这种拉长是正常的吗？
