### ISSUE TITLE
P站的默认代码好像永用不了了

### ISSUE THREAD

**Issue by myrena** [hoothin/UserScripts#486]
main>section ul>li>div>a@@@@@@var noval=JSON.parse(data.querySelector("#meta-preload-data").content).novel;noval[Object.keys(noval)[0]].content;

直接黏贴自定义下载没有反应

**Comment by hoothin** [comment]
P站改版了，换用这个规则
`main>section ul>li div>a @@@@@@ var noval=JSON.parse(doc.querySelector("#meta-preload-data").content).novel;noval[Object.keys(noval)[0]].content;`
