### ISSUE TITLE
Addition for Sanfoundry.com website

### ISSUE THREAD

**Issue by themrsami** [hoothin/UserScripts#488]
it was working before for sanfoundry.com but i have reloaded 10 times but it is not working now. it should auto show next page below.

reference link : https://www.sanfoundry.com/engineering-mathematics-questions-answers-nth-derivative-some-elementary-functions-1/

![image](https://github.com/hoothin/UserScripts/assets/91170768/60ce4843-d9ec-4a9d-a0aa-65fc84d4ed74)

in the left sidebar there is list of next pages. please make it work because last time it was working.

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Sanfoundry",
    "url": "^https?://www\\.sanfoundry\\.com/",
    "nextLink": ".sf-nav-prev-bottom+div > a[rel=next]"
}
</pre>

**Comment by themrsami** [comment]
thank you soo much.
