### ISSUE TITLE
Please add support for FIreMonkey

### ISSUE THREAD

**Issue by gnadgnaoh** [hoothin/UserScripts#490]
error
    Type error for parameter userScriptOptions (Error processing scriptMetadata: Value must either: be a null value, be a number value, be a string value, be a boolean, be an array value, .grantRemove must () => {
    let array = Array.from(choices, forceString);
    let n = array.length - 1;
    array[n] = `or ${array[n]}`;
    return `must either [${array.join(", ")}]`;
    }, .registerMenuCommand must () => {
    let array = Array.from(choices, forceString);
    let n = array.length - 1;
    array[n] = `or ${array[n]}`;
    return `must either [${array.join(", ")}]`;
    }, .remoteCSS must () => {
    let array = Array.from(choices, forceString);
    let n = array.length - 1;
    array[n] = `or ${array[n]}`;
    return `must either [${array.join(", ")}]`;
    }, .resourceData must () => {
    let array = Array.from(choices, forceString);
    let n = array.length - 1;
    array[n] = `or ${array[n]}`;
    return `must either [${array.join(", ")}]`;
    }, or .storage must () => {
    let array = Array.from(choices, forceString);
    let n = array.length - 1;
    array[n] = `or ${array[n]}`;
    return `must either [${array.join(", ")}]`;
    }) for userScripts.register.

**Comment by hoothin** [comment]
No, please use Violentmonkey or Greasemonkey.
