### ISSUE TITLE
dm5 规则在Greasemonkey和tampermonkey的效果不一致

### ISSUE THREAD

**Issue by atbsi** [hoothin/UserScripts#491]
v.1.9.37.9 
win 10 64
firefox 121 64
url https://www.dm5.com/m807727/
在 dm5，Greasemonkey 和 tampermonkey 都触发的是这个规则：
```
{
    "name": "动漫屋 1",
    "action": 1,
    "url": "^https?://www\\.(dm5|1kkk)\\.(com|cn)/(m|ch)",
    "pageElement": ".view-main>.item",
    "nextLink": "span.current+a,div#chapterpager+a+a",
    "rate": 3
}
```
但 Greasemonkey 在加载第二页后，第三页就一直处于加载状态。tampermonkey 则一直正常加载。

**Comment by hoothin** [comment]
感谢反馈，暂时修复了，但是最好还是用 tampermonkey 或者 violentmonkey。

火狐有个 DeadObject 机制，会定时清除 dom 来释放内存，greasemonkey 和 firemonkey 这些在 firefox 上没有优化过的插件都会定期清除掉永页机存储的对上一页的引用对象，导致出错。

**Comment by atbsi** [comment]
谢谢，我会尝试 violentmonkey，既然是开源的，看看能否修改出加载本地脚本的方法来。
