### ISSUE TITLE
自定义分隔条样式不生效

### ISSUE THREAD

**Issue by freedomspiritJohn** [hoothin/UserScripts#495]
![image](https://github.com/hoothin/UserScripts/assets/129288685/573175b0-682d-4c1e-b0a0-565b30645e6d)
![image](https://github.com/hoothin/UserScripts/assets/129288685/33d7cf53-f328-4c5c-b99e-5c756ec3d240)
自定义完还是默认这种样式，不知道哪里有问题

**Comment by hoothin** [comment]
优先级不够，加个`!important`
