### ISSUE TITLE
Use the mouse scroll wheel to adjust the magnification level of the magnifier

### ISSUE THREAD

**Issue by MRawen** [hoothin/UserScripts#497]
Could you add a feature to use the mouse scroll wheel to adjust the magnifier's zoom level? I only found the feature to adjust the magnifier's size using the scroll wheel in the settings. Thank you.

**Comment by hoothin** [comment]
Click to pin the magnifier at first, then you can scale the magnifier's size

**Comment by MRawen** [comment]
Not the size of the magnifier. I want to be able to increase the zoom level of the image by scrolling the mouse wheel. Some magnifier images zoom in too little, almost appearing not to zoom, while others zoom in too much to view.

**Comment by hoothin** [comment]
There is a option named `Zoom Range` under `ImgWindow`, do you mean this?

**Comment by MRawen** [comment]
It doesn't zoom in large enough to see the details. 
![1](https://github.com/hoothin/UserScripts/assets/108231351/085f9a90-3a02-4fcc-a3ec-9f463ce3194b)

**Comment by hoothin** [comment]
The magnifier doesn't zoom image, it just show original size. you need to popup the image for scale.

**Comment by MRawen** [comment]
Could you add a feature to adjust the zoom level when using the magnifier? I find it quite convenient when viewing images.

**Comment by hoothin** [comment]
Ok, I'll try.

**Comment by hoothin** [comment]
You can check the option "Zoom image by wheel" under magnifier now.

**Comment by MRawen** [comment]
"Awesome, it worked, but I think it should be activated by pressing Shift + scrolling the mouse (or a similar key) to avoid interfering with page scrolling while viewing."

**Comment by MRawen** [comment]
There's an issue that it doesn't work when the "Enable wheel zoom" feature is turned off, and I think the "Zoom image by wheel" feature only needs to zoom the image instead of both zooming the image and using the wheel zoom.

**Comment by hoothin** [comment]
I've already hooked it up with some options. If it's doing you a solid, help me spread the word. Much appreciated!

**Comment by MRawen** [comment]
Thank you for the solution, my friends were very fond of it when I introduced it to them.
