### ISSUE TITLE
幻想次元新姿势

### ISSUE THREAD

**Issue by fantastlcok** [hoothin/UserScripts#5]
添加cookie
wordpress_logged_in
可直接免登录查看文章。

**Comment by hoothin** [comment]
多谢告知，但是幻想次元有回复可见的文章吗？能否给我个链接？

**Comment by fantastlcok** [comment]
@hoothin  并没有此功能。

**Comment by hoothin** [comment]
那这是指哪些站点？这个漏洞新的wp应该都修复了吧

**Comment by fantastlcok** [comment]
@hoothin 这不是wp漏洞。是nginx做的判断条件。 幻想次元 acg18.us

**Comment by hoothin** [comment]
没理解，囧啊，既然没有回复可见的文章，免登录查看文章又是什么意思？这是指幻想次元上分享的姿势还是针对幻想次元的姿势？要不你直接fork了给我merge吧

**Comment by fantastlcok** [comment]
@hoothin 
`javascript:document.cookie="wordpress_logged_in=test";`
很多文章都是需要登录才能查看的。

**Comment by Aimerzz** [comment]
我来试一下
