### ISSUE TITLE
add support for e-hentai.org to download all images

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#503]
https://e-hentai.org/g/2775620/85df90d569/  (nsfw)

**Comment by hoothin** [comment]
You need to click inside, open the gallery, and then click on the 'Load More' button at the top.

**Comment by cleuton4k** [comment]
It happens that sometimes the order in which the images are displayed/downloaded is wrong.
![689](https://github.com/hoothin/UserScripts/assets/90144967/6f460d93-92e3-415e-a6c6-3f6c26b27436)
![690](https://github.com/hoothin/UserScripts/assets/90144967/0dded3e0-3c78-40be-8cb1-11a8d1833d9b)

**Comment by hoothin** [comment]
The images are inserted only after they have finished loading and their sizes have been obtained. Therefore, if there is network lag while loading a particular image, it may get inserted later in the sequence.
However, I have tested it locally, and the order appears to be normal on my end.
![image](https://github.com/hoothin/UserScripts/assets/5361213/f14b4cf6-d686-499a-9825-ad24278eb5ec)
