### ISSUE TITLE
wrong toolbar positions

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#507]
When choosing certain positioning options, the bar appears in positions outside the image.
![694](https://github.com/hoothin/UserScripts/assets/90144967/e6baed8e-c5f2-4ea1-b8cc-894094e9e2b3)
![695](https://github.com/hoothin/UserScripts/assets/90144967/ddc5d394-e8a5-4d3a-a6fb-0d7da6f9c1b2)

**Comment by hoothin** [comment]
Thank you for report, it's fixed.
