### ISSUE TITLE
add support for mypikpak

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#509]
pikpak is a cloud storage service and you can create a free account and test the premium version.
https://mypikpak.com/drive/activity/invited?invitation-code=37485252

-the site shows thumbnails of the images, but to download the original size image you need to right-click and click on "download to pc", one by one, as the site does not allow you to download several at the same time, there is a way to automate this process? OR
-it is possible to see the image in original size by double clicking on the image, however it is not possible to download the image using the "download (d)" function of your extension, what would be the best way to download several original images at the same time?

https://drive.google.com/file/d/1tgGAmQfvdZw3vqXgdLNc3xLXaG871blQ/view?usp=sharing

**Comment by hoothin** [comment]
Pikpak show the image in original size by blob, which means the image has no url but direct point the file in server.
Best way to download multiple files is downloading with its desktop app.
I can write a script to download all but it seems that the server limit the download rate.

**Comment by cleuton4k** [comment]
create a new script or integrate with picviewer?

**Comment by hoothin** [comment]
You can try my [SearchJumper](https://search.hoothin.com).
Move all images that you want to download to a new folder.
Then download all with this rule:
```
#p{loopStart(1)&click(div.thumbnail-wrap > div.grid-operation > a.pp-link-button)&click(li[aria-label\="Download to PC"])&sleep(1000)&loopEnd}
```
![image](https://github.com/hoothin/UserScripts/assets/5361213/c8055d2c-ece0-4536-b786-58c920386ad0)

**Comment by cleuton4k** [comment]
I didn't understand

**Comment by hoothin** [comment]
Just follow step-by-step under:
+ Install SearchJumper extension
+ Right click extension icon
+ Click "Add current engine"
+ Paste the rule I post before into the "url" input
+ Click "Test" or "Save"
