### ISSUE TITLE
求问大佬为什么打开图库的时候能看到所有图片，而下载后有些图片说不显示该格式无法查看

### ISSUE THREAD

**Issue by sjkwxdc** [hoothin/UserScripts#511]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hoothin** [comment]
你手动改下后缀名加上个`.png`就行了。
另外提问时把网址一并贴上来吧。
