### ISSUE TITLE
grayish buttons

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#512]
Why are the buttons gray in Microsoft Edge and in other Chromium based browsers they are colored?
![636](https://github.com/hoothin/UserScripts/assets/90144967/8991f73f-ad66-42af-807a-5387cbc7816a)
![632](https://github.com/hoothin/UserScripts/assets/90144967/8facd57f-6c4a-45cc-b5a1-1eb272ad9b89)
![635](https://github.com/hoothin/UserScripts/assets/90144967/5f4193b0-aa85-4d5e-bcb2-8ca7f11b4aff)
![634](https://github.com/hoothin/UserScripts/assets/90144967/b7144131-1a43-4562-965f-42370f5472b6)

**Comment by hoothin** [comment]
It's depend on the default style of the browser.
