### ISSUE TITLE
corrupted gallery buttons

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#513]
https://porn.hair/photos/propertysex-gizelle-blanco-features-high-heels-mobi-xxx-sexo-pics   (nsfw)

![638](https://github.com/hoothin/UserScripts/assets/90144967/eb3983e2-5a25-4d3d-9101-1d2ef73abe76)
![637](https://github.com/hoothin/UserScripts/assets/90144967/66df9966-cf6f-4e98-b6bf-c5d8a01b5c37)

**Comment by hoothin** [comment]
This site has been made compatible.
