### ISSUE TITLE
有的页面拼接完成后 图片无法正常显示

### ISSUE THREAD

**Issue by WXqwer** [hoothin/UserScripts#514]
![image](https://github.com/hoothin/UserScripts/assets/73450696/178d63e6-b033-4d94-8410-739850da3301)
![image](https://github.com/hoothin/UserScripts/assets/73450696/82bb255e-7539-4f73-b25e-adb59e118b7e)

**Comment by hoothin** [comment]
`"css":".b-img.sleepy .b-img__inner{opacity:1}"`
