### ISSUE TITLE
very small image detection

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#515]
Even after increasing the values ​​to show the toolbar, it continues to be shown.
https://twitter.com/yourfavlil/status/1749945910132683241
https://www.youtube.com/watch?v=Qt2mbGP6vFI
![639](https://github.com/hoothin/UserScripts/assets/90144967/947e856d-72d1-482c-aa95-cc0ad7d2b0e3)
![642](https://github.com/hoothin/UserScripts/assets/90144967/4ca19612-728e-408c-b75e-7fbae9f3f11e)
![643](https://github.com/hoothin/UserScripts/assets/90144967/b7ad9e17-8bb4-4a62-8df0-6a5fc423512b)

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/c1e87267-e262-47f7-9b51-8a3caae53597)
Uncheck this

**Comment by cleuton4k** [comment]
![644](https://github.com/hoothin/UserScripts/assets/90144967/0f3a2056-dfc1-4936-bc63-914cab12adef)

**Comment by hoothin** [comment]
It's fixed now.
