### ISSUE TITLE
small image detection

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#516]
https://xxxrip.net/  (nsfw)
![645](https://github.com/hoothin/UserScripts/assets/90144967/8e340879-3320-4c38-8e86-71ef2ba2f48c)

**Comment by hoothin** [comment]
It's not a small image; it points to `https://xxxrip.net/templates/Default/images/style/header3.gif`, which serves as the background image for the `<div class="header3">` element, stretching beyond a size of 100% * 223px.
