### ISSUE TITLE
Hope to support the complete saving of the current page including extra content.希望能支持完整保存当前页面包括额外内容

### ISSUE THREAD

**Issue by luckylemonade24** [hoothin/UserScripts#517]
I see some guides and the like and always want to save with one click.,After all, I only play stand-alone games.,And the machine configuration is poor.,Open an edge good card and load too slowly.,So I hope to support the complete saving of the current page including extra content.

If you can keep the original format as much as possible, it would be best to use a long screenshot, not to reduce the resolution like edge, or save a piece of each page to the download directory by page name plus serial number

Generally, only the original page can be saved

I don't know much about code, I don't understand some of the difficulties, I don't know if it's possible, if not, I can just forget it
above text was translated By Bing Translator

中文原文：
我看到一些攻略之类的总想一键保存，毕竟我也只玩单机游戏，而且机器配置差，开个edge好卡加载太慢，所以希望能支持完整保存当前页面包括额外内容

如果能尽可能保留原格式最好了，或者就通过长截图，不是edge那种缩减分辨率的，或者每页一截按页面名称加序号保存至下载目录

一般保存都是只能保存原本页面

我不是很懂代码，一些困难之处我不懂，我不知道这是否可行，如不行也只能算了

**Comment by hoothin** [comment]
另存为mhtml就行
