### ISSUE TITLE
可不可以添加一个拼接时把上下元素的顶部和底部减去一定像素的功能?感谢大佬!

### ISSUE THREAD

**Issue by LMAXRouterCN** [hoothin/UserScripts#518]
**Is your feature request related to a problem? Please describe.**
在某些网站拼接过后两个元素中间还是会有空隙
**Describe the solution you'd like**

**Describe alternatives you've considered**
可不可以添加一个拼接时把上下元素的顶部和底部减去一定像素的功能?感谢大佬!
**Additional context**
![image](https://github.com/hoothin/UserScripts/assets/108993738/be8acb8b-a04f-4a08-856f-777a45a2f2d3)

**Comment by hoothin** [comment]
编辑规则，添加`"pageBar": 0`
