### ISSUE TITLE
corrupted images

### ISSUE THREAD

**Issue by cleuton4k** [hoothin/UserScripts#519]
When downloading images that are in webp, the script converts them to jpg and the image becomes corrupted.
https://www.reddit.com/r/lingeriedream/  nsfw

https://github.com/hoothin/UserScripts/assets/90144967/9386df5c-058e-444c-a43a-962b192dc03a

**Comment by hoothin** [comment]
No, the image isn't converted
![image](https://github.com/hoothin/UserScripts/assets/5361213/21f130db-ec9a-4953-b110-e45cdb5e1014)
webp one is only thumbnail.
