### ISSUE TITLE
[Pagetual] Wrong behavior in lcsc.com

### ISSUE THREAD

**Issue by boromyr** [hoothin/UserScripts#520]
**The url of site**
[LCSC](https://www.lcsc.com/) 

**Is your request related to a problem? Please describe.**
On the LCSC website, you can search through thousands of electronic components in the catalog, and you can use many filters to search within desired values. With Pagetual these filters are applied to the first search page, and not to those subsequently loaded.
To reproduce the issue:

1.  Go to the example page [to search for components](https://www.lcsc.com/products/Wire-To-Board-Wire-To-Wire-Connector_11068.html) and apply the filter in the second column "Package" selecting the first 3 options, "P=0.8mm" "P=1mm" "P=1.25mm"
![image](https://github.com/hoothin/UserScripts/assets/52782032/2c06f073-040f-45bb-97e8-08d81bd6092b)
Please note that 50 available items are being filtered, and the default number of items displayed is 25, so this only requires two pages.
2. Click on "Apply" to apply the filter and scroll down the page to see the result.
![image](https://github.com/hoothin/UserScripts/assets/52782032/8d18c8c7-64fc-438b-8abf-e908e50ce2ad)
The filters are deselected and the available pages exceed 200, so it's as if the initial page was loaded without filters.
**Describe the result you'd like with the rule**

**Custom rule you've tried**
The settings are the default ones provided by Pagetual and I performed a factory reset before taking the screenshots.

**Additional context**
Windows 11 
Edge Version 121.0.2277.83 (Build ufficiale) App stable, canale beta (64 bit)
Tampermonkey v5.0.6192
Pagetual  1.9.37.23

**Comment by hoothin** [comment]
You can use the ['init'](https://pagetual.hoothin.com/rules/init.html) function to copy the selection status to the next page, or I can write a rule for you when I have time.

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Wire To Board / Wire To Wire Connector | Connectors | LCSC",
    "url": "^https?://www\\.lcsc\\.com/products/",
    "example": "https://www.lcsc.com/products/Wire-To-Board-Wire-To-Wire-Connector_11068.html",
    "author": "Hoothin",
    "refreshByClick": "button.primary.v-btn"
}
</pre>
Work with 1.9.37.24

**Comment by boromyr** [comment]
I updated the page and imported the rule and now it works, but twice after some time I receive the error `403 forbidden access denied` and I can only reconnect to the site with a VPN, I think it's a temporary ban, and I have to wait a bit before I can reconnect with my IP.

**Comment by hoothin** [comment]
Yes, the site restricts the visit rate.

**Comment by boromyr** [comment]
Ok thanks anyway, I think it is among the sites incompatible with this script unfortunately

**Comment by hoothin** [comment]
I means, just add ['sleep'](https://pagetual.hoothin.com/rules/sleep.html).
<pre name="pagetual">
{
    "name": "Wire To Board / Wire To Wire Connector | Connectors | LCSC",
    "url": "^https?://www\\.lcsc\\.com/products/",
    "example": "https://www.lcsc.com/products/Wire-To-Board-Wire-To-Wire-Connector_11068.html",
    "author": "Hoothin",
    "refreshByClick": "button.primary.v-btn",
    "sleep": 1000,
    "iframeInit": "win.self=win.top;"
}
</pre>
