### ISSUE TITLE
自定义章节内分页好像没起作用

### ISSUE THREAD

**Issue by mggzhu** [hoothin/UserScripts#521]
在自定义章节分页的正则表达式中，我写了如下的规则
^\s*(下一[章页頁张張]|next\s*page|次のページ)
但是当前章节中，只会下载第一页的内容。网页中的分页标题就是 “下一章”

**Comment by hoothin** [comment]
这只适用于下一页有对应链接的简单情况，如果下一页是动态生成的，那就需要自己写规则生成下一页链接

**Comment by mggzhu** [comment]
> 这只适用于下一页有对应链接的简单情况，如果下一页是动态生成的，那就需要自己写规则生成下一页链接。 规则范例里有好几例都是对应这种情况的，大概思路是抓取内容后暂时不返回，抓取所有分页并且拼接之后一起返回。

试了一天没能解决，大佬有时间帮忙适配下这个网站吗"www.booktxts.com", 跪谢

**Comment by hoothin** [comment]
这个网站是动态加载内容的，你是用 iframe 下载的？

**Comment by mggzhu** [comment]
> 这个网站是动态加载内容的，你是用 iframe 下载的？

是的大佬

**Comment by hoothin** [comment]
之前的版本动态加载是不支持内分页的，现在应该是可以了。
但是这个网站有个特殊的地方，下一章除了内分页还会指向真实的下一章，因此开启分页嗅探的情况下不能实现仅下载部分章节。

**Comment by mggzhu** [comment]
> 之前的版本动态加载是不支持内分页的，现在应该是可以了。 但是这个网站有个特殊的地方，下一章除了内分页还会指向真实的下一章，因此开启分页嗅探的情况下不能实现仅下载部分章节。

是的大佬，我还发现他不分目录<a>中并不是href指向该章地址，而是通过onClick执行一个js函数拼接出来的。大佬有时间的话能够适配下这两个问题。对于前端小白来说，确实不知道如何写规则来弄。

**Comment by hoothin** [comment]
最近暂时没有更多精力，你可以先参照着规则库里的规则试着改改，不行等我有空了给你写一个规则

**Comment by mggzhu** [comment]
> 最近暂时没有更多精力，你可以先参照着规则库里的规则试着改改，不行等我有空了给你写一个规则

感谢大佬，您先忙哈，有时间再说

**Comment by hoothin** [comment]
已經加入規則庫，不過最好是配合永頁機一起用，因爲目錄有頁碼

**Comment by haz1920** [comment]
请问最后你们是怎么解决的呢？？

**Comment by haz1920** [comment]
之前完全没接触过这些，不太搞的懂，点了更新在线规则，但是好像没变化，不知道怎么回事![image](https://github.com/hoothin/UserScripts/assets/97822448/c5dd99e4-9743-47af-80b3-e455e38b1658)
