### ISSUE TITLE
能否增加目录功能

### ISSUE THREAD

**Issue by xiezhengyun** [hoothin/UserScripts#522]
大部分txt版本的小说阅读器。默认是用以下格式分辨目录

===第一章===

===第二章===

不知道下载的小说能否支持这种？或者现有功能就可以？我看了下文档，没尝试出来

**Comment by hoothin** [comment]
下载为markdown之后格式为
```
第一章
===

第二章
===
```
这样。如果想改为你那样的话，可以用 vscode 或者 sublimetext 正则替换 `(.*)\n===$` 为 `===\1===`
