### ISSUE TITLE
请求适配微软新闻

### ISSUE THREAD

**Issue by freedomspiritJohn** [hoothin/UserScripts#523]
**The url of site**
https://news.microsoft.com/source/view-all/

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**
想自动拼接这个页面的新闻，但是又不会写规则，请求大家帮忙。

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Microsoft news",
    "url": "^https?://news\\.microsoft\\.com/",
    "nextLink": "a.next"
}
</pre>
