### ISSUE TITLE
求大佬适配https://www.uaa002.com/novel

### ISSUE THREAD

**Issue by luckylemonade24** [hoothin/UserScripts#524]
https://www.uaa002.com/novel

显示无法获取文本

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/2ddb7cbd-0be9-4fda-aec9-4f9a8411b7b1)
注册可见的章节需要登录账号，注意确认脚本版本是最新的

**Comment by luckylemonade24** [comment]
我懂了，
是要开启“下载前显示章节筛选排序窗口”，
不过iframe这选项在章节排序里实在难以让人想到，
如果在操作说明里标明就好了，
感谢大佬了

**Comment by hoothin** [comment]
是故意藏起来的，可以筛掉一部分不友好的用户
