### ISSUE TITLE
知网高级搜索页面未匹配

### ISSUE THREAD

**Issue by eastsea00** [hoothin/UserScripts#525]
测试配置如下：
{
    "name": "中国知网",
    "url": "^https?://kns\\.cnki\\.net/kns8s/",
    "nextLink": "a#PageNext",
    "pageElement": "body > div.module-main > div.module-wrap-content.wrap-content.is-filter-on",
    "iframeInit": "let doc;let ready=()=>{let fn1=window.BriefExtend.setFullTextState;window.BriefExtend.setFullTextState=()=>{fn1();win.$('#PageNext').attr('data-curPage',window.$('#PageNext').attr('data-curPage'))}; win.BriefParam._getSearchPaperArgModel=(isSearch, cPage)=>{return window.BriefParam._getSearchPaperArgModel(isSearch, (!!cPage ? cPage : win.BriefParam._getCurPage()))};doc.querySelector('#txt_search').value=document.querySelector('#txt_search').value;doc.querySelector('.search-btn').click()};let checkPage=()=>{if(win.document.querySelector('#txt_search')){doc=win.document;ready();}else setTimeout(checkPage,100)};checkPage();",
    "initRun": 0,
    "wait": 100
}
经过80swaitTime后，控制台报错为：Stop as no page when emu
请问下是配置没正确输入还是别的问题

**Comment by eastsea00** [comment]
页面网址如下：https://kns.cnki.net/kns8s/AdvSearch?classid=WD0FTY92

**Comment by hoothin** [comment]
你直接复制过去当然不能用，txt_search 是默认搜索页的，AdvSearch 页没有。你需要自己找到页内所有变量输入框，然后修改 iframeInit ，克隆到下一页
