### ISSUE TITLE
Hello, can you add a simple version note when you update?

### ISSUE THREAD

**Issue by greataolu** [hoothin/UserScripts#526]
Hello, I suggest you add a simple version description when you update.
Because I don't know if there are any new features after the automatic update, I'm curious, and I didn't find it on the details page. And the code comparison is incomprehensible.
Thank you very much!

**Comment by hoothin** [comment]
不好意思，这个是个人项目，工作之外写日志还是饶了我吧。

**Comment by greataolu** [comment]
好的，找到解决办法了，通过把greasyfork的版本对比页面发给moonshotAI，让他解释就好。麻烦您了，感谢您的工作
