### ISSUE TITLE
Unable to fully download image by Picviewer CE+

### ISSUE THREAD

**Issue by Froktime** [hoothin/UserScripts#532]
Some time ago, I reported to you about this website (fuhux.net). the website has changed its image access status.
Sample link: https://api.funhub.net/fhredirect/yn6POWwJf6-rMZ6hiW-Oorc86osYfiAFX-W8-BFQLv4
So the script cannot take the image links fully. 
![ảnh](https://github.com/hoothin/UserScripts/assets/98095197/065955bf-712c-44c6-9b1f-6b31ac7a327c)
- https://static.theshalola.xyz/rimages/n0ldaIqwKUgTbTHCo2jyw2TlhrIjHoCfvefL9qxbPTn4rgFpXbBkNJu7bvzBE8KLOEzoIsQzOil3-36sr22Gahnz8gw-BUiOScLGpr3qI6zYTh0xQskKDV15pJD2kaiT.webp?s=c511417a0b9e8b96826b31089c8ef704

A few days ago, I could download normally. Could this also be due to other causes that I don't know about? They use javascript or something... Hope you will check out the sample link

**Comment by Froktime** [comment]
> Picviewer CE+ is not a cracking tool. If you wish to bypass restrictions set by the website(it's illegal), please consider hiring professional hackers and paying for their services to accomplish the task.

Ok. But this website is **_illegal_**, not legal. Though they're illegal contribution, they are outrageous when creating trying to block downloads.

**Comment by hoothin** [comment]
Nevertheless, I am not a user of this site, and I have no interest in engaging in a game of offense and defense with it. Please understand.
