### ISSUE TITLE
Bing 搜索引擎会自动弹回顶部

### ISSUE THREAD

**Issue by Myzhx1** [hoothin/UserScripts#537]
先拉到页面底下自动翻页，翻个两三页，然后随便点开一个网站，停留一会再回到搜索页面，就会发现bing搜索自己跳回顶部了，好像只有bing，百度没有。而且这个脚本一关掉就没事了，排了半天排查出来

脚本版本  1.9.37.31
网站  cn.bing.com
浏览器  Edge  121.0.2277.112  x64
拓展  油猴脚本  5.0.1
系统  Win11

用的官方自定义规则，没有个人规则，且更新的最新规则。

如果有需要补充的信息或者解决方案请留言，谢谢

**Comment by hoothin** [comment]
#385
