### ISSUE TITLE
下载图片的过程中无法放在后台吗？

### ISSUE THREAD

**Issue by shaoyouvip** [hoothin/UserScripts#550]
您好开发者！感谢您开发此程序非常优秀！感谢您！
我在使用中遇到了一些问题，也就是正在进行下载图片的浏览器的标签页不能挂在后台，挂在后台他就不下载了，不走下载进度。而重新打开标签页后它会恢复进度进行下载，是否是我浏览器设置问题还是，您这个程序必须在前台使用？

**Comment by hoothin** [comment]
我没有写这个功能，应该是你安装的脚本管理器的设置,或者你是在移动端使用的？
