### ISSUE TITLE
请问有没有机会添加下载时转换格式的功能？(webp -> gif; avif -> png/jpg)

### ISSUE THREAD

**Issue by HeisensOppings** [hoothin/UserScripts#553]
在上网冲浪的过程中，总会遇到想要保存的图片或者动图，但是网页的下载的默认图片格式时avif，动图是webp，很多图片查看器不支持，只能用浏览器查看；

虽然有很多解决方法，例如转换网站等，意味着下载的图片都要转换一遍，就想着能否下载图片的时候可以顺便转换为常用的格式例如gif png/jpg等

**Comment by hoothin** [comment]
因为 webp 可以是动图，也可以是静态图片。因此在下载时转换固定格式是不合适的。
