### ISSUE TITLE
关于鼠标双击切换启用和暂停的功能,希望可以更改!!!

### ISSUE THREAD

**Issue by wwwxxx0402** [hoothin/UserScripts#557]
**Is your feature request related to a problem? Please describe.**
希望能够更换快捷操作,而不是必须要鼠标双击.
当我在某些页面需要暂时禁用翻页时,我使用定义的快捷键(例如ctrl)+鼠标双击,我希望我能快速的暂时禁用翻页功能,但是更加常见的是我通过鼠标双击选择了某一块文本(尽管我的鼠标指针已经放在了网站页面的空白处)

**Describe the solution you'd like**
通过其他的快捷键操作触发暂时的禁用和启用

**Describe alternatives you've considered**
可自定义的其他按键 例如 ctrl + shift + i 等
**Additional context**
鼠标双击选择元素,可以在很多时候剩下很多功夫.希望大佬能增加以下快捷键的自定义功能

**Comment by hoothin** [comment]
配置快捷键之后取消勾选双击暂停就行了

**Comment by hoothin** [comment]
有以下几种模式
1. 没配置快捷键，没绑定功能键。这是默认模式
2. 没配置快捷键，但绑定了功能键。此时双击失效，必须按住功能键双击
3. 配置了快捷键，绑定了功能键。此时双击和快捷键均可生效
4. 配置了快捷键，绑定了功能键，且取消勾选了双击暂停，此时仅快捷键生效
