### ISSUE TITLE
Support needed for Full-size url

### ISSUE THREAD

**Issue by Omledd** [hoothin/UserScripts#559]
Can you help with the custom full-size code? 

**The url of an example full-size picture**
(https://ampworld.org/include/modelphotos.php?model=Jasmina01&file=02980653453339806&size=full)

** The url Picviewer uses without any custom full-size code:
(https://ampworld.org/include/modelphotos.php?model=Jasmina01&file=02980653453339806)

**Describe the result you'd like with the rule**
I am unable to get it to work. I need to append "&size=full" to the picture url

**Custom rule you've tried**
[
  {
    name: "Ampworld",
    url: /^https?:\/\/www\.ampworld\.org\//
    r: &file=\d
    s: &file=\d+&size=full
  }
]

Many thanks!

**Comment by hoothin** [comment]
The regular expression needs to be replaced like this.
```
{
name: "Ampworld",
url: /^https?:\/\/www\.ampworld\.org\//,
r: /(&file=\d+)/,
s: "$1&size=full"
}
```
