### ISSUE TITLE
下载功能时好时坏

### ISSUE THREAD

**Issue by w774431242** [hoothin/UserScripts#560]
**Describe the bug**
“开始下载小说”功能有时候点击无反应 或 一闪而过
“自定义规则下载”功能时好时坏。

**To Reproduce**
在“https://www.44yydstxt426.com/   ”     这个网站，打开一本书的目录页面。
1.首先使用“[📕東北人小説網](https://www.dbrxs.org/86/86323/)”网站规则，正常情况可以下载，内页也有。
2.“自定义规则下载”功能失效，使用“开始下载小说”功能正常下载，但大多数生效于几十章节以上的书。

环境：
WIN10 Chrome
**Additional context**
qwq

**Comment by hoothin** [comment]
说明规则不匹配，你可以打开控制台看看有没有报错信息，或者去群里问问其他会写规则的朋友。以后都不会解决小说下载器的适配请求了，否则站长也要来找我麻烦了。
