### ISSUE TITLE
CodePen

### ISSUE THREAD

**Issue by Auditormadness9** [hoothin/UserScripts#562]
**The url of site**
https://codepen.io/search/pens?q=steam&depth=title_desc_tags

**Is your request related to a problem? Please describe.**
Just for comfort.

**Describe the result you'd like with the rule**
Load all results in one page instead of having to click Next each time.

**Custom rule you've tried**
```js
{
    "name": "CodePen Search",
    "url": "^https?://codepen\\.io/search/",
    "example": "https://codepen.io/search/pens?q=steam&depth=title_desc_tags",
    "pageElement": "#react-page > div.PageLayout-module_root-rNerP > main.PageLayout-module_main-FuM10 > div.Search_root-9UPWB > div.width-wrapper > div > div.item-grid.ContentGrid-module_root-rDB6N",
    "nextLink": "#react-page > div.PageLayout-module_root-rNerP > main.PageLayout-module_main-FuM10 > div.Search_root-9UPWB > div.width-wrapper > div > nav.Pagination-module_pagination-3Nbew > button"
}
```

**Additional context**
Thanks a lot in advance 🙏🏼🫡

**Comment by Auditormadness9** [comment]
Any clue?

**Comment by hoothin** [comment]
Sorry but I did not find any issue.
![image](https://github.com/hoothin/UserScripts/assets/5361213/5d7faa7b-0b24-4a28-9127-354d1bab4f5c)

**Comment by hoothin** [comment]
Have you tried after deleting your custom rule?

**Comment by Auditormadness9** [comment]
> Have you tried after deleting your custom rule?

Yes, still no


https://github.com/hoothin/UserScripts/assets/71278545/ba1444c3-aacc-4459-8b8c-6db42ba61f36

**Comment by hoothin** [comment]
There doesn't seem to be any problem on my end. Could you please provide your console log for me to review?

**Comment by Auditormadness9** [comment]
> There doesn't seem to be any problem on my end. Could you please provide your console log for me to review?

![image](https://github.com/hoothin/UserScripts/assets/71278545/50c4facf-f527-4705-80ea-1a24238b54bd)

I refreshed and it worked in a sense of paginating to the next page, however the tiles don't load.

**Comment by hoothin** [comment]
try this rule
<pre name="pagetual">
{
    "name": "CodePen Search",
    "url": "^https?://codepen\\.io/search/",
    "example": "https://codepen.io/search/pens?q=steam&depth=title_desc_tags",
    "waitElement": "![class*=ContentGridItemLoading]",
    "pageElement": ".item-grid>article"
}
</pre>

**Comment by Auditormadness9** [comment]
perfect 👍🏼

**Comment by Auditormadness9** [comment]
perfect 👍🏼
