### ISSUE TITLE
Request Pagetual: tokopedia.com

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#566]
**The url of site**
[Tokopedia
](https://www.tokopedia.com/search?navsource=&ob=3&origin_filter=sort_price&pmin=44000&srp_component_id=04.06.00.00&srp_page_id=&srp_page_title=&st=&q=tupperware%202%20liter)

**Describe the result you'd like with the rule**
scroll to load next page

**Additional context**
![image](https://github.com/hoothin/UserScripts/assets/19517680/d9db43e7-56d1-4c39-ad5c-5429df5a6b94)

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Tokopedia",
    "url": "^https?://www\\.tokopedia\\.com/",
    "nextLink": "[aria-label='Laman berikutnya']",
    "pageElement": "[data-testid='divSRPContentProducts']",
    "waitElement": "!.IOLazyloading"
}
</pre>

**Comment by 3xploiton3** [comment]
different page doesnt work

https://www.tokopedia.com/find/car-charger

![image](https://github.com/hoothin/UserScripts/assets/19517680/90d34887-26c4-4a64-85fe-d6a2bdf8192b)

**Comment by hoothin** [comment]
<pre name="pagetual">
  {
    "name": "Tokopedia",
    "url": "^https?://www\\.tokopedia\\.com/",
    "nextLink": "[aria-label='Laman berikutnya']",
    "pageElement": "[data-testid='divSRPContentProducts'],[data-testid='cntrFindProductsResult']",
    "waitElement": "!.IOLazyloading,[data-testid='divLazyFindProduct'],[data-testid='divProductPlaceholder']",
    "action": 3
  }
</pre>
Splitting it into two separate rules might be a better approach. Feel free to edit and optimize it yourself.
