### ISSUE TITLE
vsco.co

### ISSUE THREAD

**Issue by https433** [hoothin/UserScripts#569]
**vsco**

https://vsco.co/(user)/collection/1

Any user with a repost collection

**Custom rule you've tried**
```
{
"name": "VSCO",
"url": "^https://vsco.com/*/collection/*",
"pageElement": "id("root")/grain-theme[1]/div[@class="css-1n2jhjr e1lxikmc0"]/div[@class="css-1fod2s4 e1lxikmc0"]/main[@class="main css-ayxofz e19mt3zn0"]/div[@class="css-87mlbn e1c94cdo0"]/div[@class="css-lnnxvk e1l3i6oy1"]/ul[@class="css-r147me e1lxikmc0"]/li[@class="css-1xij1vs esu64ia0"]",
"nextLink": "id("root")/grain-theme[1]/div[@class="css-1n2jhjr e1lxikmc0"]/div[@class="css-1fod2s4 e1lxikmc0"]/main[@class="main css-ayxofz e19mt3zn0"]/div[@class="css-87mlbn e1c94cdo0"]/div[@class="css-lnnxvk e1l3i6oy1"]/div[@class=""]/a[@class="css-1wi2s0h"]",
"action": 1,
"pageElementCss": "display:none"
}
```

**Comment by hoothin** [comment]
Utilize [pagePre](https://pagetual.hoothin.com/rules/pagePre.html) to analyze the data and create elements, and then employ pageElement to extract the elements you have created, for example `"pagePre": "let data = response.match(/window\\.__PRELOADED_STATE__ = (.*?)<\\/script>/)[1]; eval('data='+data); console.debug(data.entities.images);"`. The data.entities.images contains all the images on the page, you can createElement on your way.

Alternatively, forget pagePre, you can simply utilize the 'Ignore X-Frame Headers' extension to bypass CORS.
