### ISSUE TITLE
求大佬适配33.agilestudio.cn

### ISSUE THREAD

**Issue by szczebiak** [hoothin/UserScripts#570]
**The url of site**
The example urls of site. Do not paste only domain without pathname.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "33台词 - 通过台词找影片素材",
    "url": "^https?://33\\.agilestudio\\.cn/\\?subtitleKeyword",
    "waitElement": ".el-pager>li.active"
}
</pre>
