### ISSUE TITLE
pagetual: pdki-indonesia.dgip.go.id

### ISSUE THREAD

**Issue by 3xploiton3** [hoothin/UserScripts#571]
**The url of site**
[pdki-indonesia.dgip.go.id](https://pdki-indonesia.dgip.go.id/search?type=trademark&keyword=madu+nahl&page=1&showFilter=true)

**Is your request related to a problem? Please describe.**
please help make rule scroll down to next page,

**SS**
![image](https://github.com/hoothin/UserScripts/assets/19517680/b9152ce3-2f60-4b5a-a882-76b804a3a7c3)

**Comment by hoothin** [comment]
Try `"waitElement": ".justify-end .ant-pagination-next>button"`

**Comment by 3xploiton3** [comment]
working, thanks

>   "name": "pdki-indonesia.dgip.go.id",
    "url": "^https?://pdki-indonesia\\.dgip\\.go\\.id/",
    "waitElement": ".justify-end .ant-pagination-next>button",
    "nextLink": "#__next > div.relative > div.min-h-screen.pb-12 > div.flex.flex-col.items-center.justify-center.w-full.space-y-4 > div.flex.w-full.px-5 > div.w-full.space-y-6 > div.justify-end.hidden > ul.ant-pagination > li.ant-pagination-next > button.ant-pagination-item-link"

![image](https://github.com/hoothin/UserScripts/assets/19517680/b1ac2261-1103-4a51-ae4c-cfe2414908f6)
