### ISSUE TITLE
能否新增自动滚动网页到底后自动切换到下一标签页继续自动滚动翻页的功能？

### ISSUE THREAD

**Issue by EvanVV** [hoothin/UserScripts#577]
**Is your feature request related to a problem? Please describe.**
在浏览一些网站时，网页并没有翻页的功能按钮，一个页面就是一个主题，如果需要同时浏览多个主题的话，就需要打开多个浏览器标签，能否在自动滚动的功能基础上，添加网页滚动到底后自动切换到下一个浏览器标签继续自动向下滚动的功能？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hoothin** [comment]
脚本只能影响当前页面或当前页面打开的窗口，没法切换标签页。
