### ISSUE TITLE
我好像发现bug了。

### ISSUE THREAD

**Issue by gjd898** [hoothin/UserScripts#578]
安装的时候显示要安装两个项目，我仅仅安装了其中一个。

现在出现的问题就是不管是否重新安装两个项目，是否关闭、删除脚本，甚至关闭油猴都无法禁用该东方脚本。

求解决方法。

**Comment by hoothin** [comment]
检查你的 adguard 或者类似的去广告软件，在软件里面找到脚本管理，然后删除脚本。
