### ISSUE TITLE
69小说网请求追加

### ISSUE THREAD

**Issue by lyonLeeLPL** [hoothin/UserScripts#579]
**Describe the bug**

**To Reproduce**
1. Go to 'https://m.69xsw.com/book/7333/'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]

**Smartphone (please complete the following information):**

**Additional context**

这种网站时，下拉才会触发js，加载下一个章节，反爬手段挺高。

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/987f979f-fe61-4361-b77e-b3dbf13892fd)
没发现问题
