### ISSUE TITLE
在telegram中无法正常使用

### ISSUE THREAD

**Issue by GHVIP0** [hoothin/UserScripts#582]
**Describe the bug**
telegram中无法正常使用

**To Reproduce**
1. Go to '[...](https://web.telegram.org/)'
2. Click on '查看原图、放大镜、下载图片等'
3. See error

**Expected behavior**
修复使用，可以正常查看并下载

**Screenshots**
当查看原图时
![image](https://github.com/hoothin/UserScripts/assets/169181867/517724d4-fa51-491e-b40b-78f8ffe78da8)
下载图片时无反应

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [Edge]
 - Version [24.0.2478.80 (正式版本) (64 位)]

**Comment by hoothin** [comment]
看起来是 edge 的问题，chrome 没问题，已经修复了。
