### ISSUE TITLE
Picviewer的图库预读功能似乎无法正确适配Pixiv

### ISSUE THREAD

**Issue by pukamoe** [hoothin/UserScripts#583]
**Describe the bug**
Pixiv的预读功能似乎没有办法正常使用，每次点下一个图片的时候，还是有概率会重新加载，导致没那么流畅。怀疑跟原图的后缀有关系，原图的后缀可能是jpg或者是png，不知道对预载有没有影响。

**To Reproduce**
随便打开Pixiv页面，打开图库，等预读加载完成，然后throttling设置断网，向后翻页，有概率图片正常从缓存中读取，也有概率图片无法显示。

**Expected behavior**
所有图片都从缓存中获取。

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome
 - Version 124

**Comment by hoothin** [comment]
因为我为了省事，pixiv 获取大图用的是遍历 jpg 与 png 的方式，jpg 加载失败就获取 png ，预读的时候如果遇到原图是 png 的图片，预读的就是错误对象。
可以换用 xhr 规则来写，但是要多一次网络请求，打开图库的时候发送请求过多容易被 pixiv 封号吧。

**Comment by pukamoe** [comment]
> 因为我为了省事，pixiv 获取大图用的是遍历 jpg 与 png 的方式，jpg 加载失败就获取 png ，预读的时候如果遇到原图是 png 的图片，预读的就是错误对象。 可以换用 xhr 规则来写，但是要多一次网络请求，打开图库的时候发送请求过多容易被 pixiv 封号吧。

Ok如果是这个原因的话，我在想是不是可以用p1200这个大图，虽然不是原图，但是分辨率其实也够用了。我看了下似乎都是.jpg结尾的，例如
https://i.pximg.net/img-master/img/2024/04/12/08/06/22/117761778_p0_master1200.jpg
如果要修改这个的话，是不是改这里的s呀？
![image](https://github.com/hoothin/UserScripts/assets/83722037/dbd25cd8-8ac3-4624-9ed8-503d9d9c2a94)

**Comment by hoothin** [comment]
是的，加到自定义规则里就行了，形如
```
[
    {
        name: "Pixiv",
        url: /pixiv\.net|pximg\.net/,
        src: /pximg\.net\/c\/\d+x\d+/i,
        r: /pximg\.net\/c\/\d+x\d+.*\/img\/(.*)_.*$/i,
        s: "pximg.net/img-master/img/$1_master1200.jpg"
    }
]
```
