### ISSUE TITLE
手机端图片较多时打包后浏览器崩溃

### ISSUE THREAD

**Issue by zhbzxf** [hoothin/UserScripts#591]
我使用X浏览器+picviewer CE+ 下载网页图片，发现图片较多时（300张以上）批量下载打包成zip后浏览器崩溃，无法保存，请问有没有办法解决？

个人猜测是图库界面显示的图片太多耗光内存，如果图库界面可以只显示文件列表或许能解决？

设备 红米k70 12+256

感谢

**Comment by hoothin** [comment]
可以用复制大图地址功能，然后用迅雷或者百度网盘下载

**Comment by zhbzxf** [comment]
> 可以用复制大图地址功能，然后用迅雷或者百度网盘下载

能否增加“导出至txt”功能？直接复制可能有长度限制

另外，脚本很好用，但在手机上UI似乎有点问题，如果可能，希望优化一下，只是建议


感谢作者，解决了大问题

**Comment by hoothin** [comment]
加上了，点击复制大图地址后，左上角会显示一个下载图标
