### ISSUE TITLE
vip视频破解怎么从gf下架了。。而且好像怎么都不能用了

### ISSUE THREAD

**Issue by SetoKaiba** [hoothin/UserScripts#6]
vip视频破解怎么从gf下架了。。而且好像怎么都不能用了

**Comment by hoothin** [comment]
我删掉了，因为被人抄袭生气了，而且本来就没啥技术含量，安装量却太吓人了

**Comment by SetoKaiba** [comment]
那github这边还更新么- -、这么好的一个脚本没了太可惜了呀。。
