### ISSUE TITLE
感觉应该是b站前端的问题，东方永动机中搜索页面点击一下空白地方拼接的页面就没了

### ISSUE THREAD

**Issue by freedomspiritJohn** [hoothin/UserScripts#602]
![PixPin_2024-06-02_16-34-39](https://github.com/hoothin/UserScripts/assets/129288685/43454d94-95f7-4d3b-9d73-a2bed74147eb)

翻页之后点击空白地方就没办法拼接了，请问怎么解决呀

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "bilibili search",
    "action": 1,
    "url": "^https://search\\.bilibili\\.com",
    "pageElement": "ul>li.video-item,div.video-list.row>*",
    "sandbox": false,
    "listenUrlChange": false
}
</pre>
因为b站点击后网址就变了，用这个规则忽略网址变化就行了
