### ISSUE TITLE
Request Pagetual support for www.ku138.cc

### ISSUE THREAD

**Issue by Ruizhi-S** [hoothin/UserScripts#611]
**The url of site**
https://www.ku138.cc/b/9/51119.html
The example urls of site. Do not paste only domain without pathname.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
The site is not reachable.
