### ISSUE TITLE
自动刷新页面和自动滚动失效

### ISSUE THREAD

**Issue by XiaoYin320** [hoothin/UserScripts#615]
1在e-hentai使用时有时候会自动刷新页面，回到顶端。
打开某一漫画，向下翻页，有时候会自动刷新页面，然后就回到顶部。

2还有自动滚动功能，我试了下，缩放70%以下的时候，会停止自动滚动。

Desktop (please complete the following information):**
插件版本：1.9.37.51

 - OS: 版本	
Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎7/‎20
操作系统内部版本	19045.4412
体验	Windows Feature Experience Pack 1000.19056.1000.0

 - Browser  edge
 - Version 125.0.2535.85 (正式版本) (64 位)

**Comment by hoothin** [comment]
有具体的 url 吗？我自己也有用exhentai，没遇到过这样的问题，可以的话重现步骤请再详细一些。

**Comment by XiaoYin320** [comment]
> 有具体的 url 吗？我自己也有用exhentai，没遇到过这样的问题，可以的话重现步骤请再详细一些。

我又试了下，当图片加载失败的时候，会发生自动刷新页面

**Comment by hoothin** [comment]
多谢报错，的确是的，ehentai 的 img 里带了一句 `onerror="this.onerror=null; nl('4976-477152')"` 会自动刷新，我待会重写个规则

**Comment by XiaoYin320** [comment]
> 多谢报错，的确是的，ehentai 的 img 里带了一句 `onerror="this.onerror=null; nl('4976-477152')"` 会自动刷新，我待会重写个规则
好的，麻烦作者了。
还有自动滚动失效的问题........

**Comment by hoothin** [comment]
我这边尝试缩放，没有发现自动滚动失效，还有其他步骤吗？

**Comment by XiaoYin320** [comment]
> 我这边尝试缩放，没有发现自动滚动失效，还有其他步骤吗？

任意页面，比如百度，缩放为70%以下，就不会再自动滚动了.......

**Comment by XiaoYin320** [comment]
![111111111111](https://github.com/hoothin/UserScripts/assets/97751884/d0e10024-9e12-4177-93b9-cbd889835c09)
![2222222222222222](https://github.com/hoothin/UserScripts/assets/97751884/c1b4192e-447d-4ab4-b096-65e3fd28c588)

**Comment by XiaoYin320** [comment]
> ![111111111111](https://private-user-images.githubusercontent.com/97751884/337596270-d0e10024-9e12-4177-93b9-cbd889835c09.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTEzNzAsIm5iZiI6MTcxNzc1MTA3MCwicGF0aCI6Ii85Nzc1MTg4NC8zMzc1OTYyNzAtZDBlMTAwMjQtOWUxMi00MTc3LTkzYjktY2JkODg5ODM1YzA5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA5MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MjVlZWE1NGI2MzA3Y2Q5MTQ5YWVhMjMwNDZjODJlYTEwZjIyZWQ1MWMzOGM5MDI1MDIyODc4MTY0MzM0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JKlHOCNU7ASdoCWlLLncIRIGU17fEai5NwC8DhailMk) ![2222222222222222](https://private-user-images.githubusercontent.com/97751884/337596344-c1b4192e-447d-4ab4-b096-65e3fd28c588.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTEzNzAsIm5iZiI6MTcxNzc1MTA3MCwicGF0aCI6Ii85Nzc1MTg4NC8zMzc1OTYzNDQtYzFiNDE5MmUtNDQ3ZC00YWI0LWIwOTYtNjVlM2ZkMjhjNTg4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA5MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjY3ZDgwOGJlNmZmYmRjZjIzOGY0ZTM2Y2FjYmZkNDNmOTZlMDdmNWRlOTQxMGFjYmQ1N2VmODljODYyNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FWHb1EYUmtR7h9L6a3UyssJfcwIiEuwmg-GYsQA8MKo)

![33333333333333](https://github.com/hoothin/UserScripts/assets/97751884/7e61b90c-b2c2-42dd-8b02-9222d5c4efd6)

**Comment by hoothin** [comment]
看起来是 edge 的 bug，chrome 没有问题，我试试看能不能解决

**Comment by XiaoYin320** [comment]
> 看起来是 edge 的 bug，chrome 没有问题，我试试看能不能解决

好的，麻烦作者了。

**Comment by hoothin** [comment]
已经更新 1.9.37.52 ，你试试看有没有解决

**Comment by XiaoYin320** [comment]
> 已经更新 1.9.37.52 ，你试试看有没有解决

缩放问题解决了，自动刷新页面不一定能遇到，我一会再试试。

**Comment by hoothin** [comment]
规则我是更新在在线规则库中的，所以你需要手动点击更新规则

**Comment by XiaoYin320** [comment]
> onerror
我更新了规则库，还是会自动刷新，和之前情况是一样的，加载失败就会刷新

**Comment by XiaoYin320** [comment]
> > onerror
> > 我更新了规则库，还是会自动刷新，和之前情况是一样的，加载失败就会刷新
> 
> [https://ghproxy.com/https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json[rules](https://ghproxy.com/https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json%5Brules): 751]https://ghproxy.com/https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json[rules: 751]
> 
> [http://wedata.net/databases/AutoPagerize/items_all.json[rules](http://wedata.net/databases/AutoPagerize/items_all.json%5Brules): 3816]http://wedata.net/databases/AutoPagerize/items_all.json[规则：3816]

地址栏多了内容:
?nl=44895-477157&nl=44895-477157

**Comment by hoothin** [comment]
#616 
现在应该可以了，你重新更新试试。nl=44895-477157 是 exhentai 自己在刷新时添加的，应该是为了忽略缓存吧

**Comment by XiaoYin320** [comment]
> #616 现在应该可以了，你重新更新试试。nl=44895-477157 是 exhentai 自己在刷新时添加的，应该是为了忽略缓存吧

现在【绿色的裂开的小图标】出现的时候，不会自动刷新页面了。
现在是出现之后就自己消失了，过一会，又会出现，然后又会消失...重复这样循环。

**Comment by hoothin** [comment]
是的，我把原先它自帶的加载失败刷新页面改成了加载失败刷新图片，如果你不想这样的话可以导入这个自定义规则，这个规则会直接把这个功能置空。
<pre name="pagetual">
{
    "name": "E-Hentai",
    "author": "skofkyo",
    "example": "http://e-hentai.org/，https://exhentai.org/",
    "url": "^https?://(e-hentai|exhentai)\\.org/",
    "nextLink": "//table[@class='ptt']//a[string()='>'] | id('next') | id('unext')",
    "pageElement": ".itg>div,.itg>tbody>tr:not(:first-of-type),.gl1t, #gdt>div:not(.c), #img",
    "replaceElement": ".ptt,.ptb,.sn,.searchnav",
    "css": "#img {max-width: 100% !important;height: auto !important;min-height: 400px;}",
    "pageInit": "doc.getElementById('img').setAttribute('onerror','');"
}
</pre>

**Comment by XiaoYin320** [comment]
> 是的，我把原先它自帶的加载失败刷新页面改成了加载失败刷新图片，如果你不想这样的话可以导入这个自定义规则，这个规则会直接把这个功能置空。
> 
> {
>     "name": "E-Hentai",
>     "author": "skofkyo",
>     "example": "http://e-hentai.org/，https://exhentai.org/",
>     "url": "^https?://(e-hentai|exhentai)\\.org/",
>     "nextLink": "//table[@class='ptt']//a[string()='>'] | id('next') | id('unext')",
>     "pageElement": ".itg>div,.itg>tbody>tr:not(:first-of-type),.gl1t, #gdt>div:not(.c), #img",
>     "replaceElement": ".ptt,.ptb,.sn,.searchnav",
>     "css": "#img {max-width: 100% !important;height: auto !important;min-height: 400px;}",
>     "pageInit": "doc.getElementById('img').setAttribute('onerror','');"
> }
> 导入

好的，感谢作者了！！！
