### ISSUE TITLE
东方永页机 (Pagetual) “failed to update rules”

### ISSUE THREAD

**Issue by Heimiaomiao** [hoothin/UserScripts#616]
**Describe the bug**
脚本：东方永页机 (Pagetual)
不能更新规则库，能正常访问规则库的链接里的内容，但点击更新后，规则库数量还是0

**To Reproduce**
1. 安装脚本
2. 脚本自动更新基础规则
3. 访问 https://pagetual.hoothin.com/rule.html 更新规则库
4. 不能更新规则库（始终为0）

**Expected behavior**

**Screenshots**
![1 1](https://github.com/hoothin/UserScripts/assets/25890429/53db67d6-49ce-4b8f-9765-2e7a50d5212a)
![2](https://github.com/hoothin/UserScripts/assets/25890429/bed6f3c1-890a-41e4-b13e-bb582edd9ccd)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2/11 24H2
 - Browser: chrome, Firefox
 - Version: 125.0.6422.142, 126.0.1

**Additional context**
尝试关闭代理，全局代理，更换浏览器，重装浏览器（未安装其他扩展），都是这个结果。

**Comment by hoothin** [comment]
你打开控制台看看错误类型是不是 timeout？

**Comment by Heimiaomiao** [comment]
`【Pagetual v.1.9.37.52】 Error json: SyntaxError: JSON.parse: expected double-quoted property name at line 8 column 1 of the JSON data
    onload moz-extension://ca70500f-b11e-422f-a9a5-35f421b3f06f/userscripts/Pagetual.user.js?id=4555d162-af3a-4986-aa8a-6ba20e90ec7a:1330
    wt https://pagetual.hoothin.com/rule.html#google_vignette:9
    i https://pagetual.hoothin.com/rule.html#google_vignette:37
    wt https://pagetual.hoothin.com/rule.html#google_vignette:9
    r https://pagetual.hoothin.com/rule.html#google_vignette:24
    ko https://pagetual.hoothin.com/rule.html#google_vignette:25
    v https://pagetual.hoothin.com/rule.html#google_vignette:78
    v https://pagetual.hoothin.com/rule.html#google_vignette:78
    wt https://pagetual.hoothin.com/rule.html#google_vignette:9
    f https://pagetual.hoothin.com/rule.html#google_vignette:77
    l https://pagetual.hoothin.com/rule.html#google_vignette:79
    send https://pagetual.hoothin.com/rule.html#google_vignette:80
    Wn https://pagetual.hoothin.com/rule.html#google_vignette:17
    send https://pagetual.hoothin.com/rule.html#google_vignette:79
    ko https://pagetual.hoothin.com/rule.html#google_vignette:25
    Ao https://pagetual.hoothin.com/rule.html#google_vignette:25
    i https://pagetual.hoothin.com/rule.html#google_vignette:37
    f https://pagetual.hoothin.com/rule.html#google_vignette:46
    f https://pagetual.hoothin.com/rule.html#google_vignette:47
    q https://pagetual.hoothin.com/rule.html#google_vignette:45
    f https://pagetual.hoothin.com/rule.html#google_vignette:45
    message https://pagetual.hoothin.com/rule.html#google_vignette:20
    wt https://pagetual.hoothin.com/rule.html#google_vignette:9
    t https://pagetual.hoothin.com/rule.html#google_vignette:9
    message https://pagetual.hoothin.com/rule.html#google_vignette:20
    message https://pagetual.hoothin.com/rule.html#google_vignette:21
    <anonymous> https://pagetual.hoothin.com/rule.html#google_vignette:83
    v https://pagetual.hoothin.com/rule.html#google_vignette:78`

![Uploading 3.png…]()

**Comment by hoothin** [comment]
感谢报错，是因为有用户提交的规则多了一个逗号，现在已经修复了，我试试看加个校验

**Comment by Heimiaomiao** [comment]
> 感谢报错，是因为有用户提交的规则多了一个逗号，现在已经修复了，我试试看加个校验

谢谢，已解决
