### ISSUE TITLE
[Picviewer CE+]关于推特大图规则的建议

### ISSUE THREAD

**Issue by Auroradanica** [hoothin/UserScripts#618]
现在脚本的规则似乎是直接将连接中的format=jpg&name=large改为format=jpg&name=orig,但是相对jpg格式，png格式会不会更加好一点，可否改为format=png&name=large(尝试过name=orig似乎不可以），多谢大佬了

**Comment by hoothin** [comment]
感谢建议，但是我不确定是否所有`format=png&name=large`都有返回值。目前后缀是保持原样的，原先是 jpg 大图就是 jpg，原先是 png 大图就是 png。
如果你依旧想要改成 png，可以点击下面的代码导入自定义规则，记得点击确定来保存。
```
{
    "name": "twitter",
    "url": "^https://(www\\.)?(x|twitter)\\.com|pbs\\.twimg\\.com",
    "description": [
        "./..",
        "aria-label"
    ],
    "r": "/format=\\w+&name=\\w+/i",
    "s": "format=png&name=large"
}
```

**Comment by Auroradanica** [comment]
非常感谢大佬!

**Comment by Auroradanica** [comment]
新的问题：
下载当前所有时为什么会卡在最后一张一直不动，能否加入aria2下载或所以下载链接导出以方便多线程下载器调用下载。感谢！
![image](https://github.com/hoothin/UserScripts/assets/87475428/7a832645-783d-4446-ac09-1cc9144c2ae6)

**Comment by hoothin** [comment]
点击菜单中的`复制显示大图`就能自动复制所有地址了

**Comment by Auroradanica** [comment]
那是否可以加入一键发送到aria2功能呢

**Comment by hoothin** [comment]
可以，我忙完手头的事就加一下。

**Comment by hoothin** [comment]
已經加上了，打開設置添加服務器和密鑰。然後在圖庫裏寄送至 aria2 即可
