### ISSUE TITLE
建议留下“相关搜索”

### ISSUE THREAD

**Issue by draftman9** [hoothin/UserScripts#62]
首先感谢您开发出“东方永页机”这样便利的脚本。
其次我想对该脚本的功能提一个建议：有时我搜索的关键词并非有利于我找到想要的信息，所以在搜索页面（通常是第一页）下方的“相关搜索”对我来说是很有帮助的，我希望可以固定“相关搜索”的位置，而不是将它移到末尾。
在这一点上，duckduckgo做的相当好。但在google时“相关搜索”就被移至末尾了。希望您能考虑加入该功能。🙂
![2022-02-12_150902](https://user-images.githubusercontent.com/99490289/153701472-74a4103b-613d-43ca-abc3-6e75e324585e.png)

![2022-02-12_144922](https://user-images.githubusercontent.com/99490289/153701467-9e21c34d-686f-40b5-bb52-1cb318037a62.png)
。

**Comment by hoothin** [comment]
<pre>
  {
    "name":"Google Search",
    "action":1,
    "nextLink":"id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
    "pageElement":"id('rso')/div|id('center_col')/style[contains(.,'relative')]|id('search')/div/div/style[1]|id('bres')",
    "type":0,
    "url":"^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)"
  }</pre>
粘贴至自定义规则即可。建议学一下自定义规则，这样再有类似需求可自行修改规则。

**Comment by hoothin** [comment]
注意要粘贴到[]“中括号”内

**Comment by hoothin** [comment]
另外最好是保持 https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json 优先级在 wedata 之前。错乱是因为匹配到了 wedata 的规则
