### ISSUE TITLE
Request Pagetual support for www.pixiv.net

### ISSUE THREAD

**Issue by Anan6024** [hoothin/UserScripts#624]
**The url of site**

The example urls of site. Do not paste only domain without pathname.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
Make sure you have imported online rules.

**Comment by Doofy420** [comment]
I've imported the rules and it doesn't work on pixiv. It works on other sites though. It used to work until I upgraded to the latest version.

**Comment by hoothin** [comment]
![image](https://github.com/hoothin/UserScripts/assets/5361213/06d8b23b-600c-4e39-ae37-c1587e68ce80)

I haven't found any issues. Please confirm that the site is not blocked and the rules have been correctly imported.

**Comment by Doofy420** [comment]
Yes, I've imported from `https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json`
It works on every booru site, kemono, e-h, ehx, etc. The only site it won't work on is pixiv. I've tried a different browser and still the same.

**Comment by Doofy420** [comment]
Yes, I've imported from https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json
It works on every booru site, kemono, e-h, ehx, etc. The only site it won't work on is pixiv. I've tried a different browser and still the same.

Tested on the latest versions of tampermonkey on both firefox 127, and chrome 126, same results on both browsers.

**Comment by hoothin** [comment]
Ah, it seems we may be referring to different URLs. Could you please provide the specific URL you're working with so I can better assist you?

**Comment by Doofy420** [comment]
Sorry, this slipped my mind. I noticed that it works for this page
`https://www.pixiv.net/en/tags/blue%20archive/artworks?s_mode=s_tag`

But not for any artist illustration page such as this one
https://www.pixiv.net/en/users/860868

I have tried different browsers and have not messed with any kind of exclusion rules at all. It works on other sites just fine.
