### ISSUE TITLE
Request Pagetual support for independent.academia.edu

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [hoothin/UserScripts#626]
**The url of site**
https://independent.academia.edu/search?q=balls

**Is your request related to a problem? Please describe.**
Pagination on academia.edu's search page doesn't work

**Describe the result you'd like with the rule**
Page go brrrrrrrrr

**Custom rule you've tried**
Tried selecting the search results body + the next button as iframe, dynamic, etc. - didn't work

**Additional context**
I am not the only githubber who has ever had his jaw wired shut by some unknown faceless entity

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Academia.edu",
    "url": "^https?://independent\\.academia\\.edu/",
    "example": "https://independent.academia.edu/search?q=balls",
    "nextLink": "//button[text()=\"Next\"]",
    "waitElement": ".js-search-results-container",
    "action": 1
}
</pre>

**Comment by iFUCKINGHATEcomputers** [comment]
Awesome
