### ISSUE TITLE
div覆盖了所有元素，无法点击

### ISSUE THREAD

**Issue by liaanj** [hoothin/UserScripts#63]
![屏幕截图 2022-02-13 154525](https://user-images.githubusercontent.com/98246557/153744361-ee499aef-1769-47df-91e1-b0d2eab44cbf.png)
![屏幕截图 2022-02-13 153933](https://user-images.githubusercontent.com/98246557/153744362-dade0295-853d-4f61-8f50-871885ed2ec0.png)

**Comment by hoothin** [comment]
你可以尝试下把[pagetualRules.json](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json)的优先级提到wedata之前，然后热更新一下，看看有没有解决

**Comment by liaanj** [comment]
![屏幕截图 2022-02-13 162843](https://user-images.githubusercontent.com/98246557/153745247-be0b9e88-6765-4cca-88f2-f1ecee74108e.png)
还有如何提优先级啊……我不是很明白

**Comment by hoothin** [comment]
你这个是自动规则，看起来是规则都没有下载，你需要热更新一下，在配置页点“更新于xxx”就行。优先级在配置页点上下箭头保存就行

**Comment by liaanj** [comment]
可以了，谢谢！
