### ISSUE TITLE
Request Pagetual support for www.xbqgg.com

### ISSUE THREAD

**Issue by LBY05** [hoothin/UserScripts#631]
**The url of site**

The example urls of site. ⚠Do not paste only domain without pathname⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
为什么突然之间多了这么多没有任何说明，也不提供具体 url 的适配请求？都是从哪冒出来的？
<pre name="pagetual">
{
    "name": "笔趣阁",
    "url": "^https?://www\\.xbqgg\\.com/reader/PDL1BCg/",
    "example": "http://www.xbqgg.com/reader/PDL1BCg/",
    "pageElement": "article",
    "nextLink": "//a[@class='active']/preceding-sibling::a[1]",
    "action": 0
}
</pre>
