### ISSUE TITLE
Request Picviewer CE+ support for service.ebook.hyread.com.tw

### ISSUE THREAD

**Issue by Joyngjtc** [hoothin/UserScripts#632]
**The url of site**
The example urls of site. ⚠Do not paste only domain without pathname⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
你已經提交三次無效 issue 了，具體 url 和大圖位址都不提供，是要我怎麽幫你？
