### ISSUE TITLE
Request Pagetual support for ikstar.com

### ISSUE THREAD

**Issue by enernitv** [hoothin/UserScripts#635]
**The url of site**
https://ikstar.com/forum-433-1.html
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
没有发现问题，这个论坛是 bbsThreadlist1 规则驱动的，请确认已经正确导入在线规则
