### ISSUE TITLE
关于iOS设备翻页bug

### ISSUE THREAD

**Issue by Burn-Sin** [hoothin/UserScripts#64]
我在iOS上的Safari中使用插件安装了脚本，但是每次翻页只会执行一次，之后就不工作了，拖到页面最下方会闪一下少女祈祷中，请问如何解决呢

**Comment by hoothin** [comment]
你用的是Userscripts吗？故障网址是哪一个呢？

**Comment by hoothin** [comment]
我用Userscripts远程调试了一下，做了一些修改，我本地是可以正常翻页了，你更新下脚本试试

**Comment by Burn-Sin** [comment]
多谢作者回复，现在好像完全失效了，配置页面也没有了

**Comment by hoothin** [comment]
请问你是用Userscripts这个插件装载的吗？ios版本之类的信息方便提供一下吗？

**Comment by hoothin** [comment]
玛德😡，被卡饭上一个憨批带到沟里去了，已经修好了，感谢反馈。

**Comment by Burn-Sin** [comment]
感谢作者，我是用的Userscripts。代码真心赞，之后会打赏的，车万人不骗车万人😃
