### ISSUE TITLE
Why Pagetual change google search result text color in dark mode?

### ISSUE THREAD

**Issue by trnkobayashi** [hoothin/UserScripts#649]
Pagetual change google search result text color

1. Search for sth in google dark mode
2. See error

**Expected behavior**
A brighter color

![Screenshot](https://github.com/hoothin/UserScripts/assets/117138163/8a2e82c5-36ce-4cf8-82c8-1cb2010ce041)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 127.0.2
 
 It works fine on my chrome
 
 
![ChromeScreenshot](https://github.com/hoothin/UserScripts/assets/117138163/46a79f17-f812-44c0-891e-95c06e2ca2d2)

**Comment by hoothin** [comment]
I haven't added any functionality to change the keyword color for Pagetual. It's possible that one of the extensions on your Firefox is causing this behavior.

**Comment by hoothin** [comment]
Try this rule on firefox
<pre name="pagetual">
{
    "name": "Google Search",
    "nextLink": [
        "id('pnnext')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a",
        "id('pnprev')|id('navbar navcnt nav')//td[span]/following-sibling::td[1]/a|id('nn')/parent::a"
    ],
    "pageElement": "id('rso')|id('center_col')/style[contains(.,'relative')][id('rso')]|id('search')/div/div/style[1]",
    "action": 2,
    "pageNum": "&start={10*($p-1)}",
    "pageBarTop": 55,
    "url": "^https?://[^./]+\\.google(?:\\.[^./]{2,3}){1,2}/(?:c(?:se|ustom)|search|webhp|m|#)",
    "replaceElement": "[role='navigation']>[role='presentation']",
    "css": "ol>li{display: inline-flex;}"
}
</pre>
