### ISSUE TITLE
东方永页机: Request Pagetual support for www.32995.com

### ISSUE THREAD

**Issue by efaun** [hoothin/UserScripts#659]
**The url of site**
https://www.32995.com/saner/4539231392/57823973.html
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**
内置分页的网页自动翻页只能翻到下一章, 无法匹配下一页

**Describe the result you'd like with the rule**
自动拼接下一页→下一章

**Custom rule you've tried**
尝试使用"nextLink": "#PageSet > a:nth-child(4)", 但这样只能匹配下一页又不能匹配下一章了

**Additional context**

请问类似有内置分页的网页应该怎么适配?

**Comment by hoothin** [comment]
我是说这个站的问题是 base ，所以你需要更新永页机到最新版

**Comment by efaun** [comment]
> 我是说这个站的问题是 base ，所以你需要更新永页机到最新版

哦哦, 理解错了, 我更新到了最新版, 目前的状态是可以拼接当前章节的分页, 无法拼接下一章的分页, 会提示"已到达最后一页"

**Comment by hoothin** [comment]
你试试删除这个站的自定义规则，让永页机自己判断下一页

**Comment by efaun** [comment]
> 你试试删除这个站的自定义规则，让永页机自己判断下一页

不行啊, 删除了自定义规则以后一刷新又有了

https://github.com/hoothin/UserScripts/assets/13315821/a19675db-4ef8-4476-ae54-f28397aa868a

**Comment by hoothin** [comment]
你把nextLink这一行删掉保存就行了

**Comment by efaun** [comment]
> 你把nextLink这一行删掉保存就行了

感谢! 可以了
![MuaKissGIF](https://github.com/hoothin/UserScripts/assets/13315821/d617836f-045c-4752-9f99-2dc2f9f16657)
