### ISSUE TITLE
东方永页机 水木论坛带图帖子拼接异常

### ISSUE THREAD

**Issue by superbillgates** [hoothin/UserScripts#66]
不带图的基本OK，但带大量图片的（非附件图）帖子貌似都有问题，直接在主贴进行拼接了。

例如，同一个帖子，m开头的移动版页面
https://m.mysmth.net/article/FamilyLife/1765285870
和www开头的桌面版页面
https://www.mysmth.net/nForum/#!article/FamilyLife/1765285870
都有问题～～～

请帮忙修正，兄弟辛苦，十分感谢！

**Comment by hoothin** [comment]
兄弟客气了，接着
```
  {
    "name":"水木桌面端",
    "url":"https://www\\.mysmth\\.net/nForum/#!article/",
    "nextLink":"a[title='下一页']",
    "pageElement":"div.b-content"
  },
  {
    "name":"水木移动端",
    "url":"https://m\\.mysmth\\.net/article/",
    "pageElement":"#m_main>ul.list"
  }
```

**Comment by superbillgates** [comment]
> 兄弟客气了，接着
> 
> ```
>   {
>     "name":"水木桌面端",
>     "url":"https://www\\.mysmth\\.net/nForum/#!article/",
>     "nextLink":"a[title='下一页']",
>     "pageElement":"div.b-content"
>   },
>   {
>     "name":"水木移动端",
>     "url":"https://m\\.mysmth\\.net/article/",
>     "pageElement":"#m_main>ul.list"
>   }
> ```

收到，再次感谢！脚本越来越完善啦，哈哈哈～～～
