### ISSUE TITLE
Request Pagetual support for linux.do

### ISSUE THREAD

**Issue by cikichen** [hoothin/UserScripts#660]
**The url of site**
https://linux.do/latest
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
在 Discourse 上默认禁用了，这里面没有什么地方需要永页机吧？

**Comment by cikichen** [comment]
> 在 Discourse 上默认禁用了，这里面没有什么地方需要永页机吧？

一碰就停了

**Comment by hoothin** [comment]
你是说自动滚动？倒是把问题描述清楚啊。可以看看 listenUrlChange 这个，设为 false 就可以了
