### ISSUE TITLE
Firefox 浏览器中启用 Pagetual 后无法在 B 站评论区跨行选择文本

### ISSUE THREAD

**Issue by benzBrake** [hoothin/UserScripts#662]
**Describe the bug**
其他扩展均已关闭的情况下，在暴力猴中安装  Pagetual 并导入基础规则，B站评论区无法跨行选择文本。

**To Reproduce**
1. 在暴力猴中安装 Pagetual
2. 在 GreasyFork 页面导入基础规则
3. 访问 B 站，滚动到评论区
4. 手动跨行选择文本

**Expected behavior**
选择文本

**Screenshots**

https://github.com/user-attachments/assets/6fafbfb4-c5de-4531-a308-22aa6c500dbf

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 128

**Smartphone (please complete the following information):**

**Additional context**
Bitwarden 是为了登录 B 站打开了，但是实际上关闭 Bitwarden 的时候也是不能选择。

**Comment by hoothin** [comment]
![image](https://github.com/user-attachments/assets/cd5fbdf7-5a0b-45b3-8004-3c60d64a29e4)

没重现你的问题，另外永页机在 B 站播放页默认是[禁用](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L7269)的

**Comment by hoothin** [comment]
找到原因了，这不是永页机的问题，而是 vm 的问题。
vm 在最新版的火狐上不知为何不允许出现阿拉伯文字，一旦出现就会有问题。
例如，这样一个空白脚本就能导致问题，简直莫名其妙，建议换 tm 吧。
``` js
// ==UserScript==
// @name         Test
// @match        *://*/*
// ==/UserScript==

(function() {
    'use strict';
    //تمكين تصحيح الأخطاء
})();

```

**Comment by benzBrake** [comment]
> 找到原因了，这不是永页机的问题，而是 vm 的问题。 vm 在最新版的火狐上不知为何不允许出现阿拉伯文字，一旦出现就会有问题。 例如，这样一个空白脚本就能导致问题，简直莫名其妙，建议换 tm 吧。
> 
> ```js
> // ==UserScript==
> // @name         Test
> // @match        *://*/*
> // ==/UserScript==
> 
> (function() {
>     'use strict';
>     //تمكين تصحيح الأخطاء
> })();
> ```

可能是 FF 的问题了，用 Tamper Monkey 也这样

**Comment by hoothin** [comment]
那就只能手动添加排除网址了 `https://www.bilibili.com/video/*` ，我看看有空把阿拉伯语言编码一下

**Comment by hoothin** [comment]
我已经把阿拉伯语全编码了，现在应该没有问题了
