### ISSUE TITLE
Request Pagetual support for www.bing.com

### ISSUE THREAD

**Issue by zenone99** [hoothin/UserScripts#665]
**The url of site**
https://www.bing.com/search?q=pagetual&toWww=1&redig=9B1FCF4C54094D0C888DDC1DE2EB07F3
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
So what? What exactly is the problem???
