### ISSUE TITLE
翻页时会丢失已设定的筛选条件

### ISSUE THREAD

**Issue by nekogyo** [hoothin/UserScripts#666]
**Describe the bug**
1、自动翻页时，未按照设定好的时间段发送下一页请求，而是加载默认检索条件【近3月】的下一页。
2、但人工点击，或者开启"clickMode": true并不会出现此问题。

**To Reproduce**
1.打开http://www.ccgp-guangxi.gov.cn，随便搜索一个关键词，如“医院”，可见默认检索时间条件为【近3月】
2.修改日期筛选日期为【3日内】
3.滚动到底部
4.可复现错误，加载了非【3日内】的数据。

**Expected behavior**
设定好时间段【3日内】，自动翻页也应该加载【3日内】的数据。

**Screenshots**
错误示例：
![image](https://github.com/user-attachments/assets/514c7f38-7442-41a9-83f6-6763569d72f8)
网络请求的内容：
![image](https://github.com/user-attachments/assets/61ac003f-5971-4a78-beca-51d1cf356386)

后台发送接送正常情况【人工或clickMode】：
{"keyword":"医院","firstCode":"","secondCode":"","districtCode":[],"publishDateBegin":**1720972800000**,"publishDateEnd":**1721250774195**,"pageNo":1,"pageSize":15,"isTitleSearch":null,"order":"desc","leaf":"0"}
后台发送接送异常情况【自动翻页拼装】：
{"keyword":"医院","firstCode":"","secondCode":"","districtCode":[],"publishDateBegin":**1713369600000**,"publishDateEnd":**1721250781575**,"pageNo":1,"pageSize":15,"isTitleSearch":null,"order":"desc","leaf":"0"}

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser：EDGE
 - Version：lastest

**Additional context**
脚本示例：
```
{
	"name": "CCGPGX",
	"url": "^https?://www\\.ccgp-guangxi\\.gov\\.cn/site/",
	"example": "http://www.ccgp-guangxi.gov.cn/site/search?k=?",
	"action": 1,
	"refreshByClick": "#floor-1671623174995065 > div.comp-body.lego-pc-wsg-mainSearchPage-front > div.po-row > div.po-col.po-col-24 > div.lego-pc-wsg-homesearchinput-front > div.searchInput-content > div.searchInput-content-input > div.input-button.title",
	"pageElement": "#floor-1671623174995065 > div.comp-body.lego-pc-wsg-mainSearchPage-front > div.po-row > div.po-col.po-col-24 > div.lego-pc-wsg-homesearchreslist-front > div.searchResList-content",
	"nextLink": "#floor-1671623174995065 > div.comp-body.lego-pc-wsg-mainSearchPage-front > div.po-row > div.po-col.po-col-24 > div.resPagination > div.po-pagination.is-background > button.btn-next"
}
```

**Comment by hoothin** [comment]
用 [init](https://pagetual.hoothin.com/rules/init.html) ，添加`if (iframe == null) return; await click('xxx'); await click('xxx');`
把xxx替换为合适的选择器

**Comment by nekogyo** [comment]
加了inti，让inti自动去设置自定义筛选条件。但是自动翻页时，还是会载入默认筛选条件的内容。
没能得到期望的内容。
{
	"name": "CCGPGX",
	"url": "^https?://www\\.ccgp-guangxi\\.gov\\.cn/site/",
	"example": "http://www.ccgp-guangxi.gov.cn/site/search?k=?",
	"action": 1,
	"init":"let e =  document.querySelector('div.level-content-timeItem:nth-child(7)'); let d = document.querySelector('#floor-1671623174995065 > div > div:nth-child(6)') ; if(d) d.remove() ; e.click();",
	"refreshByClick": "div.input-button.title",
	"pageElement": "div.lego-pc-wsg-homesearchreslist-front",
	"nextLink": "button.btn-next"
}

**Comment by hoothin** [comment]
你操作的是主页的元素。当然没用，我给的 click 直接用啊
