### ISSUE TITLE
[bug] [东方永页机]火狐扩展页面翻页图标变得巨大无比

### ISSUE THREAD

**Issue by youxiaohou** [hoothin/UserScripts#67]
网页地址：https://addons.mozilla.org/zh-CN/firefox/search/?sort=random&type=extension

![image](https://user-images.githubusercontent.com/82362675/155273960-e123cfa8-0370-4dd7-b2e0-07dff825e8a2.png)

**Comment by youxiaohou** [comment]
解决方法：给 svg 添加宽高 <svg width="30" height="30" style=".....">.......

**Comment by hoothin** [comment]
感谢油小猴反馈:) ，要不要和我一起维护永页机呀？
