### ISSUE TITLE
Brave search bug

### ISSUE THREAD

**Issue by https433** [hoothin/UserScripts#676]
**The url of site**
search.brave.com/search?q=

**Is your request related to a problem? Please describe.**
Brace search double search bar, on all splitting modes 

**Describe the result you'd like with the rule**
n/a

**Custom rule you've tried**
n/a

**Additional context**
![brave](https://github.com/user-attachments/assets/95c42f03-585e-4fef-aea3-984c4c59f489)

**Comment by hoothin** [comment]
Thanks for report, fixed now.

**Comment by https433** [comment]
> Thanks for report, fixed now.

Thanks
