### ISSUE TITLE
Request Picviewer CE+ support for https://www.amazon.com/

### ISSUE THREAD

**Issue by mrqmy** [hoothin/UserScripts#678]
**The url of site**
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.
https://www.amazon.com/-/zh_TW/%E8%97%8D%E7%B6%A0%E8%89%B2%E8%A3%9D%E9%A3%BE%E6%8A%B1%E6%9E%95%E5%A5%97-%E7%B6%A0%E6%9D%BE%E7%9F%B3%E5%92%8C%E7%81%B0%E8%89%B2-%E7%8F%BE%E4%BB%A3%E9%9B%9B%E8%8F%8A%E8%8A%B1%E5%8D%89%E6%9E%95%E9%A0%AD%E5%A5%97-%E7%8F%BE%E4%BB%A3%E7%B0%A1%E7%B4%84%E6%B3%A2%E8%A5%BF%E7%B1%B3%E4%BA%9E%E9%A2%A8%E9%9D%A0%E5%A2%8A%E5%BA%8A-%E6%88%B6%E5%A4%96%E5%AE%B6%E5%B1%85%E8%A3%9D%E9%A3%BE/dp/B0BWT5PGTQ/ref=pd_ci_mcx_di_int_sccai_cn_d_sccl_2_3/138-5961304-5018052?pd_rd_w=qoS97&content-id=amzn1.sym.751acc83-5c05-42d0-a15e-303622651e1e&pf_rd_p=751acc83-5c05-42d0-a15e-303622651e1e&pf_rd_r=8Q0981KY96K31NKD5ZEQ&pd_rd_wg=8su15&pd_rd_r=b50d984e-aeaf-4cfe-96f0-574e8d641d53&pd_rd_i=B0BWSZD1LP&th=1

**Is your request related to a problem? Please describe.**
When I shortcut into the gallery, the programme doesn't help me find all the big HD images, it always misses them!

**Describe the result you'd like with the rule**
Find all the original high-resolution images and add them to the gallery.

**Custom rule you've tried**
The rule you've made before.
I'm not well versed in this, tried a simple custom rule but it didn't work very well

**Additional context**

**Comment by hoothin** [comment]
Can you please point out the specific missing HD imgs?

**Comment by mrqmy** [comment]
> Can you please point out the specific missing HD imgs?

They always get lost, sometimes a single hi-res image can't be found, and I'm sorry to say that I don't seem to be able to figure out the rules for them getting lost.

**Comment by hoothin** [comment]
Have you tried adjusting the size slider upside? And is the required image currently visible on the page?

**Comment by mrqmy** [comment]
> Have you tried adjusting the size slider upside? And is the required image currently visible on the page?

They are not limited by the size of the display, the slider is pulled down to the smallest possible size and appears as a vector image.

**Comment by mrqmy** [comment]
> Have you tried adjusting the size slider upside? And is the required image currently visible on the page?

<img width="734" alt="Snipaste_2024-07-25_14-54-11" src="https://github.com/user-attachments/assets/9b0c068d-e281-430b-b9f0-13edc6722e92">
<img width="1920" alt="Snipaste_2024-07-25_14-54-46" src="https://github.com/user-attachments/assets/1a8c06ae-e296-4401-a3b3-841c19021883">

It doesn't identify all of the large HD images.

**Comment by hoothin** [comment]
As I mentioned above, you must ensure that the images have been loaded into the current page.
Specifically for this page, you need to pre-hover the mouse over all the thumbnails, only then will the required image elements be inserted into the current page, and then you can retrieve them from the gallery.

**Comment by mrqmy** [comment]
> As I mentioned above, you must ensure that the images have been loaded into the current page. Specifically for this page, you need to pre-hover the mouse over all the thumbnails, only then will the required image elements be inserted into the current page, and then you can retrieve them from the gallery.

It works fine according to what you said, thanks.
But there is one dimensional image he won't load automatically, it's bugging me, he's not much different in the js code, can you take a look at it.

<img width="619" alt="Snipaste_2024-07-25_15-26-14" src="https://github.com/user-attachments/assets/ed28380b-8701-4307-a764-c990ebec9e29">
<img width="1702" alt="Snipaste_2024-07-25_15-26-32" src="https://github.com/user-attachments/assets/123f9071-dfb8-44c8-98bc-a075e6e8f1bf">
<img width="1425" alt="Snipaste_2024-07-25_15-27-00" src="https://github.com/user-attachments/assets/6fae0ada-4dfc-4508-af9e-b59e7593b82b">

**Comment by mrqmy** [comment]
> As I mentioned above, you must ensure that the images have been loaded into the current page. Specifically for this page, you need to pre-hover the mouse over all the thumbnails, only then will the required image elements be inserted into the current page, and then you can retrieve them from the gallery.

It is not a probability event, and in fact I was unable to add size charts to the gallery for any of the items.

**Comment by hoothin** [comment]
After opening the gallery, not all image sizes are immediately retrieved. Some unloaded images may have temporary dimensions until their actual sizes are obtained. That's why I asked you to try adjusting the size slider as low as possible.

**Comment by mrqmy** [comment]
> After opening the gallery, not all image sizes are immediately retrieved. Some unloaded images may have temporary dimensions until their actual sizes are obtained. That's why I asked you to try adjusting the size slider as low as possible.

The dimensional drawing came up when I limited the height to 470, it works fine, thanks, sorry to bother!
