### ISSUE TITLE
有个新闻网站加载不了，请帮忙看一下，谢谢

### ISSUE THREAD

**Issue by vicentory** [hoothin/UserScripts#68]
这个网站加载不了，请帮忙看一下，谢谢http://www.hynews.net/
<img width="666" alt="image" src="https://user-images.githubusercontent.com/10493597/155847189-6b6fba98-e547-4509-83f4-3b00a9447e15.png">

**Comment by hoothin** [comment]
接着兄dei
<pre>
  {
    "name":"淮安新闻网",
    "url":"http://www\\.hynews\\.net/",
    "loadMore":"#_more"
  }
</pre>

**Comment by vicentory** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/10493597/156187292-01340503-aaed-4a91-a49c-ccc5c9c246d1.png">
4万行规则啊，真是厉害了。没看懂第一行这个raindrop的链接是啥意思啊？

**Comment by hoothin** [comment]
这个是你手动禁用再启用或者开启白名单模式后启用时写入的，后面的1代表在app.raindrop.io这个网站启用，如果是0则是禁用

**Comment by vicentory** [comment]
大佬，这个网站失效了呢，有时间帮忙看看，多谢

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "淮安新闻网",
    "url": "^http://www\\.hynews\\.net/",
    "loadMore": ".listLoadMore"
}
</pre>
