### ISSUE TITLE
油猴脚本Picviewer CE+被自动删除

### ISSUE THREAD

**Issue by forcyan** [hoothin/UserScripts#680]
**Describe the bug**
系统版本win11 23H2，浏览器为edge 版本 126.0.2592.113 (正式版本) (64 位)，通过油猴v5.1.1使用Picviewer CE+。
最近（无法确定具体时间，但目前最新版本7.25.1稳定遇到该问题）每次重新安装该脚本后都会被自动删除，且在windows安全中心也找不到相关记录。
被删除后，进入greasyfork，会显示【重新安装】而非【安装】

**Screenshots**
![QQ_1721986995957](https://github.com/user-attachments/assets/895b3425-10f6-4bb3-978c-50831c52944f)

**Desktop (please complete the following information):**
 - OS: win11 23H2
 - Browser: edge 126.0.2592.113 (正式版本) (64 位)

**Comment by hoothin** [comment]
我的 edge 没遇到过这问题，所以应该是你机子上某个扩展或者软件导致的。显示重新安装说明脚本在回收站。点开 tm 管理台，标签栏有个回收站图标，点进去就能看到。
tm 只装了这一个脚本吗？其他脚本也会被删除吗？

**Comment by forcyan** [comment]
> 我的 edge 没遇到过这问题，所以应该是你机子上某个扩展或者软件导致的。显示重新安装说明脚本在回收站。点开 tm 管理台，标签栏有个回收站图标，点进去就能看到。 tm 只装了这一个脚本吗？其他脚本也会被删除吗？

感谢大佬的回复，其他脚本不会被删除，也都是用了挺久的脚本，之前没遇到这种情况，所以没有怀疑对象，确实在回收站里有，我从回收站里点了重置，使用了二十分钟左右，暂时没遇到自动删除的情况了。

另外想请教大佬一个问题，现在点击下载时，保存图片名选默认
![QQ_1722044630247](https://github.com/user-attachments/assets/b1507265-68c3-4665-9df3-e409587d5750)
，经常出现下载得到的文件名不带title的情况，比如https://www.bilibili.com/opus/958394103565910022?spm_id_from=333.1365.0.0，
![QQ_1722044611077](https://github.com/user-attachments/assets/2234648b-4a07-461a-9af7-44b0e74155e0)
请问您有遇到过这种情况吗？

**Comment by hoothin** [comment]
这张图没有 alt 属性吧？文件名这样是正常的，你是想要把网页标题加进去？

**Comment by forcyan** [comment]
> 这张图没有 alt 属性吧？文件名这样是正常的，你是想要把网页标题加进去？
您的意思是文件描述是指alt属性吗？我试用了url+文件描述的模式，也切回默认试过，结果并不稳定
![QQ_1722045678982](https://github.com/user-attachments/assets/e2706aad-f3ab-4369-8638-bc7a7178958f)
另外，呃，大佬，脚本又被删掉了。

**Comment by hoothin** [comment]
也有可能是开了TESLA被同步数据覆盖了吧，或者你切到暴力猴试试

**Comment by hoothin** [comment]
我倒是遇到过有用户因为开了同步，导致脚本删掉之后又自动安装，你这个情况正好相反。所以你可以在同步这一块找找原因。

**Comment by forcyan** [comment]
> TESLA

enmmm，虽然不知道您说的TESLA是什么，但我试了下关闭脚本同步，确实没有被删除了，暴力猴也不会自动删除，可能就是脚本同步的原因吧。

另外，我确实是想把网页标题作为图片名，之前使用默认设置都是这种效果，
![QQ_1722053567415](https://github.com/user-attachments/assets/d0d0fb9a-fc43-4dcf-8e0d-424ed548eb8d)，
现在各种设置都试过，下载下来的时候都不带网页标题，请问是我该怎么做呢？

**Comment by hoothin** [comment]
这个啊😓。因为之前有用户说不希望带网页标题，所以我去掉了。
我加一个选项吧。

**Comment by hoothin** [comment]
已经更新上去了，你试试

**Comment by forcyan** [comment]
> 这个啊😓。因为之前有用户说不希望带网页标题，所以我去掉了。 我加一个选项吧。

相比同类脚本我最喜欢您的脚本的其中一点就是可以带标题，因为我比较喜欢收藏的图片知道出处的感觉hh，现在可以了，感谢大佬。
