### ISSUE TITLE
之前是正常的，现在直接第二页就跳转到最后一页了 Request Pagetual support for xiutaku.com

### ISSUE THREAD

**Issue by KwaBEF** [hoothin/UserScripts#682]
**The url of site**

The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
`"nextLink": ".pagination-next"`
