### ISSUE TITLE
Request Pagetual support for try.lingxiangniao.com

### ISSUE THREAD

**Issue by Xylooona** [hoothin/UserScripts#686]
**The url of site**
https://try.lingxiangniao.com/TryRecord/TryList/TryHistory
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
Sorry, I have no account
