### ISSUE TITLE
【东方永页机】BUG、建议和功能请求

### ISSUE THREAD

**Issue by wordpure** [hoothin/UserScripts#69]
1. 【BUG】插入元素的类型为 `li` 时，即使透明度为 0，分页隔条也不会隐藏。
	
	可以到 [ yande.re](https://yande.re/post?tags=key) 和 [AlternativeTo](https://alternativeto.net/software/calibre/) 测试。
	
	![图片](https://user-images.githubusercontent.com/68013962/155930744-225e8c47-8e57-4ba3-82fa-03bbf0298df1.png)

	看了一下，好像是 [2036 行](https://github.com/hoothin/UserScripts/blob/070a1ccdd0786e4a3ab0c5226796c7bc08719e5b/Pagetual/pagetual.user.js#L2036) 的 `style` 把前面的给覆盖了。
	
	![图片](https://user-images.githubusercontent.com/68013962/155934452-42c24a8f-26e1-43a5-8b53-b69743bcff80.png)
	
	我在那里加了个判断之后就正常了，不过或许在前面统一处理样式会比较好？

	```js
	pageBar.style.display= rulesData.opacity === 0 ? "none" : "inline-block";
	```
	
2. 【BUG】拼接后，[AlternativeTo](https://alternativeto.net/software/calibre/) 的图片无法正常显示。
		
	![图片](https://user-images.githubusercontent.com/68013962/155947866-7e055e27-0aab-4c2a-9b13-24489bcf979b.png)

3. 【建议】没有 `tfoot` 的表格，可以把下一页表格的 `//tr[not(th)]` 插入到上一页表格的尾行，而不是直接嵌入整个表格。
	
	[最新动作排行 - Quicker](https://getquicker.net/Share/NewActions?sort=vote)
	
	![图片](https://user-images.githubusercontent.com/68013962/155946039-042151c6-f1a6-4393-9ca8-c46f9f8b4e5e.png)

4. 【功能请求】快速定位到上次拼接时的位置。
	
	有时看到一半就因为各种原因关闭了网页，后面想继续看的时候，因为拼接时网址没有更新，要花点时间才能定位到上次浏览的位置。
	
	Infy Scroll 是通过 [拼接后自动更新浏览历史和页面标题](https://github.com/sixcious/infy-scroll/blob/ce90912589181ae64fba409a2d152773e258f132/src/base/js/scroll.js#L319) 来解决这个问题的。但油猴好像没有操作浏览器历史的 API，没办法这么做。
	
	想问一下大佬有没有好的解决方法。

**Comment by hoothin** [comment]
Nice issues! 感谢反馈，我来试试这道题：)

**Comment by hoothin** [comment]
调整完毕，你试试。
其中alternativeto需要添加一个规则
<pre>
  {
    "name":"alternativeto",
    "url":"^https://alternativeto\\.net/",
    "nextLink":"nav[aria-label='Pagination Navigation']>a",
    "action":1,
    "pageElement":"div.container>ol>li",
    "pageInit":"eles.forEach(e=>{let span=e.querySelector('div>div>div>span');if(span)span.onVisible()})"
  }
</pre>

**Comment by wordpure** [comment]
大佬威武，问题基本都解决了。

不过 3、4 现在还有点小瑕疵。

以 [最新动作排行 - Quicker](https://getquicker.net/Share/NewActions?sort=vote) 为例，现在拼接的时候，上下两页的表格虽然连接起来了，但下一页的表头没有被排除掉。而且，出现了和之前插入 `li` 一样的问题，[1994 行](https://github.com/hoothin/UserScripts/blob/070a1ccdd0786e4a3ab0c5226796c7bc08719e5b/Pagetual/pagetual.user.js#L1994) 的 `display: table-row` 把 ·`display: none` 给覆盖了😂

![图片](https://user-images.githubusercontent.com/68013962/155983997-317bf814-c321-4efa-9d43-5bb0e1fa6ccb.png)

以 [/key | Page 31 | yande.re](https://yande.re/post?page=40&tags=key) 为例，现在更新浏览历史的时候，只会更新网址，不会一并更新页面标题，这就导致历史记录里有很多标题和网址对不上。

![图片](https://user-images.githubusercontent.com/68013962/155985326-01544faa-dc76-4a6a-a5fe-200fd7094776.png)

---

以 [calibre Alternatives: 25+ Similar eBook Readers | AlternativeTo](https://alternativeto.net/software/calibre/) 为例，目前脚本是拼接后立即更新浏览历史，而不是等待用户滚动到嵌入元素再更新，这就导致浏览历史永远领先于浏览进度。

由于脚本往往会预加载一页，所以可以看到这样一种诡异的情况：一个开启了自动拼接的网页，每刷新一次，地址栏的页码就会 +1🤣

![刷新时页码变化](https://user-images.githubusercontent.com/68013962/155992021-f05a70cd-9e77-4a3c-8b4e-e9a2ccc6ea7a.gif)

或许，可以给分页隔条加一个滚动事件，只在它滚动到页面中间的时候更新浏览历史，这样可能会比较符合直觉。

**Comment by hoothin** [comment]
表格那个可以使用规则排除表头和第一项
<pre>
  {
    "name":"getquicker",
    "url":"^https://getquicker\\.net/",
    "type":0,
    "nextLink":"//a[@class=\"page-link\"][contains(text(),'下一页')]",
    "pageElement":"//table/tbody/tr[not(./th)][position()>1]"
  }
</pre>
历史记录这一块暂时无解，因为所有浏览器都忽略传入的title项了，如果你发现有类似扩展实现了历史记录title更新可以发给我参考一下。
然后预加载延后写入也添加了，目前是插入下一页的同时将当前页写入历史记录。

**Comment by wordpure** [comment]
> 表格那个可以使用规则排除表头和第一项

我知道可以用规则解决，但想偷一下懒，所以[前面](https://github.com/hoothin/UserScripts/issues/69#issue-1153826112)建议把去除表头作为默认规则使用。

> 3\. 【建议】没有 `tfoot` 的表格，可以把下一页表格的 `//tr[not(th)]` 插入到上一页表格的尾行，而不是直接嵌入整个表格。

大佬考虑一下？

---

> 历史记录这一块暂时无解，因为所有浏览器都忽略传入的title项了，如果你发现有类似扩展实现了历史记录title更新可以发给我参考一下。

标题其实不用传入，只要在更新网址之后修改 `document.title` 就可以了。

![图片](https://user-images.githubusercontent.com/68013962/156112621-80d3988a-90fc-4ada-9265-cc78101e69ab.png)

**Comment by hoothin** [comment]
谢谢提醒！title我这就加一下。
表头这块我是担心下一页th内容变更，比如有时间之类的变量，不过目前看起来似乎想多了，我暂时先改成默认去掉th吧，以后遇到情况再说。
另外这个站即使默认去掉了表头也是需要规则的，因为下一页的第一项与当前的最后一项重复了。

**Comment by wordpure** [comment]
试了一下，相当完美:+1:。

> 另外这个站即使默认去掉了表头也是需要规则的，因为下一页的第一项与当前的最后一项重复了。

前两天我和开发者反映过这问题了，后面应该能正常显示。

**Comment by wordpure** [comment]
大佬，控制台的输出信息是不是默认隐藏一下比较好？有时会显示很多😂

Picviewer CE+和多选框伴侣也有这个问题。

![图片](https://user-images.githubusercontent.com/68013962/156123176-ee06dede-612e-4482-bb87-c13cf7723827.png)

![图片](https://user-images.githubusercontent.com/68013962/156124267-06e12fd7-c556-43f4-b7a3-35efff3e8345.png)

**Comment by hoothin** [comment]
好的，我加一个调试选项。另外你那个报错网站方便贴上来吗？

**Comment by wordpure** [comment]
> 好的，我加一个调试选项。另外你那个报错网站方便贴上来吗？

[现代 JavaScript 教程](https://zh.javascript.info/)

**Comment by hoothin** [comment]
调试选项加好了，取消勾选就不会有输出了。
多选框伴侣这个是jquery引入时的报错，报错在脚本执行之前，我也不知道怎么解决，猜测可能是网站覆写了style属性 ；）

**Comment by wordpure** [comment]
> 多选框伴侣这个是jquery引入时的报错，报错在脚本执行之前，我也不知道怎么解决，猜测可能是网站覆写了style属性 ；）

不知道为啥，把脚本的运行时机改成 `document-body`，或者加上 `no-frames` 之后，报错就消失了。

![图片](https://user-images.githubusercontent.com/68013962/156151162-e6badd7a-80d7-44d2-a462-ed64bff0472d.png)

**Comment by hoothin** [comment]
其实这个jquery引入报错我很早就抓到了，只是因为太懒了不想去跟踪，因为彻底解决的方法是用原生js重写相关功能，想想就头大。
如果改成document-body就没有报错说明大概就是style或者其他属性的set方法被覆写了。因为document-body是在检测到body元素且页面js执行之前运行的。
