### ISSUE TITLE
Can't save image on Huggingface

### ISSUE THREAD

**Issue by Andru2033** [hoothin/UserScripts#694]
When I press hotkey to save an image on [this](https://huggingface.co/spaces/llamameta/flux-pro-uncensored) webpage (after the image is generated), nothing is happening.

1. Go to [this](https://huggingface.co/spaces/llamameta/flux-pro-uncensored) webpage
2. Enter any prompt in the input field, and press generate button.
3. Hit save image hotkey (which is configured for Picviewer CE+)
4. Aaaaand, nothing

**Expected behavior**
The image should start saving on my PC after I press the hotkey.

**Additional context**
On most of the websites, the script works perfectly.

**Comment by hoothin** [comment]
Please update the script and try again.

**Comment by Andru2033** [comment]
> Please update the script and try again.

Thanks, I can't check that though (the images are not generating anymore).
However, the script does not work on [this](https://huggingface.co/spaces/llamameta/fluxproV2) second version of the page that is looks identical to the first one.

**Comment by hoothin** [comment]
Use https://fluxpro3-kdykor8nubyjbs9ksh9wfp.streamlit.app instead.

**Comment by Andru2033** [comment]
Thank you, everything working.
