### ISSUE TITLE
Request Pagetual support for www.52pojie.cn

### ISSUE THREAD

**Issue by Cyh9527o** [hoothin/UserScripts#698]
**The url of site**
https://www.52pojie.cn/thread-1862524-1-1.html
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
请导入规则
