### ISSUE TITLE
在github上怎么不管用了?

### ISSUE THREAD

**Issue by suliult** [hoothin/UserScripts#70]
最近在github your stars上不自动翻页了

**Comment by hoothin** [comment]
我测试了是可以正常翻页的，你排除网络因素了吗？
如果确定不是网络以及扩展冲突导致的，可以把问题链接扔上来吗？

**Comment by suliult** [comment]
解决了，your star页面还是不行自己翻页

**Comment by suliult** [comment]
应该是冲突了，打扰您了

**Comment by suliult** [comment]
我在edge中安装同样的拓展和脚本，它依然能够翻页。但chrome不同，脚本显示也不同 
chrome
![image](https://user-images.githubusercontent.com/85177880/156099332-054bd210-0a32-4530-ae9c-19c45d52d628.png)
edge
![image](https://user-images.githubusercontent.com/85177880/156099345-5fb88fde-9548-412a-beb4-9d937c36841e.png)

**Comment by suliult** [comment]
> 我测试了可以正常翻页的，你解决网络问题了吗 ？

我在edge中安装同样的拓展和脚本，它依然能够翻页，应该不是冲突了。但chrome不能，脚本显示样式也不同
chrome
![image](https://user-images.githubusercontent.com/85177880/156099505-d496bf1e-e34e-4003-8b75-af14521f1244.png)

edge
![image](https://user-images.githubusercontent.com/85177880/156099524-536b4f7b-b694-44f4-bc1f-8653171f2a13.png)

**Comment by hoothin** [comment]
Chrome测试了没问题啊，你是否已经更新到最新版了？
![屏幕截图 2022-03-01 125024](https://user-images.githubusercontent.com/5361213/156106946-9b27beb4-efe2-4cb8-a340-e06e34dcf959.jpg)
