### ISSUE TITLE
Request Pagetual support for www.luogu.com.cn

### ISSUE THREAD

**Issue by f2666** [hoothin/UserScripts#701]
**The url of site**
https://www.luogu.com.cn/paste?page=1
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
#597
