### ISSUE TITLE
Request Pagetual support for libproxy.lut.yitlink.com

### ISSUE THREAD

**Issue by AppleJack-eng** [hoothin/UserScripts#702]
**The url of site**
https://libproxy.lut.yitlink.com/https/443/net/cnki/kns/yitlink/kns8s/defaultresult/index?crossids=YSTT4HG0%2CLSTPFY1C%2CJUP3MUPD%2CMPMFIG1A%2CWQ0UVIAA%2CBLZOG7CK%2CPWFIRAGL%2CEMRPGLPA%2CNLBO1Z6R%2CNN3FJMUV&korder=SU&kw=%E5%B8%82%E5%9C%BA%E8%90%A5%E9%94%80
The example urls of site. ⚠**Do not paste only domain without pathname**⚠.

**Is your request related to a problem? Please describe.**

**Describe the result you'd like with the rule**

**Custom rule you've tried**
The rule you've made before.

**Additional context**

**Comment by hoothin** [comment]
这是校内的在线代理吧，我没法访问。
你可以尝试套用规则库内的[知网规则](https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L5936)。
