### ISSUE TITLE
Picviewer CE+ 设置：请问能否在「浮动工具栏」→「启用以下快捷键」→「打开大图」追加鼠标左键作为快捷键？

### ISSUE THREAD

**Issue by Ameryou** [hoothin/UserScripts#709]
开发者您好，这样设置的话，在出现悬浮条时（浮框本身也有过滤条件），直接使用鼠标达到目的，而不必再用键盘（直接点击图片）。

**Comment by hoothin** [comment]
图片上可能会有链接，此时响应左键会使链接失效。
如果一定要用左键的话，可以用自定义规则 https://github.com/hoothin/UserScripts/blob/master/Picviewer%20CE%2B/pvcep_rules.js#L44
用 clickToOpen 就行

**Comment by Ameryou** [comment]
> 图片上可能会有链接，此时响应左键使链接失效。 如果一定要用左键的话，可以用自定义规则[https://github.com/hoothin/UserScripts/blob/master/Picviewer%20CE% 2B/pvcep_rules.js#L44](https://github.com/hoothin/UserScripts/blob/master/Picviewer%20CE%2B/pvcep_rules.js#L44) 用clickToOpen就行

谢谢您
