### ISSUE TITLE
大佬好，问题反馈和规则请教

### ISSUE THREAD

**Issue by LChener** [hoothin/UserScripts#71]
1.https://search.bilibili.com/video?keyword= 页面自动翻页的前两页似乎会重复显示部分搜索结果，第三页之后开始整页重复，如图
![bilibili search](https://user-images.githubusercontent.com/98654480/156163865-19a98986-cbb9-4d28-8efc-01422648631c.png)
翻页时地址栏中也一直重复：
https://search.bilibili.com/video?keyword=%E6%B5%8B%E8%AF%95&page=2&page=2&page=2&page=2&page=2&page=2

2.更新脚本并更新规则后https://space.bilibili.com/178163886/bangumi 依旧无法正常翻页，脚本选项里也没有强制拼接。
F12查看元素之后发现下一页为<a href="javascript:;" class="p next-page">下一页</a>，选择元素时“下一页”的按钮显示为“a.p.next-page”。仿照配置页的例子尝试在现有的那条bilibili space的基础上将 "nextLink":".be-pager-next"改为"nextLink":"a.p.next-page"后依旧无法正常翻页但有了强制拼接选项，但开启后只显示分页隔条不显示第二页的内容，如图
![bilibilispace](https://user-images.githubusercontent.com/98654480/156166021-5d4a76e6-6bf1-4e78-b268-3b54fd6d37bd.png)
现加入的自定义规则如下：
 {
    "name":"bilibili space",
    "url":"https://space\\.bilibili\\.com/",
    "sandbox":false,
    "nextLink":"a.p.next-page",
    "wait":1000
  }
请问应该如何更改？

3.pixiv的问题应该是pixiv.net下所有需要翻页的页面都有的，任何一个标签或者分类都是。现在规则里有自动强制拼接也是只显示分页隔条不显示内容，如图
![pixiv](https://user-images.githubusercontent.com/98654480/156166129-63b4b4fc-70da-451d-bcc0-f4486d6f8966.png)
有时分页隔条还会出现“排版”问题，如图
![pixiv2](https://user-images.githubusercontent.com/98654480/156166228-886a4226-ebdc-439c-ac3b-eb26611b9353.png)
 
暂时遇到的就这几个，由于相关知识不足描述上可能非常啰嗦先道个歉。【如果方便的话可以看看都是什么问题吗？感激不尽

**Comment by hoothin** [comment]
感谢反馈！这几个规则我写完看生效了就没再测试了，明天我修一下

**Comment by hoothin** [comment]
这位车车人早哇，请问你用的是什么浏览器？bilibili的规则已经修复了，b站前端真是超级无敌无聊，三天两头改版。
pixiv我本地测试是正常的，也许是浏览器环境或者脚本管理器不同？方便的话再提供多一点信息呢。

**Comment by hoothin** [comment]
这样啊，我爬了一下。你可以把pixiv plus这个脚本里
<pre>
// 2. 删除动态添加的广告
        let adSelectors = ['iframe', '._premium-lead-promotion-banner',
</pre>
这里的'iframe',去掉

**Comment by LChener** [comment]
感谢大佬，已解决！
