### ISSUE TITLE
[日经新闻网] 无法隐藏 pageBar

### ISSUE THREAD

**Issue by lyserenity** [hoothin/UserScripts#711]
- 测试页面: [日元套利交易是日股大跌的元凶吗？ 日经中文网](https://cn.nikkei.com/columnviewpoint/column/56420-2024-08-16-05-00-27.html)

- 站点编辑的规则:
```json
{
    "name": "日元套利交易是日股大跌的元凶吗？ 日经中文网",
    "url": "^https?://cn\\.nikkei\\.com/columnviewpoint/column/",
    "example": "https://cn.nikkei.com/columnviewpoint/column/56420-2024-08-16-05-00-27.html",
    "nextLink": "#contentDiv > div.newsText.fix > div.pagenavbar > div > span.article_pagination_next > a",
    "pageElement": "body > div.wrapper > div.contentMain.fix > div > div.column-2.mainContent > div.newsDetailContent > div.newsContent > div.overflow > div.newsText.fix",
    "pageBar": 0,
    "action": 0
}
```
-----
但是 pageBar 还是无法隐藏
想请问是不是我哪里设置错误，还是图中蓝框的部分并不是 ``pageBar``？
（如果不是 ``pageBar``，那有其他方式可以隐藏吗？）
<img width="721" alt="image" src="https://github.com/user-attachments/assets/fc462d76-b68f-46ff-8531-c1d400c9ff10">

我有努力看了教程，但可能太小白了，所以有错误的地方还请见谅，谢谢！

**Comment by hoothin** [comment]
pageBar 是指永页机自身的分页条。
可以用 `"css": ".pagenavbar{display: none}"` 来隐藏

**Comment by lyserenity** [comment]
果然是我误会了
我一度想尝试 ``css`` ，但没有成功
原来是这样写的，非常感谢！
