### ISSUE TITLE
下一页的分割按钮是横条的，希望能适应不同网站改为方块

### ISSUE THREAD

**Issue by vicentory** [hoothin/UserScripts#72]
https://www.v1tx.com/page/4/
一个小建议，这个下一页的分割按钮是横条的，但其实类似这种方块形的信息流网站应该很多，能否把这个下一页的分割横条适应网站改为方块呢？
<img width="916" alt="image" src="https://user-images.githubusercontent.com/10493597/156295658-d36d581a-5b38-4f51-98aa-7e8614d3d2ee.png">

**Comment by hoothin** [comment]
这个是grid布局导致的，我加了个兼容代码，你更新试试。如果想要改成方块，可以添加规则属性“pageBar”，然后用js代码玩弄分割条。也可以在设置页隐藏分割条。
