### ISSUE TITLE
登录此网站会导致下一页翻到相同元素

### ISSUE THREAD

**Issue by Wei-Winter** [hoothin/UserScripts#722]
**Describe the bug**
https://orionfeedback.org/
这个网站我测试没登录前翻页正常，登录后永页机翻下一页跟第一页的内容相同，好奇怪。翻到相同的一页是下一页链接找错了吗

**To Reproduce**

**Expected behavior**
登录后也可以正常翻页

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone]
 - OS: [iOS17]
 - Browser [Orion browser]
 - Version [Violentmonkey 2.20.0]

**Additional context**
难道是因为登录后页面元素变了？？

**Comment by hoothin** [comment]
这个网站的 url 是假的吧？没有对应到具体页码的内容，我看 `?page=1` `?page=2` `?page=3` 内容都是一样的啊。
你试试添加`"action": 3`

**Comment by hoothin** [comment]
不不不，注意你的t，直接加就可以了
<pre name="pagetual">
{
    "name": "Orion Public Issue Tracker",
    "url": "^https?://orionfeedback\\.org/",
    "example": "https://orionfeedback.org/?page=3",
    "action": 3
}
</pre>
