### ISSUE TITLE
在这个在线作图网站开启会出现字体重影

### ISSUE THREAD

**Issue by weavers1f** [hoothin/UserScripts#73]
网址：https://818ps.com/search/0-0-0-0-0-null-31_1_0_708-0-0-0-0.html
开启的话如下图，点击在此站禁用后显示正常
![1646793858563](https://user-images.githubusercontent.com/19663899/157362621-1cdd40db-cf46-44c7-a9be-0ba47630d08c.png)

**Comment by hoothin** [comment]
<pre>
  {
    "name":"图怪兽",
    "url":"https://818ps\\.com/",
    "pageElement":"#masonry"
  }
</pre>

**Comment by weavers1f** [comment]
好快！哈哈。创客贴这里不生效，不过它模板展示页每页的本身也够长https://www.chuangkit.com/templatecenter

**Comment by hoothin** [comment]
<pre>
  {
    "name":"创客贴",
    "url":"https://www\\.chuangkit\\.com/",
    "type":0,
    "nextLink":"//div[@class='number']/ul/li[@class='item active']/following-sibling::li/a",
    "pageElement":"//div[@class='ckt-waterfall-content']",
    "pageAction":"let infos=doc.querySelector('body>script').innerText.match(/designTemplateId:\\d+,designTemplateImageUrl:\".*?\"/g),infoMap;if(infos){infoMap={};infos.forEach(i=>{let id=i.replace(/designTemplateId:(\\d+).*/,'$1');let src=i.replace(/.*designTemplateImageUrl:\"(.+)\"/,'$1');src=JSON.stringify(src);src=src.replace(/\\\\\\\\/g,'\\\\');src=JSON.parse(src);infoMap[id]=src;})};[].forEach.call(eles[0].querySelectorAll('.temp-sec__bottom>div>a'),a=>{let id=a.href.replace(/.*?(\\d+).*/,'$1');let src=infoMap[id];let img=a.parentNode.parentNode.previousElementSibling.querySelector('img');img.src=src;img.style.opacity=1;})"
  }
</pre>
