### ISSUE TITLE
这个网站有问题

### ISSUE THREAD

**Issue by liaanj** [hoothin/UserScripts#74]
https://www.jpmn8.com/Xrqj/XiuRen/17499.html
![屏幕截图 2022-03-10 092235](https://user-images.githubusercontent.com/98246557/157568532-7bf36e90-5863-45cc-adbb-064ca6d515e3.png)

**Comment by hoothin** [comment]
<pre>
  {
    "name":"秀人网",
    "url":"https://www\\.jpmn8\\.com/",
    "pageElement":"p>img"
  }
</pre>
