### ISSUE TITLE
狐猴浏览器使用暴力猴脚本管理器，无法导入规则

### ISSUE THREAD

**Issue by yumuing** [hoothin/UserScripts#743]
**Describe the bug**
狐猴浏览器使用暴力猴脚本管理器，正常打开配置页面，无法导入规则，
- 相应脚本规则页面均可进入，点击初始化规则正常出现规则数，排除网络问题
- 一旦点击保存设置，刷新页面，显示没有导入规则，尝试了三条默认规则及第三方镜像，排除规则网站问题
- 暴力猴脚本管理器使用其他脚本正常运行，排除脚本管理器问题，但可能存在适配问题，本人技术力有限

**To Reproduce**
1. https://greasyfork.org/zh-CN/scripts/438684-pagetual 安装脚本
2. 等待浏览器自动刷新，跳转配置页面，发现重复打开了好几个配置页面
3. 选择第一个配置页面，点击导入规则，等待更新
4. 自动刷新页面后，仍提示导入规则
5. 打开暴力猴脚本页面，进入该脚本高级配置页面
6. 尝试修改配置页面规则，也无法实现，此外，在此规则页面中，选择点击初始化规则，规则数正常显示

**Comment by hoothin** [comment]
别用暴力猴，暴力猴是 mv2 的，已经部分失效了，换 Tampermonkey，然后开启 developer mode

**Comment by hoothin** [comment]
![image](https://github.com/user-attachments/assets/62bb926b-8e48-4c6b-9f95-32fd7409e67b)

**Comment by yumuing** [comment]
> ![image](https://private-user-images.githubusercontent.com/5361213/371142062-62bb926b-8e48-4c6b-9f95-32fd7409e67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTQzMjAsIm5iZiI6MTcyNzM1NDAyMCwicGF0aCI6Ii81MzYxMjEzLzM3MTE0MjA2Mi02MmJiOTI2Yi04ZTQ4LTRjNmItOWY5NS0zMmZkNzQwOWU2N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTIzMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE0ZTJiNTQxMmQ1MGQzY2UyYjFjNDVhYTNlNTVhMWZkZTllNzQyZDYzNDQ3OTNiN2VjZjVhMjNjNDlhZjBiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ls1awaCooTgzgTOBZ4G3xZrFLTvVhbjjfnglyoTZYi4)

使用新脚本管理器，已能正确使用，感谢
