### ISSUE TITLE
md的gif里番网址能发发吗。pleas

### ISSUE THREAD

**Issue by cc1aymore** [hoothin/UserScripts#744]
https://github.com/hoothin/UserScripts/tree/master/Easy%20offline#%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD

魔蕙字幕组。pleas give url .thanks

**Comment by hoothin** [comment]
不讲礼貌！这种情况下不叫声”老哥“说得过去吗？
