### ISSUE TITLE
雪球规则

### ISSUE THREAD

**Issue by YandLiu** [hoothin/UserScripts#75]
尝试写了下雪球的规则，如在这个页面：
https://xueqiu.com/S/SZ002475

但是翻出来的只是第一页的重复

```json
[
  {
    "name":"雪球",
    "action":1,
    "url":"^https://xueqiu\\.com/",
    "pageElement":".status-list",
    "nextLink":"a.pagination__next"
  }
]
```

**Comment by hoothin** [comment]
这是动态加载的，需要指定变化内容为主体
<pre>
  {
    "name":"雪球",
    "url":"^https://xueqiu\\.com/",
    "pageElement":".status-list>article",
    "nextLink":"a.pagination__next"
  }
</pre>
这条规则需要更新一下最新脚本
![image](https://user-images.githubusercontent.com/5361213/157573721-22688f28-1034-4e1a-a4ef-5e53d91b0524.png)
