### ISSUE TITLE
Request Pagetual support for search.luxirty.com

### ISSUE THREAD

**Issue by Ouweiming** [hoothin/UserScripts#757]
**The url of site**
https://search.luxirty.com/search?q=sdad#gsc.tab=0&gsc.q=%E5%92%A9&gsc.sort=
The example urls of site. ⚠**Do not paste only domain without pathname, or I'll close the issue without explanation**⚠.

**Is your request related to a problem? Please describe.**
Nope.

**Describe the result you'd like with the rule**
实现自动翻页

**Custom rule you've tried**
暂无
**Additional context**

**Comment by hoothin** [comment]
<pre name="pagetual">
{
    "name": "Luxirty",
    "url": "^https://search\\.luxirty\\.com/",
    "pageElement": ".gsc-expansionArea>.gsc-result",
    "nextLink": ".gsc-cursor-current-page+div",
    "wait": 500
}
</pre>
