### ISSUE TITLE
b站搜索第二页以后的封面图不显示

### ISSUE THREAD

**Issue by liaanj** [hoothin/UserScripts#76]
![image](https://user-images.githubusercontent.com/98246557/157642649-7a078f6c-0e6b-48d8-80c0-c7b9ba5b472b.png)
谢谢！

**Comment by hoothin** [comment]
你得导入我Github上的规则库呀

**Comment by hoothin** [comment]
<pre>
  {
    "name":"bilibili search",
    "action":1,
    "url":"^https://search\\.bilibili\\.com",
    "pageElement":"ul>li.video-item,div.video-list.row>*:not(.to_hide_xs)",
    "nextLinkByUrl":["(.*keyword=.*?)(?:&page=|$)(\\d*).*","$1&page={($2.0||1)+1}"],
    "sandbox":false,
    "wait":"return doc.querySelector('.bili-video-card__wrap')"
  }
</pre>
