### ISSUE TITLE
iao.su 翻页后开始文章封面图不显示

### ISSUE THREAD

**Issue by JPLiu** [hoothin/UserScripts#77]
你好，此网址：https://iao.su/
翻页后文章封面图不显示，谢谢！
![图片](https://user-images.githubusercontent.com/13379952/157998050-c5fbfa9e-5c22-417c-b8ad-2130530c572a.png)

**Comment by hoothin** [comment]
<pre>
  {
    "name":"不死鸟",
    "url":"^https://iao\\.su/",
    "pageElement":"#index>article",
    "action":1
  }
</pre>

**Comment by JPLiu** [comment]
实测已解决，好勤勉的开发者。
