### ISSUE TITLE
edge上失效了

### ISSUE THREAD

**Issue by qq57240** [hoothin/UserScripts#78]

**Comment by qq57240** [comment]
javbus.com
javdb.com
目前发现这两个站上不能用

**Comment by hoothin** [comment]
是什麽失效了？

**Comment by qq57240** [comment]
> 是什麽失效了？

您试一下这两个网站就知道了，在磁边链边上有脚本黑圈下载箭头图标，但是点击图标无反应。我发现这个问题发现有一两周了。更新了好几次还是没有解决。

**Comment by hoothin** [comment]
是一鍵離綫下載嗎？這倆站沒有自帶磁力吧？

**Comment by hoothin** [comment]
配合挊使用確實有bug，感謝反饋，我修復一下

**Comment by qq57240** [comment]
> 配合挊使用確實有bug，感謝反饋，我修復一下

我目前没有安装拤脚本，依然点击无反应的，辛苦了。

**Comment by hoothin** [comment]
修好了，你試試

**Comment by qq57240** [comment]
> 修好了，你試試
可以用了，但是115那边总是99%停住不动，应该不是脚本问题。辛苦了！
