### ISSUE TITLE
插件冲突

### ISSUE THREAD

**Issue by liaanj** [hoothin/UserScripts#79]
大大，麻烦看一下这个
https://greasyfork.org/zh-CN/scripts/438420-%E7%99%BE%E5%BA%A6%E6%96%87%E5%BA%93%E5%87%80%E5%8C%96-%E8%A7%A3%E7%A6%81%E7%BB%A7%E7%BB%AD%E9%98%85%E8%AF%BB-%E5%BC%80%E5%90%AF-vip
插件在翻页机启用的时候就无法使用了，只能在油猴里排除，或许会有一点帮助？

**Comment by hoothin** [comment]
具体是哪里冲突？我尝试同时启用测试了一下，并没有发现哪里不对劲呀

**Comment by liaanj** [comment]
额，我这里似乎也暂时无法复现，可能是偶发问题，下次遇到了我详细记录下，谢谢
