### ISSUE TITLE
永页机能加个暂停翻页功能吗？

### ISSUE THREAD

**Issue by itheabyss** [hoothin/UserScripts#81]
说一个很实际的问题：

当你想搜索一个问题时，可能并不清楚具体要怎么表达，只能想到一个关键字，搜的结果很大程度上并不满意。但是不管是G家还是B家，底下会有些建议，这里面很大可能有你需要的完整问题。起码我是经常会用到底下的搜索建议。

但是用了永页机后就真的永远看不到下面的建议了。这脚本功能很好，但真心希望能有个暂停按键，让我可以暂时停止翻页。

谢谢

**Comment by hoothin** [comment]
1、双击
2、点击分隔条
3、点击右侧太极

**Comment by itheabyss** [comment]
这个刚才自己发现了，准备来删除这个ISSUE的。

这个真的很好用，以前用自动无缝翻页，那个翻页效果也行，但是太多页面不支持。比如HDC，一些老论坛都翻不了。永页机都没问题。

好东西，感谢。

**Comment by hoothin** [comment]
不用谢，发现有问题的网站尽管提交上来：）
