### ISSUE TITLE
这个是跟百度有冲突？

### ISSUE THREAD

**Issue by itheabyss** [hoothin/UserScripts#82]
发现只要打开picviewer ce，用百度搜索时就会卡几秒，然后出现下图这个。在油猴里关掉一切正常。

试过google,bing都正常。只有百度才出现。

![网页捕获_19-3-2022_14104_www baidu com](https://user-images.githubusercontent.com/21150155/159110018-8251b973-12bc-49d3-b687-a0df1eaefd45.jpeg)

**Comment by hoothin** [comment]
应该是和其他脚本或者扩展冲突了，方便的话你排查下其他脚本扩展，看看是哪一个，然后把冲突的脚本或者扩展发给我

**Comment by itheabyss** [comment]
测试了一下，跟发现跟两个有关：

1. AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列，地址：https://greasyfork.org/zh-CN/scripts/14178 ，冲突的情况是搜索时会卡几秒。

2. HTML5视频播放器增强脚本，地址：https://greasyfork.org/zh-CN/scripts/381682-html5 ，这个就会出现一楼的提示。

还有一个冲突是跟https://greasyfork.org/ 的网站有关。不知为何只要打开pvce+，已经安装过的脚本会显示图一，但这是不对的。油猴里关掉pvce+后刷新页面，就正常了，如图二。

图一：
![网页捕获_19-3-2022_143324_greasyfork org](https://user-images.githubusercontent.com/21150155/159110601-f24cdddd-a603-4120-8e7f-77edd164e050.jpeg)

图二：
![网页捕获_19-3-2022_143353_greasyfork org](https://user-images.githubusercontent.com/21150155/159110625-b1b2c60b-c4d0-4805-9982-90a35728da9c.jpeg)

**Comment by hoothin** [comment]
你的浏览器和脚本管理器信息给我一下呢

**Comment by itheabyss** [comment]
系统：Win10 19044.1618

Microsoft Edge
版本 99.0.1150.46 (正式版本) (64 位)

Tampermonkey  版本4.15

**Comment by hoothin** [comment]
我测试了一下，这个是 HTML5视频播放器增强脚本 和 AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列 的冲突，应该是抢夺样式优先级时产生的问题
![image](https://user-images.githubusercontent.com/5361213/159111973-ab16afe4-a51f-47ab-a9a8-9263f66fa62e.png)

**Comment by hoothin** [comment]
第二个问题我这里没有重现
![image](https://user-images.githubusercontent.com/5361213/159112021-8cc2db0c-a9d6-43e9-a41e-ee24c2cf2209.png)

**Comment by itheabyss** [comment]
> 

那还挺奇怪的，第二个问题我这里是100%重现。图片上其它所有的脚本全部停用。

![屏幕截图 2022-03-19 153403](https://user-images.githubusercontent.com/21150155/159112186-83402067-d172-49b9-b4b5-271bea391906.jpg)

**Comment by hoothin** [comment]
油叉是直接调用 `window.external.Tampermonkey` 来显示已安装版本号的。我在大人的Greasyfork里也有写过这个。而picviewer ce+除了对字符串的一个功能性覆写并没有哪里添加过修改window下函数的代码

**Comment by hoothin** [comment]
你这个截图里是禁用了一堆但还没有刷新的。你再单个启用测试看看呢

**Comment by itheabyss** [comment]
> 

图是刷新后截的。

只开了PIC，我又试了一次，只开PIC，然后刷新，油猴上显示红标是1：

![屏幕截图 2022-03-19 154920](https://user-images.githubusercontent.com/21150155/159112788-1a76f39b-bc81-49a9-b212-4382d669445a.jpg)

把pic关掉，其它我需要的全打开：

![屏幕截图 2022-03-19 155033](https://user-images.githubusercontent.com/21150155/159112826-df4b91a6-f34b-434c-8dd0-5d56ca6c914f.jpg)

**Comment by hoothin** [comment]
难不成是和某个扩展冲突了？你试试新开一个InPrivate页面，单独启用油猴和picviewer ce+呢

**Comment by itheabyss** [comment]
没用，我在虚拟机里的试了一次，还是一样。这个EDGE啥扩展都没装。刚装了个油猴，脚本也只装了PIC。可以说是非常干净了。

![屏幕截图 2022-03-19 162631](https://user-images.githubusercontent.com/21150155/159113867-a7f3b948-ef4e-4653-a911-4eaf93a7e604.jpg)



![屏幕截图 2022-03-19 162745](https://user-images.githubusercontent.com/21150155/159113891-6d81f187-9b0d-4bd2-bd7d-e2235f576af5.jpg)

**Comment by hoothin** [comment]
好奇怪，同样的环境我这边就是没法重现，要是可以把你的电脑拉过来调试就好了

**Comment by hoothin** [comment]
我再换一台设备测试试试

**Comment by hoothin** [comment]
新装了一个edge测试，也还是没有办法重现。这也太奇怪了，还有哪里不一样吗？
![image](https://user-images.githubusercontent.com/5361213/159115398-2888fdea-edfc-4c20-b4be-5ad2f6b6256a.png)

**Comment by itheabyss** [comment]
哈哈，搞不懂了。先就这样用着吧，反正这个问题不是太影响使用。就是第一个问题不知能不能解决，那个是影响使用了。

**Comment by hoothin** [comment]
因为我没法重现，这边我放飞头脑猜测一下啊，也许是你的电脑配置较差，导致加载 picviewer ce+ 时耗费了太多时间，使得油叉调用`window.external.Tampermonkey`时 Tampermonkey 还没初始化完毕，所以获取不到版本信息。

至于第一个问题，这应该和picviewer ce+无关，你可以试试在【HTML5视频播放器增强脚本】旁点击【>】排除“baidu.com”

**Comment by hoothin** [comment]
回头我再过一遍代码，看看有没有哪里有可能导致lag，找到就优化掉。后续如果你定位到了问题所在也麻烦提交给我了。感谢。

**Comment by itheabyss** [comment]
我今天才试了新版，以上三个问题全部没有了。现在一切正常。牛逼
