### ISSUE TITLE
这个网站不适配

### ISSUE THREAD

**Issue by 1458069353** [hoothin/UserScripts#83]
极简壁纸https://bz.zzzmh.cn/index#index

**Comment by hoothin** [comment]
适配可以是可以。但这个站为反爬加了太多限制，动态加载，代码混淆，验证码，能堆的都堆上了。从下一页抽出来的元素会丢失vue绑定的点击事件，重绑的话我还得自己再去实现一套前后端交互逻辑，太麻烦了。如果你只是想要翻页可以用下面的规则，翻页前需要输一次验证码。
<pre>
  {
    "name":"极简",
    "url":"^https://bz\\.zzzmh\\.cn/",
    "pageElement":"div.img-box",
    "nextLink":"div.vue_pagination_next",
    "wait":"let preload=doc.querySelector('.v-image__image--preload');if(preload){var actualTop=preload.offsetTop;var current=preload.offsetParent;while(current!==null){actualTop+=current.offsetTop;current=current.offsetParent;}doc.documentElement.scrollTop=actualTop;return false;}return doc.querySelector('div.vue_pagination_next');",
    "init":"if(iframe){iframe.style.position='fixed';iframe.style.top=0;iframe.height=1000;let mask=doc.querySelector('div.mask');setInterval(()=>{if(mask.style.display!='none'){iframe.style.visibility='';}else{iframe.style.visibility='hidden'}},1000)}"
  }
</pre>
