### ISSUE TITLE
东方永页机，浏览东财的一些页面时会无限展示最后一页

### ISSUE THREAD

**Issue by goeway** [hoothin/UserScripts#84]
比如外汇 http://quote.eastmoney.com/center/gridlist.html#forex_cross 这个页面，当显示完所有分页后，再往下拉，会无限重复显示最后一页（总共只有5个分页）
![20220325032121](https://user-images.githubusercontent.com/23276757/159994189-9d8fc374-9178-45b5-b843-d754b0a13812.png)

**Comment by hoothin** [comment]
这边可以加规则通过下一页按钮的状态来判断。因为这个表格内容是一直在动态变化的，而脚本原理是有变化就当作下一页。
<pre>
  {
    "name":"东方财富",
    "url":"^http://quote\\.eastmoney\\.com/",
    "pinUrl":"true",
    "nextLink":"a.next:not(.disabled)",
    "pageElement":"#table_wrapper-table>tbody>tr"
  }
</pre>

**Comment by hoothin** [comment]
如果有其他页面也是一样的，照着这个规则修改就行。搞不定可以再提交给我

**Comment by goeway** [comment]
> 如果有其他页面也是一样的，照着这个规则修改就行。搞不定可以再提交给我

好的，谢谢，已解决
