### ISSUE TITLE
打开知网页面，东方永页机自动翻页工具不跳转到下一面

### ISSUE THREAD

**Issue by Murphy119** [hoothin/UserScripts#87]
![知网截图](https://user-images.githubusercontent.com/44918329/161966495-156a582d-1572-4ad2-a94f-5debba791bcc.jpg)
望修复，不胜感激

**Comment by hoothin** [comment]
https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L164
规则是有的，我测试了也没问题。你确定已经导入了github上的规则了吗？

**Comment by Murphy119** [comment]
您好，不太清楚怎么导入规则，不太明白怎么使用






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
https://github.com/hoothin/UserScripts/blob/master/Pagetual/pagetualRules.json#L164
 规则是有的，我测试了也没问题。你确定已经导入了github上的规则了吗？

**Comment by hoothin** [comment]
打开配置页，按照提示点击一下那一行规则，然后更新一次就行了

**Comment by Murphy119** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
打开配置页，按照提示点击一下那一行规则，然后更新一次就行了

**Comment by Murphy119** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hoothin/UserScripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 晚上9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
打开配置页，按照提示点击一下那一行规则，然后更新一次就行了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


不知道为啥会有报错

**Comment by Murphy119** [comment]
想知道为啥会出现不能加载的情况
![出现报错](https://user-images.githubusercontent.com/44918329/161989876-b2b555f1-951a-4a2b-ad2d-14b6234fe16d.jpg)
![更新规则](https://user-images.githubusercontent.com/44918329/161989889-9827ccf3-e323-4a49-859f-4a351680ab73.jpg)

**Comment by hoothin** [comment]
你也可以选择把规则里知网那一段规则复制到你的自定义规则里

**Comment by Murphy119** [comment]
能劳烦示范一下吗？因为这块不是很熟悉，不知道怎么修改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
你也可以选择把规则里知网那一段规则复制到你的自定义规则里

**Comment by Murphy119** [comment]
![image](https://user-images.githubusercontent.com/44918329/161993522-bf73053c-92d3-45ed-b0d5-64d3cdcc622a.png)
不知道怎么复制规则，并且复制到哪

**Comment by hoothin** [comment]
删除github的规则，用这个cdn版的吧
https://cdn.jsdelivr.net/gh/hoothin/UserScripts/Pagetual/pagetualRules.json

**Comment by Murphy119** [comment]
您好，是把这些代码全部删除，复制您刚刚发的那些代码吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月7日(星期四) 上午9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
删除github的规则，用这个cdn版的吧
 https://cdn.jsdelivr.net/gh/hoothin/UserScripts/Pagetual/pagetualRules.json

**Comment by hoothin** [comment]
1、点击raw.github这条规则旁的x
2、将 https://cdn.jsdelivr.net/gh/hoothin/UserScripts/Pagetual/pagetualRules.json 粘贴进“导入规则url”下方的文本框
3、点击保存
4、点击更新于xx前

**Comment by Murphy119** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月7日(星期四) 上午10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
1、点击raw.github这条规则旁的x
 2、将 https://cdn.jsdelivr.net/gh/hoothin/UserScripts/Pagetual/pagetualRules.json 粘贴进“导入规则url”下方的文本框
 3、点击保存
 4、点击更新于xx前

**Comment by Murphy119** [comment]
您好，再次打扰您，遇到了一个技术问题解决不了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月7日(星期四) 上午10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
1、点击raw.github这条规则旁的x
 2、将 https://cdn.jsdelivr.net/gh/hoothin/UserScripts/Pagetual/pagetualRules.json 粘贴进“导入规则url”下方的文本框
 3、点击保存
 4、点击更新于xx前

**Comment by Murphy119** [comment]
![image](https://user-images.githubusercontent.com/44918329/162133380-9cc24f75-e78d-4449-a693-b7881202d8c8.png)
![image](https://user-images.githubusercontent.com/44918329/162133440-25d08059-d255-4ac9-ae79-381efd6dc759.png)
目前按您的指导操作了，应该是自己操作不熟练还是其他原因，知网页面没有跳转，然后专门查找您发的链接中打开知网网页的页面，也会进行json报错

**Comment by hoothin** [comment]
规则用大括号“{}”包裹之后再扔进中括号“[]”里面

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/162134363-a791bc04-8abb-4bb6-9f2f-85cfe0c9318f.png)
效果是这样的

**Comment by Murphy119** [comment]
![image](https://user-images.githubusercontent.com/44918329/162136477-6fc82ef8-4450-4745-8398-4c85d0439555.png)
![image](https://user-images.githubusercontent.com/44918329/162136542-386332be-de32-4f66-b569-5bcda8e2f218.png)
刚刚测试了，将单串“中国知网”的代码复制到最下端白色框了，效果很理想，已经修复了知网刚刚不自动翻页的问题。就是想问下，如果之后还遇到了类似的网站不能翻页，也是把代码中的name和网站链接换成目标网站吗？

**Comment by hoothin** [comment]
如果是已经识别了下一页链接，仅是正文内容不对，可以尝试“强制拼接”。
否则都需要规则驱动，规则是针对每个网站适配的，不能通用。

**Comment by Murphy119** [comment]
你像这种情况的话，是不是就要针对网站编写单条规则了？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月7日(星期四) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hoothin/UserScripts] 打开知网页面，东方永页机自动翻页工具不跳转到下一面 (Issue #87)





 
如果是已经识别了下一页链接，仅是正文内容不对，可以尝试“强制拼接”。
 否则都需要规则驱动，规则是针对每个网站适配的，不能通用。

**Comment by hoothin** [comment]
你如果遇到了可以扔上来，我有空就帮你写掉。
当然你也可以自己学一下，大部分规则都不需要太多高级编程技巧，会定位到元素就能覆盖大多数需求。

**Comment by Murphy119** [comment]
好的，感谢答主的耐心细致的解答，作为读研新生，这个工具能很大地提高科研效率，必须支持
