### ISSUE TITLE
nsfw https://www.imn5.net/XiuRen/XiuRen/10396_1.html 自动翻页有问题

### ISSUE THREAD

**Issue by liangxyz** [hoothin/UserScripts#88]
如题，https://www.imn5.net/XiuRen/XiuRen/10396_1.html
这个NSFW网页自动翻页不会显示图片，只能强制凭借

**Comment by hoothin** [comment]
这个是匹配到wedata上的博客规则了
<pre>
  {
    "name":"imn5",
    "url":"https://www\\.imn5\\.net/",
    "pageElement":"div.imgwebp>p"
  }
</pre>
