### ISSUE TITLE
Sometimes refreshes doesn't pin to bottom, Sometimes page missing.

### ISSUE THREAD

**Issue by GoroFourArms** [hoothin/UserScripts#89]
https://fiction.live/stories/Boots-A-Star-Wars-Story-FINISHED-/BdkTLaQZeypEzoCEg

[
  {
    "url":"^https://fiction.live/",
    "pageElement":"article.chapter",
    "nextLink":".nextChapter"
  }
]

**Comment by hoothin** [comment]
<pre>
  {
    "url":"^https://fiction\\.live/",
    "pageElement":"#storyPosts>div>article.chapter",
    "nextLink":".nextChapter",
    "action":1,
    "wait":500
  }
</pre>
There's 2 kind of article.chapter so you should use #storyPosts>div>article.chapter instead.
And action need set to 1 so you can get element didn't load in stastic.
Remenber to update the script first.

**Comment by GoroFourArms** [comment]
I don't know if its another extension or setting but while its loading it its just opens the links in the same page and sometimes it constantly refreshes.  Its just this site specifically. I found out about your script because weautopagerize wouldn't work with xpath. I guess because the link doesn't include the https.fiction.live part.  I also have firefox setting limit the link to open in same tab.

**Comment by hoothin** [comment]
What's your version of this script? Have you tried to check the option "Open urls of additions in new tab" on config page?

**Comment by hoothin** [comment]
I think maybe you have checked the "Write history after page turning" option, uncheck it and try again.

**Comment by GoroFourArms** [comment]
Yah i think those two things messed me up it seems to be working now. I am a complete novice so I have no idea when to use what. So i was just checking and unchecking everything. It took me forever to learn xpath. Thanks for your help.  It might be worth it to make a idiot proof tutorial.

**Comment by hoothin** [comment]
Thanks for the suggesting, A tutorial will be nice.
