### ISSUE TITLE
微博翻页后无法显示出视频

### ISSUE THREAD

**Issue by liaanj** [hoothin/UserScripts#91]
![image](https://user-images.githubusercontent.com/98246557/163305787-f38f1ee1-0ded-4f92-8b60-ce324b309066.png)
![image](https://user-images.githubusercontent.com/98246557/163305979-b1b0bb03-4903-4c40-a734-13282bb75c59.png)

**Comment by hoothin** [comment]
{
    "name":"微博搜索",
    "url":"^https://s\\.weibo\\.com/weibo\\?q",
    "pageElement":"#pl_feedlist_index>div>div.card-wrap",
    "action":1,
    "pageAction":"eles.forEach(e=>{let vc=e.querySelector('a.WB_video_h5');if(vc){let v=vc.querySelector('video');let b=vc.querySelector('button.wbpv-big-play-button');b.onclick=e=>{v.style.zIndex=9;v.controls=true;v.play()}}})"
  }

**Comment by liaanj** [comment]
谢谢，但是edge浏览器似乎还是无法显示，chrome可以显示
![image](https://user-images.githubusercontent.com/98246557/163312970-6f3293f4-2457-4012-9203-4b21e0026c2d.png)
![image](https://user-images.githubusercontent.com/98246557/163313010-e8d61426-5d52-4011-8708-c0f86486d41d.png)

**Comment by hoothin** [comment]
<pre>
  {
    "name":"微博搜索",
    "url":"^https://s\\.weibo\\.com/weibo",
    "pageElement":"#pl_feedlist_index>div>div.card-wrap",
    "action":1,
    "pageAction":"eles.forEach(e=>{let vc=e.querySelector('a.WB_video_h5');if(vc){let v=vc.querySelector('video');let b=vc.querySelector('button.wbpv-big-play-button');b.onclick=e=>{v.style.zIndex=9;v.controls=true;v.play()}}})"
  }
</pre>

**Comment by liaanj** [comment]
可以了谢谢！
