### ISSUE TITLE
请问这个网站的小说应该如何下载?

### ISSUE THREAD

**Issue by qingwu1687** [hoothin/UserScripts#92]
https://yuyan.pw/

辛苦哥哥了,全靠在这个小说网站看小说了.若能解决愿奉上奶茶一杯

**Comment by hoothin** [comment]
<pre>
https://yuyan.pw/novel/9508/[1790174-1790351].html@@@@@@var c=data.querySelector('body>script:nth-of-type(8)').innerHTML.match(/var chapter =(.*?);\n/)[1];eval(c).replaceAll("<br />","");
</pre>
因为没有目录页，自己找一下第一页和最后一页替换规则中的链接。记得更新脚本到最新版

**Comment by qingwu1687** [comment]
显示下载了123章, 但实际只下载到了56, 第57显示内容已锁.
https://yuyan.pw/novel/9476.html

**Comment by hoothin** [comment]
你打开链接来看一下呀，123页的内容就是“57已锁”

**Comment by qingwu1687** [comment]
抱歉抱歉, 我的错, 谢谢哥哥, 奶茶马上奉上.

**Comment by qingwu1687** [comment]
奶茶已奉上, 另外能否把这个issue删除, 谢谢

**Comment by hoothin** [comment]
不用了，这样好像一杯奶茶买我做外包似的，不合适。

**Comment by qingwu1687** [comment]
完全不是如此, 如果你在我身边, 我会买杯奶茶到你身边说, 哥哥帮我弄一下嘛我请你喝奶茶

**Comment by hoothin** [comment]
好的，我删除一下

**Comment by qingwu1687** [comment]
远隔互联网也只能这样了
另外能不能把这个issue删除, 不要关闭, 是删除.谢谢哥哥啦
