### ISSUE TITLE
x浏览器上某些小说网站自动加载的内容乱码

### ISSUE THREAD

**Issue by deviblue** [hoothin/UserScripts#93]
比如：jpxs123.com
在以下环境：
       安卓手机+x浏览器：自动加载内容乱码
       雷电安卓模拟器+x浏览器:自动加载内容乱码
       pc+edge:正常运行。

但是在www.txt520.com这个网站上  以上三者均正常运行。

**Comment by hoothin** [comment]
这个可能无解了，x浏览器不支持overrideMimeType
可以换kiwi浏览器。
以后我没事做了再研究下适配方法。

**Comment by deviblue** [comment]
> 
了解了  谢谢
我去试试kiwi
