### ISSUE TITLE
加载下一面后排版错乱

### ISSUE THREAD

**Issue by linmii** [hoothin/UserScripts#95]
https://zh.u1lib.org/s/%E7%94%B5%E5%B7%A5%E5%B7%A5%E4%B8%9A%E5%87%BA%E7%89%88%E7%A4%BE?

![image](https://user-images.githubusercontent.com/17309471/165110286-dcd5a641-2520-4d59-af30-5413ab061d0f.png)

**Comment by hoothin** [comment]
已修复

**Comment by panqucheng** [comment]
建议：能否显示当前页数和总页数，并且增加跳转到上/下一页，指定页数

**Comment by hoothin** [comment]
规则里有个pageNum属性，目前已经支持百度谷歌和discuz论坛，仿照内置规则里的例子添加到自定义规则就可以点击分隔条页码跳转到指定页。
类似 superpreloader 的当前页、总页数、上翻下翻因为我自己用不着，另外也觉得加上太臃肿，暂时不准备添加。
