### ISSUE TITLE
Settings Editor not in Github page

### ISSUE THREAD

**Issue by megamorphg** [hoothin/UserScripts#96]
I am recently moving over to use Firefox but cannot see editor in Github page in Firefox:
![image](https://user-images.githubusercontent.com/1782353/165146918-ea0e502c-9b48-4d61-b9c0-b3d8c436beff.png)

I have the same settings in Tampermonkey in both Chrome and Firefox because I did a full zip migration.
Using latest version of Firefox (99.0.1).

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/165194486-27894a66-e433-4b8c-84dc-cb9f36103367.png)
Maybe you can report more details, like the console error messages

**Comment by megamorphg** [comment]
You were right... I had Firefox's content blocker enabled but even after whitelisting in it and Ublock, it still doesn't show.

Would appreciate any other tips. Maybe a Tampermonkey setting?
![image](https://user-images.githubusercontent.com/1782353/166458843-98eb7e55-11ba-4ef3-956d-50d1e574c030.png)

Here's the console message too:
`Content Security Policy: Ignoring duplicate source 'unsafe-inline'
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'
Content Security Policy: Ignoring duplicate source 'unsafe-inline'
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/runtime-ca13a2edbb19.js [runtime-ca13a2edbb19.js](https://github.githubassets.com/assets/runtime-ca13a2edbb19.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/environment-4a9660289ca1.js [environment-4a9660289ca1.js](https://github.githubassets.com/assets/environment-4a9660289ca1.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/5724-640299416084.js [5724-640299416084.js](https://github.githubassets.com/assets/5724-640299416084.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/93-c88b26ce3c81.js [93-c88b26ce3c81.js](https://github.githubassets.com/assets/93-c88b26ce3c81.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/8630-5ad00158d0e0.js [8630-5ad00158d0e0.js](https://github.githubassets.com/assets/8630-5ad00158d0e0.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/5157-ee87317516de.js [5157-ee87317516de.js](https://github.githubassets.com/assets/5157-ee87317516de.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/9244-eedfea9bdaec.js [9244-eedfea9bdaec.js](https://github.githubassets.com/assets/9244-eedfea9bdaec.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/github-elements-5bef466c281d.js [github-elements-5bef466c281d.js](https://github.githubassets.com/assets/github-elements-5bef466c281d.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/element-registry-0964b4010bcd.js [element-registry-0964b4010bcd.js](https://github.githubassets.com/assets/element-registry-0964b4010bcd.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/5388-1dbf1debd575.js [5388-1dbf1debd575.js](https://github.githubassets.com/assets/5388-1dbf1debd575.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/8932-24f1e0ea55c2.js [8932-24f1e0ea55c2.js](https://github.githubassets.com/assets/8932-24f1e0ea55c2.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/7077-10871e8911f9.js [7077-10871e8911f9.js](https://github.githubassets.com/assets/7077-10871e8911f9.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/4862-21afc99a5dfd.js [4862-21afc99a5dfd.js](https://github.githubassets.com/assets/4862-21afc99a5dfd.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/3682-fab1d6916eca.js [3682-fab1d6916eca.js](https://github.githubassets.com/assets/3682-fab1d6916eca.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/3932-24b9e74cf858.js [3932-24b9e74cf858.js](https://github.githubassets.com/assets/3932-24b9e74cf858.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/6153-b71ff84a2185.js [6153-b71ff84a2185.js](https://github.githubassets.com/assets/6153-b71ff84a2185.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/5222-6b85a0658795.js [5222-6b85a0658795.js](https://github.githubassets.com/assets/5222-6b85a0658795.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/716-5eb5398842ed.js [716-5eb5398842ed.js](https://github.githubassets.com/assets/716-5eb5398842ed.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/behaviors-3abe3211bcde.js [behaviors-3abe3211bcde.js](https://github.githubassets.com/assets/behaviors-3abe3211bcde.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/7749-9d9a605eb06f.js [7749-9d9a605eb06f.js](https://github.githubassets.com/assets/7749-9d9a605eb06f.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/notifications-global-28a2c6fa1139.js [notifications-global-28a2c6fa1139.js](https://github.githubassets.com/assets/notifications-global-28a2c6fa1139.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/90-c721876308de.js [90-c721876308de.js](https://github.githubassets.com/assets/90-c721876308de.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/3878-6de1eeb75418.js [3878-6de1eeb75418.js](https://github.githubassets.com/assets/3878-6de1eeb75418.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/codespaces-5509339f6445.js [codespaces-5509339f6445.js](https://github.githubassets.com/assets/codespaces-5509339f6445.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/6813-018aadde1dde.js [6813-018aadde1dde.js](https://github.githubassets.com/assets/6813-018aadde1dde.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/6637-bbcafc50efdb.js [6637-bbcafc50efdb.js](https://github.githubassets.com/assets/6637-bbcafc50efdb.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/6791-017f321ec06f.js [6791-017f321ec06f.js](https://github.githubassets.com/assets/6791-017f321ec06f.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/repositories-4358bb8ca5a3.js [repositories-4358bb8ca5a3.js](https://github.githubassets.com/assets/repositories-4358bb8ca5a3.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/topic-suggestions-24e2339b7700.js [topic-suggestions-24e2339b7700.js](https://github.githubassets.com/assets/topic-suggestions-24e2339b7700.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/code-menu-9bec4b6ed946.js [code-menu-9bec4b6ed946.js](https://github.githubassets.com/assets/code-menu-9bec4b6ed946.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/4775-157c5e29a233.js [4775-157c5e29a233.js](https://github.githubassets.com/assets/4775-157c5e29a233.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/9255-1f75d78b4d3b.js [9255-1f75d78b4d3b.js](https://github.githubassets.com/assets/9255-1f75d78b4d3b.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/5623-0824f5ff836d.js [5623-0824f5ff836d.js](https://github.githubassets.com/assets/5623-0824f5ff836d.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/command-palette-08ed10af4637.js [command-palette-08ed10af4637.js](https://github.githubassets.com/assets/command-palette-08ed10af4637.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://avatars.githubusercontent.com/u/1782353?s=40&v=4 [1782353](https://avatars.githubusercontent.com/u/1782353?s=40&v=4)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://camo.githubusercontent.com/48b79ce7f45fdd051a84fa88b5c41321a0d7c44ec3176a218716165d281e2bc3/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30312f30362f6c45714b574c48473755424f3641592e6a7067 [68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30312f30362f6c45714b574c48473755424f3641592e6a7067](https://camo.githubusercontent.com/48b79ce7f45fdd051a84fa88b5c41321a0d7c44ec3176a218716165d281e2bc3/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30312f30362f6c45714b574c48473755424f3641592e6a7067)
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:112:337
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:112:481
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:71:798987
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:2:292
SingleFile is hooking the IntersectionObserver API to detect and load deferred images. 2 [hooks-frames-web.js:1:514](moz-extension://212f21a8-30bb-4597-9dae-de6f8bbc40e4/lib/web/hooks/hooks-frames-web.js)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/chunk-4656-398224bbeaf5.js [load script:46:29](https://github.githubassets.com/assets/webpack/runtime/load%20script)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/chunk-9039-ceb142b269be.js load script:46:29
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/chunk-280-a794c415e82b.js [load script:46:29](https://github.githubassets.com/assets/webpack/runtime/load%20script)
Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://github.githubassets.com/assets/chunk-1416-b89471c02c56.js load script:46:29
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://b04745f3-dbbe-42af-ac2a-1b1762426cb9/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map

Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://avatars.githubusercontent.com/u/5361213?s=48&v=4 [index.js:26:34](https://github.githubassets.com/assets/node_modules/@github/include-fragment-element/dist/index.js)`

**Comment by hoothin** [comment]
I check my config of TM, that's all the same with yours.
Can you try [violentmonkey](https://violentmonkey.github.io/get-it/) ?
I guess it is caused by some settings of other extensions because I can't see menu command before the "Edit".
Disable all other extensions for temporariness and enable one by one would be a tip too.

**Comment by megamorphg** [comment]
@hoothin I found the offending extension: "HTTPS Everywhere"
After whitelisting the github page, it works again.

**Comment by hoothin** [comment]
Congrats on figuring it out. :-)
