### ISSUE TITLE
Sensei, sorry this is out of my league

### ISSUE THREAD

**Issue by GoroFourArms** [hoothin/UserScripts#97]
https://inoveltranslation.com/chapters/2370

**Comment by GoroFourArms** [comment]
Out of curiosity I was wondering if you knew a solution that automatically redirects links like this https://lightnovelstranslations.com/road-to-kingdom-chapter-568-part-1/ to the end link.  I saw a couple solutions that use url but not css or xpath.

**Comment by hoothin** [comment]
<pre>
  {
    "name":"inoveltranslation",
    "url":"^https://inoveltranslation\\.com/",
    "pageElement":".chakra-skeleton>p",
    "nextLink":"button[aria-label='next chapter']"
  }
</pre>

**Comment by hoothin** [comment]
Remember to update script first

**Comment by hoothin** [comment]
You can try "nextLinkByUrl"

**Comment by GoroFourArms** [comment]
Sorry I didn't explain myself better on second link. I was wondering if you can do something like this https://addons.mozilla.org/en-US/firefox/addon/redirector/ for css or xpath. Thanks for the first link.

**Comment by hoothin** [comment]
I've add a option "autoClick" in rule.
So you can click any element with xpath or css now.
Just like:
<pre>
  {
    "name":"lightnovelstranslations",
    "url":"^https://lightnovelstranslations\\.com/",
    "nextLink":"p.alignright>a",
    "pageElement":".entry-content>p",
    "autoClick":"//a[contains(text(),'CLICK HERE TO READ')]",
    "pinUrl":true
  }
</pre>

**Comment by GoroFourArms** [comment]
Thanks for the that, super appreciate it! Unfortunately I can't get it to work yet. I tried refreshing page, updating rules and reinstalling script.

**Comment by hoothin** [comment]
Yeah, it's a custom rule and I didn't put it into buildin rules.
You can add the custom rule on [Config page](https://github.com/hoothin/UserScripts/tree/master/Pagetual).

**Comment by GoroFourArms** [comment]
Yes, I copied that into my custom rules also.

**Comment by hoothin** [comment]
Did you mean this site https://lightnovelstranslations.com/road-to-kingdom-chapter-568-part-1/ ?
Or you are testing others ?

**Comment by GoroFourArms** [comment]
Yes, that specific site doesn't work. I'm in the process of testing others.

**Comment by hoothin** [comment]
Does the version of pagetual equal 1.6.8.9 ?

**Comment by GoroFourArms** [comment]
Yes

**Comment by GoroFourArms** [comment]
I use firefox  violentmonkey

**Comment by hoothin** [comment]
Thank you, there are still some bugs under firefox violentmonkey. I'll fix it now.

**Comment by hoothin** [comment]
Fixed. You can try again now.

**Comment by GoroFourArms** [comment]
Wow you're fast. Thanks it works now!

**Comment by hoothin** [comment]
Thanks too for the report!
