### ISSUE TITLE
无法翻页 

### ISSUE THREAD

**Issue by noriole** [hoothin/UserScripts#98]
https://www.pixiv.net/tags/%E3%82%B4%E3%83%96%E3%83%AA%E3%83%B3/illustrations?mode=safe
不管是小说，插画都是这样
![image](https://user-images.githubusercontent.com/62467022/165433772-acb253fe-7ba3-4103-8e23-3eff02f870b3.png)

**Comment by hoothin** [comment]
先阅读脚本页的说明导入规则库呀

**Comment by noriole** [comment]
![image](https://user-images.githubusercontent.com/62467022/165434084-3500f6ca-6d0b-4e28-bdaa-5e7795d0ceb1.png)
忘了说明我之前就导入了

**Comment by hoothin** [comment]
你用的浏览器是什么？方便把控制台输出截取给我吗？

**Comment by noriole** [comment]
[www.pixiv.net-1651031108067.log](https://github.com/hoothin/UserScripts/files/8568597/www.pixiv.net-1651031108067.log)
已经删掉了cdn镜像库并重新更新
浏览器是
Vivaldi | 5.2.2623.39 (Stable channel) （64 位）

**Comment by hoothin** [comment]
![image](https://user-images.githubusercontent.com/5361213/165440184-feb95123-2b1d-41db-ba0e-cf1d44612b78.png)
在配置页勾选调试模式。然后ctrl+shift+j截图给我看看

**Comment by noriole** [comment]
![image](https://user-images.githubusercontent.com/62467022/165440752-2a63bc77-04a3-4bd4-8725-938487f97ffa.png)
![image](https://user-images.githubusercontent.com/62467022/165440806-05120bd1-cc91-47a7-ad76-015ba2120da5.png)

**Comment by hoothin** [comment]
先在在配置页勾选调试模式。
控制台会输出抓取到的下一页和主页框架选择器。

**Comment by noriole** [comment]
![image](https://user-images.githubusercontent.com/62467022/165442307-bc869f76-60d3-4354-afcc-b0a130b8dbe6.png)

**Comment by hoothin** [comment]
先在[脚本的配置页](https://github.com/hoothin/UserScripts/tree/master/Pagetual)勾选"调试模式，输出信息至控制台"

**Comment by hoothin** [comment]
我猜你本地没获取到规则。
你试试 https://raw.githubusercontent.com/hoothin/UserScripts/master/Pagetual/pagetualRules.json 能访问不？

**Comment by noriole** [comment]
从提交bug之前，这个一直都是勾选的
可以访问

**Comment by hoothin** [comment]
那就奇怪了，你方便加我qq远程一下瞅瞅不？

**Comment by noriole** [comment]
行

**Comment by hoothin** [comment]
406244213

**Comment by hoothin** [comment]
原因是pixiv plus把iframe当作了广告，解决方案是删除252行【"iframe",】
