### ISSUE TITLE
doubles first page then is fine

### ISSUE THREAD

**Issue by GoroFourArms** [hoothin/UserScripts#99]
https://www.scribblehub.com/read/215867-goddess-of-ice-reborn-as-narutos-twin-sister/chapter/215873/

man i really didn't think id run into another issue so soon lol

**Comment by hoothin** [comment]
<pre>
  {
    "name":"scribblehub",
    "url":"^https://www\\.scribblehub\\.com/read",
    "pageElement":"#chp_raw"
  }
</pre>

Here you are :-)

**Comment by GoroFourArms** [comment]
Still copies first page for some reason. It's really quirky some other pages copy a later page.

**Comment by hoothin** [comment]
{
    "name":"scribblehub",
    "url":"^https://www\\.scribblehub\\.com/read",
    "pageElement":"#chp_raw",
    "nextLink":"a.btn-next"
  }
Sorry, I did not test before. It might be OK now.

**Comment by GoroFourArms** [comment]
Gosh its working now, Its really driving me nuts because im certain i entered that before. except i didn't put \\ after www
